### ISSUE TITLE
[SUGESTÃO] Notificações gerais

### ISSUE THREAD

**Issue by friaca** [filipedeschamps/tabnews.com.br#1000]
No momento, quando você recebe um comentário num post ou alguém responde algum comentário seu, você não tem visibilidade disso, só tomando conhecimento caso verifique periodicamente. Isso gera um atrito enorme caso um usuário interaja em diversos posts diferentes, tendo que verificar todos eles pra ver se existe alguma atividade nova.

**Comment by gabrielsozinho** [comment]
@friaca hoje você é notificado no email sobre novos comentários nos seus conteúdos.

**Comment by friaca** [comment]
Sim, mas não concorda que notificar no e-mail não é tão prático quanto na própria plataforma? E se eu não estiver logado no e-mail, ou não tiver o costume de ficar verificando meu e-mail, ou N outras possibilidades. Notificação na própria plataforma é muito mais cômodo e deixa a UX bem melhor.

**Comment by gabrielsozinho** [comment]
Concordo totalmente! Pensei que você não sabia que era notificado no e-mail, por isso aquele comentário. 😅

**Comment by GabrielVictorF** [comment]
Acabei de postar sobre isso na plataforma e quando vim aqui já tinha conteúdo sobre isso 😅, que bom que essa ideia é apoiada.

**Comment by Rafatcb** [comment]
Tem vários issues sobre essa sugestão de notificação no repositório, mas não me lembro de ter visto uma com discussão substancial ou sugestões de implementação. Acho que podemos concentrar a discussão aqui:

* https://github.com/filipedeschamps/tabnews.com.br/issues/878

@aprendendofelipe se você souber algum issue melhor, por favor, me corrija.

**Comment by aprendendofelipe** [comment]
Turma, obrigado pelas contribuições! 💪

Vou fechar diversas issues com assuntos relacionados. Por isso estou listando abaixo as que serão mantidas abertas e onde recomendo concentrarmos o que foi debatido/sugerido aqui:

- #645 
- #738
- #742 

Fechando essa aqui 🤝
