### ISSUE TITLE
Segurança: Checagem de IP's Cloudflare

### ISSUE THREAD

**Issue by hiagodotme** [filipedeschamps/tabnews.com.br#1003]
Notei que foi criado um arquivo em models/ip.js com o objetivo de recuperar o IP do cliente. O header **cf-connecting-ip** permite há qualquer usuário mal intencionado definir qual IP ele quer que o sistema interprete (caso tenha o IP real, por trás do cloudflare).

O ideal seria antes de olhar para o **cf-connecting-ip** checar se o IP da request realmente está dentro dos blocos do Cloudflare. Talvez a aplicação possa fazer um request para obter os blocos de IP's do cloudflare quando ela sobre de forma automática.

Para isso pode utilizar os endereços abaixo:

- Blocos IPv4: https://www.cloudflare.com/ips-v4
- Blocos IPv6: https://www.cloudflare.com/ips-v6

Durante a semana, tentarei realizar a implementação! Porém caso alguém queira tentar, fiquem à vontade.

**Comment by filipedeschamps** [comment]
@hiagodotme show de bola! O `cf-connecting-ip` não representa o IP real deles? Considerando que todas as requests estão passando pelo Proxy deles, eu especulei que este era um cabeçalho que seria injetado por eles, independente se o `client` enviar isso como cabeçalho, exatamente como o `x-forwarded-for` quando é enviado por um servidor que você confia.

De qualquer forma, **por favor** nos ajude a testar este recurso meu caro e muito obrigado por criar a isseu 🤝

**Comment by hiagodotme** [comment]
@filipedeschamps exatamente o cloudflare vai injetar e descartar caso alguém envie. O problema seria alguém descobrir os IPs da vercel e chamar sem passar pelos proxies da Cloudflare, aí a pessoa conseguiria manipular o seu IP.

A proposta é apenas criar uma regra pra aceitar o header desde que o ip que esteja fazendo o request seja de um bloco válido da cloudflare. Caso contrário, ignore o cf-connecting-ip e recupera o ip real da conexão.

Durante a semana penso em como fazer, porém não é um problema tão grande uma vez que pra se aproveitarem disso a pessoa precisaria saber o IP público de sua aplicação na Vercel. Tem um outro esquema do cloudflare que a aplicação só aceita conversar com os servidores deles aí dispensaria essa tratativa..

**Comment by filipedeschamps** [comment]
Show!!! Faz total sentido 🤝 👍

**Comment by aprendendofelipe** [comment]
Fala @hiagodotme, tudo certo? Obrigado pelas dicas! 💪

Só hoje cheguei nessa issue, mas acredito que tudo relacionado já foi resolvido, conforme relatado em #1150.

Então vou fechá-la, mas qualquer coisa podemos reabrir. 🤝
