### ISSUE TITLE
[Sugestão] Redirecionar os hiperlinks para uma nova aba do Navegador

### ISSUE THREAD

**Issue by MVIEIRAB** [filipedeschamps/tabnews.com.br#1006]
Olá, boa noite, tudo jóia?

Percebi que ao clicar em um hiperlink, está sendo carregado na pagina atual, e não criando uma nova pagina em branco com o conteúdo do link referenciado.

Seria bem interessante que o link que for aberto, abra em outra aba do navegador, com isso não perdemos o progresso da leitura naquele momento.

**Comment by buzzcoode** [comment]
Posso trabalhar nessa funcionalidade.

**Comment by giovaniif** [comment]
Cara isso seria muito util mesmo, é bem ruim perder a referência de onde você estava, tanto pra quem fez o tab quanto pra quem está lendo. 🚀

**Comment by Rafatcb** [comment]
Temos um issue aberto sobre isso (https://github.com/filipedeschamps/tabnews.com.br/issues/477) com um comentário do Filipe agregando pra discussão: https://github.com/filipedeschamps/tabnews.com.br/issues/477#issuecomment-1182110074

**Comment by aprendendofelipe** [comment]
Vamos seguir com a sugestão do @Rafatcb e centralizar a discussão na #477 👍
