### ISSUE TITLE
[FEATURE] Lista de posts já lidos

### ISSUE THREAD

**Issue by otaviolms** [filipedeschamps/tabnews.com.br#1007]
Uma sugestão seria em criar uma página que trouxesse uma lista dos posts já lidos, para que você não tenha necessariamente que interagir ou salvar para ler mais tarde, mas quando precisar relembrar ou revisitar algum conteúdo, será muito mais fácil de buscar.

**Comment by Rafatcb** [comment]
Não me parece que ter uma lista de posts já lidos ajudaria a revisitar um conteúdo, porque pelo menos no meu caso, acabo visitando praticamente todas as publicações. Apesar disso, acho que essa sugestão pode ser feita no seguinte issue:

* https://github.com/filipedeschamps/tabnews.com.br/issues/518

Atualmente a diferenciação de publicação é feita por meio do `:visited`, ou seja, local no navegador, mas me parece que ainda existe a possibilidade de implementar isso de forma "por conta", o que permitiria ter uma página com a lista de conteúdos visitados.

Acredito que a melhor solução para esse tipo de situação é ter uma lista de conteúdos mesmo:

* https://github.com/filipedeschamps/tabnews.com.br/issues/645

Faz sentido fechar este issue para concentrar nos outros?

**Comment by aprendendofelipe** [comment]
@otaviolms, obrigado pela sugestão! 💪

Concordo com o @Rafatcb que é melhor concentrarmos nas outras issues. 👍

Vou fechar essa aqui 🤝
