### ISSUE TITLE
[Sugestão] Cadastrar o TabNews como criador verificado no Brave para possibilitar a doação ao site e aos publicadores de conteúdo

### ISSUE THREAD

**Issue by braiansmarzaro** [filipedeschamps/tabnews.com.br#1013]
O navegador Brave possui um sistema de recompensa com Bat, uma criptomoeda. Pode ser interessante a verificação para permitir o uso de doação no site. Vejo que seria uma vantagem sem efeitos colaterais.

**Comment by Rafatcb** [comment]
Como ninguém colaborou no assunto em mais de um ano, e minha investigação ficou sem respostas o longo dessas três semanas, estou fechando o issue para organizar o repositório.

Caso alguém encontre uma informação adicional ou o Brave mude o funcionamento e permita que o TabNews libere a doação de BAT para os usuários, podem comentar aqui com informações que reabrimos o issue.

Obrigado pela sugestão, Braian!
