### ISSUE TITLE
Proposta de melhorias para TabNews

### ISSUE THREAD

**Issue by MatheusComino** [filipedeschamps/tabnews.com.br#1015]
[Proposta de melhorias para TabNews](https://www.tabnews.com.br/MatheusComino/proposta-de-melorias-para-tabnews)

**Comment by aprendendofelipe** [comment]
Boa @Rafatcb, muito obrigado pela ajuda na organização das issues! 💪💪💪

Principalmente nas semanas próximas ao lançamento do TabNews o volume de issues foi muito grande e, infelizmente, muitas ficaram sem a merecida atenção.

Fechando... 🤝
