### ISSUE TITLE
Categorização de publicações e Filtros de publicação.

### ISSUE THREAD

**Issue by LucasBispoMenezes** [filipedeschamps/tabnews.com.br#1016]
Olá! Seria interessante ter a possibilidade de adicionar tags nas publicações, podendo então categoriza a publicação com uma ou várias categorias, e ter um filtro em que pudesse filtrar quais publicação eu quero ver no momento.

**Comment by Rafatcb** [comment]
É uma boa sugestão e foi feita repetidas vezes, então é realmente desejada pela comunidade. Dito isso, acho melhor concentrarmos a discussão aqui: https://github.com/filipedeschamps/tabnews.com.br/issues/742. A issue já tem alguns comentários e sugestões de implementação.

**Comment by aprendendofelipe** [comment]
Acatando a sugestão do @Rafatcb, vamos centralizar na #742. 👍

Fechando essa aqui... 🤝
