### ISSUE TITLE
[FEATURE] TabNews Challenger

### ISSUE THREAD

**Issue by DecaiDenza** [filipedeschamps/tabnews.com.br#1017]
Como descrevi no `tab` "Desafios para todos!", seria ótimo uma área de desafios.

**Comment by JiroRauwers** [comment]
Coloca o link do `tab`.

**Comment by DecaiDenza** [comment]
https://www.tabnews.com.br/DecaiDenza/desafios-para-todos

**Comment by Rafatcb** [comment]
Hoje um usuário pode criar, por conta própria, uma publicação que envolva algum tipo de desafio. No meu ponto de vista, algo mais elaborado e específico demandaria muito esforço por um retorno pequeno, ao menos hoje.

**Comment by aprendendofelipe** [comment]
Me parece algo que seria resolvido com as tags (#742), não é?

Vamos concentrar a discussão por lá, até porque aqui não houve muito engajamento com a ideia. 🤝
