### ISSUE TITLE
Antivirus detecta PUP ao abrir o tabnews em qualquer browser

### ISSUE THREAD

**Issue by m4cm3nz** [filipedeschamps/tabnews.com.br#1019]
Por mais que possa ser um falso positivo, um warning de PUP ao acessar o tabnews.com.br pega mal pra caramba.
Para reproduzir o problema basta ter instalado algum antivirus que faça este tipo de detecção e acessar o tabnews.com.br

**Comment by Jetrom17** [comment]
Deschamps não se responsabiliza por isso. Esse relatório deve ser feito ao antivírus instalado. Procure saber ou acompanhar mais a reputação do seu antivírus. Provavelmente um falso-positivo como bem disseste.

**Comment by coffee-is-power** [comment]
Windows be like:
