### ISSUE TITLE
undefined:undefined bug

### ISSUE THREAD

**Issue by PanDabStudios** [filipedeschamps/tabnews.com.br#1024]
Oi, bug simples, mas n sei como arrumar, mas basicamente, fassa um post e tente da um upvote em seu proprio post, ele alerta undefined undefined,

**Comment by filipedeschamps** [comment]
@PanDabStudios você poderia testar novamente? Estávamos passando por uma instabilidade dado a uma manutenção que fizemos 🤝

**Comment by yunger7** [comment]
Tenho quase certeza que isso ocorreu devido a queda mencionada em #1025, fui editar um conteúdo e também apareceu `Undefined undefined:undefined`. Logo em seguida dei um refresh e o TabNews estava fora do ar.
