### ISSUE TITLE
TabNews está fora do ar?

### ISSUE THREAD

**Issue by browzilio** [filipedeschamps/tabnews.com.br#1025]
<img width="1440" alt="Untitled" src="https://user-images.githubusercontent.com/47532063/204401488-cc14e0ce-5d82-4c17-83f6-7fb1b4c3071c.png">

**Comment by filipedeschamps** [comment]
Estava fora do ar sim! Fizemos uma manutenção aqui do nosso lado, mas o acesso já deve ter sido reestabelecido. Se puder confirmar, seria show! E obrigado por abrir essa issue 🤝

**Comment by browzilio** [comment]
Voltou, vou fechar a issue aqui. Obrigado @filipedeschamps!
