### ISSUE TITLE
Sistema de notificações / Sistema de perguntas separadas

### ISSUE THREAD

**Issue by lucasFelixSilveira** [filipedeschamps/tabnews.com.br#1026]
<h1>Vocês poderiam adicionar um sistema de notificações, por ex.</h1>

# Que tipo de notificações?
- Simples, sempre q você for respondido, será enviado uma notificação.
- Coisas a mais que poderiam ser adicionadas nesse sistema:
- - Sons de notificação assim como o do Whatsapp ( em tempo real )

<h1>O sistema de perguntas poderia ser como o do Stackoverflow</h1>

# Perguntas
 - Algo simples, assim como os posts normais, porém dedicado totalmente a perguntas e repostas.
 - Conter um campo de busca que procura pelos argumentos de título de cada postagem, dando preferência aos  _**Mais Respondidos**_
 - Motivo:
 - - Eu fiz uma publicação recomendando meu módulo NPM, e lá mesmo respondi com uma pergunta, provavelmente o usuário não verá e não teremos a página dedicada a algo de perguntas e repostas. Traduzindo, meu post se perdeu na vastidão de publicações.
 
<div align="center">
  <img src="https://media.discordapp.net/attachments/1045802171146453124/1046940839760375908/unknown.png?width=783&height=498">
</div>

**Comment by Hanufu** [comment]
Só o fato de ter um botão onde lista as notificações de comentários etc, já ajudaria bastante, eu mesmo tenho que ficar verificando o e-mail para saber se alguém comentou nos meus posts.

**Comment by shuhikari** [comment]
Além de dar um up, vou coletar os outros tópicos que também falam de notificações. 

Poderíamos montar um dossiê numa discussão única, acho a featura ultra válida.

Outros locais mencionados:
#1000 #738 #920 #1116 


@filipedeschamps já tem algum tipo de roadmap referente a essa funcionalidade ou ainda está em aberto a discussão?

**Comment by Rafatcb** [comment]
Como já temos o issue https://github.com/filipedeschamps/tabnews.com.br/issues/878 falando sobre notificação dentro da plataforma, podemos editar este para ser referente apenas à parte de "sistema de perguntas"?

**Comment by aprendendofelipe** [comment]
Turma, obrigado pelas contribuições! 💪

Pelos menos nas primeiras versões, a questão de perguntas pode ser uma tag específica, combinada com tags do assunto sobre a dúvida.

Por organização, vou fechar diversas issues com assuntos relacionados. Por isso estou listando abaixo as que serão mantidas abertas e onde recomendo concentrarmos o que foi debatido/sugerido aqui:

- #645 
- #738
- #742 

Fechando essa aqui 🤝
