### ISSUE TITLE
Nome de usuários mesmo que o de paginas

### ISSUE THREAD

**Issue by potatowski** [filipedeschamps/tabnews.com.br#1030]
Atualmente está permitindo que o usuário tenha nome de paginas do sistema (recentes, contato) e quando vai acessar a pagina do usuário vai pro perfil

Images do ocorrido:
![image](https://user-images.githubusercontent.com/4248081/204617725-4f1e3f7a-a348-48ff-869d-a28b5999fe5f.png)

![image](https://user-images.githubusercontent.com/65042811/204616838-5e37cb67-2379-494c-819a-ff273ac88e48.png)

**Comment by filipedeschamps** [comment]
`contato` não deveria deixar, pois está nesta lista:

https://github.com/filipedeschamps/tabnews.com.br/blob/306bc05efd9854512598c4ce96554e8d7ebf5b73/models/user.js#L194

Você não recebeu uma mensagem de erro?

E `recentes` não encontrei na lista que bloqueia, é necessário cadastrar, belo achado 😍 🤝 👍

**Comment by potatowski** [comment]
Eu tive a suposição que com contato iria acontecer o mesmo que recentes, testei aqui e deu realmente erro

**Comment by aprendendofelipe** [comment]
Resolvido em #1045

**Comment by aprendendofelipe** [comment]
Oi @potatowski, obrigado por reportar esse problema! 🚀
