### ISSUE TITLE
[SUGESTÃO] Ter um outro nome de usuário, como um nickname ou apelido

### ISSUE THREAD

**Issue by treepo1** [filipedeschamps/tabnews.com.br#1032]
Atualmente, ao trocar o usuário na plataforma, é disparada a seguinte mensagem: 
![image](https://user-images.githubusercontent.com/78393422/204649496-f97bc214-1cae-445e-bd94-406673954d74.png)

O que faz total sentido e gera a necessidade de uma tratativa para que as urls não quebrem de uma hora pra outra.
Uma sugestão é adotar um outro tipo de nome de usuário, como um "nickname" ou apelido, similarmente ao que ocorre no Twitter.
Talvez dessa forma, apesar de não resolver o problema diretamente, a alteração de um nickname seja algo que ocorra com mais frequência e consequentemente a quebra de urls se torne menos frequente.

**Comment by Rafatcb** [comment]
A referência para essa tomada de decisão foi o GitHub. O GitHub também quebra os links caso você mude o seu "username", mas permite adicionar um "Nome", e acho que nada impede termos isso no TabNews também.

Um outro issue relacionado é esse:

* https://github.com/filipedeschamps/tabnews.com.br/issues/723

**Comment by aprendendofelipe** [comment]
Acredito que podemos fechar essa issue, pois um outro nome não resolveria a quebra de links ao se alterar o username.

E agora é possível colocar seu nome (ou os dados que quiser) na página do perfil, então acredito que isso atenda de forma parecida com o que o GitHub faz.

Vou fechar também por inatividade, já a ideia não atraiu muita atenção.

Mas qualquer coisa reabrimos, se for necessário 🤝
