### ISSUE TITLE
Email de recuperação de senha não chega

### ISSUE THREAD

**Issue by Hanufu** [filipedeschamps/tabnews.com.br#1034]
Bom, criei uma conta porém não chegou o email de ativação. E quando eu clico em recuperar senha aparece a mensagem dizendo que foi enviado uma nova senha, porém o email nunca chega com a tal senha.  O mesmo acontece quando tento fazer login, fala que a conta não está ativada e que enviaram um link para a ativação da mesma, porém o link nunca chega...

**Comment by filipedeschamps** [comment]
@Hanufu por favor, envie um email para contato@tabnews.com.br através do email utilizado na conta para eu investigar 🤝 👍
