### ISSUE TITLE
(CHORE) @TODO move suggestEmail function to a separate file to make it reusable

### ISSUE THREAD

**Issue by imLeonam** [filipedeschamps/tabnews.com.br#1035]

**Comment by imLeonam** [comment]
![image](https://user-images.githubusercontent.com/66780830/204693346-532f75ca-9948-41fe-b26e-eb1e5258679d.png)

**Comment by Rafatcb** [comment]
Parece que isso já entrou em produção no PR https://github.com/filipedeschamps/tabnews.com.br/pull/1429. Essa issue pode ser fechada, certo @aprendendofelipe ?

Arquivo: https://github.com/filipedeschamps/tabnews.com.br/blob/main/pages/interface/utils/email-suggestion.js

**Comment by aprendendofelipe** [comment]
Boa @Rafatcb! E obrigado @imLeonam! 💪

Fechando... 🤝
