### ISSUE TITLE
Permitir ignorar publicações

### ISSUE THREAD

**Issue by FabioSmuu** [filipedeschamps/tabnews.com.br#1038]
Criei uma resposta em um post sobre este assunto.

Acho o mais viável, uma opção de "ignora postagem", assim as postagens teria números no título, mostrando total de view e quanto destas views clicaram em ignorar.

Da uma lida por favor 😌

https://www.tabnews.com.br/FabioSmuu/61795cdb-3002-47ab-970e-033ec14ec72b

**Comment by Rafatcb** [comment]
Fábio, obrigado pela sugestão!

Provavelmente isso sofrerá o mesmo problema que a sugestão https://github.com/filipedeschamps/tabnews.com.br/issues/1382. Citando o comentário https://github.com/filipedeschamps/tabnews.com.br/issues/1382#issuecomment-1602751913:

> Os conteúdos (e as listas de conteúdos) do TabNews são exibidos em páginas estáticas. Ainda não existem páginas personalizadas para cada usuário, e, provavelmente, isso deve demorar para entrar no radar, tanto pela exigência de muito mais performance do back-end, quanto de reformulação total do sistema.

**Comment by aprendendofelipe** [comment]
Acho que essa issue também pode ser fechada por falta de adesão da Turma.

Mas qualquer coisa reabrimos 🤝
