### ISSUE TITLE
[FEATURE/SUGESTÃO] Publicação compartilhada/vários autores

### ISSUE THREAD

**Issue by DaniloCarSan** [filipedeschamps/tabnews.com.br#1040]
Opção de contribuição na publicação, ou seja, a mesma publicação ser de vários usuários, pois é comum ver um poste e logo abaixo os alguns comentários postando conteúdo para compor o post, isso evitaria duplicação e melhor visualização do conteúdo sendo que o mesmo estaria centralizado.

**Comment by Rafatcb** [comment]
Essa sugestão me parece misturar duas outras sugestões:

* https://github.com/filipedeschamps/tabnews.com.br/issues/965
* https://github.com/filipedeschamps/tabnews.com.br/issues/714

Acho que podemos fechar este e concentrar a discussão nos outros, mais específicos.

Lembrando que não é errado alguém comentar algo que complemente a publicação original, isso permite um tom diferente da publicação original, um ponto de vista do próprio autor do comentário e também que ele ganhe TabCoins com isso.
