### ISSUE TITLE
Deschamps quero sua atenção

### ISSUE THREAD

**Issue by Jetrom17** [filipedeschamps/tabnews.com.br#1042]
Queria que o Deschamps me respondesse aqui sobre isso. 

https://www.tabnews.com.br/SimithCahori96/all-lives-matter

Recebi -16 downvote. Agora estou com -203 tabCoins.

Como recebi essa quantidade? Por fazer o **certo**. A publicação não estava de acordo com a plataforma que foi destinado a ter "valor concreto", segundo Deschamps diz. E outros usuários não gostaram disso e foram contra mim. Agora a publicação foi removida pelo autor ou por um moderador e fiquei com -203 tabCoins.

![Screenshot_20221130-101533.png](https://user-images.githubusercontent.com/72875404/204806434-65932daa-b51b-4081-8cb3-0d989bff105b.png)

Essa imagem é única que tenho por ter salvo o cache do navegador.

**Comment by filipedeschamps** [comment]
@Jetrom17 obrigado meu caro, vou avaliar a movimentação de TabCoins contra este seu comentário 🤝

**Comment by Jetrom17** [comment]
> Vou lhe propor o seguinte: na próxima Milestone [...] irei resetar este post, devolvendo a você as TabCoins, combinado? 

Certo. Isso me é justo.

> Milestone vamos implementar uma ferramenta para um moderador

Seenhor Deschamps, como faço para ser um de seus moderadores voluntários? 

> Eu só peço que aguarde um pouco para que seja possível fechar a Milestone atual (que será feito em Live hoje)

 Live vai ser público no YouTube ou termo "live" é referente a outra coisa, da qual, desconheço?
