### ISSUE TITLE
Listar conteúdos por quantidades de TabCoins, visualizações, comentários etc.

### ISSUE THREAD

**Issue by yancordeiro** [filipedeschamps/tabnews.com.br#1043]
como o titulo sugere, a possibilidade de filtrar de acordo coma quantidade de tabcoins, maior para menor e vice versa

**Comment by Poveii** [comment]
É uma boa ideia. Para um futuro que tenhamos mais configurações em relação a filtragem dos posts, tipo invés de ter só a aba de recentes que mostram os posts recentes, teria um botão para indicar parâmetros para uma filtragem mais profunda e avançada. Mas de toda forma é uma boa! ^^

**Comment by Rafatcb** [comment]
@aprendendofelipe Me parece que tanto a busca de conteúdos no geral, quanto de conteúdos do usuário fazer uso do `findWithStrategy`:

**Comment by aprendendofelipe** [comment]
@Rafatcb, eu também acho que podemos fechar aqui e manter a #1388, então já estou fechando 🤝

Mas é bom deixar registrada nossas restrições atuais com relação a essa ideia. Nós não temos os dados de visualizações no nosso banco (apenas no analytics e limitado a 12 meses) e não temos cache do saldo de TabCoins.

E esses indicadores isoladamente não dizem muita coisa, mas a combinação entre eles é capaz de pegar um contexto melhor, por isso acredito que a prioridade deva ser melhorar o ranqueamento de relevantes antes de disponibilizar outros ranqueamentos.

### Cache de saldos de TabCoins

Para que o ranqueamento se atualize em tempo real, queremos evitar o cache enquanto for possível. Por isso computamos os saldos em tempo real, mas isso sempre acontece em um número restrito de conteúdos, de acordo com cada consulta. Sempre é filtrado por tempo e, às vezes, também pelo usuário.

Classificar todos os conteúdos pelo saldo exigiria computar em tempo real o saldo de todos conteúdos publicados, o que monopolizaria o uso do banco de dados, prejudicando o desempenho de todo o sistema.
