### ISSUE TITLE
[FEATURE/SUGESTÃO] - Blog pessoal no Tabnews

### ISSUE THREAD

**Issue by leandersonandre** [filipedeschamps/tabnews.com.br#1046]
Adicionar uma feature para utilizar o Tabnews como um blog pessoal,
ou alguma forma que seja possível listar apenas as postagens pessoais.
Atualmente no link pessoal apresenta as postagens e comentários.

**Comment by Rafatcb** [comment]
Isso já é possível hoje, algumas pessoas já publicaram sobre isso no TabNews ([aqui tem um exemplo](https://www.tabnews.com.br/evertonribas/blog-pessoal-a-partir-das-apis-tabnews)).

Apesar disso, não acho que seja ideal o TabNews focar em possibilitar ser usado como blog pessoal, pois as regras do TabNews devem ser respeitadas, e já aconteceu de usuários publicarem o mesmo conteúdo em inglês e português para ter no próprio blog, ou de ser banido por infringir alguma regra e "perder" as publicações.
