### ISSUE TITLE
[bug] Os caracteres '<' e '>' não são mostrados corretamente em blocos de código 

### ISSUE THREAD

**Issue by Gabriel-Tapes** [filipedeschamps/tabnews.com.br#1048]
Quando estava comentando em uma publicação do tabnews coloquei um bloco de código que continha os operadores de comparação > e <, lendo o código para revisar vi que nas partes do código onde tinha o caractere < aparecia a sequência &lt e para > &gt, resolvi fazer alguns testes no mesmo comentário editando e constatei que isso só ocorre em blocos de código mesmo, para o restante do texto os caracteres aparecem normalmente.

link do post em questão: https://www.tabnews.com.br/joelcarneiro/o-problema-dos-numeros-primos-na-programacao

**Comment by aprendendofelipe** [comment]
Oi @Gabriel-Tapes, acho que agora está tudo certo com a sua publicação.

Se puder verificar, acho que já não precisa daquele comentário.

Vou encerrar a issue, ok?
