### ISSUE TITLE
Erro ao tentar criar uma Pull request

### ISSUE THREAD

**Issue by rodrigoKulb** [filipedeschamps/tabnews.com.br#1050]
@filipedeschamps depois que o projeto ficou publico não consigo enviar PRs, sabe se preciso configurar algo?

![Captura de tela em 2022-12-01 00-34-34](https://user-images.githubusercontent.com/5334261/204959909-13c50699-fc58-47c0-8457-b475d86e5f73.png)

**Comment by filipedeschamps** [comment]
@rodrigoKulb show! Agora o repositório volta ao fluxo normal de um repositório open source, onde você precisa fazer um **Fork** aqui deste repositório (que é uma cópia que fica vinculada com a origem), clonar este Fork para a sua máquina, fazer as alterações, fazer o push para este Fork, e daí abrir o PR 🤝 

Se ficou muito denso a explicação, me avise 👍
