### ISSUE TITLE
[FEATURE] Implementar RSS

### ISSUE THREAD

**Issue by mgunther** [filipedeschamps/tabnews.com.br#1052]
Implementar RSS, de forma a permitir a leitura das postagens off-line.

**Comment by Rafatcb** [comment]
Temos esse RSS: https://www.tabnews.com.br/recentes/rss

A implementação foi feita aqui: https://github.com/filipedeschamps/tabnews.com.br/pull/621

**Comment by mgunther** [comment]
Perfeito!
Funciona maravilhosamente bem!
Seria interessante colocar na página um ícone informando a sua existência/ativação.
No rodapé talvez?
Obrigado!
