### ISSUE TITLE
[Feature] Modo de revisão 

### ISSUE THREAD

**Issue by megalexandre** [filipedeschamps/tabnews.com.br#1054]
Olá amigos.
Primeiramente, parabens pelo TabNews! 

## posposta: 

** Problema: **

Escrevo postagens longas e detalhadas,
Escrever, revisar, adicionar gráficos de mermaid 

coisas que juntas podem levas horas, adorei todo TABNEWS, mas sinto falta de um mode de salvar o conteúdo parcialmente para ser completado depois. 
 
 ** Solução: **
 
 Minha proposta é:
 
 1. adicionar um botão de salvar na tela de postagem de artigo: 
 
![image](https://user-images.githubusercontent.com/5364466/205071348-297c5f1e-4036-4b67-9394-c37c9b39ac23.png)

 2. adicionar um botão de publicar para os post não publicados: 
 
 ![image](https://user-images.githubusercontent.com/5364466/205071938-b456e6dc-578d-495a-900d-a95e46d9440c.png)

**Comment by edumats** [comment]
Eu publiquei meu primeiro artigo no TabNews, mas fiquei com medo de perder o meu trabalho digitando no site da TabNews, pois faço várias revisões e correções, então acabei escrevendo tudo no site da Hashnode e depois colando no TabNews para ser publicado.

Eu vi que o conteúdo que escrevo na página "Publicar conteúdo" do TabNews fica salvo, mesmo fechando a aba do navegador e reabrindo. Acho que deveria ficar mais claro para o usuário que o conteúdo ficará salvo. Assim, acredito que os usuários ficariam mais tranquilos para elaborar melhor os posts ao invés de tentar escrever e publicar em uma tacada só.

**Comment by Rafatcb** [comment]
Como foi dito, hoje o conteúdo fica salvo no `localStorage`, e poderia ficar mais claro que foi salvo realmente, mas acho que podemos fechar esse issue como duplicado de:

* https://github.com/filipedeschamps/tabnews.com.br/issues/960
