### ISSUE TITLE
Corretor ao escrever um post

### ISSUE THREAD

**Issue by Luciano655dev** [filipedeschamps/tabnews.com.br#1056]
Quando você escreve um post um pouco mais longo, é normal que você precise verificar se uma palavra ou outra estão corretas antes de apertar no botão de "publicar"
A questão é que, diferentemente de outras plataformas, como o próprio GitHub onde estou escrevendo isso, o TabNews não disponibiliza um corretor enquanto você escreve (linhas vermelhas em baixo das palavras, etc)
Isso dificulta muito na hora de revisar uma postagem longa, que você precisa ler cuidadosamente cada palavra para não correr o perigo de errar alguma letra e não precisar ir editanto o post diversas vezes
Acredito que seja algo bastante simples de ser feito, certamente deve existir alguma lib ou até mesmo alguma função do próprio navegador que disponibilize esse recurso
Também tem gente que falou que tinha uma extensão que já fazia isso, mas curiosamente a mesma não pegava no TabNews

Fiz um post no site falando sobre essa e outras sugestões, algumas pessoas concordaram comigo
Link: https://www.tabnews.com.br/Luciano655/denunciar-usuarios-e-barra-de-pesquisa-no-tabnews

Espero que levem em consideração!

**Comment by Rafatcb** [comment]
Realmente seria útil ter um corretor na caixa de texto, mas como isso já foi sugerido na issue https://github.com/filipedeschamps/tabnews.com.br/issues/970, acho que podemos concentrar a discussão lá.

Vale mencionar também que temos outros problemas com o editor atual, como mencionado em https://github.com/filipedeschamps/tabnews.com.br/issues/648.

**Comment by aprendendofelipe** [comment]
Obrigado @Luciano655dev e @Rafatcb! 💪

Acredito que as discussões sobre o editor de texto podem ser unificadas na #648.

No mínimo as discussões relacionadas ao que não podemos resolver sem a troca do editor, ou colaborando diretamente no repositório do ByteMD (que em sua nova versão está sendo desenvolvido como [HashMD](https://github.com/pd4d10/hashmd)).

É o caso da verificação ortográfica, que nem é o editor em si que faz, mas sim o navegador, mas no ByteMD não dá pra habilitar. Então vou fechar essa aqui. 🤝
