### ISSUE TITLE
Selos de verificado nas contas

### ISSUE THREAD

**Issue by Luciano655dev** [filipedeschamps/tabnews.com.br#1057]
Lá no site teve um problema que um perfil estava postando notícias e todos achavam que era bot, até que o @filipedeschamps explicou que se tratava de uma conta oficial. Mesmo assim, antes disso, isso causava uma pequena confusão
Para evitar esse tipo de acontecimento, um selo de verificação em algumas conta seria uma boa ideia
Isso ajudaria a distinguir perfis falso de reais, etc

Para não transformar o selo de verificado em uma grande burocracia, eles poderiam ser dados apenas a contas selecionadas ou aqueles que contribuíram com o projeto
Talvez até ter diferentes selos para quem tem quantidade X de TabCash, para quem contribuiu, para contas oficiais, etc...
Ou, se não quiser complicar, apenas para algumas contas específicas como disse antes

Isso traria uma ajuda imensa e evitaria vários motivos de desentendimentos em relação a identidade
fiz um post com essa e outras sugestões no TabNews, aqui o link: https://www.tabnews.com.br/Luciano655/denunciar-usuarios-e-barra-de-pesquisa-no-tabnews

Espero que levem em consideração!

**Comment by Rafatcb** [comment]
Acho essa preocupação legal, e inclusive acabou gerando alguns comentários na issue https://github.com/filipedeschamps/tabnews.com.br/issues/1289. Mesmo ela sendo uma issue mais recente, acho que poderíamos concentrar o assunto por lá. Que tal @aprendendofelipe ?

**Comment by aprendendofelipe** [comment]
@Luciano655dev, obrigado pela sugestão! 💪

Vamos seguir a sugestão do @Rafatcb de manter o debate na #1289. 🤝
