### ISSUE TITLE
Favoritar/Salvar post

### ISSUE THREAD

**Issue by Luciano655dev** [filipedeschamps/tabnews.com.br#1058]
Já me vi diversas vezes na situação em que quero guardar um post para vê-lo depois, como aqueles que falam sobre a API do TabNews ou qualquer outro assunto distinto
Para fazer isso atualmente, preciso copiar o link da postagem e salva-lo em outro lugar, como em um servidor privado do Discord ou em um arquivo de bloco de notas, o que não é nem um pouco prático

Assim como o Instagram ou YouTube, criar uma opção de "Salvar" para os posts ajudaria muito nessa questão, ou pelo menos adicionar uma aba que te permite ver as postagens que você já curtiu, certamente ajudaria um grande número de pessoas com algo relativamente simples de ser implementado

Escrevi essa e outras sugestões lá no site e algumas pessoas concordaram comigo
Aqui o link: https://www.tabnews.com.br/Luciano655/denunciar-usuarios-e-barra-de-pesquisa-no-tabnews

Espero que leve em consideração!

**Comment by theJoseNeto** [comment]
Sugeri algo parecido aqui. https://www.tabnews.com.br/ojotaneto/opcao-de-salvar-postagens-no-tabnews também

**Comment by aprendendofelipe** [comment]
Obrigado pela issue! 👍

Por organização, estou fechando as duplicadas com a #645 🤝
