### ISSUE TITLE
[FEATURE/SUGESTÃO] Disponibilizar a documentação da API do tabnews via Swagger ou outra ferramenta

### ISSUE THREAD

**Issue by yuhrao** [filipedeschamps/tabnews.com.br#1066]
Acho que seria interessante e até estimularia a galera a se utilizar mais das APIs se houvesse uma documentação mais explícita e de fácio acesso. Acho que o Swagger 2 (ou OpenAPI 3) serviriam bem. Além de ser uma abordagem legal pra apenas abrir a página e experimentar as requests, é uma maneira bem automatizada de manter a documentação sempre atualizada.

Também há a possibilidade de usar ferramentas como o [Read The Docs](https://readthedocs.org), mas acho que seria mais trabalhoso.

A lib que eu vi o pessoal mais utilizando é essa aqui: [next-swagger-doc](https://github.com/jellydn/next-swagger-doc). Eu experimentei e não tive problemas

Também tem o [Redoc](https://github.com/Redocly/redoc) que parece ser interessante e mais bonitinho até ahha A maior vantagem dele é que a interface mobile é bem boa

**Comment by EduardoSpek** [comment]
O usuário coffeeispower já desenvolveu uma muito bacana:

[Documentação da API do TabNews](https://coffee-is-power.github.io/tabnews-openapi/)

Veja também o post que ele fez sobre a documentação lá no TabNews:

[Post feito pelo coffeeispower](https://www.tabnews.com.br/coffeeispower/pitch-minha-documentacao-da-api-do-tabnews)

**Comment by joseribeiroejrs** [comment]
Alguém sabe como anda a análise do PR dele? Isso ao meu ver é algo essencial e que vai ajudar muitooooo. Também senti muita falta disso.

**Comment by gabrielsozinho** [comment]
@joseribeiroejrs vai ser analisado na próxima milestone,

**Comment by aprendendofelipe** [comment]
@yuhrao, obrigado pelas sugestões! 💪

Vou fechar essa issue para centralizarmos na #555. Combinado? 🤝
