### ISSUE TITLE
Sugestão de Usabilidade para o Tabnews - Parte 1

### ISSUE THREAD

**Issue by iihieiii** [filipedeschamps/tabnews.com.br#1071]
Segue as ideias:

# <img src = "https://iili.io/HJiNdvI.jpg">
# <img src = "https://iili.io/HJieN7p.jpg">
# <img src = "https://iili.io/HJieZT7.jpg">
# <img src = "https://iili.io/HJik0Ff.jpg">
# <img src = "https://iili.io/HJsqniN.jpg">
# <img src = "https://iili.io/HJsUI4e.jpg">

https://www.tabnews.com.br/Chitaum/sugestao-de-usabilidade-para-o-tabnews-parte-2

**Comment by Rafatcb** [comment]
Sobre as sugestões:

1. Foto de perfil aparecendo na publicação: Acho que não temos um issue sobre isso.
2. Notificações: https://github.com/filipedeschamps/tabnews.com.br/issues/738
3. Salvar publicação: https://github.com/filipedeschamps/tabnews.com.br/issues/645
4. Funcionamento do site: https://github.com/filipedeschamps/tabnews.com.br/issues/1380
5. Pesquisa: Já implementado.

@aprendendofelipe acha que faz sentido editar esse issue para ficar apenas sobre o primeiro ponto?

**Comment by aprendendofelipe** [comment]
Eu acredito que adicionar fotos de perfil nos conteúdos (ou na lista de conteúdos) é algo fora dos planos do TabNews. Acho que esse é um dos pontos que tentamos fazer diferente. Já foi falado mais de uma vez sobre não dar mais importância ao autor do que ao conteúdo... Uma referência:

https://github.com/filipedeschamps/tabnews.com.br/issues/328#issuecomment-1180867579

Outra referência é a #530, onde foi descartada a ideia de colocar o username do autor no final da linha (onde atualmente fica o "tempo de publicação"), pois isso daria mais destaque ao autor, imagina uma foto então...

Nada impede da pessoa colocar fotos na página de perfil (eu mesmo coloquei). Mas por enquanto a foto precisa estar hospedada em outro local.

Para ter uma maneira oficial de adicionar a foto ao perfil, precisamos primeiro de um sistema de armazenamento de arquivos próprio. O armazenamento próprio está no radar para permitir fotos nas publicações sem depender de hospedagens externas. E quando isso estiver implementado, também vai facilitar adicionar fotos na descrição do perfil. Mas mesmo estando no radar, não é algo prioritário por enquanto.

Então não vejo motivo para deixar a issue aberta, já que esse ponto não deve ser implementado (pelo menos não no curto prazo), e que os outros pontos já possuem issues próprias.

Concordam?

**Comment by Rafatcb** [comment]
Seguindo o que foi discutido nos comentários, e como não houve nenhuma resposta contrária, estou fechando o issue para organizar o repositório.

Obrigado pelas sugestões, iihieiii!
