### ISSUE TITLE
Abrir a comunidade de discussões do repositório 

### ISSUE THREAD

**Issue by acamilateixeira** [filipedeschamps/tabnews.com.br#1072]
Ache que seria bacana configurar no repositório a parte de discussão assim poderíamos evitar varias issues que são apenas ideias de até mesmo votar em algumas antes de se tornar uma issue.

**Comment by Rafatcb** [comment]
Isso chegou a ser discutido em https://github.com/filipedeschamps/tabnews.com.br/issues/480 , mas o issue foi fechado. Atualmente o https://github.com/filipedeschamps/tabnews.com.br/issues/598 está aberto com a mesma sugestão.

**Comment by acamilateixeira** [comment]
@Rafatcb  obrigada! vou fechar essa.
