### ISSUE TITLE
busca no site e onde está meu artigo?

### ISSUE THREAD

**Issue by shadowruge** [filipedeschamps/tabnews.com.br#1073]
Bom dia.<br>
Quero deixar aqui minhas felicitações pois foi muito acertiva a ideia para o site. <br>
Mas também acho que está faltando algo "construtiva",
Campo de busca e notificações para o usuário:<br>
* 1-saber que sua postagem, foi publicada e não está em avaliação "notificação"<br>
* 2-poder buscar por tabs de sua preferência <br>
Obs:.fiz um post e não o acho no site.<br>
Bom dia e parabéns.

**Comment by mpedroni** [comment]
Olá! Abri uma issue (#1084) com uma ideia para resolver o problema da busca no site. Quero implementar mas não faço ideia de como será a aceitação disso kkkk então, se puderem comentar o que pensam sobre, ou se alguém já teve alguma experiência com o serviço que propus e queira compartilhar algo, será muito bem vindo!

**Comment by Rafatcb** [comment]
Hoje, ao publicar um conteúdo, você é redirecionado para a publicação e confetes aparecem na página. Se for para Recentes, a princípio a publicação não aparecerá por causa do cache, mas ao dar F5 ela aparece.

@aprendendofelipe consegue confirmar se tem uma forma melhor de lidar com isso? Se já foi discutido em algum issue

Sobre o segundo ponto, a busca já foi implementada: https://github.com/filipedeschamps/tabnews.com.br/pull/1472

**Comment by aprendendofelipe** [comment]
> Obs:.fiz um post e não o acho no site.

Nem todas publicações vão para a página de relevantes.

Na página `/recentes` as publicações ficam classificadas pelo tempo de publicação, então ela deve ter aparecido ali logo após o cache da página ter sido invalidado, ou seja, no primeiro acesso após 10 segundos. Se o cache já estiver obsoleto, nem precisa de F5, pois o `next-swr` buscará os dados recentes em segundo plano e atualizará a página quando eles estiverem disponíveis.

Na época ainda não havia o item <kbd>Meus conteúdos</kbd> no menu, então nem todos sabiam que dava para listar seus conteúdos ao clicar no seu username. Nessa página, `/[username]` na época da issue e `/[username]/conteudos/1` hoje, vale o mesmo sobre o cache.

Não ficou claro em que momento não encontrou seu conteúdo, mas se a procura levou mais do que o tempo de invalidação do cache, era para ter encontrado na sua própria lista (e nos recentes), então pode ter procurado apenas nos relevantes. A não ser que sua publicação tenha sido excluída pela moderação, caso em que não iria encontrá-la em nenhum lugar.

Dado que hoje a UX está melhor para localizar seus próprios conteúdos, que já temos uma barra de busca, e que, fora os pedidos pelo sistema de busca que já está disponível, não houve casos semelhantes de dificuldades para localizar suas próprias publicações, vou encerrar a issue, mas podemos reabrir se surgirem novas informações. 🤝
