### ISSUE TITLE
Adicionar suporte ao asciinema

### ISSUE THREAD

**Issue by DouglasdeMoura** [filipedeschamps/tabnews.com.br#1076]
O [asciinema](https://asciinema.org/) é uma plataforma para compartilhar gravações de terminal feitas em SVG. É um jeito bem bacana de compartilhar, visualmente, como fazer as coisas no terminal (vocês podem ver um exemplo do uso em um artigo meu [aqui](https://dev.to/douglasdemoura/use-this-npm-script-to-create-your-editorconfig-files-1e3c)).

**Comment by Rafatcb** [comment]
No seu artigo do dev.to, você precisou incluir por meio do script? Por exemplo, adicionando `<script async id="asciicast-569727" src="https://asciinema.org/a/569727.js"></script>` no artigo?

**Comment by aprendendofelipe** [comment]
Por enquanto é possível exibir a gravação do asciinema usando SVG:

```md
<img src="https://raw.githubusercontent.com/OrKoN/newsletter-cli/master/demo.svg?sanitize=true">
```

ou


```md
![](https://raw.githubusercontent.com/OrKoN/newsletter-cli/master/demo.svg?sanitize=true)
```

Que resulta em:

<img src="https://raw.githubusercontent.com/OrKoN/newsletter-cli/master/demo.svg?sanitize=true">

Assim como para inserir qualquer imagem no TabNews, é preciso fornecer a URL de onde o arquivo foi hospedado.

Algumas desvantagens desse método são:

- A performance, pois o processamento do SVG pode ser pesado, principalmente se houver mais de um na mesma publicação. 
- Não é possível copiar o conteúdo do terminal.

---

Eu acredito que adicionar o texto em um bloco de código (como no exemplo abaixo) nos atende bem, seja na apresentação (didática, acessibilidade, visão completa etc.) ou pela indexação pelos mecanismos de busca:

```shell
# Rodar apenas /tests/api/v1/_use-cases/registration-flow.test.js
npm run test:watch -- registration-flow

# Rodar todos os testes de "users" da api "v1"
npm run test:watch -- v1/users/

# Rodar apenas /tests/api/v1/users/[username]/patch.test.js
npm run test:watch -- username./patch

# tests/integration/api/v1/contents/[username]/[slug]/get.test.js
npm run test:watch -- contents/.username./.slug./get
```

**Comment by Rafatcb** [comment]
Eu concordo que texto cumpre bem o papel, apesar do svg "gif" parecer mais bonito. Esse SVG que você publicou só começou a rodar para mim depois que abri o link do SVG em uma nova guia para ver se o problema era o GitHub.

O caso de uso que enxergo que isso poderia ser útil seria para mostrar alguma ferramenta pelo terminal, mas aí acho que um GIF satisfaz essa necessidade sem precisar adicionar uma tag `<script> ou depender de um `<svg>`, que pode dar problemas como eu relatei no primeiro parágrafo.

**Comment by Rafatcb** [comment]
Seguindo o que foi discutido nos comentários sobre como colocar esse tipo de informação num conteúdo do TabNews, vamos seguir sem a adição do asciinema diretamente, para não adicionar uma nova dependência de um script de terceiros para ter um desempenho melhor nas buscas ao colocar o código em texto e um exemplo em GIF (ou SVG).

Obrigado pela sugestão, Douglas! Estou fechando o issue para a organização do repositório.
