### ISSUE TITLE
Permitir a adição de URLs canônicas para o conteúdo

### ISSUE THREAD

**Issue by DouglasdeMoura** [filipedeschamps/tabnews.com.br#1077]
Algumas vezes, o usuário tem um blog próprio e deseja republicar o conteúdo no TabNews. Nestes casos, é preciso definir a [URL canônica](https://developers.google.com/search/docs/crawling-indexing/consolidate-duplicate-urls?hl=pt-br) daquele conteúdo, de modo que o artigo não apareça, de maneira duplicada, nos resultados de pesquisa.

## Exemplo

Como adicionar uma URL canônica no [dev.to](https://dev.to/):
![image](https://user-images.githubusercontent.com/564542/205396847-74369c5f-1e7e-4798-bed9-d2b1c177ca99.png)

**Comment by aprendendofelipe** [comment]
@DouglasdeMoura, vamos centralizar a discussão nessa #860 que é mais antiga. Combinado? 🤝
