### ISSUE TITLE
[REPORT]Bug Redirecionamento

### ISSUE THREAD

**Issue by cybernerd007** [filipedeschamps/tabnews.com.br#1078]
**ATENÇÃO: JA REPORTEI PELO EMAIL POREM COMO JA SE PASSARAM 24H E NÃO TIVE RETORNO ACHEI POR BEM ABRIR UMA ISSUES PARA REPORTAR**

Meio que sem querer descobri que existe uma forma de jogar qualquer usuario LOGADO no Tabnews para um link externo segue o link

`https://tabnews.com.br/login?redirect=https://tabnews.com.br/login?redirect=https://www.youtube.com/watch?v=uv3ghuwSSf0`
OBS.: Caso não redirecione 2 vezes ele te joga pra dentro do Tabnews e ignora o redirecionamento externo.

Como e visto quanto compartilhado o link (Não usei encurtador no segundo redirecionamento em um exemplo real seria um ponto crucial para capturar mais usuarios)
![Screenshot_2](https://user-images.githubusercontent.com/8114976/205405016-02642266-b7b7-4b2f-b9cd-a5a97d0bf16f.png)

**Comment by filipedeschamps** [comment]
@cybernerd007 show, eu vi o seu email mas não tive tempo de reportar. Não atuei de imediato nesta questão por não considerar crítica (que é acessar ou alterar alguma informação privada fora do seu escopo de usuário). Então iria incluir ela dentro da próxima Milestone sobre Performance e Segurança.

Mas posso estar enganado na minha avaliação, então pergunto: ela é crítica?

Obrigado 🤝

**Comment by cybernerd007** [comment]
Me dediquei 5 minutinhos para fazer esse pequeno exemplo...
coloca o mouse em cima do [LINK TESTE](https://tabnews.com.br/login?redirect=https://tabnews.com.br/login?redirect=https://tabnews-seven.vercel.app/) e verifica a URL que aparece...(não usei nenhum encurtador mais poderia)
agora clicka nele(no link)....
Bom essa pagina FAKE que eu fiz seria para coletar os dados porem ela não funciona ja que e para uma simples demostração.

agora pensa, ja imaginou aparecer um **E-mail** escrito fulano respondeu seu post e o link e esse **FAKE** ou ate mesmo **Compartilhado no whatsapp**.

ai eu te devolvo a pergunta: você cairia? agora alguem desatento cairia?
se a resposta for sim para **UMA** e **MEDIA** se for sim para as **DUAS** e **GRAVE**... agora se for não absulutamente e baixa kkkk

fico feliz por ajudar a comunidade, estou SEMPRE a disposição...

**Comment by cybernerd007** [comment]
**LEMBRANDO O USUARIO TEM QUE ESTAR LOGADO PARA FUNCIONAR**

**Comment by Gabriel-Tapes** [comment]
Uma outra forma de explorar o bug seria mandando um link de login que redireciona para uma falsa página de login, assim seria possível obter email e senha do usuário. É claro que o usuário facilmente poderia perceber ao olhar a URL da página, mas tenho certeza que pouquíssimos verificam sempre a URL em páginas que visitam frequentemente como redes sociais, então muitos cairiam.

**Comment by filipedeschamps** [comment]
@cybernerd007 o @aprendendofelipe fez o PR #1081 que lida com este tipo de situação e acabamos de fazer o deploy.

Você pode realizar uma nova bateria de testes? 🤝 

Caso precise criar novos conteúdos, você pode usar a última branch de Homologação: https://tabnews-8kgcqlch1-tabnews.vercel.app/

Caso contrário, você já pode testar em produção: https://www.tabnews.com.br/

**Comment by cybernerd007** [comment]
@filipedeschamps Fiz os testes e foi **CORRIGIDO** 🎉🎉🎉

Vou ficar com o link do ambiente de homologação para continuar com os testes anteriores....

fico feliz em poder ajudar a deixar nosso pedacinho de internet mais seguro.

**FICO A DISPOSIÇÃO**

**Comment by filipedeschamps** [comment]
Sensacional meu caro! Peço perdão por não conseguir responder seu email a tempo, eu toco sozinho aquele email e toda carga do restante do TabNews e da vida tá bem pesada 😅

Bom, muito obrigado @cybernerd007 por encontrar a falha, @Gabriel-Tapes por participar e @aprendendofelipe por consertar 🤝
