### ISSUE TITLE
[FEATURE/SUGESTÃO] desfazer upvotes/downvotes

### ISSUE THREAD

**Issue by HoepersDuarte** [filipedeschamps/tabnews.com.br#1079]
Acabei de passar por um problema de misclick e acabei dando downvotes em um comentário o qual não tinha necessidade, o problema é que não existe forma de desfazer esta ação.

A ideia seria alem de ter como desfazer esta ação, por mais que seja algo que possa ocorrer poucas vezes, é importante pois pode tirar ou dar tabcoins indevidamente da pessoa.

isso tbm permite que postagens que estão recebendo donwvotes, apos serem ajustadas, possam ser retiradas.

**Comment by AndreLuisOvidio** [comment]
Isso acabou de ocorrer comigo, minha cabeça associou o botão de downvote com o botão de fechar comentários, algo parecido com o botão de fechar pastas no vscode:
 
![image](https://user-images.githubusercontent.com/74057361/205449088-4ad0deb4-1bd0-4365-9707-7d4ed00db41e.png)

![image](https://user-images.githubusercontent.com/74057361/205449124-fc762225-2005-415b-983f-2f8c1a367576.png)

**Comment by JacksonSamuel42** [comment]
eu acredito que seria legal ter um pré publish assim como temos normalmente nos hedlers cms.

**Comment by alberto255345** [comment]
Acho que é necessário. Principalmente em um sistema de transação.

**Comment by aprendendofelipe** [comment]
Turma, obrigado pelas contribuições! 💪

Temos a issue #1183 em que a discussão avançou um pouco mais, então vamos fechar essa aqui e direcionar o debate para lá 🤝
