### ISSUE TITLE
"Access denied" ao acessar o site

### ISSUE THREAD

**Issue by vadolasi** [filipedeschamps/tabnews.com.br#1083]
Esteou desenvolvendo um projeto de utilizar a API do tabnews para criar uma interface para o terminal: https://github.com/vadolasi/tabnews-cli

Durante os meus testes, eu realmente acabo fazendo bastante chamas as vezes. Mas ultimanente, tenho recibido muitos bloqueios, e agr quando fui tentar acessar o site me deparei com a seguinte tela:

```
Access denied Error code 1020
You cannot access tabnews.com.br. Refresh the page or contact the site owner to request access.

Troubleshooting information
Copy and paste the Ray ID when you contact the site owner.

Ray ID: 773deb033d099acb
```

**Comment by cybernerd007** [comment]
Recomendo enviar um email para `contato@tabnews.com.br` com seu `IP` e relatando o ocorrido.
isso tb ja aconteceu cmg kkkkk

**Comment by filipedeschamps** [comment]
@vadolasi obrigado pelas informações, de fato seu CLI está fazendo muitas chamadas, principalmente `GET` contra o endpoint `/api/v1/user`. Veja o gráfico abaixo, mesmo dentro do rate limit, você estava fazendo em média `400` requests a cada 30 segundos:

![image](https://user-images.githubusercontent.com/4248081/205457279-3cd44180-00de-4590-a3d8-1d6afc9c2a0e.png)

Fora do rate limit você fez em média `1.600` requests por minuto contra o mesmo endpoint:

<img width="836" alt="image" src="https://user-images.githubusercontent.com/4248081/205457372-b4a1dbf5-7ed1-48a6-9ecb-d9102c06a173.png">

Eu peço encarecidamente que você avalie o que o seu CLI está fazendo para precisar de tantas chamadas, principalmente contra o endpoint `/api/v1/user` (que deveria ser chamado só em situações específicas).

**Comment by vadolasi** [comment]
Vou dar uma olhada, certamente é algum bug. Perdão pelo transtorno e
obrigado pelas informações!

Em sáb., 3 de dez. de 2022 às 15:59, Filipe Deschamps <
***@***.***> escreveu:

**Comment by coffee-is-power** [comment]
Clássico...
