### ISSUE TITLE
Ideia de implementação para busca de `contents` publicados

### ISSUE THREAD

**Issue by mpedroni** [filipedeschamps/tabnews.com.br#1084]
## Contexto

Acredito que se faz necessário no TabNews um mecanismo de busca eficiente e preciso para que os usuários consigam encontrar o que precisam, além de evitar a duplicação de `contents`. Por conta disso, quero abrir essa discussão e propor uma solução para esse problema.

## Soluções existentes

Implementar esse tipo de solução do zero acredito ser inviável devido a complexidade envolvida nesses tipos de mecanismos de busca, além de não ser o diferencial do TabNews, não tendo necessidade ser algo desenvolvido "internamente". Portanto vejo que faz sentido utilizar algum serviço existente, sendo necessário avaliar os custos necessários para tal.

Indo mais direto ao ponto, imagino que os serviços mais conhecidos que resolveriam esse problema de busca são o [Algolia](https://www.algolia.com/) e o [ElasticSearch](https://www.elastic.co/elasticsearch/). Ambos serviços tem "fama" de ter altos custos de utilização e não são ferramentas _open source_ (o Algolia é _closed source_ e o ElasticSearch é distribuído sob a licença SSPL que, [segundo a Open Source Initiative](https://opensource.org/node/1099), não se trata de uma licença _open source_.

## Solução Proposta

Uma outra solução que poderia resolver o problema em questão é o [MeiliSearch](https://www.meilisearch.com/), que é um sistema _open source_ (licença MIT) e que acredito fazer sentido no contexto do TabNews. O MeiliSearch possui um serviço em nuvem próprio (uma espécie de MeiliSearch gerenciado) que é pago, porém é possível rodar o MeiliSearch em um container e utilizá-lo sem custo adicional além dos recursos computacionais necessários para rodar ele.

## Conclusão

Acredito que utilizar uma solução desse tipo faça sentido no TabNews visto que, na minha visão, um sistema de busca eficiente é um ponto importante para a aceitação e continuação do projeto.

Não deixem de contribuir com as suas opiniões sobre isso!

**Comment by italosll** [comment]
Busca de tabs é a feature cuja ausência mais me incomoda, me dá a sensação de que os conteudos passados serão perdidos, porquê não há uma forma de alcança-los...  Infelizmente não tenho qualificação para opinar sobre a melhor forma de implementar esse serviço...

**Comment by mpedroni** [comment]
> Busca de tabs é a feature cuja ausência mais me incomoda, me dá a sensação de que os conteudos passados serão perdidos, porquê não há uma forma de alcança-los... Infelizmente não tenho qualificação para opinar sobre a melhor forma de implementar esse serviço...

Concordo... e, como falei, acredito que deva ser um sistema de busca mais robusto porque, do meu ponto de vista, encontrar conteúdos específicos dentro do TabNews deveria ser uma feature core, e acredito que o MeiliSearch consegue entregar isso com um bom custo benefício.

Quero começar a implementar essa solução mas não sei como funciona o processo, se a gente só implementa e abre o PR ou se é necessário abrir a issue primeiro e discutir a proposta com o @filipedeschamps e com a comunidade (acredito que a segunda opção faça mais sentido kkk)

**Comment by jjpaulo2** [comment]
@mpedroni gostei da sua ideia.

Talvez o primeiro passo seja transformar o campo `title` em um index do postgres, e caso o postgres venha a se tornar um gargalo, podemos enviar esses index pra algum banco de busca, como o caso do MeiliSearch.

**Comment by mpedroni** [comment]
@jjpaulo2 pode ser uma boa... o único problema que vejo nisso é a limitação que esse tipo de busca, pois as buscas precisariam ser muito exatas e pouco flexíveis para se encontrar os posts relevantes, sem contar que seria útil poder incluir o conteúdo do post na busca também.

De qualquer forma, concordo contigo de que esse seria um bom primeiro passo para essa feature e ver se só isso já resolve o problema.

Uma outra coisa, saberias dizer se o index no banco de dados também ajuda para buscas do tipo LIKE (`title LIKE "%query%"`) ou apenas para buscas exatas (`title = query`)?

**Comment by jjpaulo2** [comment]
@mpedroni até onde eu conheço o postgres, o ideal é usar o módulo `pg_trgm` e criar indexes baseados no gin.

Podemos fazer essa tentativa e validar a feature. Encontrei um artigo falando sobre esses index de texto aqui:

https://niallburkley.com/blog/index-columns-for-like-in-postgres/

**Comment by mpedroni** [comment]
Excelente! Achei muito promissor o `pg_trim`, ainda não conhecia. Vamos validar essa feature sim e ver se há realmente necessidade de utilizar uma solução mais parruda tipo o MeiliSearch ou se o `pg_trim` já resolve

**Comment by jjpaulo2** [comment]
Pelo que eu vi aqui é mais fácil do que parece adicionar essa extensão. A ferramenta de migrations que o projeto tá usando dá suporte à instalação de extensões.

https://salsita.github.io/node-pg-migrate/#/extensions

Acho que agora é só mandar a ver @mpedroni. A partir da próxima semana, eu consigo ajudar codando algo que for necessário.

**Comment by jjpaulo2** [comment]
Posso ajudar nessa questão de configurar o banco com a extensão, o index e construir as querys 😄

Podemos fechar um escopo pra essa busca? Que tal nesse momento inicial fechar a busca apenas pelo título da postagem?

**Comment by codigocafe** [comment]
@mpedroni e @jjpaulo2 , vocês já viram essa função nativa de banco "full-text search"?  

Veja o vídeo do Dias de Dev. 

https://youtu.be/zjNPAPknZgE

**Comment by jjpaulo2** [comment]
@codigocafe os indexes GIN/GiST são a forma de construir buscas full-text no postgres 😄

**Comment by codigocafe** [comment]
@jjpaulo2 , desculpa, mas não entendo muito de Postgres, mas o GIN/GiST resolveria este problema? Outra dúvida é se dessa forma a busca iria acarretar em um sobrecarga no DB?

**Comment by mpedroni** [comment]
> Pelo que eu vi aqui é mais fácil do que parece adicionar essa extensão. A ferramenta de migrations que o projeto tá usando dá suporte à instalação de extensões.
> 
> https://salsita.github.io/node-pg-migrate/#/extensions
> 
> Acho que agora é só mandar a ver @mpedroni. A partir da próxima semana, eu consigo ajudar codando algo que for necessário.

@jjpaulo2 Fechoou! Eu estou estudando um pouco sobre isso para poder começar a implementar algo, além de estudar um pouco sobre o próprio projeto. Acredito que essa semana consigo subir alguma coisa, aí abro um PR vinculado com essa issue a gente vai contribuindo lá. Pode ser?

**Comment by mpedroni** [comment]
> 

@codigocafe então, também não sou um grande entendedor de Postgres, mas acredito que as buscas nesse caso teriam um desempenho bom por conta de estarem usando um índice feito pra esse tipo de busca (no artigo que o @jjpaulo2 dá de ver bem isso). Nesse caso, acredito que o que poderia sobrecarregar o banco seriam muitas consultas concorrentes, e nesse caso acredito que teríamos que pensar em algum tipo de escalabilidade, seja utilizando cache ou réplicas de leitura do banco de dados.

De qualquer forma, acredito que seja algo que precisaríamos testar na prática pra ver como o banco vai se comportar

**Comment by jjpaulo2** [comment]
@codigocafe sobrecarregar a ponto de derrubar, eu acredito que não. Mas vai aumentar razoavelmente o consumo, porque provavelmente vai ser uma feature bastante usada.

**Comment by mpedroni** [comment]
pessoal, eu estava navegando aqui pelo repositório e encontrei uma ferramenta desenvolvida pelo @Karyton , disponível nesse [repo](https://github.com/Karytonn/tabnews-google-search). Basicamente, trata-se de uma extensão para o navegador que faz buscas no Google com o formato `${query} site:tabnews.com.br`. Dessa forma, o Google retorna apenas os resultados sob o domínio `tabnews.com.br`.

Confesso que fiquei admirado com a eficiência das buscas e fiquei me perguntando se, nesse momento, realmente se faz necessário implementar um sistema de busca próprio ou utilizar a extensão ou o próprio Google já resolveria o problema (com buscas mais eficientes inclusive)?

PS: Vi em um post no TabNews alguém falar que os conteúdos postados levam cerca de 1 dia para serem indexados

PS 2: Na minha opinião, vale a pena utilizar o Google para buscar posts do TabNews, que além de não gerar custo nenhum pro TabNews, é extremamente eficiente e resolve o problema tranquilamente. O único problema que vejo é que é uma "feature" escondida. Acho que seria interessante ter pelo menos uma barra de busca dentro do TabNews que, assim que o usuário fizer uma pesquisa, ele é redirecionado para o Google com a pesquisa já feita. Acredito ser o melhor custo benefício entre valor gerado (usuário encontrar o que procura) e custo para manter (nesse caso, de graça).

**Comment by aprendendofelipe** [comment]
@mpedroni, obrigado pela sugestão! 💪

Obrigado também aos que contribuíram na discussão! 🤩

Apesar da conversa nessa issue ter se desenvolvido bastante, eu já direcionei diversas outras issues parecidas para a #927, que é mais antiga, então recomendo centralizarmos a conversa lá.

Vou fechar essa aqui. Combinado? 🤝
