### ISSUE TITLE
[REPORT]MarkDown vazando (criando DIV e demais codigos)

### ISSUE THREAD

**Issue by cybernerd007** [filipedeschamps/tabnews.com.br#1085]
Bom continuando meus testes descobri que utilizando o proprio sistema contra o sistema eu consegui fazer uma DIV não fui mais a fundo explorando essa falha porem acredito que se eu continuasse eu conseguiria injetar blocos de codigos inteiros comprometendo o site.

utilizando do mecanismo que comentar tags como `javascript` e demais notei que poderia utilizar para passar alguns codigos para o site
(AS SETAS VERMELHAS SÃO OS CODIGOS QUE PASSARAM, OS VERDES SÃO OS QUE FORAM PEGOS)
![Screenshot_1](https://user-images.githubusercontent.com/8114976/205458437-7e60f83f-0787-4939-ad9e-a9e5c1db3ee2.png)

![Screenshot_2](https://user-images.githubusercontent.com/8114976/205458440-5db9f9d6-864c-4be6-b658-559c778ff64f.png)

**Comment by cybernerd007** [comment]
**Deixo o link da publicação para verificar melhor** [**Publicação Teste**](https://tabnews-8kgcqlch1-tabnews.vercel.app/Matrixs0beit/xss-teste)

**Comment by cybernerd007** [comment]
**DEIXO O LINK PARA VERIFICAREM MELHOR** [**LINK DO TESTE](https://tabnews-8kgcqlch1-tabnews.vercel.app/Matrixs0beit/xss-teste)

**Comment by cybernerd007** [comment]
**DEIXO O LINK PARA VERIFICAREM MELHOR** [**LINK TESTE**](https://tabnews-8kgcqlch1-tabnews.vercel.app/Matrixs0beit/xss-teste)

**Comment by filipedeschamps** [comment]
@cybernerd007 vou remover esta publicação para conversarmos pelo contato@tabnews.com.br, pois isto pode ser sensível para estar assim de forma pública, combinado?
