### ISSUE TITLE
Estrelas como no Github, para guardar como favorito

### ISSUE THREAD

**Issue by cassioKenji** [filipedeschamps/tabnews.com.br#1086]
[FEATURE/SUGESTÃO]
Poder dar "estrela" para guardar como favorito e ler depois, assim como no Github.

**Comment by emerson-oliveira** [comment]
## [Sugestão / Melhoria] Implementar Funcionalidade de Favoritos

### Descrição:
Recentemente, encontrei um site chamado [CodeBites](https://www.codebites.dev/), que é um agregador de artigos de blogs para desenvolvedores. Uma das funcionalidades que me chamou a atenção foi a capacidade de adicionar postagens como favoritas. Acredito que seria muito útil se pudéssemos desenvolver uma funcionalidade similar em nosso site.

## Proposta
Minha sugestão é implementar uma funcionalidade de favoritos em nosso site, similar ao que o CodeBites faz. Isso permitiria aos nossos usuários marcar artigos de seu interesse para leitura futura.

## Benefícios
Ao implementar essa funcionalidade, poderíamos:
1. Aumentar o engajamento dos usuários, pois eles teriam a facilidade de salvar conteúdos de interesse.
2. Tornar nosso site um recurso mais personalizado e útil para nossa comunidade de usuários.

**Comment by aprendendofelipe** [comment]
Turma, obrigado pelas contribuições! 💪

Vou fechar diversas issues com assuntos relacionados. Por isso estou listando abaixo as que serão mantidas abertas e onde recomendo concentrarmos o que foi debatido/sugerido aqui:

- #645 
- #738
- #742 

Fechando essa aqui 🤝
