### ISSUE TITLE
Tabcoin Erro

### ISSUE THREAD

**Issue by cybernerd007** [filipedeschamps/tabnews.com.br#1087]
Bom hoje estava com 1tabcoin decidi apagar um comentario que era 1tabcoin logo pensei 1-1= 0... mas para a minha surpresa ficou -1 tabcoin fiquei sem entender pq ele não passou pelo ZERO já que comentario você ganha 1tabcoin acredito ser um erro.

**Comment by cybernerd007** [comment]
PS.: fiz alguns testes e realmente ele não esta passando pelo ZERO ele esta pulando direto para o -1

**Comment by 33gustavo33** [comment]
toda vez que você apaga um comentário/post você perde **2** tabcoins.

Como você tinha 1 tabcoin, então faz sentido que você tenha ficado com -1 tabcoin.
$(1 - 2 = -1)$

**Comment by cybernerd007** [comment]
comentario dá somente 1 tabcoin e não 2

**Comment by filipedeschamps** [comment]
Adicionando mais alguns pontos:

1. Toda vez que você deleta uma publicação (`root` ou `child`), você perde as TabCoins originais que ganhou criando ela, ou seja, hoje `2` TabCoins.
2. Além disso, se uma publicação possuía TabCoins **positivas**, você também perde elas.
3. Mas se uma publicação possuía TabCoins negativas, ao deletar, você continua sendo negativado por elas.
