### ISSUE TITLE
Colocar os artigos criados no perfil

### ISSUE THREAD

**Issue by guxtavodev** [filipedeschamps/tabnews.com.br#1088]
Não consigo encontrar um artigo que criei, poderiam colocar no perfil do usuário para ficar fácil de achar, para editar, deletar ou algo do tipo.

**Comment by jjeanjacques10** [comment]
@guxtavodev Já temos os artigos criados no perfil, só ir no menu e selecionar seu nickname. Será apresentada uma lista com seus artigos.

![image](https://user-images.githubusercontent.com/32225403/205665183-c7e54e26-87e9-4a64-a16d-2b97480fd99c.png)

**Comment by Jetrom17** [comment]
> @guxtavodev Já temos os artigos criados no perfil, só ir no menu e selecionar seu nickname. Será apresentada uma lista com seus artigos.
> 
> ![image](https://user-images.githubusercontent.com/32225403/205665183-c7e54e26-87e9-4a64-a16d-2b97480fd99c.png)
> 

Não só os artigos como os comentários feitos.

**Comment by jjeanjacques10** [comment]
Concordo, talvez adicionar 2 abas, uma para as publicações e outra para os comentários. Assim fica bem separado.

**Comment by rodrigoKulb** [comment]
Olá @guxtavodev conforme apresentado pelo @jjeanjacques10 os artigos e comentários são listados na aba do perfil. Você pode verificar que todos os comentários também ficam nessa área!

Se deseja sugerir **separa os comentários dos artigos** em ABAS, sugiro finalizar essa Issue como resolvida ou alterar o titulo da mesma. 

Muito obrigado ❤️!
