### ISSUE TITLE
Mixed content / insecure passive content

### ISSUE THREAD

**Issue by gabrielsozinho** [filipedeschamps/tabnews.com.br#1090]
Quando acessei [essa](https://www.tabnews.com.br/Rodrigo182/livros-gratuitos-de-programacao) publicação, o Firefox me deu o seguinte aviso:
![ilustration](https://i.imgur.com/ybKJQfr.png)

Clicando no saiba mais, ele me levou para essa página que fala mais sobre o problema: [Mixed content blocking in Firefox](https://support.mozilla.org/en-US/kb/mixed-content-blocking-firefox?as=u&utm_source=inproduct&redirectslug=how-does-content-isnt-secure-affect-my-safety&redirectlocale=en-US). 

Não sei até que ponto um atacante pode explorar essa falha, mas pesquisando sobre isso, ocorre porque o criador daquela publicação colocou alguns links que usam `http`.

As soluções mais simples que eu encontrei foram:
1. Adicionar `Content-Security-Policy: upgrade-insecure-requests` no cabeçalho da resposta.
2. Ou adicionar uma tag `meta` na seção `head`:  `<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">`.

Assim, o navegador automaticamente irá procurar os links via `https`.

Fonte: https://web.dev/i18n/en/fixing-mixed-content/
<br>
Não implementei pois uso o Codespaces pra desenvolver e nem consigo reproduzir a falha, ele deve ter alguma forma de impedir as requisições `http`.

**Comment by rodrigoKulb** [comment]
Olá @gabrielsozinho ótima observação mas acredito que não seja o problema dos links com http:// o problema todo está em um comentário que colocou uma imagem de origem sem https

![Captura de tela em 2022-12-07 22-56-23](https://user-images.githubusercontent.com/5334261/206337757-eb51d1da-5bcf-45c7-98db-f48da9a66ead.png)

Para evitar esse tipo de problema podemos bloquear imagens que não utilizaram https como origem, até porque o usuário pode acabar estragando uma postagem apenas colocando uma imagem sem https.

**Comment by rodrigoKulb** [comment]
Só pra teste coloquei uma imagem aqui no git com http ele cria uma nova imagem hospedada no github dentro do https
<img src="http://media-cdn.tripadvisor.com/media/photo-s/15/a4/9b/77/legacy-hotel-at-img-academy.jpg">
![Captura de tela em 2022-12-07 23-22-49](https://user-images.githubusercontent.com/5334261/206340896-3903d54c-5aaa-4a4f-9e4d-f48802649e15.png)

**Comment by rodrigoKulb** [comment]
Outro ponto esse erro é um pouco **grave** qualquer um pode quebrar um artigo / notícia colocando uma imagem de um servidor inseguro.

**Comment by rodrigoKulb** [comment]
@gabrielsozinho você estava certo, apenas adicionado esse header 
`<meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">`
Resolve o problema fiz o teste no meu servidor, a imagem é carregada pelo https mesmo colocando http.

![Captura de tela em 2022-12-07 23-47-34](https://user-images.githubusercontent.com/5334261/206343786-a232ddfd-aa98-4f79-a563-64ba4c203087.png)

**Comment by gabrielsozinho** [comment]
Obrigado @rodrigoKulb pelas pesquisas e testes! Eu acabei de abrir um PR implementando essa tag e também criei uma publicação no ambiente de homologação, para quando aquele PR for pra Preview, a gente conseguir testar: [https://tabnews-khg31eip0-tabnews.vercel.app/gsozinhos/test-mixed-content](https://tabnews-khg31eip0-tabnews.vercel.app/gsozinhos/test-mixed-content) (este link está em um deploy feito ontem (07/12))

**Comment by gabrielsozinho** [comment]
Resolvido por #1110.

**Comment by cybernerd007** [comment]
@rodrigoKulb @gabrielsozinho fiz uns testes e o erro persiste
![Screenshot_2](https://user-images.githubusercontent.com/8114976/206769043-eeafda52-711a-4d6e-981e-863e96f43553.png)

**Comment by gabrielsozinho** [comment]
@cybernerd007 Você não está usando a URL de um deploy antigo?

**Comment by cybernerd007** [comment]
@gabrielsozinho utilizei esse aqui https://tabnews-khg31eip0-tabnews.vercel.app/M0DERADOR/teste

**Comment by cybernerd007** [comment]
Meu navegador eu ativei pra ele forçar a conexão HTTPS sempre porem quando eu desativei para fazer o teste ele simplesmente carregou normalmente como esta no print que mandei.... LEMBRANDO ESSA CONFIGURAÇÃO E OPCIONAL NOS NAVEGADORES ENTÃO PODE ATINGIR O USUARIO FINAL....

**Comment by gabrielsozinho** [comment]
>@gabrielsozinho utilizei esse aqui https://tabnews-khg31eip0-tabnews.vercel.app/M0DERADOR/teste

@cybernerd007 É por isso, essa é a URL preview do `login-redirect`. Olha aqui a lista de deploys para preview mais recentes: [https://github.com/filipedeschamps/tabnews.com.br/deployments/activity_log?environment=Preview](https://github.com/filipedeschamps/tabnews.com.br/deployments/activity_log?environment=Preview)

Pela URL mais recente não existe mais isso: [https://tabnews-e7tweb4hc-tabnews.vercel.app/M0DERADOR/teste](https://tabnews-e7tweb4hc-tabnews.vercel.app/M0DERADOR/teste)

**Comment by aprendendofelipe** [comment]
> @gabrielsozinho utilizei esse aqui https://tabnews-khg31eip0-tabnews.vercel.app/M0DERADOR/teste

Você precisa acessar uma versão do sistema em que a atualização já existe. Esse deploy é de 2 dias atrás e a solução entrou no ar somente ontem.

**Comment by cybernerd007** [comment]
Erro meu, esqueci de pegar a ultima Deloy para fazer o teste foi mal pessoal...

**Comment by aprendendofelipe** [comment]
> Erro meu, esqueci de pegar a ultima Deloy para fazer o teste foi mal pessoal...

É mais provável, mas não é 100% de certeza que o último deploy vai ter todos os últimos commits, pois nada impede fazer um deploy em homologação a partir de uma branch desatualizada

**Comment by rodrigoKulb** [comment]
Estou esperando sair o curso de github do @aprendendofelipe 😅️
