### ISSUE TITLE
Opção de seguir dentro do tabnews follow

### ISSUE THREAD

**Issue by Marcoakira** [filipedeschamps/tabnews.com.br#1091]
Não encontrei outra issue.

Não tem muito oque encher linguiça, mas é notótio que existem pessoas que todo dia estão colocando algo interessante e relevante, quase um newsletter, e detrimento de outras pessoas que só postam coisas aleatórias.
Seria interessante existir uma guia, onde ficasse apenas as postagens das pessoas que ja consideramos relevantes.

ou seja, add SEGUIR

https://www.tabnews.com.br/drmarco/opcao-de-seguir-dentro-do-tabnews-follow

**Comment by nathyts** [comment]
Gostaria de pegar essa issue para desenvolver, mas queria validar algumas coisas sobre essa sugestão antes de começar a escrever o código.

[ ] Usuário pode seguir um outro usuário
[ ] Usuário pode parar de seguir um usuário que está seguindo
[ ] Usuário não pode seguir o seu próprio perfil
[ ] Aba com as publicações e respostas dos usuários que você está seguindo

Seriam estas as funcionalidades a serem implementadas?

**Comment by Diegiwg** [comment]
> 

Opa @nathyts, acredito que seja exatamente isso. Não tem muito mais para colocar nessa feature, a não ser uma mostrador de 'seguidores' no perfil do usuário. Mas acredito que isso não seja muito interessante, então 'apenas' implementar essas quatro features já será genial.

**Comment by Rafatcb** [comment]
Acredito que podemos considerar este issue duplicado do #645, que engloba seguir usuários ou conteúdo, e ter listas:

* https://github.com/filipedeschamps/tabnews.com.br/issues/645
