### ISSUE TITLE
Bug de Paginação

### ISSUE THREAD

**Issue by crhisdotaraujo** [filipedeschamps/tabnews.com.br#1092]
Uma breve história do acontecido:

Comecei a ler as publicações do TabNews às 8h de hoje (02/12/2022), tomando meu cafézinho, abrindo e lendo conteúdos muito interessantes (o pessoal tá de parabéns com as publicações de alto conteúdo e de alta variedade também), salvando algumas páginas nos favoritos para ler/reler depois.

Ao chegar no final da terceira página das publicações **Relevantes**, cliquei em **Próximo** e me deparo com página cinco, ao invés da página quatro.

![bugTabNews](https://user-images.githubusercontent.com/113248738/205703001-c610492c-05ce-4b09-986d-32e2c02a99ae.gif)

**Comment by aprendendofelipe** [comment]
Oi @crhisdotaraujo, uma possibilidade é a micro switch do seu mouse estar com defeito.

Chegou a verificar se não está disparando os cliques de vez em quando?

É um defeito pouco comum, mas que acontece.

**Comment by gabrielew** [comment]
Colocar um debounce enquanto esta buscando a anterior/próxima também ajudaria, @aprendendofelipe ?

**Comment by crhisdotaraujo** [comment]
Fala @aprendendofelipe, não é o mouse.
Testei em outros sites a funcionalidade de paginação, anterior/próximo, carrossel e em nenhum deles aconteceu a mesma situação de pular uma página.
Pode ter sido um caso isolado, pois hoje não está dando o problema novamente.

**Comment by aprendendofelipe** [comment]
> Colocar um debounce enquanto esta buscando a anterior/próxima também ajudaria, @aprendendofelipe ?

Não ajudaria, pois o componente `Link` do Next.js faz a busca antes do clique, então a navegação é praticamente instantânea. Por isso que o segundo clique já ocorre em um link diferente. Repare que a gravação mostra que ocorreram as duas navegações, a "instantânea" do primeiro clique e a segunda mais lenta porque não houve tempo de ocorrer o `prefetch`.

@crhisdotaraujo, deve ter sido algo isolado com o seu hardware, pois é pouco provável que exista esse bug no Next.js.

**Comment by rodrigoKulb** [comment]
@crhisdotaraujo fiquei curioso sobre esse problema, consegue nos atualizar se foi resolvido?

Tentei simular aqui com clique duplo e não pulou 2 páginas.

**Comment by arubesu** [comment]
Simulei aqui também e mesmo clicando duas vezes em "próximo"/"anterior" não pulou 2 páginas.

**Comment by aprendendofelipe** [comment]
@rodrigoKulb e @arubesu, acho difícil vocês simularem isso com um mouse que não esteja com defeito, pois a switch é projetada para evitar a quicada no sinal elétrico, ou seja, existe um *debounce* mecânico. 👍

É justamente esse mecanismo que faz o barulhinho "click" que dá nome ao ato de apertar o botão do mouse. 😉

No funcionamento normal, ao conseguir enviar o segundo sinal (dar o segundo click), a navegação já vai ter ocorrido, o scroll já vai ter mudado e o cursor não vai estar mais sobre o link.

Mas dá pra simular, por exemplo, focalizando o botão de navegação com a tecla "Tab" e disparando a tecla "Enter".

Obs.: Isso só ocorre da página 2 em diante, pois as páginas `/` ou `/recentes` não mantêm o mesmo elemento selecionado ao navegar para as páginas seguintes.

@crhisdotaraujo, estou fechando aqui, mas se você ver o defeito ocorrendo em outro hardware, favor nos avisar! 🤝

Valeu, pessoal!
