### ISSUE TITLE
[FEATURE/SUGESTÃO] Separar Posts de comentários no perfil do usuário

### ISSUE THREAD

**Issue by rein4nl1m** [filipedeschamps/tabnews.com.br#1093]
Ao entrar na página do perfil do usuário, conseguimos ver tudo que ele já publicou ou comentou em ordem cronológica decrescente.
Seria interessante se a gente pudesse ver somente os posts ou somente os comentários, separados por abas. Algo parecido com que temos aqui no GitHub, como o Write e Preview:

![image](https://user-images.githubusercontent.com/34170443/205746892-2a0186e6-53f6-4707-b79c-392fcfc03ac6.png)

Facilitaria pra quando a gente quisesse verificar o conteúdo que foi produzido e/ou as contribuições que o usuário deu nas postagens.

**Comment by aprendendofelipe** [comment]
@rein4nl1m, obrigado pela sugestão! 💪

Recomendo centralizar a discussão na #807. 👍

Vou fechar essa duplicada. Combinado? 🤝
