### ISSUE TITLE
Por que não migrar para NextJS?

### ISSUE THREAD

**Issue by thiagobessimo** [filipedeschamps/tabnews.com.br#1094]
Por que não usar um framework moderno que facilite a criação e atualização de componentes? Boa parte da web tem usado e com elogios até do próprio Filipe!

**Comment by felipsbreno** [comment]
@thiagobessimo o projeto já está usando Next.js.

**Comment by rodrigoKulb** [comment]
Olá @thiagobessimo se a resposta do @felipsbreno resolveu sua dúvida favor finalizar essa Issue! Muito obrigado! ❤️

**Comment by coffee-is-power** [comment]
???? O tabnews usa next já desde o começo
