### ISSUE TITLE
Extensão do Google Chrome para pesquisa no TabNews

### ISSUE THREAD

**Issue by Karytonn** [filipedeschamps/tabnews.com.br#1097]
_Orgulhosamente encontrei uma forma simples de contribuir com essa comunidade fantástica do TabNews._

**Já está online uma extensão do Google Chrome que possibilita fazer buscas no TabNews, o processo é bem simples e falo mais sobre isso em um post lá no site.**

POST:
https://www.tabnews.com.br/karytonn/extensao-de-pesquisa-para-o-tabnews

EXTENSÃO:
https://chrome.google.com/webstore/detail/tabnews-google-search/mdmnecmcjnlonddbfdhmgcfaggbpdgah

**Comment by jjpaulo2** [comment]
Ao invés de uma extensão pro browser, por que não incluir essa feature no site?

O código tá ai, é só forkar e mandar PR 😄

**Comment by jjpaulo2** [comment]
Inclusive existe uma issue que discute isso (#1084).
