### ISSUE TITLE
Sistema de TabCoins

### ISSUE THREAD

**Issue by danwhat** [filipedeschamps/tabnews.com.br#11]
Sim, eu sei que esta um pouco cedo para pensarmos na implementação. Mas nada impede a gente de debater como o sistema será.

Pensando aqui eu cheguei a um sistema que julgo legal. O meu foco foi:
- Deixar o mais simples possível. Se você não conseguir explicar para seu pet não vale.
- Resolve o problema de como as TabCoins são geradas.
- Incentiva a interação ao mesmo tempo que impede o flood

Lembrando que o importante é seu funcionamento. Por isso coloquei as variáveis em colchetes.  Sintam-se livres para ler com os números que julgarem mais justos.

## TabCoins (TC) é TabCoin Bonus (TCB)

A TabCoin será usada para sinalizar valor. Quando você "curte" uma notícia ou comentário, você estará sinalizando para a comunidade que esse conteúdo tem valor.

TabCoins:

-  Cada "curtida" gastará [1] TC (ou TCB, se tiver), e adicionará [1] TC ao saldo de que gerou o conteúdo.

- Sem TC você não poderá curtir

TabCoins Bonus:

- A cada [30 min] você ganhará [1] TCB.

- O máximo de TCB acumuladas serão [3] e seu saldo aparecerá junto do saldo de TC.
Ex.: Total de TabCoins: 357+3

- Ao curtir algum conteúdo, as TCB serão usadas antes das TC. Com isso incentiva quem é "pão duro" a sinalizar valor enquanto impede quem quiser **flodar** curtidas, já que após as TCB, você gastará suas TC para curtir.

- Ao ser usada, a TCB passa para o gerador de conteúdo como uma TC "comum". 

- Daqui que vem todas as TC do sistema. 

---

Gostei desse sistema pois o montante de TabCoins no sistema cresce conforme a comunidade cresce. Então se alguém tiver muito a mais que a média você sabe que essa pessoa acrescentou MUUUUITO valor a comunidade.

Pronto. O que acharam? Eu sei que tem falhas, mas como estou encantado não consigo ver. Então podem ir! Vai! Quebrem meu encanto! 🤣

**Comment by ArturHamannRonconi** [comment]
Opa tudo certo pessoal?
Eu gostaria de poder ter participado dessa discussão antes, lendo todos esses comentários acabou me deixando extremamente animado e fiquei um tempo no meu quarto pensando em várias situações que achei que poderiam ser interessantes.

Sou meio apreensivo sobre se realmente meus comentários podem ajudar ou se eu só estou gerando mais discussões desnecessárias, no fim, decidi compartilhar algumas possíveis regras de negócio que pensei, que talvez poderiam ser legais de implementar ou talvez pudessem ajudar em algum pensamento para melhoria (de qualquer forma já peço desculpas se a discussão realmente foi encerrada e se não é mais necessário criar comentários por aqui):

- O Revenue share Existiria em quantidade limitada e poderia ser trocado entre os usuários como se fosse ações em uma bolsa de valores (o que pode ser um incentivo para todos participarem).

- O Revenue share terá um valor de compra padrão para todos, porém, se um usuário tiver muitas TCs seu preço será em porcentagem Exemplo: 5 TabCoins e se o usuário tiver mais de 50 será 10% do que ele tem + 1 TabCoin (Isso fara com que o usuário não fique guardando muitas TabCoins para si).

- TCBs seriam somente utilizadas para dar "likes".

- TCBs seriam recebidas pelo tempo do usuário logado. Exemplo: 1 TCB a cada 20 min logado

- TCs podem ser utilizadas para "alugar" tempo de Revenue share Exemplo: eu como usuário gasto 10 TabCoins para ter 2 horas de Revenue share.

- Uma TCB se tornará uma TC quando dada a outro usuário através de "likes" em posts.

- Após o tempo estipulado do Revenue share alugado, o dono pode vender seu espaço para outro usuário pelo preço normal definido acima, mas não receberá o valor total, apenas uma porcentagem desse valor como um cashBack de 20%, caso o dono desse espaço de Revenue share não queira vender ele terá a escolha de "Re-alugar" pelo dobro do valor anterior que foi alugado (Dessa forma iria incentivar para que todos pudessem participar).

- A utilização de TCBs diária seria limitada a um determinado valor (o que faria com que os usuários pensassem 2 vezes se algo é realmente importante antes de dar um TabCoins)  Exemplo: 3 por dia.

-  Após atingir em um determinado valor de TabCoins em um post, o criador do post começa a receber o valor de TabCoins pela metade do valor anterior (isso fara com que a quantidade de TabCoins em um post chegue a ser quase uma nota, fazendo com que ela tenha um valor ideal a ser atingido e também fara com que um post não possa gerar valor infinito ao seu criador) Exemplo: ao chegar em 10 TabCoins, o usuário só receberá 0.5 TabCoins a cada usuário que der 1 TCB no post, quando chegar em 50 o usuário receberá 0.2 e assim por diante...

- TCs também poderiam ser utilizadas para dar TabCoins, entretanto, com algumas diferenças das TCBs, o usuário só pode usar TCs depois de utilizar o seu máximo de TCBs diário, uma TC daria seu valor inteiro ao criador do post independente da quantidade de TabCoins que um post tem, um também teria um valor máximo de TCs para dar por dia, após o usuário usar o valor máximo de TCs por dia durante alguns dias ele ganhará algum privilégio por isso (isso incentivará o usuário a dar likes e também dará um valor maior de TabCoins ao criador do post) Exemplo de privilégio: Após o usuário dar o máximo de TCs em likes durante 3 dias de uma mesma semana, no próximo post que ele fizer, irá ganhar o valor inteiro de TabCoins até um atingir um valor maior do que o valor escolhido da regra de cima

Espero que pelo menos eu tenha ajudado a pensar em maneiras diferentes de utilizar essas TCs e TCBs, é uma honra só poder fazer parte dessa discussão, agradeço a todos!!
