### ISSUE TITLE
🤔 [DUVIDA] Porque o Tabnews não utiliza um ORM para gerir a conexão com banco de dados?

### ISSUE THREAD

**Issue by Diegiwg** [filipedeschamps/tabnews.com.br#1106]
Estava lendo o código relacionado a busca de conteúdos e percebi que tudo está sendo feito em SQL puro, sem o auxílio de uma ORM.

Até onde sei, para projetos grandes (ou que serão grandes no futuro), o melhor é usar um ORM, para não se perder nas Querys enormes de SQL. E em NodeJS existe tantos ORM's, tal como o [Prisma](https://www.prisma.io/), [Sequelize](https://sequelize.org/), entre outros: [Top 11 Node.js ORMs, query builders & database libraries in 2022](https://www.prisma.io/dataguide/database-tools/top-nodejs-orms-query-builders-and-database-libraries#introduction).

``Minha dúvida é:`` porque não utilizar um ORM no projeto do Tabnews?

**Comment by klawdyo** [comment]
Em projetos grandes é necessário otimizar tudo o que for possível devido a questões de performance e custos. Não necessariamente esses ORMs fazem isso. Creio que a escolha por fazer as queries manualmente é com esse objetivo.

**Comment by Diegiwg** [comment]
> Em projetos grandes é necessário otimizar tudo o que for possível devido a questões de performance e custos. Não necessariamente esses ORMs fazem isso. Creio que a escolha por fazer as queries manualmente é com esse objetivo.

Entendi, achei que, os ORM's são softwares feitos para a única função de gerenciar um banco de dados. E, por isso, seus times estão focados em estabilidade, escalabilidade e segurança.

Logo, na minha concepção, 'escrever' tudo na mão, sem utilizar tais ferramentas, seria o mesmo que escrever todo o servidor Next na mão, usando alguma linguagem que não seja Javascipt, para ter o máximo de performance.

**Comment by rodrigoKulb** [comment]
Olá @Diegiwg apenas completando a resposta do @klawdyo o @filipedeschamps comentou sobre isso nessa Issue que rolou uma discussão muito massa que vale a leitura:
https://github.com/filipedeschamps/tabnews.com.br/issues/61#issuecomment-879463492
