### ISSUE TITLE
[DÚVIDA / SUGESTÃO] Validação de dados no backend.

### ISSUE THREAD

**Issue by SidiBecker** [filipedeschamps/tabnews.com.br#1107]
Olá!!

Gostaria de saber o motivo, de no login e cadastro por exemplo, as validações de campo válido serem feitas apenas no backend. Exemplo: campo email não informado, ou formato inválido.

Trazer essas validações "padrões" **também** para o frontend, não iria economizar o uso de servidor? Além de em conexões mais lentas melhorar o processo?

Abraço!

![image](https://user-images.githubusercontent.com/40251890/206347724-304bb893-f720-4b8c-83e1-6426d227ca8b.png)

**Comment by Rafatcb** [comment]
As validações mais simples costumam ficar no frontend para adiantar o processo, mas trazer todas as validações causaria duplicação das próprias validações, dificultando a manutenção e é bem provável que em algum momento as validações ficassem diferentes porque alguém só alterou em um dos lados.

Apesar disso, a validação do campo ser obrigatório ou não é bem simples e poderia estar no frontend sim. Inclusive, os campos no cadastro deveriam ter o indicador de campo obrigatório, de acordo com as recomendações na [documentação do TextInput](https://primer.style/components/text-input#anatomy), e o Login também deveria, mas não me lembro se os sites e aplicações costumam mostrar que o login e senha são "obrigatórios" para entrar.

**Comment by aprendendofelipe** [comment]
> Gostaria de saber o motivo, de no login e cadastro por exemplo, as validações de campo válido serem feitas apenas no backend.

Um motivo importante é que no backend temos testes e no frontend ainda não.

> Trazer essas validações "padrões" **também** para o frontend, não iria economizar o uso de servidor?

Quanto ao processamento no servidor a diferença seria irrisória, já quanto ao tráfego de dados, seria maior, pois o código de validação seria trafegado sempre, enquanto validando no servidor só existe tráfego extra quando os dados não passam na validação.

> Além de em conexões mais lentas melhorar o processo?

Acho que esse é o ponto que pode estar a favor de validar no client. Quando tivermos testes no frontend acho que pode valer a pena levar algumas validações para o client **se isso melhorar a UX** por trazer um feedback mais rápido.

Mas será preciso testar, pois com o processamento na *edge*, talvez não haja diferença significativa de UX que justifique a manutenção extra por ter validação em diferentes locais.

Vou fechar a issue, mas qualquer coisa podemos reabrir 🤝
