### ISSUE TITLE
Adicionar contador de "Visitas" nos posts

### ISSUE THREAD

**Issue by Diegiwg** [filipedeschamps/tabnews.com.br#1109]
Acredito que, seria muito interessante para os autores, se tivesse um contador em seus posts, que mostra-se a quantidade de visitas (total) que o post recebeu.

Não acho interessante ser uma informação 'publica', seria uma informação que iria aparecer apenas para o dono do post, como uma métrica pessoal.

Exemplo simples, com uma única string extra, logo no início do post:
![a11](https://user-images.githubusercontent.com/15692310/206452587-4e60f71a-5e72-4a4d-95d1-2c5c27905030.PNG)

**Comment by Rafatcb** [comment]
É uma boa sugestão. Acho que podemos marcar como dupllicada da #1115 que, apesar de ser mais nova, recebeu mais atenção:

* https://github.com/filipedeschamps/tabnews.com.br/issues/1115
