### ISSUE TITLE
Discussão

### ISSUE THREAD

**Issue by Jetrom17** [filipedeschamps/tabnews.com.br#1111]
Alguém concorda ao criar uma aba de discussão? 

Deixar **issue** para desenvolvimento da plataforma.

**Comment by gabrielsozinho** [comment]
Isso já foi sugerido antes nas issues #598 e #480. Olha o que o Filipe respondeu: https://github.com/filipedeschamps/tabnews.com.br/issues/480#issuecomment-1182525179.

**Comment by Jetrom17** [comment]
> Isso já foi sugerido antes nas issues #598 e #480. Olha o que o Filipe respondeu: https://github.com/filipedeschamps/tabnews.com.br/issues/480#issuecomment-1182525179.

Poxa vida. Pelo menos um formulário de bug... Ok...
