### ISSUE TITLE
Adicionar uma descrição dos botões

### ISSUE THREAD

**Issue by Hanufu** [filipedeschamps/tabnews.com.br#1114]
Não sei se só aconteceu comigo, mas acho bastante importante adicionar alguma informação nos botões de "like" e "deslike" dos posts
![Captura de tela 2022-12-08 231754](https://user-images.githubusercontent.com/45810581/206609091-612e705b-256a-4092-8566-0b3918ecbf8f.png)
Até por que a gente passa o mouse por cima, e não mostra nada, e como aconteceu comigo eu fiquei clicando que nem maluco, pra saber o que acontecia, e só depois que vim perceber que ali era o botão de adicionar tabcoin na publicação kkk Essas pequenas coisas ajudam bastante, não só a quem usa entender, mas na acessibilidade.

**Comment by filipedeschamps** [comment]
Sugiro testar em Mobile para ter certeza que o texto não ficará cortado, pois se eu não me engano, ele irá aparecer depois do `tap` (mas posso estar errado).

**Comment by B-Schmitz** [comment]
> Sugiro testar em Mobile para ter certeza que o texto não ficará cortado, pois se eu não me engano, ele irá aparecer depois do `tap` (mas posso estar errado).

No mobile realmente, fica cortado, uma solução seria renderizar o tooltip a direita?

**Comment by aprendendofelipe** [comment]
Já está praticamente pronto no PR #1277 

Só falta o @PauloIVM resolver os conflitos de merge

**Comment by aprendendofelipe** [comment]
@Hanufu obrigado pela issue! 💪

Já foi implementado no PR #1277 então estou fechando essa aqui, ok? 👍
