### ISSUE TITLE
Adicionar campo de "notificações"

### ISSUE THREAD

**Issue by AdonisUchoa** [filipedeschamps/tabnews.com.br#1116]
Basicamente notificar o usuário quando alguém houver respondido o post dele ou o comentário

**Comment by aprendendofelipe** [comment]
Turma, obrigado pelas contribuições! 💪

Vou fechar diversas issues com assuntos relacionados. Por isso estou listando abaixo as que serão mantidas abertas e onde recomendo concentrarmos o que foi debatido/sugerido aqui:

- #645 
- #738
- #742 

Fechando essa aqui 🤝
