### ISSUE TITLE
SUGESTÃO - Favoritar ou seguir as publicações

### ISSUE THREAD

**Issue by gabrielfpereira** [filipedeschamps/tabnews.com.br#1117]
Seria interessante poder marcar uma publicação como favorito e lista-las depois ou até mesmo poder seguir uma publicação para sempre que alguém comentar algo sermos notificado.

**Comment by giovanirorato** [comment]
Concordo essa é uma funcionalidade essencial.

**Comment by codigocafe** [comment]
@gabrielfpereira  e @giovanirorato , vocês acham que deve utilizar os TabCoins para adicionar em favoritos - para causar a incentivo de mais publicações - ou deixar só o botão de favoritos sem requerir nada?

**Comment by fellipematos** [comment]
@gabrielfpereira realmente faz falta algo para acompanhar as postagem, marca como favorito seria uma excelente ou salvar para ler mais tarde. tenho um monte de guia aberta kkkkkk aguardando eu ler e fazer minhas anotações.

Em resposta para @codigocafe, acredito que sem cobrar TabCoins.

**Comment by antsoftsystems** [comment]
Importante implementação, pois devido ao grande volume de publicações diária, fica mais complicado achar uma que nos interessou em algum momento, principalmente se for antiga. Obviamente que um sistema de busca facilitaria até certo ponto, mas e se você esquecer o título do post? Favoritar, na minha singela opinião, é bem mais que bem-vindo ao TabNews.
@codigocafe sem cobrança de tabcoins

**Comment by ItanuRomero** [comment]
Acabei de encontrar um artigo incrível que eu gostaria de salvar, como estamos com essa ideia?

**Comment by aprendendofelipe** [comment]
Obrigado pela issue! 👍

Por organização, estou fechando as duplicadas com a #645 🤝
