### ISSUE TITLE
Não é possível acessar um comentário (Erro 500)

### ISSUE THREAD

**Issue by gabrielsozinho** [filipedeschamps/tabnews.com.br#1119]
Não sei se o @cybernerd007 já percebeu, mas existe um comentário dele que não é possível acessar, aparece a seguinte mensagem:
![](https://i.imgur.com/tWx4WfL.png)

Link: https://tabnews-e7tweb4hc-tabnews.vercel.app/M0DERADOR/09114c6b-2503-41d9-9b73-2914292a175d

Olhando pela API, o comentário não é nada mais (eu acho) que um `</div></code>`.  O curioso é que eu fiz um comentário com o mesmo conteúdo e ele é possível acessar: https://tabnews-e7tweb4hc-tabnews.vercel.app/gsozinhos/0c4da1ea-bb7e-4b20-b4b4-b57a5e06f2c0

**Comment by cybernerd007** [comment]
@gabrielsozinho esse erro eu ja havia tratado com o @filipedeschamps

**Comment by gabrielsozinho** [comment]
@cybernerd007 ah sim, então vou fechar essa issue. 🤙
