### ISSUE TITLE
SUGESTÃO - Melhorar o layout da listagem das tabnews.

### ISSUE THREAD

**Issue by Daniel-iel** [filipedeschamps/tabnews.com.br#1120]
Para melhorar listagem da página inicial, fiz a sugestão da imagem abaixo.

**1** - Foto do perfil, nome do usuário da publicação e a data da publicação.
**2** - Uma prévia da publicação.
**3** - Tempo de leitura e a remoção do nome do usuário(nome do usuário foi para o item 1).
**4** - Remover a numeração da lateral esquerda.
**5** - Uma sutil linha separando as tabnews.

![image](https://user-images.githubusercontent.com/12504110/206852278-a20355f2-49a2-4d49-9473-1206a13fc831.png)

**Comment by ezequiaslopesdasilva** [comment]
Gostei da ideia **2** de colocar uma prévia da publicação e também da ideia **3** de adicionar um algoritmo para estimar o tempo de leitura.

Não gosto da ideia de remover os números da lateral pois com eles eu não me perco na hora que estou lendo um conteúdo (mesmo tendo o sistema que identifica os conteúdos já lidos).

Gosto da ideia de colocar uma foto de perfil (inclusive penso em implementar um sistema que sincroniza com a imagem do Github), só que com o estágio atual do TabNews, existem coisas que tem mais prioridade de serem implementadas.

**Comment by gabrielsozinho** [comment]
1. Sobre a foto de perfil, outro dia eu discuti isso com alguém (infelizmente não lembro quem), e o ponto que essa pessoa levantou foi que não seria interessante mostrar a foto de perfil da pessoa dentro da publicação porque os posts deveriam ser avaliados pelo conteúdo e não pela "beleza" da pessoa. Isso também talvez deixasse a home mais poluída. 
   A alternativa seria mostrar a foto de perfil apenas ao acessar o perfil do usuário.
2. Eu gosto do jeito que é hoje. E a ideia do TabNews é poder ler os títulos de forma linear. Uma ideia que já foi sugerida, inclusive por mim, é adicionar um preview ao passar o mouse por cima da publicação, como acontece aqui no Github e até no YouTube.
   ![image](https://user-images.githubusercontent.com/90806505/206865440-c9e91f5d-3808-44c6-b40d-a973b0a7a856.png)
3. Seria excelente, Medium é assim se não me engano.
4. Nesse ponto eu concordo totalmente com o @ezequiaslopesdasilva 
5. Volto ao mesmo ponto que abordei no item 2, a ideia do TabNews é poder ler os títulos de forma linear, talvez com a linha isso se torne mais difícil.
