### ISSUE TITLE
[SUGESTÃO] - Aprimoramento de layout e novas funcionalidades

### ISSUE THREAD

**Issue by Robson-Vasconcelos** [filipedeschamps/tabnews.com.br#1121]
Olá pessoal, gostaria de propor um aprimoramento de layout.
*Além do design, a proposta também inclui a criação de algumas funcionalidades que julgo importantes, dentre elas:

1.Tags;
2.Busca de conteúdos;
3.Links para agrupamentos do tipo (recentes,recomendado,seguindo (usuários), "criados por mim");
4.Notificações (Mas somente dentro da plataforma, quando o usuário fizer login);

Segue a imagem da minha proposta:

![Desktop - 1 (5)](https://user-images.githubusercontent.com/71492179/206874400-eed4a35b-db91-452b-b75f-5025abce168d.png)

*Esse layout é um conceito criado no Figma inspirado no Flarum, adaptado às características do TabNews.
O objetivo é aprimorar a experiência do usuário com pitadas de UI/UX adicionando cores e elementos mais destacados.

**Comment by aprendendofelipe** [comment]
Oi @Robson-Vasconcelos, muito legal essa proposta, não só o design, mas também os elementos que você adicionou e que ainda não temos no TabNews. Bom trabalho! 🤩

Mas para o começo do TabNews foi decidido seguir o máximo possível o design do GitHub.

Na **minha opinião** temos algumas vantagens com isso, entre elas:

1. Podemos aproveitar bastante a biblioteca de componentes React do GitHub (Primer);
2. Evitamos algumas decisões de UI, UX, acessibilidade etc. que tomariam um tempo que pode ser dedicado para a implementação de funcionalidades;
3. Aproveitamos um design que foi pensado para um público muito similar ao do TabNews;
4. Evitamos problemas de falta de identidade entre partes do sistema desenvolvidas por diferentes colaboradores.

Acredito que em algum momento futuro o TabNews pode se distanciar bastante do GitHub para reforçar ainda mais a identidade própria, então qualquer proposta é válida.

Mas eu adoraria ver outras versões de layout em que, por enquanto e dentro do possível, não fugissem muito da proposta inicial.

E para trazer mais soluções do que problemas, qualquer proposta de layout precisa funcionar bem:

1. Em diferentes tamanhos de tela;
2. Independentemente da criação de novas funcionalidades. 

E volto a frisar que é só a minha opinião pessoal. 👍

**Comment by iihieiii** [comment]
Bacana !

**Comment by Robson-Vasconcelos** [comment]
Obrigado pelo feedback Felipe!.
Gosto de aplicar UI, UX nos meus projetos Front-end e gostei bastante do TabNews por isso fiz a proposta de aprimoramento.
Realmente a proposta inclui novas funcionalidades, naturamente. Dentre elas:

1.Tags;
2.Busca de conteúdos;
3.Links para agrupamentos do tipo (recentes,recomendado,seguindo (usuários), "criados por mim");
4.Notificações (Mas somente dentro da plataforma, quando o usuário fizer login);

De qualquer modo, não precisam ser aplicados integralmente. É apenas  um conceito que pode ser aproveitado no futuro.
Fico à disposição para ajudar nas implementações do código e para contribuir com o projeto em geral. 😄
