### ISSUE TITLE
SUGESTÃO - Progressive Web Apps (PWA)

### ISSUE THREAD

**Issue by darnley** [filipedeschamps/tabnews.com.br#1124]
Que tal o TabNews permitir a instalação como um Progressive Web Apps (PWA)?

Com um PWA, eu posso fixar o TabNews na minha barra de tarefas como se fosse um aplicativo do computador. Além disso, consigo fazer uso dele dentro do meu celular também como se fosse um aplicativo, mas, na verdade, está abrindo no browser por trás dos panos.

# O que mudaria para o usuário?
Tendo a instalação do PWA, seja no desktop ou mobile, teria um link direto na sua página inicial para o TabNews como se fosse um aplicativo.

## Desktop
Quando abrir o TabNews, o próprio navegador identifica que o site está configurado para PWA e sugere a instalação como aplicativo.
![image](https://user-images.githubusercontent.com/4915497/206883816-d1f1e192-b201-497a-a279-93f0e5783133.png)
(Fonte: https://web.dev/learn/pwa/installation/#desktop-installation)

## Mobile
Parecido com o desktop, nos aparelhos móveis existe a opção de "Add to Home Page" ou "Adicionar à Página Inicial" quando é um PWA.

### iOS
![image](https://user-images.githubusercontent.com/4915497/206883875-4a9ebef7-d4f8-49e2-9337-0c6635363ea6.png)
(Fonte: https://web.dev/learn/pwa/installation/#ios-and-ipados-installation)

### Android
![image](https://user-images.githubusercontent.com/4915497/206883847-7970339f-4ab9-48fc-b0a8-ab7e48e23ff9.png)
(Fonte: https://web.dev/learn/pwa/installation/#android-installation)

Referência: https://web.dev/learn/pwa/installation/

**Comment by leoferreiralima** [comment]
Acabei tendo exatamente essa Ideia, seria muito interessante termos essa opção, fica literalmente na palma da mão o acesso, Vi que existe um pacote chamado next-pwa que parece bem simples de configurar

**Comment by Poveii** [comment]
Eu uso a feature de poder criar um atalho do Tabnews pelo Chrome no meu celular a bastante tempo, desde que lançou oficialmente, e até agora nada de bugs em relação a isso, é exatamente como se eu usasse no próprio navegador. E tem até splash screen.

Até um possível App oficial do Tabnews em React Native, poderíamos tentar isso.

**Comment by aprendendofelipe** [comment]
@darnley, obrigado pela sugestão! 💪

Não aparece para você a opção de instalar? Isso já foi implementado há muito tempo.

Caso esteja aparecendo, pode encerrar a issue 🤝

**Comment by darnley** [comment]
> @darnley, obrigado pela sugestão! 💪
> 
> Não aparece para você a opção de instalar? Isso já foi implementado há muito tempo.
> 
> Caso esteja aparecendo, pode encerrar a issue 🤝

Opa, @aprendendofelipe! Verifiquei aqui e já está implementado mesmo neste momento. Obrigado por avisar. Diante disso, vou encerrar a issue. ;)
![image](https://github.com/filipedeschamps/tabnews.com.br/assets/4915497/fb972fb4-d8cc-44a6-8221-ce7724f654c9)
