### ISSUE TITLE
Acesso a API foi bloqueada pela política do CORS

### ISSUE THREAD

**Issue by Dev-Lyh** [filipedeschamps/tabnews.com.br#1125]
Boa tarde turma, tudo beleza?
Seguinte, eu tive uma ideia de site a parte do TabNews, chamado TabSaves (para favoritar algum post que o usuário achou útil). Para isso eu precisaria do ID fixo de cada usuário, porém, seria necessário a autenticação por meio da conta do TabNews (email e senha não seriam armazenados, apenas o ID fixo).
Mas tive um problema com o CORS que não está deixando eu fazer o request para a API, no endpoint `/sessions`.

Meu código está chamando a API assim:
```js
fetch(`https://www.tabnews.com.br/api/v1/sessions`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Accept": "application/json",
      },
      body: JSON.stringify({
        "email": {userMail},
        "password": {userPassword},
      }),
    }).then(res => res.json()).then(json => console.log(json)).catch(err => console.log(err))
```
E o erro que estou recebendo é esse:
```
Access to fetch at 'https://www.tabnews.com.br/api/v1/sessions' from origin 'http://127.0.0.1:5173' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.
```

**Comment by coffee-is-power** [comment]
Na verdade o navegador meio que tem razão, porque você está tentando usar os cookies do tabnews para fazer requests não consentizados pelo usuário, por isso que o CORS existe.

**Comment by Dev-Lyh** [comment]
Infelizmente, mesmo colocando essa opção continua a retornar o mesmo erro.

**Comment by danielschmitz** [comment]
é incompatibilidade entre http e https

tente usar "http**s**://127.0.0.1:5173"

**Comment by Dev-Lyh** [comment]
> é incompatibilidade entre http e https
> 
> tente usar "http**s**://127.0.0.1:5173"

Infelizmente, ainda não foi. O que não entendo é que no React-Native consigo chamar a API normalmente, mas em Node e ReactJS tá dando esse problema.

**Comment by coffee-is-power** [comment]
Leia sobre o CORS nos navegadores, no react native nao tem esse problema porque não roda em um navegador, então ele não guarda cookies, vc precisa explicitamente mandar o header `Cookie`.

**Comment by Dev-Lyh** [comment]
Como eu ainda não consegui fazer minha aplicação funcionar, mesmo com a ajuda de vocês, irei fechar a issue, já que aparentemente deve ser um problema que só está acontecendo comigo, por algum motivo.

Obrigado a todos que tentaram ajudar :)

**Comment by aprendendofelipe** [comment]
@Dev-Lyh, obrigado por reportar! 💪

Não sei se conseguiu contornar de alguma forma, mas uma solução acabou de ir para produção com o merge do PR #1678 👍

**Comment by Dev-Lyh** [comment]
Olá, @aprendendofelipe!
Na época em que fiz em que comecei o projeto e me deparei com esse erro, parei de desenvolve-lo. Mas essa semana vou ver se consigo dar uma olhada nesse PR para verificar se consigo recomeça-lo.
Obrigado por lembrar dessa issue! 😁
