### ISSUE TITLE
Separar por tag

### ISSUE THREAD

**Issue by PRMSA** [filipedeschamps/tabnews.com.br#1126]
Na minha opinião separar os vários posts por tags seria mais efetivo, atualmente se alguem fizer uma pergunta ela será eternamente colocada para baixo por novos posts como tutoriais, notícias, artigos etc.

Então seria algo bom algo parecido com o sistema do stackoverflow.

**Comment by codigocafe** [comment]
@PRMSA , essas tags seriam pré-definidas ou o usuário iria colocar suas tags / keywords com limite keywords para não inserir uma publicação nas tags?  

Possuí uma [issues](https://github.com/filipedeschamps/tabnews.com.br/issues/1136) parecida com esta aqui.

**Comment by PRMSA** [comment]
poderia ser predefinida com um 'navebar' já no site, assim o usuário seria restrito na busca, e o usuário podendo também colocar as tags q achar necessário para ajudar em buscas menos restritas além de fornecer mais informações sobre o contexto do post

**Comment by codigocafe** [comment]
Não sei se possui moderador no site, mas seria um trabalho chato para adicionar novos tópicos, já que a TIC possui uma evolução grande e rápida, todos os dias possui assunto novo.

**Comment by PRMSA** [comment]
adiciona só os básicos como separar por tipo de post e liguagem de programação.
Tipo de posts: Tutorial, Artigo, Noticia, Perguntas
Linguagem é auto explicativo já as tags q o usuário adicionar é apenas pra ser restringir o q terá no post

**Comment by codigocafe** [comment]
ótima ideia.

**Comment by rodrigoKulb** [comment]
Pessoal estamos com várias Issues sobre esse assunto, vamos unificar a discussão na mais antiga?
#742 
@PRMSA poderia finalizar essa?

**Comment by aprendendofelipe** [comment]
@PRMSA, obrigado pela sugestão! 💪

Como o @rodrigoKulb mencionou, já existe uma issue sobre o assunto (#742), então também recomendo continuar a conversa por lá.

Vou fechar essa aqui. Combinado? 🤝
