### ISSUE TITLE
Modo Noturno

### ISSUE THREAD

**Issue by MaiconLuksik** [filipedeschamps/tabnews.com.br#1127]
Hoje estava eu navegando pela TabNews a noite, e o que me deu um certo desconforto foi não ter o modo noturno nela.
Seria possível implementar algo nesse sentido? Acredito que seria interessante e ajudaria na leitura noturna.

**Comment by samuelrvg** [comment]
@MaiconLuksik Eu pensei a mesma coisa hoje, já ia abrir uma ISSUE para isso.

**Comment by danielschmitz** [comment]
tem duas extensões no chrome, dark mode e dark reader

**Comment by saraiva1989** [comment]
@filipedeschamps ou admins, Eu iniciei a implementação do dark mode;

![image](https://user-images.githubusercontent.com/40599423/216158568-0563804c-338e-4725-8f3c-d918c721c6cc.png)

![image](https://user-images.githubusercontent.com/40599423/216158625-055c25d2-930c-4e41-affa-44804392da43.png)

Ainda tem alguns ajustes a ser feito, colocar no checkbox um css bonitinho e ajustar algumas coisas mais.

basicamente eu criei um CSS e altero as variaveis dependendo do tema

![image](https://user-images.githubusercontent.com/40599423/216158861-86c971b0-b088-4378-85ec-ff4b147d92d5.png)

![image](https://user-images.githubusercontent.com/40599423/216158891-3fb890fe-3d40-47e6-9cb2-cc24df681732.png)

Gostaria de saber se posso dar continuidade na implementação.

**Comment by aprendendofelipe** [comment]
Boa @Rafatcb! E obrigado pela sugestão @MaiconLuksik! 💪

O modo noturno já foi implementado e o histórico está distribuído em diferentes PRs e issues, mas um local onde tudo (ou quase tudo) está referenciado é no #1199, então podemos encerrar esse aqui. 🤝
