### ISSUE TITLE
Sem permissão para fazer login, erro: create:session

### ISSUE THREAD

**Issue by Leodots** [filipedeschamps/tabnews.com.br#1128]
Salve galera, como vocês estão? 

Estou tendo problemas ao tentar efetuar login no site do tabnews. Ao colocar meu email e senha eu recebo a mensagem de erro abaixo:

"Você não possui permissão para fazer login. Verifique se este usuário possui a feature "create:session"."

Já fiz a confirmação de senha no meu email tudo certinho, mas ainda sim sem sucesso ao efetuar o login, poderiam me ajudar?

Meu email: xxx

Username: leodots

**Comment by filipedeschamps** [comment]
@Leodots removi da issue o seu email. Você poderia enviar um email para contato@tabnews.com.br com o email que utilizou no cadastro?

Um abração!

**Comment by Leodots** [comment]
Filipe informou por e-mail que eu fiz o cadastro em um momento que o site estava passando por instabilidades, e o mesmo corrigiu o problema na minha conta.

Muito obrigado pela ajuda!
