### ISSUE TITLE
Atualização da extensão de busca [Versão Firefox ✅]

### ISSUE THREAD

**Issue by Karytonn** [filipedeschamps/tabnews.com.br#1129]
### Update v.0.0.4 ✅
- Adição de novo método de encode para evitar a exclusão de caracteres fora do conjunto ASCII, como por exemplo `#`.
- Liberado [versão para Firefox🦊](https://addons.mozilla.org/pt-BR/firefox/addon/tabnews-google-search/)

[Saiba mais](https://www.tabnews.com.br/karytonn/extensao-de-pesquisa-para-o-tabnews)

**Comment by coffee-is-power** [comment]
Faz a extensão do Firefox funcionar no android

**Comment by Karytonn** [comment]
> Faz a extensão do Firefox funcionar no android

Obrigado pela sugestão, vou adicionar ao roadmap de validação e caso se torne um update então o informo aqui.

**Comment by aprendendofelipe** [comment]
Boa @Rafatcb! E obrigado @Karytonn! 💪

Fechando a issue. 🤝
