### ISSUE TITLE
Sugestão de redesign do TabNews 😱

### ISSUE THREAD

**Issue by TiagoXavierSavioli** [filipedeschamps/tabnews.com.br#1135]
![TabNews redesign](https://user-images.githubusercontent.com/71526510/207656499-b47def8f-de2f-4177-99db-0e5feeb9cb8b.png)

Confira o design no Figma: [link](https://www.figma.com/file/G0p98rf4It7pIbBXQBcmP4/TabNews-Redesign?t=Y1QJNUHivTopOK8d-1)

### Porquê um redesign?

- adiciona uma indentidade visual mais consistente
- melhora a experiência do usuário, e primeiras impressões do site
- transmite maior credibilidade

### Features do novo design

- Adiciona mais visibilidade as moedas do site (TabCoins/TabCash)
- Torna o botão de criar conteúdo mais visível, estimulando mais a criação de valor no site
- Separa melhor barra de navegação do site, tornado melhor de se navegar
- Adiciona foto de perfil, assim ficando mais fácil a diferenciação entre usuários,
- colocando uma barra de pesquisa fica mais fácil achar um conteúdo de interesse (Ideia dos próprios usuários)
- separação de conteudos adicionando espaçamento entre os mesmos tornando a leitura mais fácil
- aplicando os valores visuais corretos nos conteúdos, aumentando os botões, e dando mais impotância aos títulos
- adição do número de visualizações nos conteúdos (Ideia dos próprios usuários)

link do post no TabNews: [link](https://www.tabnews.com.br/tiagoxsavioli/sugestao-de-redesign-do-tabnews)

**Comment by fabriciolak** [comment]
Tiago, recomendo você seguir um padrão de design system do [Primer](https://primer.style/), pois o tabnews usa e daria mais consistência ao design.

Também seria legal ter a visualização individual de cada componente, para ter mais detalhes sobre variantes, estados e afins.

P.S.: Eu gostei bastante do design, tanto que gostaria muito de fazer um redesign do tabnews e codar. Até coloquei na lista de projetos futuros. 👻

**Comment by mthmcalixto** [comment]
@TiagoXavierSavioli o melhor que eu vi até agora haha!

**Comment by Rafatcb** [comment]
Acho que fazer um redesign por completo seria um "trabalho atoa". É mais importante focar na melhoria da usabilidade, correção de bugs e novas funcionalidades. Dito isso, nada impede de fazer melhorias pontuais que poderiam ser consideradas "redesigns" de coisas específicas. Lembrando que usamos os componentes do Primer com o objetivo de não precisar estilizar as coisas, e se aproximar do design do GitHub.

Por ser algo muito abrangente, acho que faz sentido fecharmos este issue para organizar o repositório.
