### ISSUE TITLE
Localizar conteúdo

### ISSUE THREAD

**Issue by EuCesarCarvalho** [filipedeschamps/tabnews.com.br#1136]
Uma boa sugestão é colocar a opção de localizar conteúdo, como a uma gama de assuntos, o usuarios pode localizar seus conteudos para leitura.

**Comment by codigocafe** [comment]
Pode ser utilizado no formato de nuvem de tags ou colocar um campo de busca para facilitar a localização de conteúdos.

**Comment by jjpaulo2** [comment]
Tá rolando uma discussão em #1084 sobre busca de conteúdo. Acho que talvez dê pra aproveitar algo de lá.

**Comment by aprendendofelipe** [comment]
@EuCesarCarvalho, obrigado pela sugestão! 💪

Vou fechar essa por ser duplicada, e recomendo centralizar a discussão nas issues relacionadas abaixo:

- #742 
- #927 

Cominado? 🤝
