### ISSUE TITLE
[Feature Request] Hall da Fama

### ISSUE THREAD

**Issue by ozzono** [filipedeschamps/tabnews.com.br#1137]
# Feature Request
## Hall da Fama
Seria legal ter uma aba que, a priori, estou chamando de `Hall da Fama`.
Para esse hall consideraríamos visualizações, `thumbs-up` e comentários (ou poderíamos ordenar escolhendo um dos três parâmetros como critérios). Também acho pertinente ter um critério de engajamento relacionado com o tempo, afinal, naturalmente, bons posts antigos tendem a ter melhores número do que os novos, então poderíamos usar algo como `visualizações/dia`.

**Comment by Rafatcb** [comment]
Obrigado pela sugestão, ozzono! Já temos um issue aberto sobre a possibilidade de listar por TabCoins, mas acabei editando ele para ficar mais abrangente e englobar sua sugestão também, assim podemos concentrar a discussão em um único issue.

* https://github.com/filipedeschamps/tabnews.com.br/issues/1043
