### ISSUE TITLE
Tag - Meta - Article - Telegram - Sugestão

### ISSUE THREAD

**Issue by Jetrom17** [filipedeschamps/tabnews.com.br#1139]
Como sabem, o Telegram tem um formato que é possível ler um artigo sem sair da plataforma.

Veja na imagem: 

![Screenshot_20221218-174103-629.png](https://user-images.githubusercontent.com/72875404/208318883-c1fbe36d-549f-44e9-8fb8-e4e8cfbded18.png)

![Screenshot_20221218-174121-070.png](https://user-images.githubusercontent.com/72875404/208318533-a7cc9529-d941-42f3-8fa9-77746a958697.png)

Percebi que a tag usado é:

```js
<meta property="og:type" content="article" />
```

Diferente de um dos posts do TabNews:

![Screenshot_20221218-174137-917.png](https://user-images.githubusercontent.com/72875404/208318597-a1efc224-a756-4033-9c14-87bea5947efd.png)

Tag usado é:

```js
<meta property="og:site_name" content="TabNews"/>
```

Minha **sugestão** é, poderiam adicionar mais essa tag? Não sei se existem conflitos ou é exibido em outros além do Telegram.

**Comment by aprendendofelipe** [comment]
@Jetrom17, não entendi qual é a sua sugestão.

As páginas de conteúdos do TabNews já possuem as tags que você citou:

```html
<meta property="og:site_name" content="TabNews"/>
<meta property="og:type" content="article" />
```

Além de muitas outras...

**Comment by cybernerd007** [comment]
> @Jetrom17, não entendi qual é a sua sugestão.
> 
> As páginas de conteúdos do TabNews já possuem as tags que você citou:
> 
> ```
> <meta property="og:site_name" content="TabNews"/>
> <meta property="og:type" content="article" />
> ```
> 
> Além de muitas outras...

acredito que ele quer que seja adicionado uma TAG para ficar igual a primeira imagem com o botão "leitura rapida" para que seja possive ele ler dentro do telegram sem a necessidade de sair

**Comment by Jetrom17** [comment]
> > @Jetrom17, não entendi qual é a sua sugestão.
> > 
> > As páginas de conteúdos do TabNews já possuem as tags que você citou:
> > 
> > ```
> > <meta property="og:site_name" content="TabNews"/>
> > <meta property="og:type" content="article" />
> > ```
> > 
> > Além de muitas outras...
> 
> acredito que ele quer que seja adicionado uma TAG para ficar igual a primeira imagem com o botão "leitura rapida" para que seja possive ele ler dentro do telegram sem a necessidade de sair

Exatamente isso. @aprendendofelipe desculpe, não vi esse elemento no post dos usuários, somente na página home.

**Comment by aprendendofelipe** [comment]
Não era nada que faltava no site, mas precisava ensinar ao Telegram sobre como obter o título, autor, data e corpo dos artigos do TabNews para criar a página de "leitura rápida".

Já fiz isso e agora é só aguardar a aprovação deles 👍

**Comment by Jetrom17** [comment]
> Não era nada que faltava no site, mas precisava ensinar ao Telegram sobre como obter o título, autor, data e corpo dos artigos do TabNews para criar a página de "leitura rápida".
> 
> Já fiz isso e agora é só aguardar a aprovação deles 👍

Ok, posso marcar como "resolvido", embora no aguardo da aprovação?
