### ISSUE TITLE
Milestone 6 - Performance e Segurança

### ISSUE THREAD

**Issue by filipedeschamps** [filipedeschamps/tabnews.com.br#1140]
Turma, chegou a hora de organizarmos a nova fase do desenvolvimento do TabNews e dar **destaque** a todas as contribuições que estão acontecendo pela **melhor comunidade open source do Brasil**. Tudo vai seguir da mesma forma que antes, porém com uma novidade **muito interessante**: quem irá liderar a [Milestone 6](https://github.com/filipedeschamps/tabnews.com.br/milestone/10) é o @aprendendofelipe 😍 💪 👍 🤝

O @aprendendofelipe é um dos contribuidores mais ativos do projeto, possui acesso de **escrita** e **deploy** e foi o responsável por levar para produção todos os últimos Pull Requests que a comunidade fez nas últimas semanas. Dado a isso, realizei um call com ele semana passada onde discutimos alguns pontos do projeto e, de surpresa, fiz o convite para ele liderar esta Milestone e turma, **ele aceitou** 😍 😍 😍 Eu fico **genuinamente feliz** com isto, pois assim conseguirei dar mais atenção ao curso que estou desenvolvendo sem precisar parar de fazer vídeos para o canal 🤝 

Então eu irei dar o pontapé inicial na organização das tarefas para logo mais para frente passar de fato o bastão para o @aprendendofelipe 👍 

Bom, você já deve ter visto no título da issue que o nome desta Milestone é **Performance e Segurança** onde, independente de outras implementações que forem feitas, ter este norte nos ajuda a não nos esquecermos do que de fato o projeto está mais precisando no momento, principalmente para conseguirmos dar o próximo passo que é a Milestone de Revenue Share. Mas novamente, outras implementações são bem vindas, como a estabilização da implementação sobre o Dark Mode que diariamente as pessoas estão pedindo.

Então para executarmos esta Milestone sugiro dividirmos as tarefas novamente em 3 categorias:

1. Performance
2. Segurança
3. Melhorias

~Vou descrever cada uma abaixo, mas esta lista por enquanto é um **Rascunho** que irá pegar itens que já foram executados (mas não foram registrados em Milestones) e irá dar a estrutura necessária para registrar os novos itens.~

## Performance

Este são os itens que irão melhorar a performance e usabilidade do TabNews e neste ponto há muitas oportunidades, principalmente no backend (como criação de índices no banco de dados).

- #1141
- #1143
- #1145
- #1148
- #1164
- #1375
- #1169
- #1443 
- #1439 
- #1464 
- #1406 
- #1451 
- #1630 
- #1632 

## Segurança

Esta categoria envolve tanto a segurança **técnica** do sistema quanto a segurança da **economia** do TabNews.

Na parte técnica, devemos considerar desde, por exemplo, acessos não autorizados, a estabilidade do sistema e gerenciamento de erro. Na parte da economia, devemos considerar mecânicas para evitar abusos das TabCoins e expor o máximo de informação para as pessoas da comunidade conseguirem identificar manipulações, como por exemplo, ~expor quem deu up/down vote~ ([Edit] apenas a moderação pode ver quem e como votou).

- #1142
- #1146
- #1147
- #1149
- #1150
- #1151
- #1157
- #1216
- #1180
- #1307
- #1332
- #1154
- #1339 
- #1168
- #1155
- #1166
- #1167  
- #1267 
- #1531 
- #1533 
- #1541 
- #1554  
- #1170 
- #1344 
- #1516 
- #1618 

## Melhorias

Esta é uma categoria aberta e que deve listar todas as lapidações que o projeto vem recebendo.

- #1144
- #1158
- #1159
- #1160
- #1161
- #1162
- #1163
- #1217
- #1218
- #1219
- #1220
- #1221
- #1223
- #1224
- #1280
- #1281
- #1282
- #1283
- #1284
- #1286
- #1287
- #1288
- #1306
- #1308
- #1309
- #1311
- #1331
- #1333
- #1334
- #1335
- #1199
- #1360
- #1361
- #1362
- #496 
- #1386 
- #1390
- #1425 
- #1426 
- #1461 
- #1465 
- #1466 
- #788 
- #927 
- #1557 
- #1489 
- #1499 
- #1508 
- #1521 
- #1525 
- #1548 
- #1549 
- #1559 
- #1560 
- #1532 
- #1422 
- #1565 
- #1572 
- #1570 
- #1188
- #807
- #1573 
- #902 
- #1578 
- #943 
- #1588 
- #1590 
- #1582 
- #1580 
- #1594 
- #1595 
- #1593 
- #972 
- #1602 
- #1236 
- #1596  
- #1380 
- #605 
- #1605 
- #1601 
- #895 
- #1620 
- #1621 
- #1606 
- #1624 
- #1370 
- #1628 
- #1629 
- #1633

**Comment by filipedeschamps** [comment]
@aprendendofelipe registrei aqui tudo o que eu tinha no meu histórico (tirando um item que você executou, mas que sugiro aguardamos um fix naquele módulo `third party` antes de anunciarmos).

Uma pergunta: por ter `write` no repositório, você consegue editar o corpo da issue ali de cima?

**Comment by aprendendofelipe** [comment]
> @aprendendofelipe registrei aqui tudo o que eu tinha no meu histórico (tirando um item que você executou, mas que sugiro aguardamos um fix naquele módulo `third party` antes de anunciarmos).
> 
> Uma pergunta: por ter `write` no repositório, você consegue editar o corpo da issue ali de cima?

Boa @filipedeschamps! Eu consigo editar sim, então mais tarde vou adicionando os outros PRs 🚀

**Comment by brunofamiliar** [comment]
Show! Vou tentar acompanhar mais de perto essa Milestone

**Comment by filipedeschamps** [comment]
Turma, eu não sei se esqueci de algo, mas acho que cadastrei todos os itens que eu tinha aqui na fila de espera sobre performance e segurança (dos que podem ficar públicos, por enquanto).

**Comment by aprendendofelipe** [comment]
O que acham de adicionar a possibilidade de mostrarmos mensagens na página de status do sistema?

Acho que seria bom acrescentar isso nessa milestone para podermos deixar avisado por ali durante momentos de instabilidade que podem ocorrer, por exemplo, na migração da região do BD.

Acho que é uma boa oportunidade de usarmos a [Edge Config](https://vercel.com/docs/concepts/edge-network/edge-config) para criar essas mensagens sem depender do banco de dados, de serviços externos e nem de um novo deploy.

**Comment by gSarciotto** [comment]
Duvida, como saberemos se realmente havera uma melhora de performance, nos temos metricas sobre esses items?

**Comment by filipedeschamps** [comment]
> O que acham de adicionar a possibilidade de mostrarmos mensagens na página de status do sistema?

Acho massa! A gente poderia fazer um endpoint "mock" que na verdade só bate no Middleware, busca esse valor e retorna no corpo, dado que agora é possível retornar `Responde Body` pelo Middleware:

https://github.com/filipedeschamps/tabnews.com.br/blob/31dbe19f0cfb4a6d9dcced25d23a9151d2b2cdd9/next.config.js#L3

Vou criar a issue 🤝 

> Duvida, como saberemos se realmente havera uma melhora de performance, nos temos metricas sobre esses items?

Ótima pergunta @gSarciotto! Geralmente nós mensuramos com um **antes** e **depois**, veja dois exemplos:

Veja o item **3) Remoção de múltiplas idas ao banco na consulta de `contents`**:
https://www.tabnews.com.br/filipedeschamps/novas-melhorias-mais-contexto-nas-notifacoes-por-email-e-outras-8-melhorias

Veja o item **2) Páginas abrindo ainda mais rápidas** (implementação monstra feita pelo @aprendendofelipe)
https://www.tabnews.com.br/filipedeschamps/novas-melhorias-rss-e-mais-7-melhorias

**Comment by ezequiaslopesdasilva** [comment]
O #923 é considerado uma melhoria para ser adicionado nessa Milestone?

**Comment by filipedeschamps** [comment]
@ezequiaslopesdasilva com certeza! Na verdade qualquer melhoria pode entrar nesta Milestone 🤝 você chegou a ver o comentário do @aprendendofelipe lá no PR?

**Comment by filipedeschamps** [comment]
Em paralelo, acabei de criar uma publicação no TabNews anunciando este draft e um pouco da minha visão sobre o futuro da plataforma: https://www.tabnews.com.br/filipedeschamps/milestone-6-performance-e-seguranca-draft

**Comment by sudo-give-me-coffee** [comment]
Limitar uma publicação a 1 upvote e 1 downvote por usuário seria algo interessante a se fazer, é uma segurança anti ataques

**Comment by filipedeschamps** [comment]
@sudo-give-me-coffee show, você poderia elaborar inclusive isso nessa issue? https://github.com/filipedeschamps/tabnews.com.br/issues/1166

**Comment by brunofamiliar** [comment]
Nossa, li bastantes issues e minha mente tá explodindo 🤯🤯. Quanta coisa perdi, faço nem ideia como posso ajuda-los kk a barra subiu

**Comment by aprendendofelipe** [comment]
> Vi que tem muitas issues sem iteração, como fica o andamentos destas issues?

Provavelmente estão aguardando interações. 💪

Se são assuntos que ainda precisam de mais discussão e/ou falta alguma implementação, elas estão ficando abertas para facilitar para quem tenha algo a contribuir, pois, se forem fechadas, vão sendo criadas novas issues com o mesmo foco, mas que não consideram as discussões anteriores, e isso dificulta a evolução das soluções.

Provavelmente algumas já podem ser fechadas, seja porque estão fora do radar, mas algumas porque o problema foi resolvido parcialmente. E nesses casos talvez seja melhor abrir novas issues com o problema atualizado, explicando apenas o que falta implementar. Já em outras é melhor manter todo o contexto existente até a solução mais completa ser implementada. 👍

**Comment by brunofamiliar** [comment]
> 

Booa Felipe! Só pra me situar, estão priorizando a atuação em ordem na qual estão listadas as atividades nessa milestone, ou não necessariamente?

**Comment by Rafatcb** [comment]
@aprendendofelipe acha que faz sentido encerrar esse issue e a Milestone 6, e organizar a Milestone 7 (#1490)? Precisa de ajuda com algo?

**Comment by aprendendofelipe** [comment]
Também estou com essa dúvida sobre organizar aqui ou na 7 tudo que foi feito recentemente. Não sei se o Filipe irá parar com os vídeos para encerramento/abertura das Milestones, mas, até pelos tipos de implementações que estão sendo realizadas, acredito que não começamos a Milestone 7.

**Comment by Rafatcb** [comment]
> Também estou com essa dúvida sobre organizar aqui ou na 7 tudo que foi feito recentemente. 

O que foi feito até agora podemos considerar da Milestone 6, já que a 7 não foi oficialmente iniciada. Creio que mesmo o issue do FAQ, que foi citado em #1490, pode ser movido para esta lista. O mesmo raciocínio vale para os outros issues resolvidos que foram citados lá.

> Não sei se o Filipe irá parar com os vídeos para encerramento/abertura das Milestones

Eu já não lembrava desses vídeos, mas vendo a [playlist](https://www.youtube.com/playlist?list=PLMdYygf53DP7VRIRKmkSdGuDf-6OXcj4H), a Milestone 6 não teve uma live de inauguração.

**Comment by filipedeschamps** [comment]
Fala turma! Acredito que o foco de produção de vídeos acabou ficando no curso e acho mais válido ao invés de uma live sobre a Milestone 7, lançar um vídeo no canal.

Estava pensando aqui sobre qual melhor momento, fazer no início da Milestone ou no final dela e talvez o momento ideal seja quando o recurso de Revenue Share estiver rodando para valer e daí explicar o que foi feito, como foi feito e convidar a turma para testar. O que acham?

**Comment by aprendendofelipe** [comment]
Realmente, se for um vídeo público, é melhor lançar quando já estiver implementada pelo menos alguma versão.

Então é melhor fazermos o encerramento da 6 e abertura da 7 em publicações no TabNews?

**Comment by filipedeschamps** [comment]
> Então é melhor fazermos o encerramento da 6 e abertura da 7 em publicações no TabNews?

Total!! Inclusive posso compartilhar a publicação nas minhas redes também 🤝

**Comment by aprendendofelipe** [comment]
Publiquei o encerramento da Milestone 6:

https://www.tabnews.com.br/FelipeBarso/tabnews-encerramento-da-milestone-6

🎉🎉🎉
