### ISSUE TITLE
Melhora na performance da paginação de conteúdos

### ISSUE THREAD

**Issue by filipedeschamps** [filipedeschamps/tabnews.com.br#1141]
## Contexto

A paginação de conteúdos do TabNews utiliza a estratégia de `offset`, onde é uma estratégia simples de se implementar, porém possui um tradeoff de performance que é precisar percorrer por todos os itens do offset, mesmo que o limite de itens a ser devolvido seja `1`. E eu especulo que isso se agrava, pois para cada linha é computado o `get_current_balance()`, o que para algumas páginas, não dava mais tempo de processar o retorno dentro de 60 segundos, retornando para o client um `504`.

## Execução

 - #823

**Comment by gpoleszuk** [comment]
Prezado desenvolvedor.

Primeiro, peço desculpas pela falta de acentuaç~ao.

Reporte:
Ao tentar atualizar um rascunho em um comentario, o servidor retornou HTTP 504 apos 60 segundos de espera. Repeti a tentativa algumas vezes pensando ser problema por aqui no navegador. Entao, para gerar evidencias para voces, repeti o processo novamente em 20241129T084200Z utilizando o `curl` com a requisiçao gerada pelo navegador. Eu acho que ha algo no conteudo, pois postar algo mais simples, foi rapidamente aceito pelo servidor. A postagem ja foi removida.

Caso seja de vosso interesse, posso enviar a requisiçao POST completa que foi enviada para o servidor. Por hora, deixo uma versao sem os cookies de secao nesta postagem temporaria https://pastebin.com/dbFGUd0w (password: bmKQBJPiqH). Expira em pouco menos de 24 horas.

**Comment by aprendendofelipe** [comment]
@gpoleszuk, muito obrigado por reportar! 💪

O problema foi resolvido com o PR #1822 🤝
