### ISSUE TITLE
Bug - Cadastro e recuperação de senha

### ISSUE THREAD

**Issue by gabrielclimb** [filipedeschamps/tabnews.com.br#1152]
Bom dia, fui tentar recuperar minha senha e deu o seguinte erro:
![image](https://user-images.githubusercontent.com/21311863/208410470-b7a71f0b-c61e-4c2f-a9b9-38ad3d2d9620.png)

Fui tentar cadastrar e o sistema não deixo pois disse que o usuário já existe:
![image](https://user-images.githubusercontent.com/21311863/208410725-eda2d085-52bb-47a6-b28e-dbd96c3a6bea.png)

Teria como deletar o usuario do banco para eu me cadastrar novamente? Obrigado

**Comment by danielschmitz** [comment]
primeiro username tem o L

o outro não

**Comment by aprendendofelipe** [comment]
@gabrielclimb não existe usuário `gabrielclimb` no TabNews, porém existe o usuário `gabrieclimb`.

Sugiro que recupere sua senha utilizando o email e, se for o caso, após se logar, altere o nome do usuário pela página ["Editar Perfil"](https://www.tabnews.com.br/perfil).

Estou fechando a Issue. Ok? 🤝
