### ISSUE TITLE
Cache da API: Endpoints de Conteúdo

### ISSUE THREAD

**Issue by filipedeschamps** [filipedeschamps/tabnews.com.br#1164]
## Contexto

O maior motivo que faz as páginas do TabNews abrirem rapidamente é o fato delas serem estaticamente geradas, onde são revalidadas a cada `10` segundos:

https://github.com/filipedeschamps/tabnews.com.br/blob/0bbb0f655dc88847fa741001a83d3f3297bf01a1/pages/%5Busername%5D/%5Bslug%5D/index.public.js#L390

Para compensar o fato de uma página estar desatualizada ao abrí-la, no client-side nós fazemos duas requests adicionais para a API, onde uma pega o conteúdo atualizado:

https://github.com/filipedeschamps/tabnews.com.br/blob/0bbb0f655dc88847fa741001a83d3f3297bf01a1/pages/%5Busername%5D/%5Bslug%5D/index.public.js#L22-L29

E outra para pegar a lista de respostas:

https://github.com/filipedeschamps/tabnews.com.br/blob/0bbb0f655dc88847fa741001a83d3f3297bf01a1/pages/%5Busername%5D/%5Bslug%5D/index.public.js#L32-L39

Ou seja, é feito duas requisições adicionais, que não passam pelo cache, onde a segunda requisição (a que pega o `children`) pode pesar bastante dependendo da quantidade de respostas:

```
/api/v1/contents/[username]/[slug]
/api/v1/contents/[username]/[slug]/children
```

## Execução

Então a idéia é adicionar o cache de `stale-while-revalidate` no `GET` destes endpoints como foi feito [neste PR](https://github.com/filipedeschamps/tabnews.com.br/pull/1060).

Porém um cuidado **muito importante** é não fazer o cache do usuário que está logado (para não cachear a sessão dele), por isto no PR citado a cima, nós alteramos de:

```js
async function getHandler(request, response) {
  const userTryingToList = request.context.user;
```

Para:

```js
async function getHandler(request, response) {
  const userTryingToList = user.createAnonymous();
```

Outro detalhe importante é entender quem deve ser responsável por revalidar o cache, pois do contrário, a página estática pode estar com um cache na frente da API (não tem problema os caches estarem dessincronizados, desde que o cache da API **sempre** esteja na frente). Então casos que precisamos considerar e entender o que fazer:

1. Quando alguém edita o seu conteúdo e ele é um conteúdo raiz.
2. Quando alguém edita o seu conteúdo, mas ele é um conteúdo filho.
   1. Esta ação deveria atualizar a lista inteira de filhos? Que é o `/[username]/[slug]/children` do `root` content?
   2. Esta ação deveria atualizar o slug específico deste conteúdo? Que é o `/[username]/[slug]` do `child` content?
3. Quando alguém qualifica algum conteúdo? O que acontece? Pois a quantidade de TabCoins vem do conteúdo.
4. Tem outros casos?

E lembrando que passar essa responsabilidade para quem gera uma ação, vai penalizar a experiência dela, a não ser que isso seja colocado numa fila como uma outra pessoa sugeriu no passado, mas sugiro não trazer essa complexidade para agora. Uma outra alternativa seja tirar o `await` da frente do `response.revalidate('...')`

Endpoits relacionados:

- [/api/v1/contents/[username]](https://github.com/filipedeschamps/tabnews.com.br/blob/main/pages/api/v1/contents/%5Busername%5D/index.public.js)
-[/api/v1/contents/[username]/[slug]/children](https://github.com/filipedeschamps/tabnews.com.br/blob/main/pages/api/v1/contents/%5Busername%5D/%5Bslug%5D/children/index.public.js)
- [/api/v1/contents/[username]/[slug]/tabcoins](https://github.com/filipedeschamps/tabnews.com.br/tree/main/pages/api/v1/contents/%5Busername%5D/%5Bslug%5D/tabcoins)

Outros endpoits que também devem ser estáticos, mas que podem ser atualizados pelo `revalidate` do cache (sem ser on-demand):

- [/api/v1/contents/[username]/[slug]/parent](https://github.com/filipedeschamps/tabnews.com.br/tree/main/pages/api/v1/contents/%5Busername%5D/%5Bslug%5D/parent)
- [/api/v1/contents/[username]/[slug]/root](https://github.com/filipedeschamps/tabnews.com.br/tree/main/pages/api/v1/contents/%5Busername%5D/%5Bslug%5D/root)
- [/api/v1/contents/[username]/[slug]/thumbnail](https://github.com/filipedeschamps/tabnews.com.br/tree/main/pages/api/v1/contents/%5Busername%5D/%5Bslug%5D/thumbnail)

**Comment by DiegoAscanio** [comment]
Não sei se seria adequado, mas, se for colocado algum controle por hash, onde a API seja a controladora dos hashes e em vez de solicitar o children, o usuário solicita apenas o hash (que estará armazenado no banco) em revalidate, para verificar se o hash da API é o mesmo que possui localmente. Se o hash tiver mudado, aí sim o usuário consome as apis de contents.

Pro caso do endpoint children, o hash incremental seria uma alternativa, pois, se existe uma função de hash incremental que tanto client quanto api conheçam, entendo que ao ocorrer uma atualização do incremento do hash, o client solicite o children apenas para os novos conteudos, em vez de solicitá-lo todo novamente.

É viável?

**Comment by aprendendofelipe** [comment]
Implementado no PR #1374
