### ISSUE TITLE
Adicionar link do RSS ao footer

### ISSUE THREAD

**Issue by gabrielsozinho** [filipedeschamps/tabnews.com.br#1175]
Muitas pessoas pediram não só aqui, mas no TabNews por um feed RSS, justamente por não saberem que ele existia. Adicionar ao footer também já havia sido sugerido antes para dar visibilidade a ele.

**Comment by cybernerd007** [comment]
bom como medida paleativa como esse recurso é acessivel por usuarios com mais conhecimento recomendo colocar junto com a documentação da API essa informação por hora ate seu PR se aprovado coisa que acredito que levara um bom tempo....
