### ISSUE TITLE
Erro de ortografia na página /status

### ISSUE THREAD

**Issue by GHCMelo** [filipedeschamps/tabnews.com.br#1186]
Um pequeno erro de ortografia na palavra "conteudos" da página de Status:

![image](https://user-images.githubusercontent.com/50326228/209580757-1dc414d6-5df4-4912-be41-c42bfb13552f.png)

**Comment by aprendendofelipe** [comment]
@GHCMelo, obrigado pela issue e pelo PR #1187!

O @Caixetadev abriu o PR #1246 com a mesma solução, então já fiz o merge colocando você como coautor 👍🤝
