### ISSUE TITLE
Autenticação automática ao cadastrar-se e confirmar o email

### ISSUE THREAD

**Issue by bernardoeuler** [filipedeschamps/tabnews.com.br#1189]
### Problema
Em diversos sites, é possível observar que quando o cadastro é feito e vamos confirmar ele no email enviado, somos redirecionados até o site em questão e geralmente já estamos logados na aplicação ao chegar neste ponto.

Atualmente, ao realizar um cadastro no TabNews, depois de redirecionado ao site, o usuário ainda precisa voltar a tela de login, preencher seus dados novamente e então logar na aplicação, coisa que poderia ser feita pelo próprio site ao confirmar o email e atestar que o cadastro é válido.

### Conclusão
Se o TabNews implementasse essa funcionalidade, a experiência do usuário seria muito beneficiada e a navegação seria mais fluida.

**Comment by cybernerd007** [comment]
Bom como a ativação e feita somente uma unica vez acredito que isso não tenha impacto real...

**Comment by bernardoeuler** [comment]
Pode até ser uma coisa pequena, mas como foi algo que senti falta na hora de me cadastrar, fiz essa observação, pra mim, é algo que ajuda na experiência de quem for usar, mes que uma única vez.

**Comment by rodrigoKulb** [comment]
Legal sua observação @bernardoeuler pensando em **segurança** essa possibilidade poderá abrir um **brecha de segurança**, onde com acesso ao link de ativação qualquer usuário poderia acessar a conta da pessoa.

Como sabemos esse link ficará gravado no histórico do navegador, fora que dependendo da rede a URL acessada pode ser gravada em logs da rede.

Colocando na balança a segurança seria prioridade VS a experiência do usuário.

**Comment by bernardoeuler** [comment]
Caramba, nem pensei nisso, obrigado pela explicação. Faz sentido, a segurança deve ser priorizada. Vou fechar esta issue então.
