### ISSUE TITLE
[PRODUÇÃO]Erro inusitado no email

### ISSUE THREAD

**Issue by cybernerd007** [filipedeschamps/tabnews.com.br#1192]
OBS.: OS TESTES FORAM FEITOS EM **PRODUÇÃO** E **HOMOLOGAÇÃO**, FOI UTILIZADO O **MOZILLA** E O **PROJECTO CHROMIUM** NOS TESTES.

Bom como dizem que uma imagem vale mais que mil palavras kkkk

(PRINT EM HOMOLOGAÇÃO)
![Screenshot_1](https://user-images.githubusercontent.com/8114976/209756928-9f8f0fd0-b50d-42ef-bcdb-14cf25fdeadf.png)

(PRINT EM PRODUÇÃO)
![Screenshot_5](https://user-images.githubusercontent.com/8114976/209756935-aa48e9d0-e6c2-4091-8adf-e0ae6346fe72.png)
no Print acima(ESTÁ EM PRODUÇÃO) você pode notar que ele está fazendo 2 requests iguais para o `user` fiz uns testes e quando ele só faz **UMA** ele da **undefined** no email e quando ele faz **DUAS** em um curto espaço de tempo fica undefined...

Bom acredito que seja essa PR que esteja causando esse problema https://github.com/filipedeschamps/tabnews.com.br/pull/804 
no caso ela foi implementada a pouco tempo.
![Screenshot_6](https://user-images.githubusercontent.com/8114976/209757056-16d21c2f-9a29-4659-b680-89f68e3023ac.png)
(Mais precisamente ONTEM)

**Comment by aprendendofelipe** [comment]
Boa @cybernerd007 👍

Solução em #1193 🤝
