### ISSUE TITLE
Sugestão para ISSUE e para o REPOSITÓRIO

### ISSUE THREAD

**Issue by Jetrom17** [filipedeschamps/tabnews.com.br#1194]
1. Sugiro o uso **CodeQL Analysis** e/ou **Dependency Review**  para segurança do repositório. Ambos são do Github oficial e atuam de forma diferente, no entanto, seguem a mesma ideia: Procurar vulnerabilidades e informar. 
Mesmo que tenha profissionais na área, automação para ajudar sempre é bem vindo, em minha opinião.
> Acredito que somente o dono ou colaborador tem acesso esse recurso. Se já há, desconsidere minha sugestão.
2. Para **ISSUE**, recomendo uma personalização rápida. Já tivemos discussões, o próprio @filipedeschamps já comentou sobre isso, ao abrir uma "sala de **discussões**" referente ao repositório. Então pelo menos configure _issue_ capaz de informar um formulário pré-personalizado com uma etiqueta quando um usuário abrir uma. Se for sobre "bug", que tenha uma etiqueta de cor vermelha e se for "suggest", que tenha etiqueta de cor azul por **exemplo**.
> Facilita a filtrar sobre o que procuras e deixa mais fácil de entender que cada _issue_ significa pelo uso da etiqueta antes de adentrar e ler em uma.

[I am sorry se estou sendo repetitivo em uma outra _issue_ que já foi sugerida, se existe]

**Comment by Rafatcb** [comment]
Acho o ponto 1. bem válido de ser estudado (eu nunca usei essas _actions_  então não sei se funcionam bem e se são úteis).

Sobre o ponto 2, podemos concentrar a discussão num issue específico sobre isso: https://github.com/filipedeschamps/tabnews.com.br/issues/902.

**Comment by Rafatcb** [comment]
@Jetrom17  não quer deixar aberto por causa das sugestões do CodeQL Analysis e Dependency Review?

**Comment by Jetrom17** [comment]
> @Jetrom17  não quer deixar aberto por causa das sugestões do CodeQL Analysis e Dependency Review?

Passaram-se 11 meses. Não creio que a sugestão seja válida. Me desconectei do TabNews há mais de um ano. Provável que eu retorne futuramente, mas não agora.

**Comment by aprendendofelipe** [comment]
Também já temos o CodeQL habilitado 👍
