### ISSUE TITLE
[PRODUÇÃO]Pequeno erro na PR #1193

### ISSUE THREAD

**Issue by cybernerd007** [filipedeschamps/tabnews.com.br#1196]
Segue um pequeno problema vindo na PR #1193 quando você se encontra no perfil e desloga da conta ao sair da aba e voltar ele da o erro undefined no username e no email...

Click no link abaixo que você sera redirecionado para o video que eu fiz e postei no youtube mostrando melhor o problema...

[![Report Falha/Bug ainda persiste PR #1193](https://i9.ytimg.com/vi_webp/izj2XeFtH7E/mqdefault.webp?sqp=CLy5sp0G&rs=AOn4CLBgh95cqunYi15q58LtX_iD6mVsFQ)](https://youtu.be/izj2XeFtH7E)

**Comment by cybernerd007** [comment]
Quando não se está logado e você troca de aba tambem ocorre esse pequeno problema...
![Screenshot_1](https://user-images.githubusercontent.com/8114976/209935865-b38f3e24-5353-40d7-bbdb-a159e85a95f2.png)

**Comment by cybernerd007** [comment]
alem do fato de esse problema esta dando acesso como se o usuario estivesse logado.
Obs.: esse problema so se propaga no front end.
![Screenshot_2](https://user-images.githubusercontent.com/8114976/209936162-607b3190-7054-43e8-80e2-430f59891103.png)

**Comment by cybernerd007** [comment]
Solução em #1200

**Comment by aprendendofelipe** [comment]
Obrigado @cybernerd007 👍
