### ISSUE TITLE
TabCoins Infinitas adicionando comentários. 

### ISSUE THREAD

**Issue by Hanufu** [filipedeschamps/tabnews.com.br#1197]
Olá, tudo começou quando boicotaram uma publicação minha hoje no TabNews, que saiu de 2º lugar para posição 28 de "Recentes", isso tudo em menos de 3 minutos. Com isso eu fiquei revoltado pois sei que por conta de alguns deslikes em um comentário do meu post, a pessoa se vingou dando vários deslikes no meu post. Me perguntei como ganhar vários tabcoins de forma fácil, e sem ser identificado, a principio pensei em criar vários posts mas poderia ocorrer de perceberem por conta do meu nick, então pensei em criar 2 contas, em uma eu crio o post e na outra eu faço os comentários. 
A principio foi isso que fiz, mas percebi que rapidamente a publicação começou a aparecer em relevantes, e eu não queria isso, pois seria fácil de me identificarem. 

Ai que veio a sacada, se eu criar um bot, junto com o ChatGPT, que vai de post em post, copiando seu conteúdo enviando para a IA como parâmetro de um texto "Entenda o texto a seguir e elabore algumas considerações e perguntas", pegando o resultado da IA e comentando no post. Assim seria possível ter tabcoins infinitos

Não cheguei a codificar, mas o teste manual que eu fiz me surpreendeu, pois as pessoas se que sabiam que as respostas vinham de uma IA, e como são comentários o máximo que poderia acontecer era alguém não gostar e dar deslike. 

Uma conta deveria ter limites de comentários "Limites humanos", ou até mesmo só poderia fazer X comentários em um intervalo Y de tempo.

**Comment by filipedeschamps** [comment]
@Hanufu muito obrigado pela sua pesquisa e eu entendo perfeitamente sua frustração, tanto que apontei as medidas que estamos tomando para evitar que isso aconteça.

Sobre o limite de comentários em um intervalo de tempo, isso já existe e já pegou casos de pessoas abusando. É um sistema que sempre ter que ir melhorando, principalmente se imbutirmos nele algum verificador, como o `fingerprint` que a OpenAI quer disponibilizar.

Agora, uma coisa a se levar em consideração é: independente do que você utilizar (manual ou automático), manipular TabCoins de forma artificial vai contra os [Termos de Uso](https://www.tabnews.com.br/termos-de-uso) do site. Então peço que envie para contato@tabnews.com.br as contas que utilizou para eu fazer o Nuke delas e evitar que eu acabe fazendo o Nuke de todas as contas relacionadas, incluindo sua conta principal, ou que algum moderador faça isso por não ter visto esta issue, combido? 🤝 

No mais, iremos combater o abuso de TabCoins com todas as forças e fico feliz em ter você do nosso lado para ajudar a testar os limites disso 👍

**Comment by Hanufu** [comment]
Fiz o que foi pedido, mandei um email contendo o link dessa issue, e explicando a situação, espero que dê tudo certo! 

Fiquei com alguma dúvida, esse é o primeiro projeto em que eu estou empenhado em melhorar, construir a premissa do TabNews é sensacional, e eu gostaria de testar coisas do tipo, sou um entusiasta de cyber security, mas não sei por onde começar, e se é permitido. Não há nada relacionado a bug hunter? ou alguma forma de contribuir  para a comunidade?  Fiquei muito curioso para testar o limite de comentários programando um bot, mas resolvi não fazer pois tive medo de ser banido ou algo do tipo existe alguma forma segura de testar o tabnews?

**Comment by filipedeschamps** [comment]
Massa @Hanufu tem como testar sem atrapalhar o ambiente de produção, que é utilizando o ambiente de homologação. Cada commit produz um ambiente novo, e você pode sempre pegar a URL do último ambiente por aqui: https://github.com/filipedeschamps/tabnews.com.br/deployments/activity_log?environment=Preview

Clique no botão **View deployment** e você será levado para a última versão do ambiente, que é uma cópia do ambiente de produção, mas com um banco de dados separado (por conta disto, você precisará fazer um novo cadastro, onde este cadastro poderá ser aproveitado entre os deploys diferentes de homologação).

**Comment by Rafatcb** [comment]
Sempre será possível burlar o sistema, a diferença é o nível de sofisticação exigido para isso. O TabNews melhorou bastante de Dez/2022 para Dez/2023, e vários casos de manipulação de votos foram lidados.

Dito isso, creio que podemos fechar o issue por ser um assunto sempre em andamento, e criar issues com propostas mais específicas para auxiliar nisso, como foi o caso dos PRs com a implementação do grafo de votos na página de [Status](https://www.tabnews.com.br/status) (https://github.com/filipedeschamps/tabnews.com.br/pull/1531, https://github.com/filipedeschamps/tabnews.com.br/pull/1533, https://github.com/filipedeschamps/tabnews.com.br/pull/1541).

Faz sentido?

**Comment by aprendendofelipe** [comment]
É isso mesmo @Rafatcb 👍

Além disso, ideias de melhorias para a economia podem ser centralizadas na

- #1438
