### ISSUE TITLE
Moderação conseguir anular as TabCoins de um conteúdo

### ISSUE THREAD

**Issue by filipedeschamps** [filipedeschamps/tabnews.com.br#1198]
## Contexto

Na busca de uma economia saudável, proponho um recurso onde seja possível alguém da moderação conseguir anular os ganhos de TabCoins de uma publicação.

Uma coisa que fiquei pensando nos últimos dias é sobre o que exatamente fazer com um comentário como "👍 ", pois se removermos ele por não respeitar os termos de uso, por exemplo, ele deixa de ser um demonstrativo de o que não deve se fazer no TabNews. Então estou pensando que é melhor ter um comentário simples negativado (para as pessoas verem que isto não é bem vindo), do que esconder esta interação ao remover o conteúdo.

E esta funcionalidade acaba sendo importante quando nitidamente um comentário precisa ser negativado, porém não foi negativado por ninguém por ele estar nas profundezas de alguma outra thread, e algum moderador não está com TabCoins suficiente para negativar. Eu já me vi nesse cenário, ao abrir um perfil de um usuário, notar alguns comentários sem valor algum, mas não ter TabCoins para negativar.

Então prefiro dar este furo na economia através da moderação, do que alguém estar se beneficiando de um comentário sem valor.

## Execução

No menu de opções de um conteúdo, adicionar uma nova funcionalidade de "Zerar valor" (ou outra nomenclatura) disponível somente para quem tem a feature `update:content:others` (ou outra feature específica para isto):

<img width="204" alt="image" src="https://user-images.githubusercontent.com/4248081/209902193-5e3fe462-2376-43ef-8886-6a930d2c4775.png">

Onde o efeito deverá ser:

1. Criar um `event` registrando isso. Este `event` deverá ter um nome único (que ainda não existe).
2. Criar uma `balance_operation` que use este evento como lastro.
3. Penalizar o conteúdo deixando ele com valor negativo (por exemplo `-1`), e penalizar o autor deste conteúdo com `-2` TabCoins.
4. Atualizar o `event` com tudo o que aconteceu, para ser possível desfazer esta operação.

Uma coisa a se considerar é penalizar o conteúdo com `-2` TabCoins e autor do conteúdo com `-4` TabCoins para o esforço do autor em criar comentários simples ter resultado negativo (o que prefiro).

**Comment by cybernerd007** [comment]
Bom recomendo fazer assim se o usuario tiver a feature `update:content:others` suas tabcoins são infinitas, e o peso de um DownVote seja -1 no posta e -2 para o autor do comentario/post acredito que assim vai reduzir a complexidade da implementação.

**Comment by Rafatcb** [comment]
Você pensa nisso como uma solução perpétua? A ideia me parece útil para ser implementada hoje e usada nos casos óbvios, deixando para gastar TabCoins nos casos menos óbvios, mas me parece uma solução temporária. Quando o ganho de TabCoins for reformulado, talvez não precisemos mais dela.

**Comment by filipedeschamps** [comment]
@cybernerd007 o problema é que desta forma não fica registrado o lastro correto no sistema, principalmente para conseguir desfazer uma operação como essa caso seja necessário. Adicionei um quarto ponto sobre isso.

@Rafatcb estava pensando como perpétua mesmo, tipo um `escape hatch`. Mas quando você fiz:

> Quando o ganho de TabCoins for reformulado, talvez não precisemos mais dela.

O que isso significa exatamente?

**Comment by cybernerd007** [comment]
@filipedeschamps parado para analisar o que o @Rafatcb falou faz sentido...

Reformulando minha Recomendação... o usuario dono do Post não ganha Tabcoins ao responder comentarios e quem comentou so ganha uma unica vez, assim esse problema e mitigado...

Em contra partida recomendo por hora que seja implementado o seguinte, se o POST tiver sido deletado quem comentar não ganha TabCoin e não e possivel efetuar Up ou Down Vote...

Assim previne apartir da implementação que seja feito tecnicas desse calibre para conseguir TabCoin e TabCash.

Obs.: Recomendo deixar todo os usuario com a feature  `update:content:others` com TabCoins ilimitadas.

posso estar errado e não ser uma boa ideia, é uma boa ideia?

**Comment by aprendendofelipe** [comment]
Acho que o problema não é falta de tabcoins infinitos para negativar/moderar, mas sim falta de moderadores infinitos para dar conta de educar os usuários e, pior ainda, dar conta dos bots. Então isso precisa ser automático e os moderadores só precisariam atuar nas exceções.

Ainda acredito que os novos usuários não deveriam ganhar tabcoins ao publicar conteúdos ou comentários. No começo ganha/perde só os tabcoins dos votos recebidos.

A reputação seria construída com os votos recebidos de usuários que já construíram reputação. Poderia ser a média dos votos dos últimos X conteúdos (ou dos últimos Y dias). Assim seria muito mais difícil burlar a economia. Ainda poderiam ocorrer abusos, mas teriam que começar com um usuário real que já atingiu boa reputação e que teria muito a perder quando o abuso for pego.

Só contaria para a reputação os conteúdos com status publicado. Assim os usuários são foçados a se educar, pois excluir um conteúdo mal avaliado melhora a reputação e excluir um conteúdo bem avaliado piora a reputação.

Deveria ter um limite negativo de reputação em que o usuário nem poderia mais publicar nada enquanto não entrar na linha. Ao tentar publicar, o usuário receberia um aviso com o link para o código de conduta ou (os termos). E ele seria orientado a remover conteúdos negativados para melhorar sua reputação.

E no lado oposto, após atingir determinado valor de reputação, ao postar conteúdo ou comentário o usuário já a ganha uma quantidade de tabcoins proporcional à reputação. Podemos começar com um limiar baixo, talvez bastando a média de votos ser positiva para o usuário já ganhar tabcoins.

Na minha opinião não adianta dar mais poderes para os moderadores. Na verdade isso criaria outros problemas sem solucionar os atuais.

**Comment by Rafatcb** [comment]
> O que isso significa exatamente?

@filipedeschamps por "reformulação", eu quis dizer sobre a possível implementação de sugestões como a que o @aprendendofelipe mencionou agora, por exemplo. Vi que algo do tipo já foi sugerido/discutido anteriormente, mas não acompanhei por completo para saber se um dia seria implementado.

**Comment by aprendendofelipe** [comment]
> @aprendendofelipe essa idéia é genial! Você se importa em criar uma issue com esse conteúdo? 🤝 talvez esse seja o mecanismo mais importante desta Milestone.
> 
> Em paralelo, ainda acredito que um escape hatch seja importante 👍

Vou criar a issue 😉👍

**Comment by aprendendofelipe** [comment]
Acho que o PR #1366 eliminou essa necessidade por enquanto. O que acham?

**Comment by Rafatcb** [comment]
> Acho que o PR https://github.com/filipedeschamps/tabnews.com.br/pull/1366 eliminou essa necessidade por enquanto. O que acham?

Eu incluiria também que o PR #1460 ajudou bastante nisso, nas situações onde o comentário é um conteúdo curto.

Como não houve nenhuma opinião contrária desde Abril, vou fechar o issue para organizar o repositório. Caso alguém queria argumentar algo defendendo a criação dessa funcionalidade, pode comentar aqui que reabrimos o issue para discussão e possível implementação.
