### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by filipedeschamps** [filipedeschamps/tabnews.com.br#1199]
## Contexto

Inicialmente disponibilizar um controle no Frontend apenas para a pessoa alternar entre os modos de visualização Claro e Escuro e persistir isto em Local Storage. Em outro momento (quando necessário), fazer esta informação persistir no backend (dentro do perfil do usuário), para ser sincronizado entre os devices.

## Execução

Dado a alguns detalhes técnicos da stack que usamos (Next.js e BytMD), esta implementação não é tão simples, mas procurando no histórico, encontrei estas duas publicações:

- #377
- #916

Lembro que teve uma terceira tentativa, mas não estou conseguindo encontrar... mas posso estar enganado sobre a existência dela.

**Comment by alvesa** [comment]
com ideia de remover duplicidades, a mesma issue foi aberta #1127

**Comment by saraiva1989** [comment]
@filipedeschamps ou admins, Eu iniciei a implementação do dark mode;

![image](https://user-images.githubusercontent.com/40599423/216158568-0563804c-338e-4725-8f3c-d918c721c6cc.png)

![image](https://user-images.githubusercontent.com/40599423/216158625-055c25d2-930c-4e41-affa-44804392da43.png)

Ainda tem alguns ajustes a ser feito, colocar no checkbox um css bonitinho e ajustar algumas coisas mais.

basicamente eu criei um CSS e altero as variaveis dependendo do tema

![image](https://user-images.githubusercontent.com/40599423/216158861-86c971b0-b088-4378-85ec-ff4b147d92d5.png)

![image](https://user-images.githubusercontent.com/40599423/216158891-3fb890fe-3d40-47e6-9cb2-cc24df681732.png)

Gostaria de saber se posso dar continuidade na implementação.

**Comment by ozzono** [comment]
Eu não aprovo nada, mas acho que ficou ótimo, mesmo com o checkbox padrão.

**Comment by saraiva1989** [comment]
Eu vou deixar melhor não é difícil.
Só não fiz tudo porque não sei se está nos moldes do projeto, aí mandei como estou fazendo para ver se faz sentido. Caso faça eu dou continuidade e devo fazer um PR esse fim de semana ainda .

**Comment by aprendendofelipe** [comment]
> Gostaria de saber se posso dar continuidade na implementação.

@saraiva1989, não precisa pedir permissão para fazer contribuições. 👍

Especificamente sobre o dark mode, vale a pena levar em consideração tudo que foi discutido no #377 e #916 para não ficar travado nos mesmos pontos. 🤝

**Comment by saraiva1989** [comment]
Eu iniciei então, estou implementando e fazendo os testes.

Agora vou ter que trabalhar um pouco no dark dos "pre" e no markdown na escrita de artigos


Uploading TabNews_ Conteúdos para quem trabalha com Programação e Tecnologia - Google Chrome 2023-02-01 21-46-52.mp4…

**Comment by saraiva1989** [comment]
Eu iniciei então, estou implementando e fazendo os testes.

Agora vou ter que trabalhar um pouco no dark dos "pre" e no markdown na escrita de artigos

https://user-images.githubusercontent.com/40599423/216204197-888a2a39-a6a3-4b9d-b7f2-4f045eca056b.mp4

**Comment by birobirobiro** [comment]
> 
> 
> Eu iniciei então, estou implementando e fazendo os testes.
> 
> 
> 
> Agora vou ter que trabalhar um pouco no dark dos "pre" e no markdown na escrita de artigos
> 
> 
> 
> https://user-images.githubusercontent.com/40599423/216204197-888a2a39-a6a3-4b9d-b7f2-4f045eca056b.mp4
> 
> 
> 
> 

Parabéns pela iniciativa! Enquanto a sua PR não chega eu desenvolvi uma maneira alternativa de ter o dark mode direto no navegador:

https://www.tabnews.com.br/birobirobiro/tema-catppuccin-para-o-tabnews

**Comment by aprendendofelipe** [comment]
Foi implementado no PR #1348, e mais ajustes foram realizados no PR #1353 🎉

Obrigado a todos que contribuíram de alguma forma para o dark mode! 💪
