### ISSUE TITLE
[Dúvida] TabNews

### ISSUE THREAD

**Issue by Jetrom17** [filipedeschamps/tabnews.com.br#1203]
A equipe de Deschamps tem acesso as digitações quando o usuário está criando um pots ou comentários em tempo real?

Após "deletado" publicações, conta do usuário ou comentários. Fica salvo do lado de vocês?

Percebi só agora que há termos de uso. Mas não há política de privacidade. Como os dados são tratados? Por exemplo, analíticos da Vercel.

**Comment by filipedeschamps** [comment]
> A equipe de Deschamps tem acesso as digitações quando o usuário está criando um pots ou comentários em tempo real?

Você diz, enquanto o conteúdo não foi publicado? Não, e o `rascunho` fica apenas na máquina local do usuário. Só temos algum dado quando o usuário escolhe enviar para o servidor através de um `POST` ou `PATCH`.

> Após "deletado" publicações, conta do usuário ou comentários. Fica salvo do lado de vocês?

Sim, tudo é um `soft delete` no banco de dados.

> Percebi só agora que há termos de uso. Mas não há política de privacidade.

Bom ponto! De fato não temos política de privacidade e deveríamos ter 🤝

> Como os dados são tratados? Por exemplo, analíticos da Vercel.

Somente salvamos de forma persistente dados do usuário que o sistema precisa para funcionar. Nossa política é: quanto menos dados tivermos, melhor, pois menos atrativo nosso banco de dados será. E também não compartilhamos nenhum dado individual com nenhum terceiro, incluindo o Analytics da Vercel, por conta desta aquisição: https://vercel.com/blog/vercel-acquires-splitbee

**Comment by Jetrom17** [comment]
> Somente salvamos de forma persistente dados do usuário que o sistema precisa para funcionar. Nossa política é: quanto menos dados tivermos, melhor, pois menos atrativo nosso banco de dados será. E também não compartilhamos nenhum dado individual com nenhum terceiro, incluindo o Analytics da Vercel, por conta desta aquisição: https://vercel.com/blog/vercel-acquires-splitbee

O da Vercel eu entendo. Que bom que terá futuramente uma política de privacidade. Quanto mais transparência, melhor. Assim como há transparência o que está acontecendo ou o que aconteceu em relação ao TabNews no GitHub e no TN.

Marcarei como "concluído".

🤝

**Comment by Jetrom17** [comment]
@aprendendofelipe quero que você tenha ciência deste caso. Vejo que as movimentações do TabNews estão vindo, através de você 🫵 Então, talvez possa ajudar a criar uma aba sobre **política de privacidade**. Pois não está claro até o momento que esta _issue_ foi criada para saber sobre "como nossos dados são tratados?".

**Comment by aprendendofelipe** [comment]
Olá @Jetrom17, a política é como o @filipedeschamps explicou, mas ainda não existe um texto bem elaborado que possa ser inserido em uma página específica sobre a política de privacidade.

Então essa é mais uma das oportunidades de contribuição que existem. 💪

Eu não tenho certeza se entendi qual é a sua dúvida, mas se quiser iniciar essa colaboração, recomendo abrir uma issue com um título que chame a atenção de quem quiser contribuir com o assunto.

Com o texto definido e revisado, aí é só abrir um PR com a criação da página. 👍

**Comment by Jetrom17** [comment]
#
> Então essa é mais uma das oportunidades de contribuição que existem. 💪
> 
> Eu não tenho certeza se entendi qual é a sua dúvida, mas se quiser iniciar essa colaboração, recomendo abrir uma issue com um título que chame a atenção de quem quiser contribuir com o assunto.
> 
> Com o texto definido e revisado, aí é só abrir um PR com a criação da página. 👍
> 
#

Certo, irei fazer uma emulação em breve. Fecharei esta _issue_ definitivamente. Estou ciente que o `@filipedeschamps` tenha falado sobre isto.
