### ISSUE TITLE
Erro ao apresentar "tela preta" indevidamente

### ISSUE THREAD

**Issue by raulpy271** [filipedeschamps/tabnews.com.br#1208]
Ao navegar pelo tabnews em dois momentos eu me deparei com o seguinte erro:

![Screenshot from 2023-01-02 21-08-30](https://user-images.githubusercontent.com/56479285/210286664-9c8716ce-4e5f-4904-b537-8e5bfbdecd0a.png)

Ao atualizar a página algumas vezes, o erro não foi mais mostrado, e sim mostrado a página 404:

![Screenshot from 2023-01-02 21-13-59](https://user-images.githubusercontent.com/56479285/210286684-10780343-1885-4530-ac88-8863649f40a8.png)

Este erro aconteceu duas vezes:

- A primeira vez aconteceu ao acessar um post que havia sido deletado. Após receber a "tela preta" e atualizar a página algumas vezes eu recebo a página de 404, ou seja, passou a funcionar como esperado.
-  A última vez aconteceu ao acessar um [post](https://www.tabnews.com.br/HerbertGeorgeWells/como-a-algebra-linear-e-utilizada-na-ciencia-da-computacao) que está publicado e disponível. Neste caso, ao acessar o post recebo a "tela preta", após atualizar algumas vezes o post eu comecei a receber 404, continuei atualizando a página, até que a página retornou o post, como esperado.

Peço perdão se não dei informações o suficientes para ajudar a entender o problema, infelizmente também não entendi quando e porquê este erro acontece.

**Comment by aprendendofelipe** [comment]
@raulpy271, obrigado por reportar. 👍

Isso será solucionado com #1154
