### ISSUE TITLE
Criar documentação

### ISSUE THREAD

**Issue by brenio55** [filipedeschamps/tabnews.com.br#1209]
Criar documentação sobre recursos do website, como explicar melhor sobre os TabCoins e TabCash, etc.

**Comment by Rafatcb** [comment]
Realmente é uma informação importante, mas acho que isso deve estar num FAQ.

Como o FAQ é mais abrangente do que apenas essa informação específica, tem uma issue específica para discutir o que ter nele e acompanhar a implementação: https://github.com/filipedeschamps/tabnews.com.br/issues/1380. Acho legal concentrarmos o assunto lá.

**Comment by aprendendofelipe** [comment]
Boa @brenio55 e @Rafatcb! 💪

Vamos centralizar na #1380 🤝
