### ISSUE TITLE
Markdown editor com um problema na digitação

### ISSUE THREAD

**Issue by letsaguiar** [filipedeschamps/tabnews.com.br#1212]
Hoje fui escrever um artigo para o tabnews e me deparei com o seguinte erro: sempre que tentava corrigir algo que foi escrito lá atrás, o editor "comia" as letras da frente. 

Exemplo: se escrevi `bon dia`, posicionei o cursor em frente ao `n` e o excluí, tudo funcionou bem. Porém, ao tentar adicionar o `m` o editor excluía o espaço logo à frente, ficando `bomdia`.

**Comment by aprendendofelipe** [comment]
Oi @letsaguiar, isso ocorreu em smartphone?

Temos um problema conhecido com a biblioteca ByteMD que de vez em quando faz isso no mobile.

**Comment by letsaguiar** [comment]
Não, foi no desktop mesmo

**Comment by Rafatcb** [comment]
Esse é o comportamento da tecla <kbd>Insert</kbd> no [modo "substituir"](https://pt.wikipedia.org/wiki/Insert_(teclado)#Modo_%C2%AB_substituir_%C2%BB) (_overtype_). Consegui reproduzir aqui colocando nesse modo. Você pode confirmar se foi isso o que aconteceu, @letsaguiar ?
