### ISSUE TITLE
Permitir a definição de assinatura

### ISSUE THREAD

**Issue by bruno-lopes** [filipedeschamps/tabnews.com.br#1213]
**Como:**
Usuário do TabNews

**Eu gostaria de:**
Definir uma assinatura que aparecesse em todas as postagens

**Para que:**
 Fique mais fácil criar nossa uma pessoal na comunidade e facilitar a identificação das pessoas.

**Descrição detalhada:**

Seria interessante no perfil poder definir uma assinatura (com limite de tamanho) para permitir uma melhor identificação do usuário. Coisas simples como por exemplo o cargo que ocupa, ou algum contato em rede social. Isso pode contribuir na formação de uma comunidade.

**Comment by Rafatcb** [comment]
Como esse issue não teve interações durante esse quase um ano, estou fechando para organizar o repositório. Se alguém deseja adicionar mais argumentos para defender a adição desse recurso, pode comentar que reabrimos para debate.

Deixando minha opinião: acredito que o nome do usuário aparecendo na publicação já é o suficiente para a identificação. Hoje, o usuário pode modificar sua descrição no perfil para compartilhar qualquer informação que deseja. A descrição não existia na época da criação desse issue.

Obrigado pela sugestão, Bruno!
