### ISSUE TITLE
[Sugestão] Salvar uma publicação como favorita

### ISSUE THREAD

**Issue by rCirelli** [filipedeschamps/tabnews.com.br#1229]
A ideia seria adicionar uma forma de salvar uma publicação como favorita pro usuário.
Eu estava procurando uma publicação que vi a algum tempo nos meus favoritos do navegador e não encontrei. Por isso acho que seria interessante algum mecanismo que possibilite favoritar uma publicação diretamente na plataforma.

**Comment by tigocode** [comment]
@rCirelli, concordo com você!
Acredito que uma funcionalidade como essa seria bacana.

**Comment by pedrolucaslcosta** [comment]
Agora mesmo quis uma opção de salvar uma publicação e não existia. Seria bastante interessante para consulta futura.

**Comment by luisArthurRodriguesDaSilva** [comment]
Po, eu vim aqui escrever uma issue falando do mesmo
Sinal que é algo bem desejável
Tem mta coisa boa la no tabnews que eu queria salvar mas n posso, ou mando pro wpp que ja tem um monte de outras anotações misturadas

**Comment by ItanuRomero** [comment]
Acabei de encontrar um artigo incrível que eu gostaria de salvar, como estamos com essa ideia?

**Comment by luisArthurRodriguesDaSilva** [comment]
Creio q parados kkkk

**Comment by ItanuRomero** [comment]
Vish, kkkkkkkkk, vou terminar o curso.dev e aprender como mexer na plataforma pra poder fazer um PR aqui criando essa funcionalidade

**Comment by aprendendofelipe** [comment]
Obrigado pela issue! 👍

Por organização, estou fechando as duplicadas com a #645 🤝
