### ISSUE TITLE
Erro de persistência

### ISSUE THREAD

**Issue by LuhBC-pixel** [filipedeschamps/tabnews.com.br#1231]
Dei downvote em um post que tinha propaganda. Aí, voltei para a lista de recentes e vi que neste post não tinha avaliações neles.

Outro caso foi quando procurava um post. Fui para primeira página, não achei e fui para segunda página e também não achei. Quando voltei para primeira página, achei o post.

**Comment by aprendendofelipe** [comment]
Olá @LuhBC-pixel, você encontrou algum problema de persistência mesmo considerando que existe cache das páginas?

O que você descreveu parece normal se levar em consideração que existe cache.

**Comment by LuhBC-pixel** [comment]
É verdade, esqueci da existência do cache.
