### ISSUE TITLE
Barra de pesquisa e Visualizações

### ISSUE THREAD

**Issue by HenryGuidelli** [filipedeschamps/tabnews.com.br#1232]
- Seria muito útil ter algum mecanismo de pesquisa, pois assim seria mais fácil encontrar uma publicação ou um usuário em especifico. 
- Minha sugestão para visualizações nas publicações é por conta de que acho que ajudaria a ver quais são as publicações com títulos mais chamativos e os assuntos que mais chamam a atenções, pois muitas publicações são muito interessantes mas não tem comentários.

**Comment by desenvolvedormatheus** [comment]
Na minha opnião, é legal não ter esse esquema de visualizações pra não terem post muito tempo sobre outros. Assim como está temos uma igualdade justa no rank das publicações.

**Comment by desenvolvedormatheus** [comment]
Na minha opnião, é legal não ter esse esquema de visualizações pra não terem post muito tempo sobre outros. Assim como está temos uma igualdade justa no rank das publicações.

**Comment by azevgabriel** [comment]
Acho relevante tbm, eu queria fazer uma pesquisa no Fórum sobre Background Jobs (filas) no Node.js mas não existe essa funcionalidade.

**Comment by Irineu333** [comment]
Também sinto falta de um sistema de pesquisa

**Comment by Mezzalir** [comment]
Uma barra de pesquisa seria extremamente útil.

**Comment by aprendendofelipe** [comment]
@HenryGuidelli, obrigado pela sugestão! 💪

Estou fechando por ser duplicada com a #927.

Sugiro continuarmos a discussão por lá. Combinado? 🤝
