### ISSUE TITLE
Abrir links em tela externa.

### ISSUE THREAD

**Issue by felipemaion** [filipedeschamps/tabnews.com.br#1233]
Seria interessante ao clicar num link de dentro de uma publicação, manter a TabNews aberta, e abrir em uma nova aba. 
Sem tirar a gente da TabNews (que está fixada no meu Browser, e quando clico fica esse novo link fixado).

**Comment by luiznasciment0** [comment]
Vou mandar uma PR abrangendo essa issue, porque foi uma "dor" que senti enquanto estava utilizando a plataforma

**Comment by aprendendofelipe** [comment]
@felipemaion, obrigado pela issue!

Vamos centralizar a discussão na issue relacionada #477 👍

Recomendo ler esse [comentário do Filipe.](https://github.com/filipedeschamps/tabnews.com.br/issues/477#issuecomment-1182110074)
