### ISSUE TITLE
[Sugestão] Tags nas publicações

### ISSUE THREAD

**Issue by kaiopiola** [filipedeschamps/tabnews.com.br#1234]
Inclusão de tags nas publicações, para posteriormente facilitar a busca por um determinado tópico ou assunto.
Estamos vendo o TabNews crescer bastante, e cada dia mais vejo mais conteúdos "não-perecíveis" sendo criados, como posts com dicas ou tutoriais, que apenas alguns dias ou horas após postado, somem no eterno limbo da página 2 pra frente dos recentes ou relevantes.
Acho que, para um futuro onde imaginamos o TN com sistema de buscas, começar a ter tags agora pode ser uma boa opção para já começar a realizar essa indexação internamente e a função de pesquisa já começar com um conteúdo-base futuramente.

Eu busquei mas não encontrei nada relacionado a isso aqui nas issues, então se já fizeram essa sugestão eu peço que me avisem, para que eu possa apenas incluir o link para a issue mais antiga e fechar essa daqui!

**Comment by Dev-Lyh** [comment]
Bom dia @kaiopiola! Tudo bem?

Acho que essa issue tem o mesmo intuito desta outra issue já aberta: <a href="https://github.com/filipedeschamps/tabnews.com.br/issues/981">[Sugestões] Labels nos posts #981</a>

Com tantos usuários do TabNews pedindo essa feature, o Filipe provavelmente vai considerar torná-la realidade :)

**Comment by kaiopiola** [comment]
> Bom dia @kaiopiola! Tudo bem?
> 
> Acho que essa issue tem o mesmo intuito desta outra issue já aberta: [[Sugestões] Labels nos posts #981](https://github.com/filipedeschamps/tabnews.com.br/issues/981)
> 
> Com tantos usuários do TabNews pedindo essa feature, o Filipe provavelmente vai considerar torná-la realidade :)

É exatamente isso que eu estava pensando, muitíssimo obrigado, vou fechar essa Issue e acompanhar pela #981 !!
