### ISSUE TITLE
Links nos artigos não tem o atributo rel="NOFOLLOW"

### ISSUE THREAD

**Issue by bgabraga2** [filipedeschamps/tabnews.com.br#1236]
Olá pessoal, venho acompanhando ativamente o **TabNews** e também criando conteúdo lá, mas identifiquei um ponto que alguém pode usar de forma maliciosa, afim de posicionar alguma coisa no google.

Veja só:
Quando escrevemos um texto e colocamos um link externo neste texto ele não adiciona o atributo NOFOLLOW. Isso é importante porque o não uso do _NOFOLLOW_, quer dizer que o **TabNews** ENDOSSA o conteúdo externo em termos de SEO.

Uma citação do artigo:

> O Google estava atento a essa mudança no padrão e entendeu que isso desvirtuava a natureza própria dos links na internet (e o motivo pelo qual os links eram um fator importante na classificação dos sites) e resolveu agir, criando o valor “nofollow” para o atributo de link “rel” que tem o intuito de sinalizar para o googlebot que o site não endossa o destino daquele link, não passando “juice”, pagerank, força, etc. Não influenciando em seu ranqueamento nos resultados de busca.

Um breve artigo aqui: https://pt.semrush.com/blog/lins-nofollow-beneficiam-seo-ou-nao/

No **TabNews** já começo a ver algumas pessoas(de propósito ou não) utilizando este recurso para melhorar o posicionamento deles com algumas palavras chaves. Veja um exemplo: https://www.tabnews.com.br/bokamoto/pitch-comunidade-indie-hacker-brasileira

Minha sugestão é: Todo link externo que for colocado no artigo, adiciona o `rel="nofollow"` para evitar esse abuso, e ter ainda mais credibilidade no **TabNews** em termos de SEO

O que vocês acham?

**Comment by Rafatcb** [comment]
Acho ótimo. Parece que precisaríamos [escrever um plugin](https://github.com/bytedance/bytemd?tab=readme-ov-file#plugin-system) para o ByteMD.

Vale mencionar que:

- Deve ser possível usar ou não usar o `rel="nofollow"`, porque hoje algumas páginas tem seu conteúdo feito com markdown e interpretadas pelo `Viewer` do ByteMD, então não há necessidade desse cuidado nessas páginas.
- Muito provavelmente essa proteção deve ser implementada tanto nos conteúdos quanto na descrição do perfil do usuário (que, na época da criação desse issue, não existia).
