### ISSUE TITLE
[Sugestão de UX] Botão de "Publicar novo conteúdo" direto no header

### ISSUE THREAD

**Issue by pedrolucaslcosta** [filipedeschamps/tabnews.com.br#1238]
Fiquei um pouco confuso de primeira sem saber onde ir para criar uma nova publicação pelo fato da função Publicar novo conteúdo estar visível apenas quando se clica na foto de usuário. Acredito que seria mais prático e intuitivo um botão de "+" ou algo semelhante diretamente no header para um acesso mais rápido.

**Comment by aprendendofelipe** [comment]
@pedrolucaslcosta, obrigado pela issue! 💪

No #1349 o @victorhcb implementou um botão no header de dispositivos com telas maiores 🎉

Então vou encerrar aqui 🤝
