### ISSUE TITLE
[Melhoria] - Sistema de buscas

### ISSUE THREAD

**Issue by patrick095** [filipedeschamps/tabnews.com.br#1239]
Se tópico estiver duplicado favor ignorar e fechar

A ideia seria implementar um sistemas de buscas pois, achei um artigo bem interessante uns dias atrás e quando fui procurar de novo deu maior trabalho para encontrar. Um outro ponto é quando vejo um artigo interessante e quero ver se há alguns parecidos e sem sistema de buscas fica bem complicado de descobrir.

Acredito que com um sistema de buscas iria ajudar bastante.

A iniciativa está muito show!! Gostando demais desse projeto! 😄

**Comment by gabrielccarvalho** [comment]
Talvez precise de alguma revisão em termos de design, mas acredito que a ideia da issue foi resolvida nesse PR.

**Comment by Lukardoso** [comment]
Ótimo, ia sugerir isso agora. Mecanismo de busca facilita muito, ou divisão por assunto ou os dois rsrsrs.

**Comment by thiagohmcruz** [comment]
+1 uma busca mesmo que básica ia fazer bastante diferença!

**Comment by patrick095** [comment]
> Talvez precise de alguma revisão em termos de design, mas acredito que a ideia da issue foi resolvida nesse PR.

Gabriel, coloquei algumas anotações no teu PR, não testei nem nada, mas são umas melhorias que podem ser vistas, valeu.

**Comment by matheuswr89** [comment]
Creio que adicionar uma aba "History" onde a gente pode ver todos os post que a gente já visualizou, seria uma boa também. Pq aí a gente não teria que ir diretamente no sistema de busca e ter que repetir os passos até chegar no que queremos ver.

**Comment by Rafatcb** [comment]
@aprendendofelipe vi que você fechou alguns issues para concentrar a discussão sobre buscas no #927, então acho que faz sentido fechar este também, certo?

**Comment by aprendendofelipe** [comment]
Boa @Rafatcb! 💪

Direcionando a discussão para:

- #927
