### ISSUE TITLE
"Tab Sobre" - Latência alta

### ISSUE THREAD

**Issue by Jetrom17** [filipedeschamps/tabnews.com.br#1240]
Meu Desktop contém 4 GB de RAM (DDR3) e o CPU de 2 núcleos. O Consumo por média é de ~54%. Sendo o processador `Intel© Celeron© CPU  J1800  @ 2.41GHz × 2`. Meu sistema operacional é Linux (Mint) e o navegador usado, Brave (Beta).

Quando acesso aba de **Sobre** há uma latência alta para ser carregada por completo.  Usei o Dev Tools para verificar. `129.90 ms` é o dado da demora de resposta do servidor. A solicitação enviada foi de `1.98 ms`. No total esperei cerca de 11 segundos para página ser completada. Além dos comentários é claro.

https://www.tabnews.com.br/filipedeschamps/tentando-construir-um-pedaco-de-internet-mais-massa

A url a cima pode afetar outros usuários novos, tendo impacto negativo sobre a plataforma. **Solicito** atenção da equipe de Deschamps para averiguar o problema.

+ Atualizando esta _issue_, percebi que **sem javascript**, página carrega cem vezes, mais rápido.

Nota: Estou usando DNS (Warp), apenas, da Cloudflare, o mesmo usado no TabNews. Estou no Brasil.

> Espero que essa "gama" de informações podem ter sido explicado melhor, sem perder objetivo do caso.
>> By Jeiel.

**Comment by cybernerd007** [comment]
Fiquei 2 dias testando/explorando e sem duvida o problema se encontra no **Children** que tem 701 comentários, acredito que seria menos estressante tanto para o navegador do usuário quanto para o servidor carregar por partes quanto o usuário for descendo a pagina...

@filipedeschamps vou marcar você pois se trata também de um problema de segurança já que pode resultar em um DDOS(ou somente sobrecarregar e tornar o site lento/instável) se aberto algumas abas já que por cada solicitação e transferido quase 1MB para o cliente

**Comment by Ryannnkl** [comment]
uma paginação para limitar o número de comentários resolveria parte do problema, mas, em contrapartida, não acho que podemos limitar o número de comentários dentro de comentários, mesmo que limite o número de comentários, o número de comentários dentro de outro comentário pode levar a esse mesmo problema.

não sei se consegui me expressar bem kk

**Comment by aprendendofelipe** [comment]
@Jetrom17, sentiu alguma melhora no últimos 10 dias? Agora só estão aparecendo cerca de 100 respostas e o restante só fica visível se clicar em "ver mais respostas".

![image](https://user-images.githubusercontent.com/77860630/227784998-c626c0d3-6458-4874-af8e-4420c33032dc.png)


Seria interessante se tivesse testado nos dois dias que ficou limitado a cerca de 20 respostas.

**Comment by filipedeschamps** [comment]
Eu abri aqui e na minha opinião ta **muuuito** mais rápido, mesmo puxando do backend tudo.

Sonho por essa feature na plataforma do curso 💪   a aula do `bem-vindo` saiu completamente do controle por conta da quantidade de comentários lá 👍

**Comment by Jetrom17** [comment]
Agora melhorou. Essa issue faz 2 meses.

**Comment by Jetrom17** [comment]
Agora melhorou. Essa issue faz 2 meses.
