### ISSUE TITLE
[Sugestão] Ordenação de resultado de content pela data de atualização

### ISSUE THREAD

**Issue by TeoCalvo** [filipedeschamps/tabnews.com.br#1241]
Seria ótimo poder pegar não só pela ordem que os contents foram criados ou pela relevância, mas também pelos mais atualizados, isto é, aqueles que receberam comentários recentemente, edição ou tabcoins.

Pode ser um feature interessante tanto pela UI quanto pela API disponibilizada. No meu caso, foi pelas consultas da API que senti falta disso.

O endpoint que utilizei foi este: https://www.tabnews.com.br/api/v1/contents?page=1&per_page=100&strategy=new

Talvez haver uma *strategy* para update evite a necessidade de um novo endpoint.

**Comment by cybernerd007** [comment]
Muito interessante sua sugestão, acredito que seja aplicada no futuro mas sem duvida da pra fazer isso que você falou somente consumindo a API e filtrando ela, fico a disposição pra te ajudar no código caso queira...

**Comment by TeoCalvo** [comment]
@cybernerd007 valeu pela resposta.

Em meus scripts, já consigo fazer uma solução de contorno, mas preciso listar todas as `pages` do endpoint. A questão é que se um post (particularmente os mais antigos) é atualizado ou ganha mais Tabcoins, mesmo pegando por essa estratégia não vamos ter visibilidade, certo? A não ser que percorra sempre todas as `pages`.  :( 

Por isso pode ser uma boa ideia ter uma strategy=updated_at (algo assim), ordenando os contents pela sua atualização, seja por edição, tabcoins, childs, etc. Assim evitamos percorrer todas as pages para pegar todos os contents atualizados, trabalhando apenas com as pages mais recentes até determinada data/hora. Não sei se me fiz entender hehe. Mas é algo que ajudaria tanto na coleta dos dados (em velocidade), quanto evitaria o escalonamento de minhas requests à API.

**Comment by Rafatcb** [comment]
Obrigado pela sugestão, Teo! Já temos um issue aberto sobre a possibilidade de listar por TabCoins, mas acabei editando ele para ficar mais abrangente e englobar sua sugestão também, assim podemos concentrar a discussão em um único issue.

* https://github.com/filipedeschamps/tabnews.com.br/issues/1043
