### ISSUE TITLE
[SUGESTÃO] Posts favoritos

### ISSUE THREAD

**Issue by desenvolvedormatheus** [filipedeschamps/tabnews.com.br#1244]
Seria legal um sistema de "favoritar" as publicações ou algo parecido pra facilitar a volta em alguma publicação posteriormente.

**Comment by coffee-is-power** [comment]
Use os marcadores do navegador, eles existem por algum motivo...

**Comment by eletroswing** [comment]
@coffee-is-power  e no smartphone? copiar os links em lugares separados certamente não é legal, além de poder criar "playlists" de posts relacionados como playlist de alguem só com conteudo de python crawler, e outro com conteudo so de gpt, etc

**Comment by aprendendofelipe** [comment]
@desenvolvedormatheus, obrigado pela sugestão! 💪

Vou fechar a issue por ser duplicada com a #645. Combinado? 🤝
