### ISSUE TITLE
[SUGESTÃO] Criar Uma Tab Separada Para Comentários-Respostas No Perfil Dos Usuários

### ISSUE THREAD

**Issue by Xnork** [filipedeschamps/tabnews.com.br#1245]
É notável que os usuários não usam direto o comentário para um conteúdo sólido, assim deixando bagunçado na visualização de posts de usuários que gostam de comentar e postar conteúdos. Minha sugestão é que tenha 2 tabs, uma para posts e outra para comentários para cada usuários.

**Comment by aprendendofelipe** [comment]
@Xnork, obrigado pela sugestão! 💪

Isso @Rafatcb, ainda não temos muito avanço sobre isso, mas acredito que a issue #807 seja o melhor lugar para centralizar o assunto. 👍

Fechando essa aqui como duplicada. 🤝
