### ISSUE TITLE
Google Console acusando problemas de CLS em várias páginas

### ISSUE THREAD

**Issue by filipedeschamps** [filipedeschamps/tabnews.com.br#1252]
Turma, olha que interessante que começou a aparecer no Google Console a partir do dia **27 de Janeiro** (apenas em Desktop):

https://user-images.githubusercontent.com/4248081/217318434-0ca4b695-725b-4832-a3bd-e97a9e0c96e0.mov

Ele está acusando problema de CLS nas páginas (layout shift):

<img width="1181" alt="image" src="https://user-images.githubusercontent.com/4248081/217317894-15d1f225-f48a-4866-8922-0a489e567e68.png">

Muito estranho, porque o último merge foi feito lá por volta do dia **10-11 de Janeiro**.

**Comment by aprendendofelipe** [comment]
Muito estranho, pois realmente o último *deploy* foi em 11/01/2023.

Poderia ser uma mudança recente na maneira como o Google pontua o CLS, mas a última mudança que divulgaram passou a vigorar em [01/06/2021](https://web.dev/cls/). Só se mudaram agora sem avisar, o que parece ser mais provável.

Sobre mudanças no código do TabNews que poderiam impactar o CLS, o `ByteMD` foi atualizado em outubro e no início de dezembro houve uma refatoração do `Content` com a criação do componente `Markdown`. Mesmo que o Google demorasse para perceber a mudança nos conteúdos antigos já indexados, acho que teríamos o início da subida das páginas com problemas muito antes de 27 de janeiro se o problema fosse por aqui, pois os conteúdos postados logo após as mudanças no código não demorariam tanto assim para serem indexados.

Outra coisa estranha é a proporção de páginas com e sem problemas (6.058/1.015). Pela grande quantidade de URLs com problema, só pode ser algo com as páginas de conteúdos, mas se fosse algo do site em si, não teríamos essas 1.015 páginas classificadas como boas. E essas boas não podem ser conteúdos antigos indexados que o Google ainda não atualizou, pois existem centenas de páginas que estão sendo qualificadas como boas, e esse número está crescendo, o que me leva a acreditar que é algo que depende do tipo de conteúdo publicado.

A primeira coisa que me vem a cabeça são as imagens, mas a proporção de conteúdos com e sem imagens não deve ser nem perto de 6.058/1.015. E no [PageSpeed Insights](https://pagespeed.web.dev/) até acusa que as imagens deveriam ter `width` e `height` explícitos, mas isso não deixa o CLS acima de 0.1 pontos (só na página de status que passa disso, chegando a 0.137).

Algo que poderia impactar todas as páginas é o aparecimento dos links para `Login` e `Cadastrar` no `Header`, que ocorre alguns instantes após a primeira renderização.

Outro pequeno deslocamento ocorre na parte que mostra a quanto tempo o conteúdo foi publicado.

Também pode ter relação com o tamanho do conteúdo publicado, talvez o visualizador do ByteMD se redimensione em algumas situações.

Mas nada disso mudou recentemente.

**Comment by filipedeschamps** [comment]
Tudo voltou ao normal e com zero páginas com problema 🤝 

<img width="1045" alt="image" src="https://user-images.githubusercontent.com/4248081/221311886-bd36c55c-c793-4376-a0df-d752b5706dff.png">
