### ISSUE TITLE
[SUGESTÃO] Redirecionamento do login

### ISSUE THREAD

**Issue by hgsantana** [filipedeschamps/tabnews.com.br#1256]
Olá, pessoal.

Em primeiro lugar, parabéns pelo projeto. Já sou um grande fã, apesar de não ter interagido na plataforma ainda.

Aqui vai a sugestão: em vez de um redirect com avanço no histórico, após o login, usar um redirect com replace do histórico.

Caso de uso e como reproduzir:
- abrir uma matéria via link (deslogado)
- tentar reagir a alguma coisa
- aparece a tela de login automaticamente; faça o login
- você é redirecionado para a matéria novamente com avanço do histórico
- ao tentar voltar, você retornará para a tela de login que te enviará automaticamente para a mesma matéria, indefinidamente.

Problema: usuário não consegue retornar no histórico para antes da tela de login. Ao menos não de forma intuitiva.

Solução: replace do histórico após o login. Assim, ao voltar, o usuário não passará pelo login e pelo redirect para frente.

**Comment by aprendendofelipe** [comment]
Olá @hgsantana, muito obrigado pela sugestão! 💪

Ela foi implementada no #1321 🚀

**Comment by aprendendofelipe** [comment]
@hgsantana você foi citado no post comemorativo: https://www.tabnews.com.br/FelipeBarso/tabnews-exibir-ocultar-respostas-e-mais-outras-melhorias 🎉
