### ISSUE TITLE
Motivo por não utilizar o styled-components

### ISSUE THREAD

**Issue by zLucasBiasi** [filipedeschamps/tabnews.com.br#1258]
Gostaria de entender o motivo de termos o "styled-components" instalado, mesmo sem utilizá-lo em nenhuma etapa do desenvolvimento. 
Tem alguma biblioteca que esteja utilizando? Caso não, poderíamos remover ele ou utilizar ele nos componentes.

**Comment by coffee-is-power** [comment]
styled components é bem controverso, css-in-js é bem controverso no geral, usaria tailwind no lugar dele, da menos dor de cabeça e consigo separar claramente as seçoes dos componentes, tipo, antes do return do html é a logica, é so js, e no html tem o conteudo e os estilos.

**Comment by aprendendofelipe** [comment]
Olá @zLucasBiasi, precisamos do `styled-components` para o `primer/react` 👍
