### ISSUE TITLE
[Feature] - Tempo gasto em escrever artigo

### ISSUE THREAD

**Issue by C4stro** [filipedeschamps/tabnews.com.br#1261]
Talvez não seja relevante pra muitos.
Mas eu vejo as vezes que a galera gasta MUITO tempo fazendo um artigo muito bom e não temos visibilidade nenhuma disso.

Seria interessante saber quanto tempo a pessoa dedicou em um artigo pois vejo um valor gigante nisso.
A pessoa gastou 1, 2, 3 horas do tempo dela pra escrever algo pra outros sem pedir nada em troca (essa pessoa é maravilhosa demais).

**Comment by silviooosilva** [comment]
Bem massa a ideia kkkk

**Comment by gabrielsozinho** [comment]
A ideia em si não é boa, eu também admiro muito pessoas que criam um artigo bem estruturado e rico e informações. No entanto, acredito que essa ideia não vá pra frente por ser facilmente manipulável, imprecisa e injusta. 

Imagine só uma situação onde a pessoa escreveu durante menos de 10 minutos o artigo e deixa o computador ligado só pra aparecer mais tempo, ou então uma em que uma pessoa passa horas escrevendo em algum outro programa e cola no editor do TabNews fazendo com que pareça que ele demorou poucos minutos pra escrever aquilo. Não acha que seria bem injusto?

Também acredito que o conteúdo deve ser avaliado pela sua qualidade, e talvez isso causaria uma interferência na decisão de se post é bom ou não. 👍🏻

**Comment by CristianoSword** [comment]
Concordo com o Gabriel, é algo muito fácil de ser manipulado. É melhor deixar que seja avaliado pelos tabcoins ou só pela qualidade mesmo. Amo essas pessoas que gastam seu precioso tempo fazendo artigos maravilhosos, tanto que tenho varios salvos nos meus bookmarks.

**Comment by zLucasBiasi** [comment]
@gabrielsozinho eu estava fazendo uns testes e consegui fazer um exemplo simples onde o tempo só continua quando o usuário digita algo, tipo se ele segurar a letra A por exemplo o tempo para de contar, o tempo apenas conta quando o usuário esta digitando realmente. Não seria uma solução?

**Comment by hkotsubo** [comment]
No meu caso, eu prefiro escrever sempre fora do site (usando algum editor, como o Sublime), por vários motivos (o textarea é pequeno e não dá pra redimensionar, não há o perigo de enviar sem querer antes de terminar, etc). Enfim, eu escrevo tudo no editor, e no final só copio e colo no site. 

Nesse caso, iria parecer que eu escrevi tudo em um segundo, o que está longe de ser verdade (já que sou um *slow typist*).

**Comment by B-Schmitz** [comment]
Seria interessante também marcar o tempo de leitura do artigo.

**Comment by Rafatcb** [comment]
@aprendendofelipe parece que a comunidade já escolheu que essa funcionalidade não seria legal para o TabNews. Podemos fechar a issue?

Sobre o tempo de leitura, foi implementado aqui: https://github.com/filipedeschamps/tabnews.com.br/pull/1445
