### ISSUE TITLE
Bug: comportamento erratico na ultima linha do editor

### ISSUE THREAD

**Issue by iget-master** [filipedeschamps/tabnews.com.br#1262]
Quando estamos digitando um texto longo no editor de textos, ao atingir o final da area do editor, o mesmo não rola automaticamente, e começamos a digitar as cegas.

Outra situação é que você digita uma ultima linha/paragrafo, e quando apaga e clica na linha anterior, o texto ressurge.

Alguém já experimentou as mesmas situações?

Uso o tabnews apenas do chrome no android.

**Comment by Ryannnkl** [comment]
o tabnews utiliza um componente chamado [bytemd](https://bytemd.js.org/) e esse campo de texto onde a gente escreve é integrado nesse componente, o que o torna difícil de mexer nele de forma íntegra.

o componente do editor no código: 
https://github.com/filipedeschamps/tabnews.com.br/blob/f0db9131dd2ae08f6417d48b2d09b99c8baf6243/pages/interface/components/Markdown/index.js#L45-L52

mas como ele aceita props é possível adicionar algumas estilizações como diminuir esse campo de texto nas versões mobile já que no desktop não tem esse problema, cabe a galera resolver se pode mexer na estilização dessa pagina.

se puder eu fico feliz em fazer uma PR.

**Comment by iget-master** [comment]
É simplesmente impossivel escrever textos longos nesse editor no mobile. Acho que este tema deveria estar nas prioridades.

Se voce digitar por exemplo

> # Algum titulo

E tentar dar enter para ir na próxima linha, ele simplesmente não aceita.

Se colocar um ponto final apos a plavra título ele deixa.

Se você desiste de um texto e tenta apagar, em algum momento o texto que vc apagou ressurge.

Tem algo muito errado, rs

**Comment by aprendendofelipe** [comment]
Turma, obrigado pela issue! 💪

Esse já é um comportamento conhecido e recomendo continuar a conversa na issue #648, que é mais antiga.

Vou fechar essa como duplicidade. Ok?
