### ISSUE TITLE
Como testar em mobile?

### ISSUE THREAD

**Issue by iget-master** [filipedeschamps/tabnews.com.br#1263]
Estou tentando trabalhar em cima de um bug que encontrei, mas quando tento debugar remotamente no meu celular, a tela carrega em branco. Alguma dica?

**Comment by PatoGordo** [comment]
Se for testar no android e com o chrome existe uma ferramenta do próprio chrome que possibilita isso, segue o link dela abaixo

https://developer.chrome.com/docs/devtools/remote-debugging/

**Comment by iget-master** [comment]
A questão não é essa. O problema é que não carrega nada, a tela fica em branco. É como se o webpack não estivesse liberando fora do localhost

**Comment by PatoGordo** [comment]
Que estranho, tenta mudar as variáveis de ambiente que usam a url localhost no front end para o ip, talvez funcione

**Comment by aprendendofelipe** [comment]
Encerrando essa issue por inatividade 🤝

**Comment by Rafatcb** [comment]
Uma outra alternativa que descobri por meio [desse comentário do TabNews](https://www.tabnews.com.br/lindias/44236a6f-a023-45a6-9758-a1ed821343f1) é que dá para expor a porta pelo próprio Visual Studio Code, por meio da conexão com o GitHub.

Para quem quiser saber mais, pode ler [a documentação](https://code.visualstudio.com/docs/editor/port-forwarding), mas é bem simples.

**Comment by aprendendofelipe** [comment]
@iget-master, você foi citado na publicação sobre as novidades do TabNews:

https://www.tabnews.com.br/FelipeBarso/tabnews-novas-correcoes-e-revenue-share-se-materializando 🎉
