### ISSUE TITLE
Erro ao conectar mensagem "Não foi possível se conectar ao TabNews. Por favor, verifique sua conexão."

### ISSUE THREAD

**Issue by teseu** [filipedeschamps/tabnews.com.br#1266]
Ao tentar responder a uma questão colocado em um post a mensagem 
`
"Não foi possível se conectar ao TabNews. Por favor, verifique sua conexão." 
`
aparece acima da área de texto e não foi possível postar.

A conexão não é o problema, abro todos os posts sem problema e também qq página.

**Comment by filipedeschamps** [comment]
@teseu interessante, os logs aqui não marcaram nenhum erro interno sobre essa tentativa e esta mensagem aparece quando de fato o `client` não consegue se conectar com o `server`. Será que foi algum proxy no meio que falhou?

E você tentou de novo? Se sim, recebeu qual mensagem?

**Comment by teseu** [comment]
Todas as tentativas deram na mesma msgm e eu ñ uso proxy aqui. Tb achei deveras estranho, por isso abri uma issue, tomando o cuidado de ver se ñ tinha algo parecido antes.

**Comment by teseu** [comment]
Até guardei a msgm pra enviar em outro momento, pq ficando assim tô 'proibido' de mandar msgm.

**Comment by aprendendofelipe** [comment]
@teseu, pode nos passar qual foi mais ou menos o horário das tentativas? Foi a partir de 19h10?

Acho que seu acesso à API foi bloqueado por ter atingido o rate-limit. Por isso você consegue navegar, mas não vai conseguir fazer nada que use a API.

**Comment by teseu** [comment]
Foi a partir desse horário mesmo. Mas pq atingi o rate-limit?

**Comment by teseu** [comment]
Eu ñ publiquei nada nos últimos dias

**Comment by aprendendofelipe** [comment]
@teseu, na verdade não foi rate-limit, mas a Cloudflare detectou uma vulnerabilidade nas requisições vindas do IP que você está utilizando.

Não tenho como saber exatamente o que ela está detectando, mas chuto que é algo que foi ou que está sendo enviado nos headers.

Pode ser algum vírus na sua máquina que está tentando aproveitar alguma vulnerabilidade, mesmo que o TabNews não tenha essa vulnerabilidade específica. Mas também pode ter sido algo que ocorreu em algum acesso para outros sites. Inclusive pode ter ocorrido com outra pessoa, caso seu IP não seja fixo ou você esteja em uma rede pública.

Consegue usar o mesmo equipamento em outra rede para isolar se o problema é com seu equipamento? Se isso não for possível, então reinicie seu modem para ele obter outro IP.

Depois nos diga o que você fez e qual foi o resultado. 🤝

**Comment by teseu** [comment]
Vírus acho difícil, tenho um comportamento bem avesso a isso, ñ precisaria de antivírus nem no windows, o q ñ é o meu caso na hora da tentativa de postagem.

As abas q tenho abertas no momento tb ñ me parecem afetar qq coisa desse tipo, cursos online, coisas relacionadas (tech guide da alura, boracodar da rocketseat, atlas da mongodb, meu email, documentação tailwind, youtube, nada q levante qq suspeita), mas o IP dado pela operadora eu ñ sei é único de verdade, operadoras nunca podemos confiar.

A rede é a única q tenho, já q estou em casa e já desconectei da vpn do trabalho, mas vou reiniciar o modem como sugerido e testar novamente, qq resultado eu informo.

**Comment by teseu** [comment]
Após reiniciar o modem, espero ter ganho um IP novo, ñ conferi qual estava antes, mas tudo permanece.

**Comment by aprendendofelipe** [comment]
@teseu, seu IP mudou sim. O estranho é que dos 128 bits do IPv6, apenas 1 bit mudou (o último), mas mudou...

Pode ser algum problema na Cloudflare, mas é pouco provável, pois teríamos outros usuários enfrentando o mesmo problema, mas só tem um único registro nos logs que veio de um terceiro IP. Você testou também usando a VPN?

**Comment by teseu** [comment]
A vpn é apenas pro trabalho, ñ uso outra.

**Comment by teseu** [comment]
Bom o erro permaneceu e aparentemente era a própria resposta, ñ sei o pq, vou deixar transcrita abaixo para q vcs possam ver.

========================================

Essas são as opções de shell disponíveis para configurar no seu vscode. Se vc ñ alterou o padrão, o seu terminal do SO deve usar o bash como shell e é esse que deve estar configurado no seu vscode para que funcione da mesma maneira.

Eu uso bash e é esse q está configurado no meu vscode, qdo no windows eu uso um semelhante, o do git bash e é ele q está configurado como padrão do vscode.

<pre>
    <code>
"terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe"
    </code>
</pre>

ou ainda:

<pre>
    <code>
"terminal.integrated.defaultProfile.windows": "Git Bash",
    "terminal.integrated.profiles.windows": {
        "PowerShell": {
            "source": "PowerShell",
            "icon": "terminal-powershell"
        },
        "Command Prompt": {
            "path": [
                "${env:windir}\\Sysnative\\cmd.exe",
                "${env:windir}\\System32\\cmd.exe"
            ],
            "args": [],
            "icon": "terminal-cmd"
        },
        "Git Bash": {
            "source": "Git Bash",
            "path": "C:\\Program Files\\Git\\bin\\bash.exe",
        }
    },
    </code>
</pre>

e no Linux:


<pre>
    <code>
"terminal.integrated.profiles.linux": {
      "Bash": {
        "path": "/bin/bash",
        "overrideName": true,
        "icon": "terminal-bash",
        "color": "terminal.ansiBlue",
        },
    },
    </code>
</pre>

**Comment by teseu** [comment]
como podem ver, o github ñ detectou a mesma coisa. Vejam os erros na resposta da minha request:

Referrer Policy: Ignoring the less restricted referrer policy “origin-when-cross-origin” for the cross-site request: https://static.cloudflareinsights.com/beacon.min.js/vaafb692b2aea4879b33c060e79fe94621666317369993 vaafb692b2aea4879b33c060e79fe94621666317369993
Failed to get subsystem status for purpose 
Object { rejected: true, message: Error }
content-script.js:95:21
XHRPOSThttps://www.tabnews.com.br/api/v1/contents
[HTTP/2 403 Forbidden 36ms]

**Comment by aprendendofelipe** [comment]
@teseu, agora vendo a mensagem que você estava tentando postar eu entendi a razão da Cloudflare estar bloqueando.

Acho que podemos desativar essa regra específica, pois ela protege de uma vulnerabilidade que não está presente no TabNews, mas vou investigar melhor primeiro.

Como não é nada urgente, devo fazer isso após o Carnaval.

Obrigado por reportar! 👍

**Comment by teseu** [comment]
Desde o princípio a intenção era ajudar a plataforma, qdo verifiquei pelo devtools mais informações sobre o erro, fui investigar e percebi q poderia publicar de outra forma, mas essa tb ñ deu certo (essa 2ª tentativa foi a q enviei aqui, antes usava a notação específica do markdown, ao invés de \<code> ou \<pre>,  com \```json, q foi qdo reportei o erro, mas as 2 deram o mesmo resultado).

Na verdade, permanecendo assim, nem sei como enviar trechos de código diretamente (claro q posso hospedar aqui no github com os gists), pq é muito mais interessante e visual incluir na msgm o trecho.

Pra mim, a urgência era pq parecia q eu ñ poderia enviar msgns, mas isso ñ é o caso, aproveite seu feriado e obrigado pela atenção.

**Comment by aprendendofelipe** [comment]
@teseu acho que você não teve mais esse problema, certo?

Vou fechar a issue, ok? 👍
