### ISSUE TITLE
[Feature] - número mínimo de caracteres para ganhar tabcoins

### ISSUE THREAD

**Issue by HarukaYamamoto0** [filipedeschamps/tabnews.com.br#1267]
## Resumo
criar uma limitação para que um usuário escreva no mínimo tantos caracteres para poder ganhar tabcoins, tanto na hora de posta um artigo, quanto na hora de criar um comentário.

## Porque?
Eu estava pensando sobre isso, pois existe alguns usuários que apenas cria umas postagens dizendo: "olha esse artigo aqui é legal recomendo ler LINK" ou comentários dizendo "legal", e eles ganha tabcoins em cima disso, acredito que as pessoas em vez de fazer isso devesse escrever ou explicar o porquê tal assunto é legal

**Comment by hkotsubo** [comment]
Isso pode minimizar o problema, mas sempre tem como burlar. Não sei como o site conta caracteres, mas imagino que o markdown entre na conta (ou seja, `**oi**` conta como seis caracteres, mesmo que somente dois sejam exibidos).

Se for esse o caso, é só encher o texto de `&nbsp;` ou qualquer outro caractere invisível (e o Unicode está cheio dessas bizarrices).

---

Na verdade eu acho que o sistema de votação como um todo deveria ser revisto. Hoje temos uma ação incrivelmente fácil e que só depende de mim (postar **qualquer coisa**) dando mais pontos do que a ação mais difícil e que depende dos outros (receber um voto positivo). Deveria ser o contrário, quanto mais fácil a ação, menos pontos deveria dar (ou até mesmo nenhum). Mas aí já é assunto pra outra issue...

**Comment by filipedeschamps** [comment]
Acompanhando mais de perto o TabNews, acho que o comportamento sugerido pelo @HarukaYamamoto0 **irá contribuir sim**. E para calcular a quantidade de caracteres, podemos limpar o Markdown. O @aprendendofelipe usou isso em outras situações para conferir se a publicação "estava em branco" (tinha Markdown, mas ele resultava em nada).

Por fim, nenhuma medida é a medida final ou vai ser a prova de balas... vai ter que ser uma grande malha de abordagens até que canse quem não quer gerar valor.

---

@hkotsubo o @aprendendofelipe fez uma proposta no passado do ganho de TabCoins ser progressivo... ou seja, quanto maior a confiança na conta da pessoa, mais TabCoins ela ganha por publicação. Então se a conta é nova, ela não ganha nada e fica a cargo de outras pessoas qualificarem essas publicações iniciais para ela ir ganhando tração e confiança do sistema/comunidade.

**Comment by hkotsubo** [comment]
> proposta no passado do ganho de TabCoins ser progressivo

Fiz uma busca e não encontrei essa issue. Tem o link?

**Comment by filipedeschamps** [comment]
No passado a gente conversou por chamada, mas se eu não me engano, foi colocado uma prévia num comentário de uma issue em algum lugar. De qualquer forma, isso vai ser oficializado dentro da Milestone atual ainda: https://github.com/filipedeschamps/tabnews.com.br/issues/1140

**Comment by aprendendofelipe** [comment]
> Fiz uma busca e não encontrei essa issue. Tem o link?

Logo vou criar a issue sintetizando, pois é um mix de várias conversas, mas acho que os dois pontos que explicam mais são esse comentário https://github.com/filipedeschamps/tabnews.com.br/issues/1198#issuecomment-1367459826 e essa publicação no TabNews:

https://www.tabnews.com.br/FelipeBarso/sugestao-mecanica-das-moedas-do-tabnews

**Comment by RodrigoGrz** [comment]
> Por fim, nenhuma medida é a medida final ou vai ser a prova de balas... vai ter que ser uma grande malha de abordagens até que canse quem não quer gerar valor.

Não li todas as issues ainda então desculpe caso alguem ja tenha comentado isso. Vendo essa questão de quantidade minima de caracteres, acho que seria interessante colocar um filtro nos comentarios que não contribuem, e que tem apenas como objetivo falar "Muito bom, obrigado". Assim um comentario desse tipo poderia diminuir radicalmente já que não agrega valor concreto ao ocnteudo.

**Comment by hkotsubo** [comment]
@RodrigoGrz Depois que a issue #1381 foi implementada, ficou mais difícil ganhar TabCoins, e pelo que percebo, diminuiu a quantidade de "_Obrigado_", "_Que legal_" e similares (só falta alguém coletar esses dados pra confirmar, mas pela minha percepção, diminuiu).

Então talvez esta issue acabe ficando com menos prioridade, já que o ganho indevido foi - pelo menos em parte - resolvido de outras formas.

**Comment by aprendendofelipe** [comment]
As mudanças no PR #1366 já estão limitado o ganho de TabCoins por publicações não relevantes. Então provavelmente podemos fechar essa issue. Concordam?

Não tem como evitar totalmente as publicações de agradecimento ou que não agregam nada ao conteúdo, principalmente porque é normal que uma boa parte dos usuários não tenha nenhum interesse em participar da economia do sistema e nem mesmo em entendê-la, mas vão estar somente consumindo o conteúdo. E essa parte dos usuários também é muito importante, pois representa boa parte da audiência do sistema, o que ajuda a viabilizar o Revenue Share.

O mais importante é que esses conteúdos/comentários não prejudiquem a economia e não ofusquem os conteúdos relevantes, mas para isso ainda é preciso algumas mudanças de comportamento que só devem ocorrer quando os usuário perceberem que não há outra razão para ter TabCoins se não for para usá-los qualificando conteúdos e assim obter TabCash, que é o que poderá ser utilizado para o Revenue Share.

**Comment by aprendendofelipe** [comment]
> Algo me diz que isso ainda pode ter validade. Digo isso, porque me machuca muito quando vejo um comentário "valeu falou" com `1` TabCoin... meio que machuca a credibilidade da economia, sabe? Meio que me lembra a teoria da janela quebrada, onde "se um fez, porque eu não posso"?
> 
> Me passaria uma percepção mais justa se um comentário muito curto tivesse por padrão `0` TabCoins, e o autor também ganhasse `0` TabCoins, independente de quem publicou esse comentário.

Mas esse é um problema do conteúdo começar com 1 e não com 0 TabCoin, não é? Dá a falsa ideia de que alguém já votou positivamente no conteúdo. Isso eu acho estranho e ainda não entendi qual é a razão.

Já ter uma quantidade mínima de caracteres para ganhar TabCoins não vai ter impacto na maioria dos conteúdos relevantes, mas deve aumentar a quantidade de caracteres dos não relevantes, ou seja, pode piorar a experiência ao aumentar a quantidade de caracteres irrelevantes, aumentando o tempo perdido ao ler.

**Comment by RodrigoGrz** [comment]
Eu acho que poderia fazer um filtro simples por enquanto do tipo:

Há o comentario teve cerca de 50 caracteres, faz um include do js para ver se tem as palavras chaves como "obrigado", "valeu", e da 0 TabCoin para esse comentario. Porque um comentario valioso não teria somente essa quantidade de caracteres.

**Comment by filipedeschamps** [comment]
> Mas esse é um problema do conteúdo começar com 1 e não com 0 TabCoin, não é? Dá a falsa ideia de que alguém já votou positivamente no conteúdo. Isso eu acho estranho e ainda não entendi qual é a razão.

Eu acho que começar com `1` é visivelmente melhor, pelo menos se considerarmos o benefício da dúvida (vamos acreditar que o conteúdo tem um valor mínimo). Agora, a proposta é em casos que há uma alta probabilidade de não ter valor, por exemplo, se o baseline é `1`, me dói muito ver um conteúdo assim com esse valor, e sabendo que o usuário _possa_ ter ganho TabCoin com isso:

https://www.tabnews.com.br/micaelSantiago/fe754a31-ea36-4b79-9961-197846c54154
https://www.tabnews.com.br/alefolibv/c58ba1bf-7b27-48ca-be72-f641752b2135
https://www.tabnews.com.br/luaneduardo/14bca5c2-33af-42fe-ba16-59761bde0609
https://www.tabnews.com.br/luaneduardo/6567a695-33e2-42b4-bd3c-43bd779d4ae3
https://www.tabnews.com.br/Ernesto/72e82f8b-7511-411e-991a-69dcb9e5e96a
https://www.tabnews.com.br/luaneduardo/257d384a-4dfd-444e-893d-0c45810098b2
https://www.tabnews.com.br/luaneduardo/18e62747-0d9c-4a81-9652-4ffc9767ec66
https://www.tabnews.com.br/luaneduardo/dfeaf808-c45a-4749-8ac2-2db40a0878af
https://www.tabnews.com.br/luaneduardo/43c0e1e0-ad9b-4d7c-8195-2544832cddc7
https://www.tabnews.com.br/airtonsena/1a552781-f25c-462b-8d3a-bbe1ec949996
https://www.tabnews.com.br/luaneduardo/d53ac867-1cc0-4040-91d0-e63158e85151

A pessoa pode não ter ganho nada (dado ao novo algoritmo), mas visivelmente seria mais agradável ver tudo isso com `0` TabCoins, e ter a _garantia_ que a pessoa não tenha ganho nada com esses conteúdos.

E sobre o efeito colateral das pessoas enchendo a linguiça, eu topo correr o risco de ver esse problema surgindo na prática e, se surgir, decidir o que fazer conforme o pattern que aparecer.

**Comment by aprendendofelipe** [comment]
Dúvidas sobre as regras:

1. Podemos usar um limiar de palavras no lugar de caracteres? Eu acho que é melhor.
2. Quantas palavras (ou caracteres) seria o limiar para o conteúdo começar com 0 ou 1 TabCoin?
3. A sugestão é aplicar exatamente as mesmas consequências de quando é uma resposta para si mesmo, certo? Ou seja, nem o autor e nem o conteúdo ganham TabCoins iniciais, mas ganham/perdem normalmente conforme os votos?

**Comment by aprendendofelipe** [comment]
Abri o PR #1460 como proposta de solução. Agradeço se puderem revisar 💪

> 1. Podemos usar um limiar de palavras no lugar de caracteres? Eu acho que é melhor.
>
> 2. Quantas palavras (ou caracteres) seria o limiar para o conteúdo começar com 0 ou 1 TabCoin?

Para não precisar limpar markdown, html e quaisquer caracteres diferentes, usei a verificação abaixo para conferir se existem pelo menos 5 palavras com no mínimo 5 caracteres:

```js
newContent.body.split(/[a-z]{5,}/i).length < 6
```

Se retornar `true`, então é um texto muito curto e não vai ser adicionado TabCoins nem para o usuário e nem para o conteúdo.

Apesar de eu não estar considerando os caracteres acentuados, as palavras acentuadas serão contabilizadas se tiverem 5 ou mais caracteres antes (ou depois) do acento. Não há necessidade de exatidão nessa verificação, já que só estamos contando as maiores palavras.

Sobre a quantidade escolhida, eu tentei fazer passar na verificação alguns comentários curtos que vi no TabNews e que continham alguma mensagem útil. Vamos analisar o resultado e, qualquer coisa, mudamos esses limites.

> 3. A sugestão é aplicar exatamente as mesmas consequências de quando é uma resposta para si mesmo, certo? Ou seja, nem o autor e nem o conteúdo ganham TabCoins iniciais, mas ganham/perdem normalmente conforme os votos?

Fiz acontecer exatamente a mesma coisa que quando respondemos para nós mesmos.

Essa é mais uma regra que terá que constar no FAQ, mas estou pensando se devemos fazer essa verificação também no lado do client, pois assim podemos informar o usuário que a mensagem dele não ganhará TabCoins iniciais. Pode ser uma mensagem de confirmação que apareça ao clicar em "publicar". E talvez fazer o mesmo para quando o usuário responder para si próprio, mas nesse caso já dá para mostrar a mensagem ao clicar no botão responder. O que acham?

**Comment by filipedeschamps** [comment]
> Pode ser uma mensagem de confirmação que apareça ao clicar em "publicar". E talvez fazer o mesmo para quando o usuário responder para si próprio, mas nesse caso já dá para mostrar a mensagem ao clicar no botão responder. O que acham?

Acho super interessante! Até para enviar ele para algum conteúdo explicando o que estamos tentando proteger nas publicações, ou simplesmente recomenda ele dar TabCoin ao invés de comentar.

**Comment by aprendendofelipe** [comment]
Adicionei as mensagens de confirmação no mesmo PR. Vejam neste comentário como ficou: https://github.com/filipedeschamps/tabnews.com.br/pull/1460#issuecomment-1616818797

> Acho super interessante! Até para enviar ele para algum conteúdo explicando o que estamos tentando proteger nas publicações, ou simplesmente recomenda ele dar TabCoin ao invés de comentar.

No caso de mensagem curta, preferi recomendar a leitura da publicação "sobre", pois muitos usuários começam publicando comentários e acabam não vendo aquele aviso que só aparece ao publicar conteúdo "root".

**Comment by aprendendofelipe** [comment]
@HarukaYamamoto0, você foi citado no post comemorativo:

https://www.tabnews.com.br/FelipeBarso/tabnews-6-milhoes-de-visualizacoes-e-muita-novidade 🎉

**Comment by HarukaYamamoto0** [comment]
estou bem feliz que minha sugestão foi aceita, mesmo que eu apenas tenha dado apenas a ideia, para mim esse é o real significado de Open Source 😁

**Comment by aprendendofelipe** [comment]
Vou dar essa issue como concluída pela implementação do PR #1460 🚀🎉

Mas novas melhorias ainda podem ser feitas, como as sugeridas em #1487 🤝
