### ISSUE TITLE
Improv/Feat: dados do array da função checkBlockedUsernames em um arquivo externo

### ISSUE THREAD

**Issue by potatowski** [filipedeschamps/tabnews.com.br#1269]
Ano passado tinha aberto uma issue sobre usuário com o nome de paginas, e o felipe me retornou essa função, e eu pensei recentemente que esse array poderia ser um arquivo externo em uma S3 ou algo do tipo, para evitar que toda vez que fosse adicionado algo nessa lista, não fosse necessário realizar um deploy 

Função https://github.com/filipedeschamps/tabnews.com.br/blob/306bc05efd9854512598c4ce96554e8d7ebf5b73/models/user.js#L194

**Comment by leoferreiralima** [comment]
Outra opção era ter isso no banco, meio que uma tabela de parametrização, acho que nos dois casos seria que precisaríamos talvez por um cache para que não fôssemos sempre no banco ou no S3 buscar o esses dados já que eles não vão a cada minuto

**Comment by aprendendofelipe** [comment]
Dada a frequência muito baixa de atualização dessa lista, comparada à frequência alta de leitura, já que ocorre, por exemplo, a cada validação de URL dos conteúdos, não vejo vantagens de mover essa lista para fora do código.

Hoje ela se encontra aqui:

https://github.com/filipedeschamps/tabnews.com.br/blob/22a6d3aca8e3c6ec24ffa7a24f5a713c48e1a5f7/models/validator.js#L801-L801

Isso dificultaria a atualização da lista, pois:

- Seria necessário fazer manualmente com acesso ao banco ou ao armazenamento escolhido (problema de segurança);
- Não poderia ser atualizada pelos próprios contribuidores dentro dos PRs que necessitem reservar novos nomes;

Quais vantagens vocês enxergam?

**Comment by Rafatcb** [comment]
Bom, como esse issue não teve feedbacks desde Março, e eu concordo que isso traria mais dificuldades do que facilidades, estou fechando o issue.

Se alguém ter uma ideia melhor, que atenda os pontos mencionados pelo @aprendendofelipe ou traga novos pontos positivos, podem criar comentários aqui com argumentos para continuar o debate e reabrirmos o issue.
