### ISSUE TITLE
[SEO/ERRO] url's estão retornando undefined

### ISSUE THREAD

**Issue by Ryannnkl** [filipedeschamps/tabnews.com.br#1271]
Me deparei com esse problema aqui:

![image](https://user-images.githubusercontent.com/48577990/220500246-4a4ea3ad-ce2e-4648-9952-2fc1a578f0ea.png)

olhando o código vi que aqui não está funcionando corretamente

https://github.com/filipedeschamps/tabnews.com.br/blob/f0db9131dd2ae08f6417d48b2d09b99c8baf6243/infra/webserver.js#L12-L14

esse if sempre é executado pelo que entendi isso retorna o *undefined:undefined*

como sugestão eu pensei em colocar mais um if e verificar se ocorreu algum erro que retorne undefined e caso ocorra seta a url padrão, mas não acho que essa seja a forma mais adequada de resolver o problema, o que vocês sugerem?

```js
if (webserverHost.includes("undefined")) {
    webserverHost = 'https://www.tabnews.com.br';
  }
```

**Comment by Ryannnkl** [comment]
fazendo uns testes percebi que as variáveis de ambiente nesse [arquivo](https://github.com/filipedeschamps/tabnews.com.br/blob/f0db9131dd2ae08f6417d48b2d09b99c8baf6243/infra/webserver.js) não reconhecem as variáveis de ambiente, pode testar dando log nelas dentro da função `getHost()`

```js
console.log("vercel_env: ", process.env.VERCEL_ENV);
console.log("database_env: ", process.env.DATABASE_URL);
```

me preocupa também não estar funcionando em produção já que em produção está retornando undefined também como  na imagem que mencionei a cima.

**Comment by aprendendofelipe** [comment]
Olá @Ryannnkl, o PR #1228 já vai corrigir esse problema 👍
