### ISSUE TITLE
[ Bug ] - Campos de cadastro/login 

### ISSUE THREAD

**Issue by pwccaa** [filipedeschamps/tabnews.com.br#1272]
- Os campos de inserção de dados, tanto na aba de login quanto de cadastro, possuem um pequeno erro de css quando inserindo dados provenientes do chrome. (A faixa cinza sobrepõem a sinalização de seleção do campo)

![bugLogin](https://user-images.githubusercontent.com/41527496/220641920-726474fe-b324-44de-8ae2-06946d67ca58.png)

**Comment by Ryannnkl** [comment]
tabnews utiliza o design system do Github chamado prime e o componente de [Input](https://primer.style/react/TextInput) deles tem esse problema mesmo, mas o tamanho default não tem esse problema:

![image](https://user-images.githubusercontent.com/48577990/220676054-5769b056-fc4b-42f3-ad40-283baed20f56.png)

me faz pensar se não seria viável "criar um design system" baseado no prime para o tabnews e deixar de depender somente do prime para ter componentes novos ou melhorar os componentes que ja tem, tava tentando criar um alert de quando ocorre um erro mais bonito mas não tem um componente para isso por exemplo, tem o [Flash](https://primer.style/react/Flash) que foi colocado no login quando o login não funciona, mas tem outra pegada o componente de Flash

**Comment by aprendendofelipe** [comment]
Olá @pwccaa, obrigado pela issue! 💪

O problema foi resolvido no PR #1348, então vou fechar aqui, ok? 👍
