### ISSUE TITLE
[Feature] Sticky Navbar

### ISSUE THREAD

**Issue by ojonasplima** [filipedeschamps/tabnews.com.br#1273]
Sugiro a implantação de uma feature para manter a navbar superior fixada quando é realizado um scroll na página, conforme comportamento abaixo.

![tabnews](https://user-images.githubusercontent.com/86431106/221322681-054856f7-8468-48d2-b118-4f8db1dbe9b3.gif)

**Comment by ojonasplima** [comment]
#1225

**Comment by alan-chris** [comment]
@ojonasplima me explica porque abriu outra issue, com o mesmo assunto, se viu que já tem uma aberta discutindo isso

**Comment by aprendendofelipe** [comment]
@alan-chris, pode ser que o @ojonasplima tenha encontrado a issue #1225 após ter aberto essa.

Vou fechar a duplicada 👍
