### ISSUE TITLE
Previsão para uso do TabCash

### ISSUE THREAD

**Issue by Diegiwg** [filipedeschamps/tabnews.com.br#1313]
Existe alguma previsão para a implementação do mecanismo de utilização dos TabCash?

**Comment by aprendendofelipe** [comment]
Oi @Diegiwg, a previsão é para a Milestone 7, mas ainda sem data definida.

A atual é a [Milestone 6: Performance e Segurança](https://github.com/filipedeschamps/tabnews.com.br/milestone/10)
