### ISSUE TITLE
Qual é o criterio utilizado para o ranking de conteúdos relevantes?

### ISSUE THREAD

**Issue by hernique33comiitei** [filipedeschamps/tabnews.com.br#1314]
Qual é o criterio utilizado para o ranking de conteúdos relevantes?

Postei um conteúdo que está com 5 tabcoins e 4 comentários, um outro post está com 0 tabcoins e 0 comentário e o mesmo está  em um rank superior ao meu.

**Comment by aprendendofelipe** [comment]
Olá @hernique33comiitei, no PR #756 é explicada uma versão que não é a atual, mas que é bem parecida, pois só recebeu pequenos ajustes que você pode acompanhar pelo histórico do arquivo [queries.js](https://github.com/filipedeschamps/tabnews.com.br/commits/main/models/queries.js)

**Comment by hernique33comiitei** [comment]
> Olá @hernique33comiitei, no PR #756 é explicada uma versão que não é a atual, mas que é bem parecida, pois só recebeu pequenos ajustes que você pode acompanhar pelo histórico do arquivo [queries.js](https://github.com/filipedeschamps/tabnews.com.br/commits/main/models/queries.js)

Obrigado
