### ISSUE TITLE
Apresentar a quantidade de visualização / views das publicações.

### ISSUE THREAD

**Issue by rodrigoKulb** [filipedeschamps/tabnews.com.br#1320]
<h2>Objetivo</h2>
Essa opção pode ajudar na moderação dos votos, conforme conversado na Issue #1167.

Basta verificar uma média de view / qualificação. Se uma publicação tiver 10 views e 8 up-votes fica claro que foi burlado.

Atualmente no site **stackoverflow** Já conseguimos verificar a quantidade de visualizações de cada publicação. 

![Captura de tela em 2023-03-13 09-14-55](https://user-images.githubusercontent.com/5334261/224699272-955c64ba-e180-4f8b-8cb5-13f05cbbfe5d.png)

<h2>Como fazer?</h2>

Acredito que devemos levar em consideração alguns pontos para contabilizar o view, hoje no youtube para contabilizar a visualização o usuário precisa assistir pelo menos 20% do vídeo, no tabnews podemos definir um tempo por palavra da notícia, desta forma não seria apenas um "acesso" e sim um tempo médio por tamanho de publicação.

Outro ponto que acredito ser necessário é não repetir visualização do usuário, cada usuário só poderá visualizar a publicação uma única vez, se o usuário não estiver logado, podemos trabalhar com visualização do IP mascarado / sessão.

Isso tudo para impedir manipulação das visualizações.

O que acham?

**Comment by hkotsubo** [comment]
> Se uma publicação tiver 10 views e 8 up-votes fica claro que foi burlado.

Não necessariamente, pode ser apenas um post que caiu no gosto da galera. Eu diria que números muito altos **podem ser um indício**, mas daí pra ter certeza absoluta, tem um caminho grande e nebuloso. Tem que juntar com outras informações, e mesmo assim, certeza absoluta geralmente se tem só em casos mais flagrantes.

Detectar fraudes é complicado, geralmente trabalha-se com probabilidades, baseadas em vários fatores analisados em conjunto (por exemplo, view de usuários logados vs não-logados, intervalo em que os votos foram dados, IP's usados, padrões de votação anteriores, horário - de madrugada o movimento é menor, então muitos votos nesse horário seria mais "suspeito" - etc - estou chutando, se fosse pra propor detecção de fraude eu pensaria melhor nos exemplos). Se algo for suspeito demais (e quanto é esse "demais" sempre será subjetivo), pode-se assumir que foi burlado, com um grau de confiança aceitável.

A quantidade de views pode ajudar, claro, mas é complicado achar que **somente** a razão dela com os votos já dá a certeza de fraude.

**Comment by rodrigoKulb** [comment]
@hkotsubo com certeza, seria somente **mais um indicativo,** digo isso pois o tabnews possui usuários leitores não cadastrados.

O usuário que tem muitas tabcoins poderá utilizar várias no próprio post com 2 contas, desta forma vamos DIFICULTAR a vida deles, imagine um post com 1 view e 20 tabcoins.

Será mais um grande parâmetro para mensuração, fora que é uma grande funcionalidade para todos do portal.

Nem sempre um vídeo legal no youtube tem muitos likes, as vezes o indicativo de view acaba sendo mais importante.

**Comment by Gabriel-Tapes** [comment]
Talvez a melhor forma de fazer isso fosse limitar o número de votos por conta ao invés de IP, ou com os dois. Atualmente cada IP pode dar um voto a cada 72h, o que já deixa muito mais difícil um mesmo usuário dar 20 tabcoins para um post, limitando isso por conta também faria com que o usuário precisasse de 20 contas, o que dificultaria muito as fraudes.

**Comment by Rafatcb** [comment]
Apesar dessa sugestão ter sido dada com o objetivo de moderação, acredito que podemos fechar o issue porque temos a mesma sugestão sendo debatida aqui:

* https://github.com/filipedeschamps/tabnews.com.br/issues/1115

**Comment by aprendendofelipe** [comment]
Boa @Rafatcb!
