### ISSUE TITLE
[Feature/Sugestão] Verificação de Notícias Duplicadas

### ISSUE THREAD

**Issue by k3ybladewielder** [filipedeschamps/tabnews.com.br#1324]
Uma feature pra evitar duplicidade de notícias poderia ser algo que verifique se o link da fonte já está em algum outro post, e indique qual o post para o usuário ir lá no original e comentar, interagir, etc com a notícia que ele teve interesse e foi lá divulgar

**Comment by jgbispo** [comment]
Se depois da verificação, ele não permitir que seja publicado por ter a mesma fonte, não acho legal. Agora, se ele apenas sugerir um post parecido, seria melhor, pois a pessoa pode usar a mesma fonte, mas apenas para dar uma introdução, não necessariamente falar do mesmo assunto.

**Comment by Rafatcb** [comment]
Obrigado pela sugestão, Alysson! Estou fechando esse issue como duplicado de https://github.com/filipedeschamps/tabnews.com.br/issues/787, para podermos concentrar a discussão lá.
