### ISSUE TITLE
[Feature/Sugestão] Busca de temas

### ISSUE THREAD

**Issue by k3ybladewielder** [filipedeschamps/tabnews.com.br#1325]
Uma coisa (que precisei e nao tem hj) que pode ser relevante é uma forma de pesquisar por posts, notícias, temas no site. Atualmente só tem as recentes e relevantes, sendo necessário percorrer todas pra buscar algo que o usuário teve interesse

**Comment by aprendendofelipe** [comment]
@k3ybladewielder, obrigado pela Issue! 👍

Não ficou claro se a sugestão é um sistema de buscas ou de tags, ambas ótimas sugestões.

Para que as ideias avancem, recomendo contribuir com as discussões abertas sobre o tema:

- #742 
- #927 

Vou fechar esse, ok? 🤝
