### ISSUE TITLE
[Sugestão] Área reservada para projetos pessoais

### ISSUE THREAD

**Issue by luissenko** [filipedeschamps/tabnews.com.br#1330]
Olá pessoal!

Tenho visto que muitas pessoas têm postado projetos pessoais, o que é algo incrível e que com certeza motiva aos demais colegas, no entanto tenho a impressão de as coisas como estão hoje deixam tudo muito embaralhado, sabe? Você tem um notícia, do lado de um texto técnico, aí do nada surge um projeto.

Diante disso, minha sugestão é a criação de uma área específica para projetos e que na mesma pudesse haver a separação dos níveis dos projetos. Algo semelhante pode ser visto neste [fórum](https://labdegaragem.com/) de eletrônica.

**Comment by rodrigoKulb** [comment]
Grande @luissenko acredito que uma boa saída seria criar tags para categorias da natureza da informação.

Temos algumas Issues com assuntos semelhantes podemos unificar todos para gerar uma conversa sobre o assunto:

https://github.com/filipedeschamps/tabnews.com.br/issues/859
https://github.com/filipedeschamps/tabnews.com.br/issues/742
https://github.com/filipedeschamps/tabnews.com.br/issues/1126

A categoria deixaríamos muito restrito a UMA única categorias, já as tags podemos colocar por exemplo:
`#php #projetopesoal #noticia #artigo`

**Comment by luissenko** [comment]
> 

Genial, rodrigoKulb! Boa ideia!

**Comment by rodrigoKulb** [comment]
@luissenko para facilitar vamos conversar sobre esse assunto somente em uma Issue, minha sugestão seria a mais antiga a #742 vamos voltar a falar desse assunto lá para tentar definir uma opção com a turma! 

Você finaliza essa Issue?

**Comment by luissenko** [comment]
Beleza!
