### ISSUE TITLE
[OTIMIZACAO] DeepScan report

### ISSUE THREAD

**Issue by repires** [filipedeschamps/tabnews.com.br#1338]
Olá pessoal,

Segue o report com algumas recomendações.

https://deepscan.io/dashboard/#view=project&tid=20438&pid=23903&bid=730298

 <img src="https://i.imgur.com/WnZTYBE.png">

**Comment by Rafatcb** [comment]
A maioria é falso positivo, reclamando de _keyword_ `const`, `import`, `export`, ou _invalid token_ `>`. As úteis são desse tipo:

1. https://deepscan.io/dashboard/#view=project&pid=23903&iid=174521272&tid=20438&subview=issues&bid=730298
> Variable 'values' is null checked here, but its property is accessed without null check prior at line 92 
> https://github.com/filipedeschamps/tabnews.com.br/blob/4c5593c8ef3d5f9adea1e476a8370e3681d3ba2b/models/content.js#L93-L110

2. https://deepscan.io/dashboard/#view=project&pid=23903&iid=174521283&tid=20438&subview=issues&bid=730298
> Expression 'user' always passes null check at this point because it is already checked at line 50 .
> https://github.com/filipedeschamps/tabnews.com.br/blob/4c5593c8ef3d5f9adea1e476a8370e3681d3ba2b/pages/interface/components/Content/index.js#L53

3. https://deepscan.io/dashboard/#view=project&pid=23903&iid=174521292&tid=20438
> Duplicate property name 'source_url' in object literal. The previous property with the same name is at line 360 
> https://github.com/filipedeschamps/tabnews.com.br/blob/4c5593c8ef3d5f9adea1e476a8370e3681d3ba2b/tests/integration/api/v1/contents/%5Busername%5D/%5Bslug%5D/children/get.test.js#L361-L362

Podemos ativar a regra [`no-dupe-keys`](https://eslint.org/docs/latest/rules/no-dupe-keys) para o terceiro caso. No primeiro caso e segundo caso, não encontrei uma regra para ajudar em JavaScript.

**Comment by repires** [comment]
@Rafatcb Novo report:

https://deepscan.io/dashboard/#view=project&tid=23222&pid=26495&bid=844489

![image](https://github.com/filipedeschamps/tabnews.com.br/assets/867660/1f35dfa4-3155-475e-a0bf-357545bd9861)

**Comment by Rafatcb** [comment]
Obrigado pela atualização, @repires . Você mudou algo para o report não ter mais tantos falso-positivos?

Também percebi que um erro que ele tinha identificado e eu mencionei no meu outro comentário (`if (user && contentObject?.owner_id === user?.id) { `) continua no código e ele não reportou, então vale verificar ambos os links na hora de corrigir este issue.

**Comment by repires** [comment]
Eu somente fiz um rebase e gerei um novo relatório
