### ISSUE TITLE
Ganho inicial de TabCoins ao publicar depender de reputação do autor

### ISSUE THREAD

**Issue by aprendendofelipe** [filipedeschamps/tabnews.com.br#1339]
## Contexto

Usuários ainda sem reputação conhecida não deveriam ganhar TabCoins ao publicar conteúdos ou comentários. No começo deve ganhar/perder só os TabCoins dos votos recebidos.

A reputação seria construída com os votos recebidos de usuários que já construíram reputação. Poderia ser a média dos votos dos últimos X conteúdos (3 ou 5, não muitos), **[Edit] desconsiderando os últimos 3 dias e talvez dando pesos diferentes para conteúdos root e respostas**. Só contaria para a reputação os conteúdos com status publicado. Assim os usuários são foçados a se educar, pois excluir um conteúdo mal avaliado melhora a reputação e excluir um conteúdo bem avaliado piora a reputação.

Deveria ter um limite baixo de reputação em que o usuário nem poderia mais publicar nada enquanto não adequar seu comportamento na plataforma (talvez 0). Ao tentar publicar, o usuário receberia um aviso com instruções para verificar o código de conduta ou os termos. E lá pode constar que é recomendado remover conteúdos negativados para melhorar sua reputação. 

E no lado oposto, após atingir determinado valor de reputação, ao postar conteúdo ou comentário o usuário já a ganha uma quantidade de TabCoins proporcional à reputação. Podemos começar com um limiar baixo, talvez bastando a média de votos ser positiva para o usuário já ganhar TabCoins. E a razão também pode ser 1 pra 1 (arredondado para baixo), ou seja, usuário com reputação de 1,7 recebe 1 TabCoin ao publicar.

A ideia é dificultar a manipulação da economia. Ainda poderiam ocorrer abusos, mas teriam que começar com um usuário real, que já atingiu boa reputação, e que teria muito a perder quando o abuso for pego.

~No futuro~ podemos pensar em separar as reputações de comentários das reputações de conteúdos root.

## Execução

- #1366

**Comment by hkotsubo** [comment]
Caso isso seja implementando, como ficaria a pontuação dos usuários já existentes? Principalmente os que tiverem contas criadas alguns dias antes da implantação, por exemplo.

Suponha que eu criei uma conta hoje, postei vários comentários inúteis ("obrigado", "que legal") e ganhei alguns tabcoins, e no dia seguinte o sistema muda para esta nova regra, como ficam meus tabcoins?

Quanto às contas antigas, isso vai ser aplicado retroativamente? (acredito que será complicado fazer isso, então é inevitável que haja "injustiças").

**Comment by aprendendofelipe** [comment]
Implementado em #1366 inclusive com a separação de conteúdos "root" e comentários.
