### ISSUE TITLE
Diferenciar retornos 403 do backend do TabNews e do Proxy

### ISSUE THREAD

**Issue by aprendendofelipe** [filipedeschamps/tabnews.com.br#1344]
## Contexto

Dependendo do tipo de desafio aplicado pelo proxy do TabNews em um momento de suspeita de ataque, pode ser necessária uma ação ativa do usuário. Mas se ele já estiver navegando em modo SPA, ele pode não receber o desafio e ficar sem acesso à API.

Precisamos conseguir identificar esses casos de erro na API por bloqueio do proxy e fornecer um aviso do ocorrido com um botão de refresh da página.

## Execução

Ao receber o status 403 da API o client deve olhar para os cabeçalhos a procura de algum que sempre esteja presente em respostas do backend, talvez algum da própria Vercel ou algum cabeçalho que podemos inserir.

Revisar se estamos utilizando corretamente o retorno 403 em todos os casos, ou se algum deles deveria ser modificado para 401 ou outro status.

Melhorar o feedback de erros para o usuário.

**Comment by filipedeschamps** [comment]
> Ao receber o status 403 da API o client deve olhar para os cabeçalhos a procura de algum que sempre esteja presente em respostas do backend, talvez algum da própria Vercel ou algum cabeçalho que podemos inserir.

Perfeito!!!

**Comment by aprendendofelipe** [comment]
Está implementada uma versão preliminar (PRs #1356, #1357, #1358, #1359).

Caso seja detectado que o usuário está sem acesso à API, ele será redirecionado para a página de login, onde haverá um refresh e o retorno para a página em que o usuário estava. Com isso o usuário recupera seu acesso mesmo que não estejamos com o desafio habilitado em todas as páginas. Basta estar habilitado na API e na página de login.

Provavelmente não será possível implementar da primeira maneira que foi pensada, pois apesar do proxy enviar o status 403, ele também causa um erro de rede, o que impede de recuperarmos o status via JS. Como o erro de rede pode não ser exatamente devido ao proxy, então implementei um único refresh da página e caso o erro persista nada mais é feito.

Acredito que os próximos passos podem ser a criação de uma página e um endpoint da API específicos para essa funcionalidade. Onde a página do desafio abre em uma nova janela e utiliza um endpoint respondido diretamente pela edge, sem utilizar nenhum outro recurso do backend.
