### ISSUE TITLE
[BUG] Lista de postagens não contém todas as minhas postagens

### ISSUE THREAD

**Issue by leoferreiralima** [filipedeschamps/tabnews.com.br#1346]
Recentemente respondi uma postagem no tabnews porém ela não conta na minha lista de postagens, outra coisa que percebi é que minha resposta está em ultimo mesmo tendo mais upvotes, não sei se existe alguma regra para ordernar mas me chamou a atenção

![image](https://user-images.githubusercontent.com/36305985/227735040-7aaed973-7e11-40f1-98bd-d1b56d3f6783.png)

Postagens do meu perfil:
![image](https://user-images.githubusercontent.com/36305985/227735081-a9ade4a3-18b5-4b49-adb8-5a7f8450c221.png)

Link para postagem original: https://www.tabnews.com.br/joseaugusto/como-um-artigo-no-tabnews-mudou-minha-forma-de-pensar

Link para o eu meu perfil: https://www.tabnews.com.br/leoferreiralima

**Comment by aprendendofelipe** [comment]
Opa @leoferreiralima 🤝

> Recentemente respondi uma postagem no tabnews porém ela não conta na minha lista de postagens

Suas respostas estão lá 👍 Provavelmente você estava visualizando uma versão em cache da página:

![image](https://user-images.githubusercontent.com/77860630/227735794-6c88ddcf-1683-402d-8d21-6af7cca41fad.png)

> percebi é que minha resposta está em ultimo mesmo tendo mais upvotes, não sei se existe alguma regra para ordernar mas me chamou a atenção

As repostas são ordenadas nessa função: 😉

https://github.com/filipedeschamps/tabnews.com.br/blob/fd7ed674099538edccf03871f03ce0f85229ec05/models/content.js#L895

**Comment by leoferreiralima** [comment]
Vi agora que apareceu o que achei estranho é que estava em outro dispositivo, provavelmente cache da vercel mesmo. Obrigado 😊
