### ISSUE TITLE
[Melhoria] Abrir os links (internos/externos) em uma nova aba do navegador

### ISSUE THREAD

**Issue by zehguilherme** [filipedeschamps/tabnews.com.br#1351]
Se for possível, dar a opção ao dono da publicação do conteúdo de colocar os links para abrir em uma nova aba.

PS: Não sei se há essa possibilidade via Markdown.

![image](https://user-images.githubusercontent.com/36301054/229118153-c543ffa7-e04d-48f4-96f9-7428aa2ab2d4.png)

**Comment by cybernerd007** [comment]
Boa noite, basta fazer dessa forma `<a href="http://www.exemplo.com.br" target="_blank">Texto do link</a>` assim ele ira abrir em outra aba.

**Comment by zehguilherme** [comment]
@aprendendofelipe faz realmente sentido os pontos levantados pelo @filipedeschamps! Sempre tive essa ideia em projetos próprios ou mesmo em outros que sempre era necessário manter o usuário na página atual caso o link a ser aberto seja de outro site de contexto diferente.
