### ISSUE TITLE
Texto quebrando

### ISSUE THREAD

**Issue by alan-chris** [filipedeschamps/tabnews.com.br#1363]
Acho que isto esta errado, fui lendo os comentários e o texto foi simplesmente sumindo

![Screenshot_20230407_094332_Chrome](https://user-images.githubusercontent.com/42983463/230611047-0ae68c09-f45e-4ae6-bc8d-2c5c560a16a9.jpg)

**Comment by aprendendofelipe** [comment]
Olá @alan-chris, recomendo acompanhar/contribuir sobre o assunto através do #379 💪

Vou fechar essa duplicidade, ok? 👍

**Comment by alan-chris** [comment]
Ok, vou dar uma olhada lá
