### ISSUE TITLE
Bloqueio da possibilidade de alterar o status de `published` para `draft`

### ISSUE THREAD

**Issue by aprendendofelipe** [filipedeschamps/tabnews.com.br#1364]
**[Edit]** A proposta não é eliminar a funcionalidade *draft*, mas apenas bloquear a reversão de *published* para *draft*.

Com exceção da regra de firewall em que os conteúdos são alterados para `draft` enquanto se analisa se é ou não um caso de abuso, para o usuário não deveria ser possível despublicar um conteúdo sem excluir ele, pois essa possibilidade é um grande complicador e abre brechas para as regras de negócio compatíveis com as melhorias abaixo:

- #1155 
- #1198 
- #1339 

Penso que as únicas possibilidades normais para um conteúdo que já foi publicado seriam só a edição ou exclusão do mesmo.

Existe alguma justificativa para manter essa funcionalidade ou podemos bloquear ela?

**Comment by filipedeschamps** [comment]
O caso de uso era publicar algo sem querer (antes de estar pronto), e ao invés de deletar, só deixar como draft. Outro caso de uso era ir construindo a publicação e ir salvando ela no servidor remoto (tipo Wordpress), para depois fazer a publicação final (isso possibilita trabalhar em múltiplas publicações paralelas).

A necessidade do primeiro caso é real e já fiz publicações erradas algumas vezes, mas o segundo caso nunca pediram. E dado a complexidade que isso traz para o sistema, eu concordo total em remover 🤝

E já deixo o convite para quanto mais coisas removermos do sistema, melhor 💪deveria ser uma luta constante nossa.

Ps: seria legal anunciar antes esta breaking change na API, pois ela assume `draft` como default.

**Comment by aprendendofelipe** [comment]
Show!

E a sugestão é mais tranquila do que parece, pois **não** estou sugerindo mudar nada com relação ao default ser `draft`. Então o caso de começar como rascunho continuará sendo possível pela API e futuramente ainda deveríamos implementar na versão web.

Já o caso de publicar algo sem querer, se não há interesse em manter publicado, por enquanto basta remover. Quando implementarmos a versão web do draft, então podemos dar a opção de criar um draft com base em algo já publicado. Mas será uma nova publicação, com um novo ID. Daí fica a critério do usuário apagar ou não a original.

**Comment by filipedeschamps** [comment]
> E a sugestão é mais tranquila do que parece, pois **não** estou sugerindo mudar nada com relação ao default ser `draft`. Então o caso de começar como rascunho continuará sendo possível pela API e futuramente ainda deveríamos implementar na versão web.

Show, entendi! 🤝 

> Quando implementarmos a versão web do draft, então podemos dar a opção de criar um draft com base em algo já publicado. Mas será uma nova publicação, com um novo ID. Daí fica a critério do usuário apagar ou não a original.

Ok, mas temos que cuidar da UX disso, pois acho que fica estranho esse modelo mental para o usuário. De qualquer forma, tem um outro status que mais para frente eu gostaria de implementar, e que se encaixa melhor nisso, que é o de `unlisted`, assim como o YouTube faz. Mas vamos discutir sobre isso mais para frente e em outra thread 🤝

**Comment by iget-master** [comment]
Eu acho que a funcionalidade de Draft não deveria ser removida, vejo total utilidade para posts longos.

Poderia inclusive limitar a N drafts por usuário para evitar abuso da funcionalidade.

Eu topo implementar front para a funcionalidade de Draft.

**Comment by aprendendofelipe** [comment]
Olá @iget-master, não está sendo proposto excluir a funcionalidade *draft*.

A proposta é bloquear a possibilidade de transformar em *draft* um conteúdo que está *published*. Se o conteúdo tiver sido publicado, então só será possível editar ou excluir.

Um dos motivos é porque existe uma penalidade ao excluir um conteúdo relevante, que é a perda dos tabcoins ganhos com esse conteúdo. Então a possibilidade de voltar o status para *draft* é uma maneira de burlar essa regra.

**Comment by danielschmitz** [comment]
Eu não entendi, até hoje, porque um "cms" como o tabnews, onde pessoas escrevem artigos, nao existe um estdado do artigo que inicialmente é draft, e depois pode se tornar publico. 

isso é básico do básico.  Sei que o tabnews é minimalista, mas essa feature é fundamental

**Comment by aprendendofelipe** [comment]
> nao existe um estdado do artigo que inicialmente é draft, e depois pode se tornar publico.

Oi @danielschmitz, o estado padrão das publicações via API é draft.

Uma solução mais completa só precisa que alguém contribua implementando 😉

**Comment by danielschmitz** [comment]
> > nao existe um estdado do artigo que inicialmente é draft, e depois pode se tornar publico.
> 
> Oi @danielschmitz, o estado padrão das publicações via API é draft.
> 
> Uma solução mais completa só precisa que alguém contribua implementando 😉

Entendo, mas quando estou no /publicar, o conteúdo é criado como published. Correto?
