### ISSUE TITLE
Recentemente criei meu primeiro conteúdo e recebi 2 tabcoins, mas na área da postagem tem 1 tabcoin de diferença

### ISSUE THREAD

**Issue by ThaysonScript** [filipedeschamps/tabnews.com.br#1365]
Se isso for novo aqui tá um report do bug:

![Captura de tela 2023-04-08 201823](https://user-images.githubusercontent.com/83515833/230746451-f4ab13f3-72be-4406-b536-b54061a1bb1d.png)

**Comment by cybernerd007** [comment]
Boa noite amigo, provavelmente alguém deu DownVote quando isso ocorre você perde 1 tabcoin...

**Comment by ThaysonScript** [comment]
> Boa noite amigo, provavelmente alguém deu DownVote quando isso ocorre você perde 1 tabcoin...

Sinceramente falando, isso aconteceu quando gerei o conteúdo na mesma hora

**Comment by aprendendofelipe** [comment]
Olá @ThaysonScript, pelas regras atuais (que devem mudar em breve), ao publicar você recebe 2 TabCoins e seu conteúdo começa com 1 TabCoin.

Se não foi isso que aconteceu, então dê mais detalhes, por favor, pois pela sua imagem parece que aconteceu exatamente o esperado. 👍

**Comment by ThaysonScript** [comment]
> Olá @ThaysonScript, pelas regras atuais (que devem mudar em breve), ao publicar você recebe 2 TabCoins e seu conteúdo começa com 1 TabCoin.
> 
> Se não foi isso que aconteceu, então dê mais detalhes, por favor, pois pela sua imagem parece que aconteceu exatamente o esperado. 👍

Há, então foi isso que aconteceu msm, obrigado!
