### ISSUE TITLE
não consigo postar

### ISSUE THREAD

**Issue by RomildoRocha** [filipedeschamps/tabnews.com.br#1368]
Não consigo fazer meu primeiro post, sempre dá esse erro "Usuário não pode executar esta operação. Verifique se este usuário possui a feature "create:content". 8eb18473-3d41-4792-89c9-a2d4687995a7"

e a cada vez que eu aperto em publicar, esse código do muda

**Comment by aprendendofelipe** [comment]
Olá @RomildoRocha, caso seu usuário no TabNews seja o "RomildoRocha", parece que está tudo certo com ele.

Tentou em outro dispositivo ou navegador? Parece que não está sendo enviado o cookie de sessão.

**Comment by RomildoRocha** [comment]
Tentei agora em outro navegador e consegui, mas pelo meu navegador padrão (Google Chrome) não consigo

**Comment by aprendendofelipe** [comment]
Show, deve ser alguma configuração no seu navegador Chrome, então revise as permissões de cookies para usar as configurações recomendadas. 

Não parece ser um problema com o TabNews, então vou fechar a issue. Mas qualquer novidade é só reabrir, combinado? 🤝
