### ISSUE TITLE
Problema ao criar uma publicação 

### ISSUE THREAD

**Issue by pab-h** [filipedeschamps/tabnews.com.br#1369]
Olá, Comunidade do TabNews!

Ontem, foi a minha primeira tentativa de publicar um artigo no TabNews. Porém, não fui capaz de concluir. Ao tentar publicar, a seguinte mensagem é mostrada na tela:

![Mensagem de Erro 1](https://user-images.githubusercontent.com/74771892/232029839-e433077c-06f6-4de8-ba38-511fda328e19.png)

Além disso, verifiquei a minha conta e, ao tentar atualizar meus dados, não sou capaz de atualizar. Vejam: 

![Mensagem de Erro 2](https://user-images.githubusercontent.com/74771892/232030023-04726c39-1e3d-4e82-809e-a13fbff7ae14.png)

**Comment by aprendendofelipe** [comment]
Olá @pab-h, muito provavelmente você tem alguma configuração no seu navegador/dispositivo que está bloqueando cookies.

Favor testar em outro dispositivo ou navegador para confirmar se é mesmo isso. 👍

E, por favor, não deixe de nos contar quando descobrir o que tinha de errado com seu dispositivo, pois isso pode ajudar outros usuários com casos iguais ao seu, como esse #1368 🤝

**Comment by filipedeschamps** [comment]
Interessante o que está acontecendo, pois ele está logado e possui todas as permissões: https://www.tabnews.com.br/api/v1/users/Pab

É estranho ele receber essa mensagem, pois ela é do Backend, mas pelo que lembro receberia de fato se estivesse enviando a request como um usuário anônimo.

Será que o `useUser()` está identificando corretamente se o usuário está logado? Na última semana recebi 3 emails similares, tanto que pedi a todos para publicarem aqui e investigarmos em grupo.

@pab-h você já estava a muito tempo logado?

**Comment by aprendendofelipe** [comment]
> Será que o `useUser()` está identificando corretamente se o usuário está logado? Na última semana recebi 3 emails similares, tanto que pedi a todos para publicarem aqui e investigarmos em grupo.

Não é impossível, mas acredito que não seja isso. Se o @pab-h e/ou @RomildoRocha puderem ajudar na investigação dando mais detalhes pra gente do que acontece...

Sobre o `useUser()`, acho que pode ser isso se o header `x-vercel-id` não estiver presente no retorno 403 que eles estão recebendo. Conseguem verificar isso no DevTools?

Um outro indício de que o problema pode ser relacionado ao `useUser()` é se bastar clicar em deslogar no menu do usuário e fazer login novamente para tudo voltar ao normal. Fizeram esse teste?

Eu acho mais provável que alguma atualização do Chrome tenha mudado algo com relação aos cookies para quem tem alguma configuração mais restrita do que a padrão.

Se for esse o caso, o que imagino que ocorre é o seguinte:

1. O cookie não está sendo salvo pelo navegador no momento do login.
2. Mas o localStorage guarda o cache do usuário logado até a próxima verificação.
3. Se o usuário não tentar publicar ou qualificar nada, ele pode permanecer por alguns minutos nessa condição como se estivesse logado, mas logo a revalidação em segundo plano deve excluir o cache do usuário e mostrar como não logado.
4. Mas se o usuário tentar interagir com algo que precisa estar logado (publicar, qualificar ou editar), ele receberá a mensagem de que não tem permissão (como está sem cookie, deveríamos mudar para 401, mas hoje recebe 403).
5. E nesse momento o cache do usuário deve ser excluído do localStorage e tudo se repete se o usuário fizer login novamente.

Se for isso, é só usar a configuração padrão do navegador ou terá que customizar as permissões para o TabNews (e provavelmente também para a Cloudflare).

É isso que acontece? Se puderem ajudar a gente com mais detalhes, vai ser massa 💪

**Comment by pab-h** [comment]
A pedido do @aprendendofelipe aqui estão os headers: 

### POST | https://www.tabnews.com.br/api/v1/contents 

**Response Headers**
```
HTTP/2 403 Forbidden
date: Fri, 14 Apr 2023 22:36:04 GMT
content-type: application/json; charset=utf-8
access-control-allow-credentials: true
access-control-allow-headers: X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version
access-control-allow-methods: GET,OPTIONS,PATCH,DELETE,POST,PUT
access-control-allow-origin: *
cache-control: public, max-age=0, must-revalidate
etag: W/"p9h9vfraqx9m"
permissions-policy: camera=(), microphone=(), geolocation=()
referrer-policy: origin-when-cross-origin
strict-transport-security: max-age=63072000; includeSubDomains; preload
x-content-type-options: nosniff
x-dns-prefetch-control: on
x-frame-options: SAMEORIGIN
x-matched-path: /api/v1/contents
x-vercel-cache: MISS
x-vercel-id: gru1::gru1::kxqrj-1681511764710-befc01f9aa38
x-xss-protection: 1; mode=block
cf-cache-status: DYNAMIC
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=bPGmAPn9Kf8JIo%2FgzcpSN6DMacfAlVQotTmFlFFpxRY%2FkxGMHpASgVPuJOgN9%2FVDRtdppqZdvQI8vMRJMfZGaBXganlBc34y3Bdh5BHjcGSbBIN3Oe3JFrEQwjdge6FJo16mVbar7ac%2BRZK5BabsyQ%3D%3D"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
server: cloudflare
cf-ray: 7b7f6cf13e2d15b9-FOR
content-encoding: br
X-Firefox-Spdy: h2
``` 

**Request Headers**
```
POST /api/v1/contents HTTP/2
Host: www.tabnews.com.br
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/112.0
Accept: application/json
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Referer: https://www.tabnews.com.br/publicar
Content-Type: application/json
Content-Length: 4616
Origin: https://www.tabnews.com.br
Connection: keep-alive
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
TE: trailers
```

**Comment by pab-h** [comment]
@filipedeschamps, sobre a pergunta se eu estava logado a muito tempo, sim, estava. Faz-se um tempo considerável desde que loguei, questão de meses, no tabnews. Nunca fui deslogado por nenhum motivo. Então, desde esse dia, não renovei o login nenhuma vez.

**Comment by pab-h** [comment]
Sobre informações armazenadas no LocalStorage, há três chaves cadastradas: colorMode, content-new e user. 

Aqui está o json armazenado na chave user:
```json
{
  "id":"22237c4b-f6c2-4bca-8b25-ba35b71d04b5",
  "username":"Pab",
  "features": [
    "create:session",
    "read:session",
    "create:content",
    "create:content:text_root",
    "create:content:text_child",
    "update:content",
    "update:user"
  ],
  "tabcoins": 0,
  "tabcash": 0,
  "cacheTime": 1677696131217
}
```

**Comment by pab-h** [comment]
Ao analisar um console, um error é constantemente logado nele.

Vejam:
![Error console](https://user-images.githubusercontent.com/74771892/232167854-e54d9d97-880d-4b7f-b770-cc8cfe8a87f6.png)

Sobre a requisição,

### GET | https://www.tabnews.com.br/api/v1/user
Response Headers
```
HTTP/2 403 Forbidden
date: Fri, 14 Apr 2023 22:56:42 GMT
content-type: application/json; charset=utf-8
access-control-allow-credentials: true
access-control-allow-headers: X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version
access-control-allow-methods: GET,OPTIONS,PATCH,DELETE,POST,PUT
access-control-allow-origin: *
age: 0
cache-control: public, max-age=0, must-revalidate
etag: W/"ckk7dxau89k"
permissions-policy: camera=(), microphone=(), geolocation=()
referrer-policy: origin-when-cross-origin
strict-transport-security: max-age=63072000; includeSubDomains; preload
x-content-type-options: nosniff
x-dns-prefetch-control: on
x-frame-options: SAMEORIGIN
x-matched-path: /api/v1/user
x-vercel-cache: MISS
x-vercel-id: gru1::gru1::xgtrf-1681513002023-e015c2662db1
x-xss-protection: 1; mode=block
cf-cache-status: DYNAMIC
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=vo7v4%2FK%2F9lUFqe7Fh7zsEnhFjB5gu3cTRcvjE89lIKHe%2FZRGe2a%2FGVAS9vtK4O0WC7XaY88X2C%2BpH2GprDM%2F2hQrv8bprZpMyIU8tuWkJMPDAKycxeWO9vTlkghy6QJrEGgwLHDAjjou6xxMJHAOLg%3D%3D"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
server: cloudflare
cf-ray: 7b7f8b25df6615bd-FOR
content-encoding: br
X-Firefox-Spdy: h2
```

Request Headers
```
GET /api/v1/user HTTP/2
Host: www.tabnews.com.br
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/112.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Referer: https://www.tabnews.com.br/publicar
Connection: keep-alive
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
```

**Comment by aprendendofelipe** [comment]
> Ao analisar um console, um error é constantemente logado nele.

Opa @pab-h, muito obrigado pela ajuda! 💪

O problema é justamente esse erro. E é problema no `useUser` mesmo. Já vou subir uma correção 👍

**Comment by aprendendofelipe** [comment]
Pronto @pab-h e @RomildoRocha, vocês só vão precisar fazer login novamente. 😉

Muito obrigado por reportar o problema e por ajudar na investigação! 🤗
