### ISSUE TITLE
[Feature] Integração com Redes Sociais

### ISSUE THREAD

**Issue by fabriciolak** [filipedeschamps/tabnews.com.br#1371]
![2023, 12_28_01 GMT-3](https://user-images.githubusercontent.com/74481921/232093238-94366f7d-6ad6-4345-b05b-736452e28a3a.png)

Para melhorar o Tabnews, acho útil permitir que os usuários adicionem links de suas contas do Twitter, Github ou outras redes sociais ao fórum. 

A proposta é adicionar botões semelhantes aos do GitHub quando se clica em editar perfil, onde seria possível adicionar links de redes sociais, como LinkedIn e Twitter. 

No começo, seria possível adicionar apenas essas duas redes, verificando a URL para não permitir que sejam adicionados links diferentes. Isso pode ser feito com uma interface simples e intuitiva, conforme mostrado na imagem anexa, seguindo os padrões do Primer. 

Os usuários poderiam clicar no link da rede social e serem redirecionados para a página correspondente. Se houver engajamento na issue, posso melhorar a interface posteriormente.

Os links poderiam ficar na página de perfil. Exemplo

![2023, 12_53_59 GMT-3](https://user-images.githubusercontent.com/74481921/232096477-b2edbec7-3189-428e-a432-e343abb86dbe.png)

**Comment by filipedeschamps** [comment]
Esta é uma melhoria que precisa vir, inclusive possibilitar a pessoa colocar um `README` assim como no GitHub, para ela poder desenvolver o que quiser sobre o seu perfil, principalmente sobre coisas que possam trazer **retorno concreto** para ela 🤝

**Comment by aprendendofelipe** [comment]
@fabriciolak, obrigado pela sugestão! 💪

Acredito que tudo que foi proposto aqui pode ser feito com a descrição no perfil dos usuários que foi implementada no PR #1470, pois está aceitando markdown.

Caso queira complementar o que foi implementado, é melhor centralizar a conversa na issue onde a discussão avançou mais (#1466). Então vou fechar essa. Combinado? 🤝
