### ISSUE TITLE
Adicionar um FAQ ao site

### ISSUE THREAD

**Issue by hkotsubo** [filipedeschamps/tabnews.com.br#1380]
Atualmente o site não tem um FAQ, e acho que seria útil, pelo menos para explicar o funcionamento básico de algumas coisas. Tem a página "[Sobre](https://www.tabnews.com.br/filipedeschamps/tentando-construir-um-pedaco-de-internet-mais-massa)", é verdade, mas ela só dá uma ideia geral do site. Acho que falta um lugar que explique certas coisas de maneira mais detalhada, como por exemplo:

- **Como buscar conteúdos no site?** Enquanto não tem uma barra de busca, um FAQ evitaria (ou diminuiria) a criação de tópicos como [esses](https://www.tabnews.com.br/kht/2b2a6e2d-6d3a-4d5f-bf90-28803e98e1c4)
- **Pontuação**: até existem posts sobre o funcionamento antigo, mas depois que [esta mudança foi feita](https://github.com/filipedeschamps/tabnews.com.br/pull/1366), não vi em nenhum lugar do site uma descrição clara do funcionamento dos TabCoins e TabCash
- **Que tipo de conteúdo pode postar**: minha impressão é que pode ser "qualquer coisa" minimamente relacionada a tecnologia, mas ainda sim, uma descrição mais detalhada seria bem útil, senão [cada um posta o que quer e o site acaba não focando em nada](https://www.tabnews.com.br/kht/e868ec52-4780-4c51-be4e-68c3a949bb60)
- etc

**Comment by aprendendofelipe** [comment]
Olá @hkotsubo, com certeza a milestone do revenue share não poderá ser concluída sem o FAQ estar pronto. Mas nada impede que já seja criada uma versão na milestone atual. 💪

Sobre a mecânica dos TabCoins, ainda virão mais mudanças na milestone atual, mas como vi sua pergunta dentro do TabNews, eu já estava escrevendo uma resposta, então criei [uma issue](https://github.com/filipedeschamps/tabnews.com.br/issues/1381) para manter a descrição do que está valendo atualmente. 👍

A criação das regras para uso de TabCash será o objetivo principal da próxima milestone. 🚀

Sobre limitar o que pode ser postado, eu acho complicado restringir. E o ideal é que a mecânica de qualificações do sistema cuide disso. Então os ajustes vão ocorrer sempre que necessário para levar o Equilíbrio de Nash cada vez mais perto do ideal.

**Comment by hkotsubo** [comment]
@aprendendofelipe  Quanto aos limites, é só pra ter uma regra clara. Um exemplo (bem exagerado de propósito): se alguém postar uma receita de arroz com frange (sem qualquer relação com tecnologia), estará fora das regras, acredito eu, e a pessoa poderá ser advertida.

Tendo a regra escrita no FAQ, dá mais subsídio pra gente poder afirmar que esse tipo de coisa não pode. Se não está escrito em nenhum lugar, sempre abrirá margem para discussão (talvez não no meu exemplo, mas enfim, podem ter casos em uma área cinzenta, e ter as regras ajuda a dar um norte).

**Comment by aprendendofelipe** [comment]
Show @hkotsubo, você já tem algo em mente para iniciar uma issue sobre que tipo de conteúdo pode postar no TabNews?

Acho que uma issue específica pode atrair mais gente querendo contribuir ou acompanhar esse assunto.

**Comment by hkotsubo** [comment]
> você já tem algo em mente para iniciar uma issue sobre que tipo de conteúdo pode postar no TabNews?

@aprendendofelipe Minha ideia era partir de alguma discussão já existente (até pra ter mais embasamento), mas em uma busca rápida pelo site não encontrei.

O máximo que tem são as páginas "Sobre" e "Termos de Uso", mas elas só mencionam "*conteúdo de valor concreto para quem trabalha com programação e tecnologia*". É  meio vago e bem subjetivo, mas enfim, é o ponto de partida que temos.

Enfim, amanhã penso nisso com mais calma. Mas se quiser já ir abrindo a issue, fique à vontade :-)

**Comment by hkotsubo** [comment]
Bom, outra sugestão de item pro FAQ: "Posso postar o mesmo conteúdo várias vezes?" (resposta: "Não").

Inspirado [nesta discussão](https://www.tabnews.com.br/kamikaze142857/23c0bf54-738b-472d-9d38-e72af6850b86).

**Comment by Rafatcb** [comment]
Vale mencionar tem um PR de FAQ que estava em andamento antes do surgimento dessa issue: https://github.com/filipedeschamps/tabnews.com.br/pull/1210. Já tem algumas informações lá e talvez o PR possa ser aproveitado para a criação do FAQ completo.

**Comment by Rafatcb** [comment]
Um PR atualizado sobre o FAQ acaba de ser aberto: https://github.com/filipedeschamps/tabnews.com.br/pull/1581

Dêem uma olhada e vejam se as perguntas foram bem respondidas e se existe algo faltando. Nada impede uma atualização do FAQ em outro PR, se necessário, mas aproveitem agora para avaliar.

**Comment by Rafatcb** [comment]
Pessoal, o PR #1581 foi mergeado mas resolvi não fechar esse issue por alguns motivos discutidos lá. Temos algumas melhorias pendentes:

1. Renomear a pergunta `Por que o TabNews foi criado?` para `Qual é o propósito do TabNews?` ([referência](https://github.com/filipedeschamps/tabnews.com.br/pull/1581#discussion_r1449755132)). Não precisa mudar o `id` nem a resposta.
2. Eventualmente, publicações serão criadas no TabNews por mim ou pelo @aprendendofelipe para complementar o FAQ. A primeira pergunta será para responder _"O que é o TabNews?"_. Com o debate, um PR deve ser aberto para criar essa pergunta e a resposta, e já atualizar o ponto `1` dessa lista no mesmo PR.
3. Possivelmente, uma publicação será criada para melhorar a resposta [Que tipo de assunto é aceito no TabNews?](https://www.tabnews.com.br/faq#assunto-tabnews). [Referência](https://github.com/filipedeschamps/tabnews.com.br/pull/1581#discussion_r1448084330).
4. Possivelmente, outra publicação será criada para falar sobre "qualidade" no FAQ e poder orientar o comportamento para votos (o que estimular e o que desestimular).

Foi discutido que a melhor forma de criar as publicações de melhoria seriam com uma pergunta por vez, para concentrar a discussão com um foco específico. Pensei também em mencionar que outras melhorias para o FAQ devem ser sugeridas neste issue, para não gerar discussões paralelas na publicação.

Se você sentiu falta de alguma pergunta/resposta ou achou que alguma resposta poderia ser melhor, já pode deixar seu feedback aqui.

PS: As publicações não serão criadas todas de uma vez para não dividir a atenção da comunidade, vamos resolver uma pergunta por vez.

**Comment by Rafatcb** [comment]
Criei a publicação para ouvir da comunidade a resposta para _O que é o TabNews?_, mas teve feedback sobre o FAQ também. Vou trazer o [comentário do kht](https://www.tabnews.com.br/kht/9d77473a-a4f4-48c4-ac35-494a41dcfc09) para cá:

> Tem dois trechos que podem dar margem a alguma confusão, pois pra mim eles parecem contraditórios.
>
> Primeiro é dito que posso publicar "*qualquer outro tipo de conteúdo que poderá fazer alguma diferença na vida de quem trabalha em áreas diretamente ou indiretamente relacionadas à área de tecnologia*".
>
> E logo depois temos"*O conteúdo publicado no TabNews deve estar diretamente relacionado à tecnologia*".
>
> No meu entendimento, a primeira regra dá a impressão de que posso falar de qualquer coisa. Usando um exemplo exagerado de propósito, eu poderia falar de culinária ("olha essa receita super saudável"), afinal devs também precisam comer e uma boa alimentação faz "diferença na vida" de qualquer um, não?
>
> Mas a segunda regra restringe isso, deixando bem claro que não posso falar de culinária, a menos que tenha uma relação clara com tecnologia (por exemplo, como fazer um site de receitas, etc).
>
> Talvez seja o caso de ajustar o texto da primeira, pois acho que "*qualquer outro tipo de conteúdo que poderá fazer alguma diferença na vida*" é amplo demais. Tem que deixar claro que não é bem qualquer coisa, tem que estar de acordo com a segunda regra.

O trecho considerado abrangente está na pergunta [Que tipo de conteúdo eu posso publicar no TabNews?](https://www.tabnews.com.br/faq#conteudo-tabnews). Concordo que ele pode dar uma abertura à interpretações que não desejamos, mas ainda não pensei numa frase para substituir.

**Comment by Rafatcb** [comment]
Atualizando:

Conforme as melhorias implementadas no PR #1605, o último ponto restante para considerar este issue como encerrado é criar uma publicação para falar sobre "qualidade" no FAQ e poder orientar o comportamento para votos (o que estimular e o que desestimular). Não sei se vamos conseguir definir algo mais objetivo para colocar no FAQ, mas vou criar a publicação para ver se conseguimos algo.

Outras melhorias podem ser feitas no FAQ com o passar do tempo, mas o fechamento deste issue será apenas para considerar que a necessidade de ter um FAQ foi atendida.

**Comment by Rafatcb** [comment]
Acabei de criar o PR abordando o assunto da qualidade: https://github.com/filipedeschamps/tabnews.com.br/pull/1625

A publicação que recebeu feedback no TabNews foi essa: [Complementando o FAQ - O que é um conteúdo de qualidade?](https://www.tabnews.com.br/rafael/complementando-o-faq-o-que-e-um-conteudo-de-qualidade)

Após esse ponto ser definido no FAQ, vamo fechar esse issue como resolvido. Apesar disso, melhorias no FAQ continuarão sendo bem recebidas.
