### ISSUE TITLE
Explicação da Mecânica Atual de TabCoins

### ISSUE THREAD

**Issue by aprendendofelipe** [filipedeschamps/tabnews.com.br#1381]
A mecânica está em constante evolução. Vou tentar manter esse texto atualizado, mas tenha em mente que a fonte da verdade é o código da branch main.

Não sei se existe maneira de simplificar essa explicação sem perder informação relevante, mas fiquem à vontade para criar as suas versões nos comentários. Principalmente algo que possa ser melhorado no FAQ, que não necessariamente precisa conter todos os detalhes explicados aqui.

É melhor que não sejam postadas nessa issue sugestões que modifiquem o as regras. Façam isso em issues específicas, ou seja, nas que já foram abertas para discussão do ponto específico que quer alterar ou, caso a issue ainda não exista, crie uma nova e fundamente a sua sugestão. Se vier com alterações nas regras aqui nos comentários saberemos que está sugerindo mudanças sem ter lido as regras atuais 😅

## Definições

- **Comentário**: Conteúdo postado em resposta a outro conteúdo. Resposta ou "conteúdo filho" são sinônimos.
- **Conteúdo**: Tudo o que é postado no TabNews, seja conteúdo "root" ou comentário.
- **Conteúdo root**: Conteúdo que não foi postado em resposta a outro conteúdo.
- **Qualificação**: Ato de informar ao sistema se um conteúdo é "relevante" ou "não relevante" na opinião do usuário.
- **TabCash**: Moeda que futuramente será utilizada para a revenue share.
- **TabCoins**: Para os usuários é a moeda necessária para adquirir TabCash com a qualificação de conteúdos. Para os conteúdos é um indicador de como estão as qualificações desse conteúdo.

## TabCoins dos conteúdos

É o indicador de como andam as qualificações dos conteúdos como "relevantes" ou "não relevantes".

### Ganho de TabCoins

Existem duas maneiras do **conteúdo** ganhar TabCoins:
* Se o conteúdo se enquadrar, ele começa com 1 TabCoin ao ser postado.
* Ao receber votos como "relevante" ele recebe mais 1 TabCoin por voto.

### Perda de TabCoins

Existem duas maneiras do **conteúdo** perder TabCoins:
* Ao receber votos como "não relevante" ele perde 1 TabCoins por voto.
* Situações que exijam atuação da moderação, por exemplo, no banimento de alguém que qualificou o conteúdo positivamente.

## TabCoins dos usuários

Os TabCoins dos usuários servem para poder qualificar conteúdos e obter TabCash com isso.

### Ganho de TabCoins

Existem três maneiras do **usuário** ganhar TabCoins:
* Ao postar conteúdos ele pode ganhar TabCoins. O ganho depende de fatores explicados mais abaixo.
* Ao ter seus conteúdos qualificados positivamente ele recebe 1 TabCoin por voto positivo.
* É possível ganhar TabCoins ao acessar o TabNews pelo menos uma vez no dia. Existe um algoritmo que leva em consideração as qualificações dos conteúdos mais recentes e também a quantidade de TabCoins que o usuário possui. Quanto melhor avaliados forem os conteúdos e menos TabCoins o usuário possuir, mais ele receberá na recompensa diária.

### Perda de TabCoins

Existem algumas maneiras do **usuário** ter seus TabCoins consumidos:
* Ao ter seus conteúdos qualificados negativamente ele perde 1 Tabcoin por voto negativo.
* Ao adquirir TabCash através da qualificação de conteúdos de outros usuários são consumidos 2 TabCoins.
* Ao excluir um conteúdo o usuário pode ter que devolver TabCoins nos casos explicados mais abaixo.
* Em situações que exijam atuação da moderação.

### TabCoins ganhos pelo usuário ao publicar conteúdos

No exato momento de publicação do conteúdo será computado qual é o ganho inicial do usuário para esse conteúdo.
Usuários respondendo a si mesmo não ganham nada ao publicar.
Para os outros casos os ganhos dependem das qualificações de seus outros conteúdos postados recentemente.

Caso seja um usuário novo, que ainda não recebeu qualificações, então o usuário não ganha nada no ato de publicar, mas poderá ganhar ou perder os TabCoins através das qualificações desse conteúdo.

O usuário ficará impedido de publicar quando houverem muitos conteúdos com votos negativos. Para sair dessa condição bastará o usuário excluir seus conteúdos avaliados negativamente. Essa regra não bloqueia as respostas em conteúdos próprios, mas isso deve ser evitado, já que esses comentários começam zerados ao invés de começarem com 1 TabCoin.

### TabCoins consumidos na exclusão de um conteúdo

Quando o usuário excluir um conteúdo, será computado e debitado o saldo de TabCoins de acordo com o caso:

* Caso o conteúdo esteja com saldo zerado ou negativo, então o usuário devolve apenas o valor ganho ao publicar esse conteúdo.
* Caso o conteúdo esteja positivo, então o usuário devolve todo saldo ganho com qualificações somado ao que ele ganhou no momento da publicação desse conteúdo.

Lembrando que o usuário pode não ter ganho nada ao publicar, então a devolução será apenas dos ganhos com qualificações.

**Comment by JuanFontes** [comment]
Olá @aprendendofelipe , gostaria de tirar uma dúvida. Especialmente sobre "autor". Isso se refere ao autor da postagem ou do comentarista? Ou os dois?
Digo isso pois nessa postagem eu ganhei 4 tabcoins https://www.tabnews.com.br/juanfontes/dce20375-6f02-442a-ba77-ff84bee03d2a porém acho que o comentarista (que não era o autor) foi banido, com isso eu perdi todas elas. Isso está correto?

**Comment by aprendendofelipe** [comment]
> Especialmente sobre "autor". Isso se refere ao autor da postagem ou do comentarista? Ou os dois?

Quando um usuário é banido, também é desfeito tudo que ele fez, incluindo publicações (comentários ou root) e os votos que ele deu. Quem ganhou ou perdeu tabcoins por votos de um usuários banido, terá os saldos corrigidos.

Já quem qualificou corretamente os conteúdos desse usuário banido, deve ter feito de acordo com sua avaliação, e já converteu seus tabcoins em tabcash normalmente, então isso não é desfeito.

> Digo isso pois nessa postagem eu ganhei 4 tabcoins https://www.tabnews.com.br/juanfontes/dce20375-6f02-442a-ba77-ff84bee03d2a porém acho que o comentarista (que não era o autor) foi banido, com isso eu perdi todas elas. Isso está correto?

Não deve ter nenhuma relação, pois a única coisa que você poderia perder eram os votos recebidos desse usuário banido, mas ele só pode dar 1 voto por conteúdo a cada 72 horas.

No momento essa sua publicação continua com 4 tabcoins, ou seja, você ganhou 3 tabcoins com ela. Também ganhou 1 tabcoin em outra publicação. Já converteu 2 tabcoins em tabcash ao qualificar algum conteúdo, restando 1 tabcash e 2 tabcoins de saldo. Parece tudo correto.

**Comment by aprendendofelipe** [comment]
Turma, agora que temos o FAQ, vamos concentrar a atualização da mecânica de maneira geral por lá, e a parte mais detalhada da mecânica é melhor consultar diretamente no código.

Por isso vou fechar essa issue. 🤝
