### ISSUE TITLE
Falha em dar um like em postagem root

### ISSUE THREAD

**Issue by maniero** [filipedeschamps/tabnews.com.br#1383]
Acabei de dar um voto positivo aqui: https://www.tabnews.com.br/sucoDeMaracuja/se-voce-pensa-em-refazer-um-projeto-do-zero-voce-nao-amadureceu-o-suficiente

Foi descontado 2 pontos do meu saldo quando cliquei no voto, soltou os confetes do voto, mas ele continua com 1.

Há a possibilidade de alguém ter dado um negativo no exato momento, ainda que improvável, aí precisaria de um histórico das ações, ou pelo menos mostrar os positivos e negativos (acho que já tem proposta disto) para acompanhar o que aconteceu.

Logo depois, enquanto eu escrevia aqui apareceu um segundo voto lá, mas ao mesmo tempo apareceu na minha resposta, então pode ser a mesma pessoa que votou nos dois.

Também pensei na possibilidade cache, mas se acontece isso, é de se pensar se isso está funcionando bem, cache não pode criar confusão nesse nível. Já cria em outros pontos menos críticos.

Até pode ser só cache mesmo porque também estou impedido de votar até 72 horas.

Pode ser um bug no frontend apenas que não atualizou o objeto do score.

Pode não ser nada de bug (o cache atrapalhar UX é bug, nem preciso colocar o meme das baratinhas) e só preciso de esclarecimento sobre a votação que eu não entendi.

Em outras oportunidades funcionou perfeitamente, e o score subiu imediatamente.

**Comment by filipedeschamps** [comment]
Para complementar na investigação: esta publicação possui apenas `1` evento de `update:content:tabcoins` vindo do seu usuário 🤝

**Comment by aprendendofelipe** [comment]
Olá @maniero, obrigado por reportar! 💪

É por causa da nova estratégia de cache mesmo. Isso deve ser corrigido em breve. 👍

**Comment by maniero** [comment]
Pelo que percebo continua acontecendo problemas de cache em quase todas as postagens. Mesmo depois de horas ou até dias eu entro, está com um score, logo depois ele muda, já comecei acostumar que tem que esperar um tempo para ver o que está real. Chega até assustar, porque tem caso que dá diferença de mais de 1 ponto do que eu sei que estava. Não sei se esse pull era para resolver isso, mas não está funcionando, precisa dar uma verificada. Obrigado.

**Comment by aprendendofelipe** [comment]
Oi @maniero, ocorrem problemas de cache ou um funcionamento característico de cache? Poderia explicar melhor o que ocorreu e como você acredita que deveria ter sido, considerando que a primeira versão visualizada sempre é do cache?

Segue um resumo apenas para quem estiver acompanhando a issue sem estar muito por dentro de como está funcionando:

As páginas sempre são carregadas com a versão em cache e logo em seguida é atualizada para uma versão mais atual. Não é só o saldo de TabCoins que pode mudar, mas qualquer dado que foi alterado na página entre a versão que carregou do cache e a mais atualizada.

No primeiro carregamento de cada página você pode ver caches de dias atrás, isso se ninguém tiver acessado a mesma página usando a mesma Edge da Vercel que você. As páginas estáticas do Next.js/Vercel por padrão são assim, só revalidam quando alguém acessa. O que será implementado futuramente é a revalidação logo após ações dos usuários que modifiquem qualquer dado da página, mas essa revalidação também não será instantânea 👍

**Comment by maniero** [comment]
É isso, em várias postagens, mas não todas, entra com um score, cerca de 1 segundo depois ele muda, para o que eu entendo deveria ser o correto. Já vi caso que deveria estar em 3, e mostra 1, depois muda para 3. Tentando várias vezes e sempre assim. Mas agora nenhum está fazendo isso.

Eu acho que você tem que entrar com o score real, só o fato de mudar já cria um desconforto, como demora um pouco se prolonga o suficiente para assimilar o erro, e a UX fica mais prejudicada.

Aí até porque curiosidade técnica. Que ganho tem em fazer isso? A impressão que me dá é até que é menos eficiente assim. Mesmo que tenha mais eficiência que eu não consigo enxergar, o custo de UX parece alto.

Quando fala do cache está falando que carrega do meu cache? Aí até consigo ver alguma eficiência, mas ainda acho um preço alto a se pagar. De qualquer forma, precisa quanto tempo ou quantas vezes para ele estabilizar?  Falha de cache pode ser pontual, quando é frequente tem algo bem errado, acho que não preciso citar o Phil Karlton.

Mas se fala em pegar cache de dias atrás porque ninguém acessou parece que está falando do cache do servidor. E aí me parece estratégia de cache errada mesmo, não só por manter algo que não deveria estar em cache, mas também por carregar o cache e depois atualizar. E mesmo que fosse isso não poderia por tanto tempo ficar com cache velho como ocorre. O custo inclusive fica muito pior porque eu fico recarregando várias vezes por causa disso.

Posso ajudar em algo mais?

**Comment by filipedeschamps** [comment]
@maniero uma dúvida: você está acessando o site do Brasil ou outra região?

**Comment by maniero** [comment]
Brasil. Vivo Fibra @filipedeschamps

**Comment by maniero** [comment]
Eu não sei se tem relação, mas fui votar em uma postagem root que eu tenho um comentário (não cliquei no meu) e apareceu:

"Você não pode realizar esta operação em conteúdos de sua própria autoria. Realize esta operação em conteúdos de outros usuários."

**Comment by aprendendofelipe** [comment]
> Eu não sei se tem relação, mas fui votar em uma postagem root que eu tenho um comentário (não cliquei no meu) e apareceu:

Opa @maniero, tem sim total relação com a solução adotada para mostrar sempre os dados mais recentes. 😕

Ao navegar diretamente entre diferentes conteúdos, o estado do componente TabCoinButtons estava sendo mantido indevidamente enquanto ocorria a revalidação. Enquanto isso você estava vendo o saldo (e botões) do último conteúdo navegado e não o do cache.

Provavelmente era devido ao mesmo bug a maioria dos outros problemas que você citou de saldo mudando toda hora ou ficando com valor incorreto. Agora você só deve ver o saldo atualizar apenas se realmente houver algum voto recente. 👍

Muito obrigado por reportar os problemas! 💪💪💪

**Comment by aprendendofelipe** [comment]
@maniero você foi citado no post comemorativo: https://www.tabnews.com.br/FelipeBarso/tabnews-otimizacoes-e-mais-melhorias 🎉
