### ISSUE TITLE
[bug] Mensagem de confirmação de email duplicada

### ISSUE THREAD

**Issue by Henrique-Gomes** [filipedeschamps/tabnews.com.br#1386]
Quando eu me cadastrei, o site exibiu uma mensagem pedindo para eu confirmar o email, o que eu fiz.

Em seguida, loguei no site e ele exibiu _novamente_ uma mensagem pedindo para eu confirmar o email, muito embora eu já estivesse logado.

Não recebi nenhum email para confirmar pela segunda vez e o site já estava 100% funcional, ou seja, o único bug foi a exibição da mensagem pela segunda vez, sem nenhum impacto adicional na usabilidade.

**Comment by aprendendofelipe** [comment]
Olá @Henrique-Gomes, obrigado por reportar isso! 💪

A tela de login normalmente envia o usuário de volta para a página em que estava, mas realmente isso não faz sentido para algumas páginas. Vou corrigir isso. 👍

Apenas para confirmar essa suspeita do que tenha ocorrido, você lembra se fez login usando a mesma aba que estava pedindo para conferir o email?

**Comment by aprendendofelipe** [comment]
@Henrique-Gomes você foi citado no post comemorativo: https://www.tabnews.com.br/FelipeBarso/tabnews-otimizacoes-e-mais-melhorias 🎉
