### ISSUE TITLE
Exclusão da conta

### ISSUE THREAD

**Issue by Jetrom17** [filipedeschamps/tabnews.com.br#1393]
@filipedeschamps ou algum responsável. Solicito a exclusão da minha conta imediatamente. 

```https://tabnews.com.br/jetrom```

**Comment by filipedeschamps** [comment]
@Jetrom17 sem problemas. Você precisa apenas enviar um email para contato@tabnews.com.br utilizando o mesmo email da sua conta no TabNews 🤝

**Comment by Jetrom17** [comment]
> @Jetrom17 sem problemas. Você precisa apenas enviar um email para [contato@tabnews.com.br](mailto:contato@tabnews.com.br) utilizando o mesmo email da sua conta no TabNews handshake

Obrigado. Espero que o TabNews tenha um botão de excluir conta conforme nossa lei LGPD.
