### ISSUE TITLE
App android, não compartilha links dentro da publicação

### ISSUE THREAD

**Issue by eduardofaria** [filipedeschamps/tabnews.com.br#1398]
Se configurar o Aplicativo do Android (não sei no iOS) para abrir os links da publicação pelo próprio aplicativo, e não no navegador preferencial do sistema, não há forma de compartilhar este conteúdo que foi aberto dentro deste conteúdo pai (ex: redes sociais e outros aplicativos do sistema).

**Comment by aprendendofelipe** [comment]
Olá @eduardofaria, obrigado pela issue! 💪

Existe como copiar o link de qualquer publicação se você tocar e segurar na data de publicação até que apareçam as opções, mas realmente poderia existir uma UX melhor.

Eu imagino que um botão de copiar o link, que pode ser colocado bem ao lado da data, já deve ajudar. O que acha disso?

![image](https://user-images.githubusercontent.com/77860630/235698212-61ba617b-854b-40e4-935e-f35d274123fc.png)

**Comment by eduardofaria** [comment]
Existe uma API que permite abrir o menu nativo do sistema para compartilhar. Acredito que poderia estar embutido nesse "botão" que mencionou. Se fosse apenas para copiar o link, deveria haver uma mensagem de "link copiado", e o usuário se encarregaria de ir no aplicativo desejado e usar esse dado. Ou, implementar essa API, ex:

Fonte 1: https://w3c.github.io/web-share/
Fonte 2: https://css-tricks.com/how-to-use-the-web-share-api/

shareButton.addEventListener('click', event => {
  if (navigator.share) {
    navigator.share({
      title: 'WebShare API Demo',
      url: 'https://codepen.io/ayoisaiah/pen/YbNazJ'
    }).then(() => {
      console.log('Thanks for sharing!');
    })
    .catch(console.error);
  } else {
    shareDialog.classList.add('is-open');
  }
})

**Comment by Rafatcb** [comment]
Não sei se esse issue foi aberto inicialmente falando sobre um aplicativo não-oficial do TabNews, mas como houve o comentário sobre usar o "Share" do dispositivo, é uma sugestão válida para o site.

Dito isso, creio que podemos concentrar a discussão no issue https://github.com/filipedeschamps/tabnews.com.br/issues/813 e levar a sugestão do menu nativo para lá, fechando este issue. Faz sentido?

**Comment by Rafatcb** [comment]
Bom, estou fechando este issue para concentramos a discussão de compartilhamento no issue #813. Obrigado pela sugestão, @eduardofaria! Mencionei o seu comentário lá.
