### ISSUE TITLE
Pré-visualização na hora de compartilhar link (não sei se está com bug)

### ISSUE THREAD

**Issue by filipedeschamps** [filipedeschamps/tabnews.com.br#1399]
Eu já tenho notado isso faz alguns dias (ou semanas?), mas não consigo isolar se é problema no LinkedIn ou no TabNews. De qualquer forma, não consigo mais compartilhar links com pré-visualização lá de forma fácil. Eu preciso ficar gerando outros links (com outras query strings) para ele ir tentando gerar o preview... e uma hora vai. Antes não tinha esse comportamento.

<img width="561" alt="image" src="https://user-images.githubusercontent.com/4248081/236061524-2d8f72cc-83cc-4ba7-8842-05b63264f702.png">

**Comment by filipedeschamps** [comment]
Talvez eu encontrei um pattern:

1) Tenta usar o link no LinkedIn, não funciona
2) Usa o share para Whatsapp, que funciona
3) Volta no LinkedIn, o mesmo link agora funcinoa

**Comment by aprendendofelipe** [comment]
Apenas para ver se os logs batem, dessa vez (na publicação sobre o prêmio) deu certo na segunda tentativa?

O LinkedIn precisa acessar a página para ler as metatags e só depois acessar o endereço da miniatura. Se não houver cache desses dois na região do datacenter deles, o LinkedIn vai ter que esperar a geração desses dados (ou a replicação dos dados na CDN da Vercel). Será que o LinkedIn não está querendo esperar muito?

Cruzando as informações na Cloudflare e no Axiom, aparentemente ainda não existia cache da página na primeira tentativa do LinkedInBot, pois ele nem chegou a tentar acessar a miniatura. Só que a requisição da página foi respondida com sucesso em 486ms. Acho que report.durationMs é só o tempo dentro da Vercel, então some a isso a ida e volta de gru para iad. Então o cache com certeza foi gerado e propagado para iad nesse momento.

Já na segunda tentativa de obter a página eles devem ter recebido a resposta já do cache, pois logo em seguida requisitaram a miniatura com sucesso.

Diretamente para o endereço da miniatura, fora a requisição do LinkedIn, no mesmo horário tiveram outras três, sendo uma que deve ter sido você compartilhando (ou testando) no WhatsApp e outra testando diretamente no Safari. E só mais uma que não sei identificar exatamente a origem, mas deve ter sido de algum serviço da Microsoft ou algo hospedado na Azure, mas que também teve sucesso na resposta.

> * Tenta usar o link no LinkedIn, não funciona
> * Usa o share para Whatsapp, que funciona
> * Volta no LinkedIn, o mesmo link agora funciona

Acho que o compartilhamento do Whatsapp só está servindo para você aguardar a propagação do cache na CDN da Vercel, pois, diferente do LinkedIn, ele é gerado no seu dispositivo.

**Comment by aprendendofelipe** [comment]
Fiz alguns testes aqui e, aparentemente, é algo com o próprio LinkedIn, pois de vez em quando ele simplesmente não faz a requisição para tentar gerar a miniatura.

Cheguei nessa conclusão, pois quando não gera de jeito nenhum, também não gera nenhum registro na Cloudflare.

Daí quando ele resolve tentar, às vezes só consegue na segunda tentativa.

**Comment by filipedeschamps** [comment]
Hoje eu compartilhei link e funcionou 100%! Vou continuar monitorando e tentando detectar se tem algum pattern 🤝

**Comment by aprendendofelipe** [comment]
> Hoje eu compartilhei link e funcionou 100%! Vou continuar monitorando e tentando detectar se tem algum pattern 🤝

Talvez pelas páginas estarem sendo geradas de forma mais rápida... Talvez!!!
