### ISSUE TITLE
Todos os comentários estão em nome do autor da publicação

### ISSUE THREAD

**Issue by GHCMelo** [filipedeschamps/tabnews.com.br#1401]
Os autores dos comentários estão sendo trocados para o usuário criador da publicação.

![image](https://user-images.githubusercontent.com/50326228/236470396-016adae9-511f-44d9-9393-069de9b5b13d.png)

**Comment by aprendendofelipe** [comment]
Olá @GHCMelo, muito obrigado por reportar! 💪

Já reverti o último deploy, então já deve ter voltado ao normal 😉

**Comment by filipedeschamps** [comment]
Show! 😍  E interessante que os testes não pegaram este comportamento. Será que o endpoint `/children` não foi afetado? Porque nele lembro de ter feito cobertura com dois usuários.

**Comment by aprendendofelipe** [comment]
> Show! 😍 E interessante que os testes não pegaram este comportamento. Será que o endpoint `/children` não foi afetado? Porque nele lembro de ter feito cobertura com dois usuários.

Não pegou porque foi um condicional que só caia quando era buscada a árvore toda pelo username e slug. Já vou subir a correção.

O que acha de criarmos um endpoint na API que busca a árvore toda? Acho que vai ser muito útil para quem usa a API, além de ajudar a pegar bugs parecidos no futuro?

**Comment by filipedeschamps** [comment]
Interessante! Acho estranho a API fornecer duas formas similares de construir o conteúdo (fonte: vozes da minha cabeça).

De qualquer forma, temos que testar o método com essas condições, mesmo que seja invocando ele direto no teste 🤝

**Comment by aprendendofelipe** [comment]
Com certeza precisa de no mínimo um teste de integração, mesmo que fora da API 🤝

Sobre o endpoint, depois vou rever o histórico de decisões para entender porque está tudo separado, pois para mim fazia mais sentido as variações de dados fornecidos para um mesmo conteúdo serem definidas por parâmetros da requisição.

Até porque na maioria dos endpoints abaixo de `/username/slug` são realizadas praticamente as mesmas consultas no banco, mas só devolvem parte dos resultados. Então seria muito melhor para quem usa a API poder pedir tudo que precisa de uma só vez.

**Comment by filipedeschamps** [comment]
> Sobre o endpoint, depois vou rever o histórico de decisões para entender porque está tudo separado, pois para mim fazia mais sentido as variações de dados fornecidos para um mesmo conteúdo serem definidas por parâmetros da requisição.

Acho que não tem esse racional anotado (posso estar enganado) 🤝 


> Até porque na maioria dos endpoints abaixo de `/username/slug` são realizadas praticamente as mesmas consultas no banco, mas só devolvem parte dos resultados. Então seria muito melhor para quem usa a API poder pedir tudo que precisa de uma só vez.

Bom ponto! Mas as vezes sim e as vezes não, dependendo do client. Pega como exemplo um `content` que possui muitos `children` e a renderização é feita em tempo-real (ex. um SPA clássico ou native). Vai ser uma experiência melhor rapidamente consultar e trafegar pela rede o conteúdo principal, e só depois os `children`.

Isso acontece no caso do repositório do curso, onde é importante eu devolver o conteúdo com o vídeo o mais rápido possível, e só depois decidir ou não fazer a consulta pelo resto. Imagina trazer os dois numa mesma request para o `bem-vindo`... apesar do tempo total ser de fato menor para trazer tudo, a UX vai ser pior. Faz sentido?

**Comment by aprendendofelipe** [comment]
> Acho que não tem esse racional anotado (posso estar enganado) 🤝

Não encontrei mesmo 😕

Isso mesmo, depende de cada caso, por isso faltou eu enfatizar o "poder" pedir tudo de uma vez, mas não ser obrigado a consumir tudo de uma vez. E isso pode ser feito por endpoints diferentes, que é como está feito, mas limita as possibilidades para quem consume a API.

Se tivermos um endpoint com a possibilidade do consumidor informar quais dados precisa, será muito mais flexível e também vai melhorar a performance tanto do backend como dos clients, pois estaria sempre otimizado para cada caso.

Provavelmente compense fazer essa modificação para a v2 da API. 👍

**Comment by filipedeschamps** [comment]
Ahh entendi seu ponto! Perfeito!!! Poder passar por query string algo como `with_children=true` no `/contents/[username]/[slug]` correto? 🤝

**Comment by aprendendofelipe** [comment]
> Ahh entendi seu ponto! Perfeito!!! Poder passar por query string algo como `with_children=true` no `/contents/[username]/[slug]` correto? 🤝

Ou mais alto ainda, no `/contents`, pois assim não fica limitado ao que está dentro de `username` e `slug`.

Eu estava pensando em como fazer os testes lidarem com as novas consultas e me pareceu mais fácil migrar tudo que fosse possível para elas. E já que são mais rápidas e flexíveis, já deixei aberta toda a flexibilidade que eu estava falando sem mudar o contrato atual da API, ou seja, apenas acrescentando possibilidades sem retirar as atuais.

Vejam o PR #1413. E vou fechar essa issue, pois o problema foi resolvido no #1402 🤝

**Comment by aprendendofelipe** [comment]
@GHCMelo você foi citado no post comemorativo:

https://www.tabnews.com.br/FelipeBarso/tabnews-novo-ranqueamento-otimizacoes-e-mais 🎉
