### ISSUE TITLE
Abrir nova tab ao clicar no link externo do Github no footer

### ISSUE THREAD

**Issue by JMTiburcio** [filipedeschamps/tabnews.com.br#1404]
![image](https://user-images.githubusercontent.com/98969322/236528041-07830100-5cbb-4928-97d2-99a30b4828ae.png)

Ao clicar em Github, o usuário sai da página Tabnews. Recomendo abrir o github em uma nova tab para que o usuário continua com a página anterior da Tabnews.

Já tenho a solução para fazer o PR.

![image](https://user-images.githubusercontent.com/98969322/236527780-d68ddc8b-23f6-42e2-a5d0-ac4ef4637817.png)

**Comment by aprendendofelipe** [comment]
Olá @JMTiburcio, obrigado pela issue. 💪

Chegou a ver o que já foi conversado sobre o assunto?

Recomendo ver principalmente esse https://github.com/filipedeschamps/tabnews.com.br/issues/477#issuecomment-1182110074

Vou fechar essa issue e a conversa pode continuar por lá. Combinado? 🤝

**Comment by JMTiburcio** [comment]
E ae @aprendendofelipe 

Não tinha visto ainda.
Interessante que vcs tem uma abordagem diferente.

Valeu pela respota rápida!
