### ISSUE TITLE
[Sugestão] Mudança de contador de comentários para versão mais compacta

### ISSUE THREAD

**Issue by victorhcb** [filipedeschamps/tabnews.com.br#1414]
Falaaa pessoal, estava fazendo alguns testes aqui no TabNews e me deparei com um problema com uma quebra do layout em pequenas telas. Na tentativa de corrigir esse problema escrevi uma forma mais compacta de visualização dos comentários. Eu gostei bastante do resultado e queria saber a opinião de vocês antes de subir um possível PR

### **Atual**
![image](https://github.com/filipedeschamps/tabnews.com.br/assets/85972147/8e798111-a394-4521-9228-b92690e1545a)
### **Sugerido**
![image](https://github.com/filipedeschamps/tabnews.com.br/assets/85972147/bb346816-3d70-4719-a39f-a1f025d9f09e)

### **Atual com quebra do layout**
Agora no mobile: percebam como no post 5 (acontece em outros posts tbm) ele ultrapassar os limites da tela e faz com que haja uma rolagem lateral no site

![image](https://github.com/filipedeschamps/tabnews.com.br/assets/85972147/1aed7cd5-73f4-4d09-a440-364ce6b38ddc)
### **Sugerido**
![image](https://github.com/filipedeschamps/tabnews.com.br/assets/85972147/84e4b60c-2489-4faf-8c7f-5b49e22c2cb8)

**Comment by aprendendofelipe** [comment]
Olá @victorhcb, obrigado pela sugestão! 💪

Esse problema também está me incomodando. Parece que só ocorre quando tem algum username mais comprido em tela. Então tinha pensado em usar o [Truncate](https://primer.style/react/Truncate) no username, assim como já é usado no menu do header, mas não cheguei a testar na lista de conteúdos.

Também precisar investigar melhor o que está ocorrendo, pois era para simplesmente quebrar a linha ao invés de quebrar o layout.

Sobre a sugestão, talvez ainda ocorra o problema, dependendo do tamanho do username. Mas se com ela resolver, uma opção é usar apenas em telas pequenas. Só que eu achei um pouco estranho esse ícone no meio do texto. Talvez ficasse melhor se colocar no final, após o tempo de publicação, mas para isso precisa resolver outro problema que é como o tooltip da data lida com overflow.

Ou seja, é um problema que parece mais simples do que realmente é, então a ajuda é muito bem vinda. 👍

**Comment by victorhcb** [comment]
Show! Vou estudar melhor e sugerir alguma correção pensando nisso

**Comment by aprendendofelipe** [comment]
Um pouco mais tarde irei fazer o merge do PR #1562, e acredito que ele elimina a necessidade do que foi proposto aqui.

Então já vinculei essa issue e a #1532 para serem encerradas junto com o merge 🤝
