### ISSUE TITLE
[Sugestão de Implementação] Filtro de Conteúdo

### ISSUE THREAD

**Issue by jorgerabello3** [filipedeschamps/tabnews.com.br#1415]
Permitir que um usuário do tabnews na página que exibe seus próprios conteúdos https://www.tabnews.com.br/seujorge  consiga filtrar em ver:

* Todos os Conteúdos
* Apenas Comentários e Respostas
* Apenas Artigos que publicou

**Comment by robsonamendonca** [comment]
Sim, concordo um campo de busca no primeiro momento ajuda muito!

**Comment by aprendendofelipe** [comment]
@jorgerabello3, obrigado pela sugestão! 💪

Recomendo centralizar a discussão na #807. 👍

Vou fechar essa duplicada. Combinado? 🤝
