### ISSUE TITLE
[Sugestão de Implementação] Opção de seguir (ser notificado quando determinada pessoa publique algo novo)

### ISSUE THREAD

**Issue by jorgerabello3** [filipedeschamps/tabnews.com.br#1416]
Às vezes encontro autores fantásticos e realmente curto o conteúdo gostaria de ser notificado sempre que determinado autor publicasse algo novo. 

Não seria necessário exibir números (exemplo quantos seguidores determinado autor possui) 

Seria legal seguir autores para que cada vez que determinado autor publicasse algo novo eu recebesse uma notificação.

**Comment by joaoGabriel55** [comment]
Nice!

**Comment by Rafatcb** [comment]
Jorge, obrigado pela sugestão! Estou fechando este issue por termos dois outros issues que abordam esse problema:

1. https://github.com/filipedeschamps/tabnews.com.br/issues/645
2. https://github.com/filipedeschamps/tabnews.com.br/issues/738
