### ISSUE TITLE
[Sugestão] Botão reportar para sinalizar algo impróprio ou fora dos padrões para os moderadores/administradores.

### ISSUE THREAD

**Issue by JuanFontes** [filipedeschamps/tabnews.com.br#1418]
Tenho reprado diversos assuntos fora do escopo do site e sinceramente não sei até que ponto instruir o usuário pode ser visto como SPAM. Diante disso, brincando com o React (Não sou desenvolvedor), cheguei a tela abaixo, um botão de reportar do lado oposto do Responder.

<img width="1042" alt="image" src="https://github.com/filipedeschamps/tabnews.com.br/assets/8904414/1ad03a27-4d9a-41fc-9be1-5f1df96b9175">

Na minha humilde concepção, o site poderia ter uma coluna com os posts reportados ao qual somente moderadores e admins poderiam ter acesso, através de um ícone de notificação, que teria um href para cada post reportado. E o processo de exclusão seria o mesmo, tendo em vista que ele já existe.

Seria interessante definir radio buttons do motivo do report e/ou um textarea, e quem foi o responsável por reportar. Nesse caso precisariamos de uma tabela pra armazenar todas essas infos, certo? Num primeiro momento acredito que uma coluna com os IDs dos posts denunciados seria um primeiro passo.

**Comment by aprendendofelipe** [comment]
Olá @JuanFontes, obrigado pela sugestão! 💪

Recomendo centralizar a conversa na issue já aberta sobre o assunto #877

Vou fechar essa por ser duplicada. Combinado? 🤝

**Comment by JuanFontes** [comment]
Olá @aprendendofelipe , agradeço pois não tinha visto essa issue. Vou colocar meus inputs lá.
