### ISSUE TITLE
[Sugestão] separar  'meus conteúdos' e  interações

### ISSUE THREAD

**Issue by YrllanBrandao** [filipedeschamps/tabnews.com.br#1423]
assim, não sei se já fizeram esta sugestão, mas me incomoda a página de meus conteúdo misturar entre minhas publicações e  interações que fiz em posts de terceiros, portanto fica aí a sugestão, valeu!

**Comment by aprendendofelipe** [comment]
@YrllanBrandao, obrigado pela sugestão! 💪

Vou fechar a issue por ser duplicada com a #807.

Recomendo centralizar a discussão por lá. Combinado? 🤝
