### ISSUE TITLE
BUG: Publicação não exibida corretamente quando algum comentário é removido

### ISSUE THREAD

**Issue by Rafatcb** [filipedeschamps/tabnews.com.br#1430]
Já percebi isso num outro link que acessei aqui pelo GitHub e não tinha entendido, mas agora "vi com meus próprios olhos".

Removi um comentário que estava contra os termos de uso, mas antes o respondi com orientações. O que acontece é que agora ao acessar a [publicação raiz](https://www.tabnews.com.br/RomarioFSoares/disponibilizacao-de-livros-didaticos-eng-software), a visualização é a mesma de caso estivesse acessando meu [comentário](https://www.tabnews.com.br/rafael/aebcacb7-7de1-4ea5-96b3-7f028cad7d76).

![image](https://github.com/filipedeschamps/tabnews.com.br/assets/26308880/cae5408d-5190-4ea3-b4b6-6d3721b11253)

Edit: Encontrei o outro caso que tinha percebido isso: [publicação](https://www.tabnews.com.br/DavidBarbieri/qual-melhor-site-para-baixar-livros) e [comentário](https://www.tabnews.com.br/juanfontes/dce20375-6f02-442a-ba77-ff84bee03d2a).

Edit 2: 20 minutos depois, revisitei o primeiro exemplo (que eu removi o comentário) e a publicação está normal, mas o exemplo da edição anterior ainda está com o problema.

**Comment by aprendendofelipe** [comment]
Solução já aplicada em produção!

Muito obrigado @Rafatcb! 💪💪💪

**Comment by aprendendofelipe** [comment]
@Rafatcb, você foi citado no post comemorativo:

https://www.tabnews.com.br/FelipeBarso/tabnews-6-milhoes-de-visualizacoes-e-muita-novidade 🎉
