### ISSUE TITLE
[SUGESTÃO] - Comentários mais votados serem premiados a se tornarem Posts e a ganhar Tabcoins

### ISSUE THREAD

**Issue by migmoroni** [filipedeschamps/tabnews.com.br#1432]
A visão geral sobre os comentários, que é uma das razões de existir o tabnews, são que eles podem ter as vezes mesmo valor ou até maior, que o post o qual faz parte.

Comentários as vezes gigantescos, cheios de informação, todavia que pegam menos visibilidade no decorrer do tempo...

Sobre as tabcoins, pegando pela fala do próprio Filipe Deschamps , visaria ser como um óleo, que lubrifica e torna o ecossistema tabnews dinâmico.

Dito isso, agora a proposta:

**Premiar comentários, se tornando estes a posts e com tabcoins**

Comentários terem uma espécie de meta de tabcoins ou sub comentários únicos, onde batendo isso, este é repostado como um post principal e ocorrem premiações aos que participaram do comentário.

Sendo uma meta hipotética de 8 tabcoins OU 16 subcomentários de usuários únicos (comentários em seu comentário), ao bater, ocorre ao final:

1 - Usuário que deu tabcoin e/ou comentou, recebe 1 tabcoin;
2 - O autor do comentário, recebe até 4 tabcoins na medida que forem dados, com os restantes dos tabcoins lhe dados apenas ao final;
3 - O autor do post que estava o comentário, recebe 2 tabcoins, pois foi o iniciador causador do comentário adjacente.

Importante ressaltar: Seria contabilizado apenas 1 tabcoin e comentário, por usuário único, buscando uma situação de apoio e não de farm. Mais comentários no mesmo post, ainda conta como 1.
Seriam mini alavancas para serem mexidas até estarem bem colocadas.

E disto, se ganha que: Bons comentários que foram feitos, mesmo que a meses atrás, podem ser alavancados pelo público e serem repostados, assim, dando novo oxigênio para aquele comentário, que poderá receber mais comentários e quem sabe, fazendo que outro seja premiado, fazendo a roda girar...

É um mecanismo que buscaria jogar óleo para fazer o sistema girar com mais fluidez.
Possivelmente isto não seria bala de prata, onde outros mecanismos em conjunto darão a fluidez que tanto esperamos para esta rede bacana que está formando.

E quanto aos farms de plantão, é a busca constante de ir sanando, até que o custo de farmar seja tão alta, que não valha a pena o fazer.

E claro, não venho para ser o cara abençoado da razão no meio da discussão haha. Comentem o que acreditam, oxigenem o assunto. Quem sabe surge mais ideias, até melhores que esta !

**Comment by hkotsubo** [comment]
Não gosto dessa ideia de repostar o mesmo conteúdo.

Se a ideia é dar destaque a conteúdo que já existe, poderia ter uma nova aba (ou então um combobox com opções de ordenação), para mostrar os posts ordenados por outro critério:

- posts com atividade mais recente (seja comentário novo ou editado)
- posts mais votados
- posts com mais comentários 
- etc

Dessa forma, evita-se a redundância desnecessária de ter o mesmo conteúdo duplicado. E cada um escolhe como ordenar, de acordo com o que está procurando.

---

Sem contar que postar novamente o mesmo conteúdo fica confuso. Muitos comentários só fazem sentido se tivermos o post principal. Sem isso, ficaria ali "jogado" sem contexto.

Outro ponto é que quantidade de sub-comentários não necessariamente implica em qualidade. Teve uma thread recente com dezenas de respostas, mas a discussão virou um flamewar, com várias ofensas e nada de efetivamente concreto (tanto que foi até apagado).

**Comment by aprendendofelipe** [comment]
@miguelmoroni obrigado por trazer uma sugestão! 💪

Não acho que esse "prêmio" faz sentido. Se o comentário independe do contexto da publicação original, o autor decide se cria uma nova publicação ou se apenas comenta, assim como você fez a sugestão em outra issue, e depois resolveu abrir essa issue aqui para tratar especificamente da sua sugestão. Isso só poderia ser um prêmio se não fosse possível fazer de outra maneira, certo?

Devolver TabCoins para quem votou muda completamente a economia, e acho que o resultado seria para melhor.

E eu ia citar outros pontos, mas o @hkotsubo já foi cirúrgico, então só reforço o comentário dele. 👍

**Comment by miguelmoroni** [comment]
Antes de tudo, obrigado pela participação de vocês aqui nesta issue !

Li as duas criticas até então e digo que gostei dos argumentos, concordando que este talvez ainda não seja o caminho ideal.

O seu argumento @hkotsubo, onde diz: "Sem contar que postar novamente o mesmo conteúdo fica confuso. Muitos comentários só fazem sentido se tivermos o post principal. Sem isso, ficaria ali "jogado" sem contexto." , diz exatamente um problema novo que isso acabaria por gerar.

E sobre a organização dos posts, para encontrar mais rápido, selecionar os mais votados, etc, acompanho que já é um pedido antigo e grande pela comunidade, o que me coloco junto a apoiar. Isso ajudaria em muito a oxigenar a comunidade !

Mas daí é papo para outra issue...

**Comment by aprendendofelipe** [comment]
@migmoroni, de acordo com sua resposta, então já vou fechar a issue, mas qualquer coisa é só reabrir. Combinado! 🤝
