### ISSUE TITLE
[Sugestão] Realizar um "zoom" nas imagens ao clicar sobre elas para terem maior destaque

### ISSUE THREAD

**Issue by zehguilherme** [filipedeschamps/tabnews.com.br#1437]
Seria interessante adicionar a mesma feature que o [Medium](https://medium.com) e outras plataformas possuem.

https://github.com/filipedeschamps/tabnews.com.br/assets/36301054/fd5a51f4-de89-41b8-8f2e-55f1d0bee6b9

**Comment by aprendendofelipe** [comment]
@zehguilherme, obrigado pela sugestão! 💪

Me parece mais limitado do que a possibilidade atual, em que já é possível ajustar o zoom da forma que achar melhor, não sendo limitado a dois tamanhos. No celular é só usar o movimento de pinça.

**Comment by LucasBPalacios** [comment]
Olá, sou novo por aqui. Estou querendo fazer essa issue como minha primeira. Mas já estou tendo problemas na hora de criar uma publicação em ambiente de desenvolvimento e colocar uma imagem. Ela fica desse jeito:
![image](https://github.com/filipedeschamps/tabnews.com.br/assets/80708595/2fcdd2fd-39e8-43c0-9799-cfa2c346ef0b)
Dei uma procurada bem rápida e não consegui ajeitar. Se puderem me ajudar agradeço.

**Comment by aprendendofelipe** [comment]
> Estou querendo fazer essa issue como minha primeira.

@LucasBPalacios, obrigado pela disposição 💪

Vou fechar essa issue porque já é possível dar zoom de forma livre em qualquer página de conteúdo, consequentemente é possível dar zoom em qualquer imagem. 🤝

---

Sobre a dúvida, o problema não parece ter relação com o ambiente de desenvolvimento, mas sim em como exibir imagens usando markdown. A imagem precisa estar acessível no endereço que você forneceu, por exemplo:

```
![image](https://github.com/filipedeschamps/tabnews.com.br/assets/80708595/2fcdd2fd-39e8-43c0-9799-cfa2c346ef0b)
```
