### ISSUE TITLE
Tabcoins Negativas

### ISSUE THREAD

**Issue by Gabriel-Tapes** [filipedeschamps/tabnews.com.br#1446]
Hoje eu resolvi fazer um teste e ir apagando alguns posts para ver se era possível ter tabcoins negativas e atestei que realmente acontece. Fui excluindo alguns posts mais antigos até chegar ao saldo de -6 tabcoins. 

É possível ver isso diretamente pela API: https://www.tabnews.com.br/api/v1/users/gabrielTapes

Não sei se esse era um comportamento esperado, nem se acontece nos casos de downvotes. Caso seja um comportamento normal e esperado apenas me avisem que irei fechar a issue.

**Comment by aprendendofelipe** [comment]
Olá @Gabriel-Tapes, é o comportamento esperado sim, pois o saldo pode ficar negativo se os débitos forem maiores do que os créditos de TabCoins.

E os débitos ocorrem ao receber votos negativos, mas também ao apagar algum conteúdo que tinha lhe rendido TabCoins.

Se você apagar conteúdo que lhe rendeu TabCoins, você está retirando do sistema um conteúdo com valor concreto, então você devolve todos os TabCoins que ganhou com esse conteúdo. Caso já tenha utilizado eles, vai ficar negativo mesmo. Deve ter sido isso que ocorreu no seu caso. 👍

O usuário ficar com saldo negativo não impede de fazer novas publicações e recuperar esse saldo caso que ficou "devendo".

O que é diferente de manter conteúdos negativados, que nesse caso podem impedir as novas publicações.

Em resumo, é assim para incentivar que sejam excluídos apenas os conteúdos negativados, e sejam mantidos os bem qualificados, pois mesmo os conteúdos antigos continuam recebendo acessos se possuírem valor concreto.
