### ISSUE TITLE
[SUGESTÃO] - Links dos conteúdos abrirem em outra aba.

### ISSUE THREAD

**Issue by tarciofranco** [filipedeschamps/tabnews.com.br#1448]
Os links que dos conteúdos dos posts são abertos na mesma **página**, sugestão para que abra em outra **TAB**.
@filipedeschamps

**Comment by aprendendofelipe** [comment]
Olá @tarciofranco, obrigado pela sugestão!

Mas como o TabNews usa o Next.js, ou seja, no fundo funciona como uma SPA, não faz nenhum sentido abrir novas abas para mostrar conteúdos que, na maioria das vezes, já estão em memória. Se abrir em nova aba, parte dos dados que já estão disponíveis terão que ser baixados novamente, enquanto a navegação na mesma aba é quase instantânea.

E se você ler esse https://github.com/filipedeschamps/tabnews.com.br/issues/477#issuecomment-1182110074 do Filipe, verá que não é interessante nem mesmo para links externos.

Vou encerrar a issue, mas qualquer coisa é só reabrir. Combinado? 🤝
