### ISSUE TITLE
[Feature] - Tags e sistema de categorias

### ISSUE THREAD

**Issue by VinTesta** [filipedeschamps/tabnews.com.br#1449]
Olá a todos os usuário e contribuidores do TabNews!
É a primeira vez que contribuo para a plataforma e gostaria de deixar uma sugestão que ao meu ver traria um grande número de usuários.
Vejo o TabNews como uma grande iniciativa e aplicação, porém, acho o uso muito difícil graças a baixa categorização da mesma.
Minha sugestão seria implementar um sistema de "tags" ou categorias que auxiliassem o usuário na hora de buscar o conteúdo que deseja ou até mesmo um sistema de comunidade onde seria possível filtrar melhor aquilo que o usuário prioriza na hora que buscar um post. 
Exemplo seria o que me ocorreu esses dias atrás, gostaria de buscar algo relacionado a Web 3 e tenho certeza que temos muitos Devs, especialista ou iniciantes na área que agregariam muito a minha pesquisa no TabNews, porém, não consigo filtrar o conteúdo disponível o que acaba por dificultar o uso da plataforma.

Me ponho a disposição para auxilia no que conseguir e agradeço imensamente ao Filipe Deschamps pela iniciativa e a todos que contribuiram, isso é muito importante para a comunidade Dev. :)

**Comment by silvaezequias** [comment]
#742

**Comment by aprendendofelipe** [comment]
Olá @VinTesta, obrigado pela sugestão! 💪

Como o @silvaezequias já mencionou, ela é duplicada, então vou fechar essa aqui e recomendo continuar a discussão pela #742.

Combinado? 🤝

**Comment by VinTesta** [comment]
> Olá @VinTesta, obrigado pela sugestão! 💪
> 
> Como o @silvaezequias já mencionou, ela é duplicada, então vou fechar essa aqui e recomendo continuar a discussão pela #742.
> 
> Combinado? 🤝

Perfeito! Muito obrigado!
