### ISSUE TITLE
Alterar provedor de email transacional de Mailgun para Resend

### ISSUE THREAD

**Issue by filipedeschamps** [filipedeschamps/tabnews.com.br#1451]
@aprendendofelipe olha que interessante: o @zenorocha fez um convite para patrocinar o uso do https://resend.com/ no TabNews

https://www.tabnews.com.br/zenorocha/2762522d-6dbe-4f2c-a72d-591fa7061cc1

Vamos fazer um teste? Vai ser uma ajuda de ambos os lados, pois hoje pagamos `USD 35` mensais o que dá mais ou menos `BRL 2.000` anuais... e podemos devolver testando o serviço para valer, encontrando bugs, etc.

@zenorocha o convite ainda está de pé? 🤝

**Comment by RobertDS07** [comment]
Voaaa :rocket:

**Comment by mthmcalixto** [comment]
@filipedeschamps Acho que será incrível, as tecnologias mudam toda hora!

**Comment by aprendendofelipe** [comment]
Fala @zenorocha, tudo bem?

Na semana passada eu estava analisando como configurar o TabNews para usar o [Resend](https://resend.com/), mas deixei para depois porque vi que a compatibilidade com SMTP estava em beta e que, para usar a biblioteca [`resend`](https://resend.com/docs/send-with-nodejs), a gente precisaria adequar nossos testes de integração e também precisaria usar algum `Request Catcher` para conseguir realizar alguns fluxos em modo de desenvolvimento (hoje usamos o `mailcatcher` em um contêiner).

Mas hoje percebi que o aviso de que o SMTP estava em beta não consta mais na [documentação do Resend](https://resend.com/docs/send-with-smtp). Não encontrei nenhum anúncio sobre isso, apenas o [vídeo](https://www.youtube.com/watch?v=xBh_F7O6rEQ) em que vocês comentam que a compatibilidade iria chegar em breve.

Usando SMPT nós podemos migrar de serviço de email simplesmente trocando as variáveis de ambiente. Inclusive já está rodando com o Resend nesta branch de homologação:

https://tabnews-3rhx8kmom-tabnews.vercel.app/FelipeBarso/2adaa2d5-014f-4f22-8f58-53dd452a3e49

Então tenho duas dúvidas:

1. O Resend já está oficialmente compatível com SMTP e podemos usar em produção?
2. Existe alguma vantagem em migrar para a biblioteca `resend`, mesmo com todas as adequações necessárias, ou teremos o mesmo resultado se continuarmos com o `nodemailer`?

Muito obrigado!

**Comment by aprendendofelipe** [comment]
Com a publicação do [vídeo de hoje sobre a integração com SMTP](https://www.youtube.com/watch?v=MM1JE6-inmc), podemos ficar tranquilos em usar o Resend com o `nodemailer`.

@zenorocha, só resta uma dúvida, o [convite](https://www.tabnews.com.br/filipedeschamps/resend-nova-plataforma-de-email-criada-por-um-brasileiro-zeno-rocha#:~:text=Super%20toparia%20patrocinar%20o%20uso%20de%20Resend%20pela%20TabNews%20se%20voc%C3%AAs%20quiserem) ainda está de pé? 

O @filipedeschamps pode confirmar, mas acredito que estamos enviando cerca de 6.000 e-mails/mês

**Comment by filipedeschamps** [comment]
Isso, próximo de 6k 🤝 

## Gráfico de `30` dias

<img width="1489" alt="image" src="https://github.com/filipedeschamps/tabnews.com.br/assets/4248081/87cc8337-cc35-44f0-8994-950edec44f39">

<img width="393" alt="image" src="https://github.com/filipedeschamps/tabnews.com.br/assets/4248081/94d638fb-6674-4a4f-bc88-fc12af9ac73c">

## Gráfico de `90` dias

<img width="1490" alt="image" src="https://github.com/filipedeschamps/tabnews.com.br/assets/4248081/474d4c11-cf62-420a-b5a6-0dbf66fa267a">

**Comment by zenorocha** [comment]
Oi pessoal,

Desculpa a falta de atenção, fazia tempo que eu não olhava as minhas GitHub Notifications.

Enfim, o convite tá de pé sim! Qual é o melhor email pra eu enviar as instruções pra vocês?

**Comment by aprendendofelipe** [comment]
> Enfim, o convite tá de pé sim! Qual é o melhor email pra eu enviar as instruções pra vocês?

Show @zenorocha! Enviei nossos e-mails por mensagem no LinkedIn 🤝

**Comment by zenorocha** [comment]
Código de desconto enviado ;)

**Comment by aprendendofelipe** [comment]
O PR #1632 já estava pronto e aguardando aprovação, mas como o Mailgun resolveu dar problema hoje, já estamos funcionando via Resend e com o Mailgun configurado como contingência. 🚀🚀🚀
