### ISSUE TITLE
Salvar/Favoritar discussões

### ISSUE THREAD

**Issue by Tchez** [filipedeschamps/tabnews.com.br#1452]
Seria legal a possibilidade de favoritar discussões. Aconteceu de eu querer salvar um post para ver depois e, por não possuir essa funcionalidade, precisei salvar a URL. Creio que uma página de favoritos seria uma adição interessante :)

**Comment by felipsbreno** [comment]
@Tchez seria mesmo, acredito que essa funcionalidade vai ajudar caso alguém queira ver um post em outro momento. Percebi que alguns posts são tutorias, de como fazer um chatbot etc...acho que pra esse casos também vai ajudar esse implementação

**Comment by aprendendofelipe** [comment]
@Tchez, obrigado pela sugestão! 💪

Vou fechar essa issue por ser duplicada com a #645. Combinado! 🤝
