### ISSUE TITLE
Divulgação de post de blog

### ISSUE THREAD

**Issue by aaamenezes** [filipedeschamps/tabnews.com.br#1453]
## Olá galera, tudo bem?

Tenho um blog pessoal onde divulgo conteúdos sobre front-end e carreira.

Cada post também publico no Medium e Dev.to para ter um alcance maior. Para que o Google não considere conteúdo duplicado, eu uso o recurso de URL canônica que essas plataformas permitem.

**Quero começar a divulgar no Tabnews também**. Porém, pelo que vi, o Tabnews não permite o recurso de inserir URL canônica.

Então pensei em duas saídas:

1. Sugerir a implementação de URL canônica para divulgar conteúdos já publicados em outros sites. Se isso for inviável...
2. A segunda saída é mais uma dúvida: posso publicar um conteúdo no Tabnews linkando para meu blog e uma breve descrição do conteúdo?

Obrigado.

**Comment by aprendendofelipe** [comment]
Olá @aaamenezes, obrigado pela sugestão! 💪

Já existe discussão aberta sobre o tema, então vou fechar essa duplicada, e podemos continuar a conversa na #860.

Combinado? 🤝

**Comment by aaamenezes** [comment]
Perfeito! Muito obrigado @aprendendofelipe
