### ISSUE TITLE
Usar typesense como busca no site

### ISSUE THREAD

**Issue by mthmcalixto** [filipedeschamps/tabnews.com.br#1454]
Depois de sentir falta de um campo de busca no site, fui procurar alguma alternativa e encontrei [typesense](https://typesense.org/) e percebi como é fácil criar algo rápido, primeiro poderia criar um arquivo .json de todos os posts do TabNews, posts.json e enviar para o typesense rodando localmente no docker.

Com isso é possível retornar em tempo real os posts, letra por letra em segundos retorna o resultado, o que acham disso? o que você acha @filipedeschamps ?

Eles tem um exemplo com 32 milhões de músicas e em segundos retorna qualquer resultado relevante na pesquisa:
[MusicBrainz Songs Search](https://songs-search.typesense.org/) 
Um site que mostra o Typesense em ação em um banco de dados de 32 milhões de músicas de [MusicBrainz](https://musicbrainz.org/).

Outro exemplo usando a vercel: 
[E-commerce Storefront with Next.js + Typesense + Vercel](https://showcase-nextjs-typesense-ecommerce-store.vercel.app/)

Analisei a quantidade total de posts no TabNews atualmente existe cerca de 10224 posts, então será muito fácil criar esse sistema.

**Comment by aprendendofelipe** [comment]
@mthmcalixto, obrigado pela sugestão! 💪

Para aumentar as chances de avanço na ideia, estou pedindo para centralizar na issue #927 qualquer conversa sobre um sistema de busca. É para lá que estou direcionando todas as novas issues, então facilita para quem estiver interessado em contribuir ou acompanhar sobre esse assunto.

Vou fechar essa aqui como duplicada. Combinado? 🤝
