### ISSUE TITLE
[Sugestões] Tabnews esta parecendo conversa de WhatsApp.

### ISSUE THREAD

**Issue by ValadaresX** [filipedeschamps/tabnews.com.br#1456]
Boa tarde! Inicialmente, acreditava que o Tabnews seria uma plataforma de conhecimento, semelhante ao Reddit e ao Medium, que focaria principalmente em artigos elaborados por profissionais da área e desenvolvedores experientes em tecnologias inovadoras. No entanto, ao longo do tempo, tenho notado uma quantidade considerável de posts muito breves e repetitivos, com um conteúdo bastante superficial. 

Surpreendentemente, essas publicações de baixa qualidade acabam alcançando posições de destaque na plataforma. Sinceramente, estou um tanto decepcionado com a forma como o conteúdo está sendo organizado na plataforma atualmente. Peço desculpas por compartilhar minha insatisfação.

Sugestões:

>- Uma sugestão para evitar postagens repetidas seria a implementação de uma funcionalidade de busca de assuntos relacionados durante a criação do título do post pelo autor. Essa funcionalidade permitiria que, ao digitar o título, o sistema realizasse uma busca e exibisse os temas similares ao que o autor está propondo escrever. Embora eu tenha visto essa funcionalidade em outros lugares, não consigo me lembrar exatamente onde.

>- Outra sugestão seria implementar a classificação dos posts, tornando obrigatório para o autor informar o tipo de postagem que está escrevendo no momento da criação. Por exemplo, como ilustrado abaixo:
![badges](https://i.ibb.co/4YBDMJF/badge-01.png)

>- Criação de abas por tipo de assunto ou tecnologia. Dessa forma, os usuários poderiam navegar diretamente para as áreas que mais lhes interessam, facilitando a busca por conteúdo relevante. As abas poderiam ser organizadas de forma intuitiva e visível na página inicial, permitindo aos usuários filtrar o conteúdo de acordo com suas preferências.

Com essas melhorias, tenho certeza de que a plataforma se tornaria mais atrativa para os desenvolvedores e pessoas interessadas em tecnologia, incentivando a criação de artigos mais completos e aprofundados. Isso ajudaria a manter a qualidade do conteúdo e proporcionaria uma experiência mais enriquecedora para todos os usuários.

Espero que essas sugestões sejam consideradas para aprimorar o Tabnews e torná-lo realmente uma plataforma de conhecimento de referência. Estou ansioso para ver as melhorias implementadas.

**Comment by aprendendofelipe** [comment]
Olá @ValadaresX, obrigado pelas sugestões! 💪

Sobre a busca automática ao escrever o título, infelizmente ela é inviável no momento, pois além de outras complexidades, ainda não existe um sistema de busca dentro do TabNews que possa ser utilizado pela funcionalidade:

- #927 

E a busca é muito importante, mas não acho que evitaria assuntos repetidos, pois, se fosse o caso, não teríamos problema parecido aqui no repositório, onde, mesmo existindo a busca do GitHub, sempre surgem novas issues com sugestões parecidas ao invés de evoluírem as discussões já existentes.

Até por isso, não sei se vale a pena manter essa issue aberta até quando a implementação for mais viável, pois provavelmente esse título não vai atrair quem queira contribuir com a ideia ou queira implementar. Talvez seja mais interessante criar uma issue específica e dar mais detalhes de como funcionaria. Se conseguir se lembrar quais lugares viu a funcionalidade em prática, também é interessante colocar na issue. 🤝

Sobre TAGs/tópicos dos conteúdos, já temos esta:

- #742 

Ainda sobre a qualidade dos conteúdos, nós temos outras discussões com ideias de mecanismos para subir o nível, caso queira dar uma olhada e contribuir, alguns exemplos sãos:

- #1438 
- #1380
- #1267 
- #1198 
- #1153
