### ISSUE TITLE
Formatar label de quantidade de comentários para o singular [FRONTEND]

### ISSUE THREAD

**Issue by cesarcanoff** [filipedeschamps/tabnews.com.br#1458]
Formatar label para quando tiver apenas 1 ou nenhum comentário, apareça "comentário" e não "comentários".

![image](https://github.com/filipedeschamps/tabnews.com.br/assets/82189342/8f7df063-24e0-4d41-8597-0dc28118d303)

**Comment by aprendendofelipe** [comment]
@cesarcanoff, você foi citado no post comemorativo:

https://www.tabnews.com.br/FelipeBarso/tabnews-6-milhoes-de-visualizacoes-e-muita-novidade 🎉
