### ISSUE TITLE
[Segurança] CORS - Access-Control-Allow-Origin setado para "*" não traz problemas de segurança?

### ISSUE THREAD

**Issue by victorhcb** [filipedeschamps/tabnews.com.br#1459]
Fala pessoal, blz?

Sou meio novato por aqui, então peço desculpa se estiver falando alguma besteira.
Mas percebi nas configurações do next que os headers da API estão configurados para ativação do CORS trazendo o valor "*" para o header Access-Control-Allow-Origin.

A questão que ficou na minha cabeça é: não seria perigoso liberar o CORS de maneira tão irrestrita? O melhor não seria restringir essa configuração para evitar possíveis explorações maliciosas?

Como a milestone sobre performance e segurança está em aberto, achei pertinente também trazer esse questionamento aqui.

**Comment by aprendendofelipe** [comment]
Oi @victorhcb, precisa ser assim, pois a API do TabNews é pública 👍

**Comment by victorhcb** [comment]
Entendi!

Mas nesse caso não seria melhor deixar irrestrito apenas pra rotas que não usam autenticação? 

Rotas que utilizam autenticação, por serem "mais sensíveis" podem ser acessadas através de um servidor / backend, evitando assim que usuários mal intencionados consigam se utilizar da sessão de usuários salvas nos navegadores.
