### ISSUE TITLE
Contagem de comentários caso algum comentário com filhos seja apagado

### ISSUE THREAD

**Issue by Rafatcb** [filipedeschamps/tabnews.com.br#1462]
Considere a seguinte situação:

1. Uma publicação é feita.
1. Um comentário A é feito.
1. Um comentário B é feito respondendo ao comentário A.
1. O comentário A é apagado.

A publicação ficará como tendo `1 comentário`. Não seria melhor mostrar `0 comentários`?  Digo isso porque, às vezes, visito uma publicação apenas para ver os comentários novos, mas hoje essa situação não teria comentários, apesar de dizer `1 comentário`

Fiz isso no ambiente de _deployment_, pegando um link [aqui](https://github.com/filipedeschamps/tabnews.com.br/deployments). Por enquanto, [esse link](https://tabnews-730hgyfob-tabnews.vercel.app/rafael/teste-com-um-comentario-com-filhos-apagado) funciona.

![Contagem de comentários](https://i.imgur.com/2YFKbkt.png)

![Publicação sem comentários](https://i.imgur.com/iT7qqie.png)

**Edit:** Não sei se isso impacta também o ranqueamento com base em comentários:

https://github.com/filipedeschamps/tabnews.com.br/blob/9ab2c8771b6167a20943e48032988c081c0163cb/models/queries.js#L23-L39

**Comment by aprendendofelipe** [comment]
Oi @Rafatcb, antes a gente fazia uma consulta recursiva para contar os comentários, e ela era o que mais pesava no sistema. Agora é feita uma consulta absurdamente mais rápida, mas ela retorna a contagem dos comentários que estão publicados, mesmo que o pai tenha sido apagado.

A ideia é mostrar a árvore toda, deixando o espaço vago dos comentários apagados, para poder mostrar todos os filhos que ainda estão publicados. Só que isso ainda precisa ser feito.

**Comment by Rafatcb** [comment]
@aprendendofelipe agora que você comentou, lembrei do problema de performance. Acho excelente mostrar os filhos que ainda estão publicados.

Tudo bem deixar esta issue aberta e fechar quando isso for implementado?

**Comment by aprendendofelipe** [comment]
@Rafatcb, vou fechar aqui, pois o problema está relatado também na #1089, então não vai ficar sem solução 🤝
