### ISSUE TITLE
Ajustes necessários no firewall interno (limite de usuários e publicações por IP)

### ISSUE THREAD

**Issue by aprendendofelipe** [filipedeschamps/tabnews.com.br#1463]
O TabNews possui um [firewall](https://github.com/filipedeschamps/tabnews.com.br/blob/main/models/firewall.js) que limita a criação de usuários e publicações vindas do mesmo IP em um curto intervalo de tempo, mas agora precisamos fazer algumas melhorias nele:

1. A mensagem de erro deve ser mais clara sobre o impacto de ter sido pego pelo firewall. Por exemplo, precisamos avisar que não apenas a mensagem atual não foi publicada, mas também algumas mensagens anteriores podem ter perdido o status de publicadas.
2. Ao invés de mudar os conteúdos para "draft", talvez precisamos excluí-los ou criar um status próprio para esses casos.
3. Independentemente da exclusão ou de um status específico, devemos aplicar todos os efeitos que ocorreriam se a publicação fosse excluída, como a perda dos TabCoins.
4. Cuidar para não criar efeitos em publicações que já estão excluídas.

Talvez existam outras melhorias necessárias, então precisamos rever:

- [Firewall](https://github.com/filipedeschamps/tabnews.com.br/blob/main/models/firewall.js)
- [stored-procedures](https://github.com/filipedeschamps/tabnews.com.br/tree/main/infra/stored-procedures)

**Comment by Rafatcb** [comment]
> 2. Ao invés de mudar os conteúdos para "draft", talvez precisamos excluí-los ou criar um status próprio para esses casos.

Acho que podemos usar um status como `review` para futuramente termos uma lista onde um "moderador" pode tomar uma ação conforme o conteúdo (apagar, permitir a publicação, contatar o autor etc.). Esse status pode ser reaproveitado em situações onde, por exemplo:

* Conteúdos barrados pelo firewall (este issue).
* O autor do conteúdo não é confiável.
* O conteúdo recebeu X sinalizações.

**Comment by aprendendofelipe** [comment]
# Execução

- #1765 
- #1638
