### ISSUE TITLE
[Sugestão] Aba de conteúdos recomendados

### ISSUE THREAD

**Issue by eletroswing** [filipedeschamps/tabnews.com.br#1468]
Fala galera, baseando-me nos conteúdos do Tabnews: 
[O Famoso Algoritmo](https://www.tabnews.com.br/Ytu/o-famoso-algoritmo-como-funciona-e-como-fazer-um-sistema-de-recomendacao-de-conteudo-um-ponto-de-partida)
[O Famoso Algoritmo 2](https://www.tabnews.com.br/Ytu/o-famoso-algoritmo-2-um-aranhaverso-de-conexoesse-aprofundando-um-pouco)

Pensei na introdução de uma nova aba, além das recentes e relevantes: a "recomendados".
Essa página úsaria a bordagem citadas nos posts, usando o sistema de relevantes atual e os dados já em db do úsuario e recomendaria os mehores//os mais provaveis posts (recentes) que o úsuario iria gostar ou interagir.

O que acham? Alguma ideia? Vale a pena?

**Comment by aprendendofelipe** [comment]
Olá @eletroswing, obrigado pela sugestão! 💪

Não vejo razão para ter ao mesmo tempo uma seção de "relevantes" e outra de "recomendados". Pra mim é a mesma coisa. 

Será que você está enxergando os "relevantes" atuais como sendo conteúdos que tiveram um bom desempenho, por exemplo, que foram mais vistos ou que se saíram melhor em algumas métricas? Possivelmente teremos esse tipo de apresentação dos conteúdos, permitindo classificar por diferentes métricas, mas algumas nós ainda não temos como disponibilizar em tempo real, como as contagem de visualizações, então isso ainda é algo para ser desenvolvido.

A ideia das páginas de "relevantes" é que ali fiquem os conteúdos recomendados do momento. E para isso usamos os dados que temos disponíveis sobre as publicações, mas não sobre os usuários. Personalizar as recomendações é uma possibilidade para o futuro do TabNews, mas exige uma revolução no sistema que não faz sentido no momento atual, em que ainda não foram vencidas etapas coma a implementação da Revenue Share e o aperfeiçoamento das qualificações dos conteúdos e outras métricas.

Um outro exemplo de etapa anterior à personalização, será a implementação de tópicos, onde existirão diferentes recomendações de acordo com os assuntos escolhidos pelos usuários, mas ainda assim, provavelmente não será algo totalmente individualizado em um primeiro momento.

Mas vai ser interessante se você desenvolver melhor a ideia que você citou de usar o sistema de relevantes atual e dados que já possuímos dos usuários. Quais dados dos usuários? Como seria a consulta que retornaria os "recomendados" individualizados?

**Comment by eletroswing** [comment]
Olá @aprendendofelipe , respondendo a **primeira parte:**
Seria mais para criar postagens que realmente tem valor ao úsuario, pq as vezes os mesmos gostam de conteúdos especificos, como css, mas a aba relevantes raramente entram conteudos de css(só um exemplo). Dessa forma, teriam uma maior rotação de tabcoins, e criação de comentarios!

**Segunda parte**:

A aba eventos e a aba de posts, especificamente, assim poderia relacionar quais conteudos os usuarios deram like ou criaram comentários, a partir deste, encontrar o autor do post(ex: do que o usuario mais deu like) e recomendar alguns outros posts dele ou que o proprio autor deu like(passando por um filtro igual o do relevantes pra esses conteudos semelhantes) ou até seguir um exemplo um pouco mais aprofundado """igual""" o page ranking do google, onde pegariamos palavras dos conteudos interagidos, e procuramos em posts que se encaixam nessas palavras, excluindo necessidade de criar novas tabelas, seria mais um trabalho de analise dos dados e não em si de coleta e geração de dados. O unico defeito dessa abordagem que eu consigo ver é o tempo para gerar o feed, mas, nao deve ter impactos altos na aplicação(pense naquela demora carregando os comentarios do post mais comentado do tabnews).

**concluindo meu ponto**:

Bem, é so uma ideia e opnião, algo que nao precisa(nem deve) ser explorado por agora se for o caso!
