### ISSUE TITLE
[Erro] Barra de pesquisa não funciona no mobile.

### ISSUE THREAD

**Issue by eletroswing** [filipedeschamps/tabnews.com.br#1473]
@aprendendofelipe  @filipedeschamps A barra de pesquisa que foi para produção no último merge não funciona corretamente(ao menos não em meu dispositivo mobile: um moto one vision), ao pesquisar e clicar na sugestão, o modal simplesmente some.

**Comment by aprendendofelipe** [comment]
Oi @eletroswing, obrigado por reportar! 💪

Removi as sugestões por enquanto. 👍

**Comment by aprendendofelipe** [comment]
Resolvido em #1475

**Comment by aprendendofelipe** [comment]
@eletroswing, você foi citado no post comemorativo:

https://www.tabnews.com.br/FelipeBarso/tabnews-6-milhoes-de-visualizacoes-e-muita-novidade 🎉
