### ISSUE TITLE
[sugestão] feature de assuntos relacionados

### ISSUE THREAD

**Issue by developerfred** [filipedeschamps/tabnews.com.br#1478]
quando um usuario abrir um topico com um assunto que já foi publicado, aparece o link ou um resumo do assunto, se mesmo assim o usuario postar sugerir em baixo assuntos sobre o mesmo tema. 

exemplo Lógica:

https://www.tabnews.com.br/PedroVSD/melhorando-a-logica-de-programacao
https://www.tabnews.com.br/Joel34L/logica-de-programacao-esta-me-matando

**Comment by Rafatcb** [comment]
Acho que fazer isso de forma automatizada tem uma grande chance de ficar ruim, tendendo para algum dos lados:

1. Publicação com pouca ou sem interação.
2. Publicação ruim.
3. Publicação boa, sobre o mesmo assunto ou parecido, mas que na prática não tem nada a ver com a publicação atual.

No Hacker News, a própria comunidade costuma mencionar _threads_ relacionadas, sobre o mesmo assunto. Lá a interação é bem maior do que no TabNews e acho que funciona bem. No TabNews, para a maioria das publicações, acho que não teríamos tantas coisas relacionadas para mostrar.

O seu comentário _"com um assunto que já foi publicado"_ me fez pensar se você está querendo algo mais para o lado de tags, como mencionado em https://github.com/filipedeschamps/tabnews.com.br/issues/742

**Comment by emerson-oliveira** [comment]
Sugeri em outra issue a implantação de um sistema de votação de tags, onde será possível ser visualizado as tags mais vistas.
Baseado nisso podemos adicionar no final das postagens o relacionamento baseado nesses tags.

- [ ] **Seção de postagens relacionadas:** Com base nas tags mais votadas, criar uma seção de “postagens relacionadas” no final de cada postagem.

**Comment by aprendendofelipe** [comment]
Turma, obrigado pelas contribuições! 💪

Vou fechar diversas issues com assuntos relacionados. Por isso estou listando abaixo as que serão mantidas abertas e onde recomendo concentrarmos o que foi debatido/sugerido aqui:

- #645 
- #738
- #742 

Fechando essa aqui 🤝
