### ISSUE TITLE
[Dúvida/Sugestão] Tabnews - Salvar conteúdo como favorito

### ISSUE THREAD

**Issue by ghermanypaganini** [filipedeschamps/tabnews.com.br#1482]
Neste momento cheguei a marca de 12 abas de publicações do Tabnews abertas no meu navegador. Devido a isso, decidi publicar pela primeira vez aqui no repositório do Tabnews uma dúvida que surgiu e que pode se tornar uma sugestão. 

Essas abas abertas são publicações extensas ou tão interessantes que eu deixo para ler ou reler em um outro momento. Dado esse cenário, minha sugestão é que tenha uma forma de favoritar ou "salvar publicação" da comunidade, como existe no Instagram, por exemplo. Essa função salvaria o link da publicação em uma "pasta arquivada" pessoal dentro do TabNews, sem ter que adicionar a página nos favoritos do navegador ou algo do tipo, podendo assim ler a publicação mais a tarde ou até mesmo acompanhar os comentários antes de interagir no tópico. 

Não sei talvez se essa seria a função do "Achei relevante" ao lado das publicações, porém, eu ainda estou com 0 coins e não consigo marcar um tópico como relevante ou talvez eu nem ache o conteúdo relevante naquele momento. 

Acompanho o site a um tempinho, já fiz um comentário mas ainda não fiz nenhuma publicação. Por esse motivo, caso eu não tenha entendido da forma clara a dinâmica do Tabnews, essa sugestão possa ser interpretada como dúvida, ou vice-versa.

Valeu galera!

**Comment by mthmcalixto** [comment]
@ghermanypaganini É uma boa feature, o problema é que o TabNews não tem laterais, então tudo fica no header, se tivesse era fácil adicionais alguns botões.

Talvez colocando em outro lugar, e pelo que o que eu entendi até agora, TabNews se parece com o Hacker News, não tem muitas funções.

**Comment by Rafatcb** [comment]
É uma boa sugestão. Já sugeriram isso algumas vezes, a discussão está concentrada aqui: https://github.com/filipedeschamps/tabnews.com.br/issues/645. Inclusive, abordaram a ideia de listas, que me parece mais interessante do que apenas favoritar.

**Comment by aprendendofelipe** [comment]
@ghermanypaganini, obrigado pela sugestão! 💪

Vou fechar apenas por organização, já que ela é duplicada com a #645 🤝
