### ISSUE TITLE
Comunidade Toxica

### ISSUE THREAD

**Issue by cybernerd007** [filipedeschamps/tabnews.com.br#1485]
Há algum tempo venho notando que os usuários do Tabnews na sua grande maioria estão agindo de uma forma toxica como por exemplo questões fáceis de resolverem sendo de forma "BRUTAL" respondida isso quando respondida kkkkkk

Proponho aqui remover o DownVote assim os usuários tóxicos seriam reduzidos ou ao menos forcado pela sua raiva a responder coerentemente dando assim a resposta por mais simples que fosse assim resolvendo o problema dos usuários tóxicos e dos usuários que publicam com uma duvida

Deixo aqui minha ideia, para discutirmos...

**Comment by filipedeschamps** [comment]
> na sua grande maioria

Não consigo ver que é a grande maioria, nem de perto isso, mas de qualquer forma acho válido fazermos algo sim sobre os down votes. Fiz uma sugestão [nessa resposta aqui](https://www.tabnews.com.br/filipedeschamps/076b3791-0928-4afb-bf84-ec357ea20723) sobre ser uma feature mais difícil de ganhar.

@aprendendofelipe o que acha de fazermos algum tipo de experimento? 🤝

**Comment by cybernerd007** [comment]
**Levei em consideração o `Recente` de 14 posts metade está ou negativo ou zerado... mas sem duvida eu exagerei**

![](https://img001.prntscr.com/file/img001/5yaPQPewRB-dfJMKyJ-NOQ.png)

**Comment by aprendendofelipe** [comment]
Considerando que os votos negativos citados foram dados por quem já publicou algo considerado relevante e ganhou TabCoins com isso. E que os votos parecem estar de acordo com os critério pessoais dos usuários que votaram. Não vejo isso como um comportamento tóxico, mas sim algo normal. Outros usuários podem concordar ou discordar das avaliações e darem seus votos.

> Proponho aqui remover o DownVote assim os usuários tóxicos seriam reduzidos ou ao menos forcado pela sua raiva a responder coerentemente dando assim a resposta por mais simples que fosse assim resolvendo o problema dos usuários tóxicos e dos usuários que publicam com uma duvida

Não foi explicado como remover o voto negativo reduziria os usuários tóxicos e nem como isso forçaria alguém com raiva a responder algo coerentemente. Mas foi confessado o exagero na criação da issue, então vou fechar essa aqui. Qualquer coisa é só abrir novamente, ou abrir outra 🤝

**Comment by aprendendofelipe** [comment]
> @aprendendofelipe o que acha de fazermos algum tipo de experimento? 🤝

Estamos nesse experimento aqui #1477, onde foi aumentando os ganhos de quem já passou da exigência mínima, mas sem diminuir essa exigência mínima.

Deixa só fechar uma semana e eu coloco os dados preliminares lá, mesmo que uma semana seja muito pouco para tirar conclusões precisas 🤝

**Comment by cybernerd007** [comment]
O "Confesso o exagero" foi na forma de expressar mas nós sabemos e já discutimos esse problema do DownVote e sinceramente eu vejo que isso e tentar evitar o inevitável...
