### ISSUE TITLE
[ Sugestão ] conteúdo mais relevante na página de perfil

### ISSUE THREAD

**Issue by lucieudo-roberto** [filipedeschamps/tabnews.com.br#1488]
Há pouco tempo atrás eu me deparei com um usuário muito inteligente nos comentários de um post, então visitei o seu perfil no tabnews para buscar mais conhecimento, porém tinha muito conteúdo na sua página. Bom, eu abri somente os que tinha mais de uma resposta e muitos votos de relevante. Poderia, na página de perfil dos usuários, ter um top ranking 3 de conteúdos relavantes do usuário, e abaixo a lista de suas contribuições. Ficaria mais fácil achar conteúdo relavente do usuário, no qual ele domina, ou não. 

Eu acredito que esse sistema de rank, que pode ter peso através dos comentários e votos, pode entregar uma noção do tipo de especialista que o usuário é.

**Comment by Rafatcb** [comment]
Lucieudo, obrigado pela sugestão! Temos o issue https://github.com/filipedeschamps/tabnews.com.br/issues/1388 que fala sobre a possibilidade de ordenar os conteúdos por diversos filtros diferentes: data, votos, quantidade de comentários etc. Vou fechar este para concentrar a discussão lá, ok?
