### ISSUE TITLE
'bug' tabcoins, implementar devolução, ou não gastar mais ao votar diferente.

### ISSUE THREAD

**Issue by renatodru** [filipedeschamps/tabnews.com.br#1493]
Ao negativar esta publicação, https://www.tabnews.com.br/moacirmoda/fui-cancelado-pela-bolha-dev
ponderei que não valia a pena gastar tabcoins para negativa-la, pois acabaria dando mais palco para o animal.
Tentei recuperar as minha tabcoins clicando no achei relevante, para minha surpresa acabei gastando mais tabcoins.
Da mesma forma que não é possível positivar duas vezes a mesma publicação ou negativar duas vezes, não deveria ser possível votar duas vezes, ainda que em opções diferentes, caso isso ocorra não deveria haver gasto de mais tabcoins ao votar em uma opção diferente.

**Comment by aprendendofelipe** [comment]
Olá @renatodru, obrigado por relatar, mas a dinâmica dos votos parece ter ocorrido como esperado.

É possível votar até 3 vezes em uma mesma publicação dentro de um período de 72 horas, utilizando o memo IP, sejam votos positivos ou negativos.

E não existe funcionalidade de desfazer os votos, pois eles podem já ter impactado no ranqueamento de relevantes.

Vou fechar a issue, ok?

**Comment by renatodru** [comment]
@aprendendofelipe, não sei se você entendeu corretamente o que eu descrevi, mas não faz sentido...
