### ISSUE TITLE
Token vazando em homologação

### ISSUE THREAD

**Issue by cybernerd007** [filipedeschamps/tabnews.com.br#1500]
Realizando os teste como sempre detectei que esta sendo vazado em homologação o token, não fui mais afundo pois acabei de descobrir então não sei o impacto real mas acredito que isso não deveria estar acontecendo... essa e a ultima deploy em homologação

![](https://i.imgur.com/1yXH71D.png)

**Comment by filipedeschamps** [comment]
@cybernerd007 eu recebi por email o conteúdo original da issue (e ele continua disponível no histórico da issue em si):

<img width="835" alt="image" src="https://github.com/filipedeschamps/tabnews.com.br/assets/4248081/2fd7a0e1-92b2-4e74-83ff-8de3f1f90278">

E dá para deletar esse histórico também (porque o texto ainda está lá).

De qualquer forma, toda vez que é feito um `POST` no `/sessions`, é retornado o token da sessão no corpo, para que um client que não use cookie consiga acessar o valor com mais facilidade (pra não precisar cavucar no header). Mas este deveria ser o único momento que o token é retornado no corpo 🤝

**Comment by cybernerd007** [comment]
@filipedeschamps eu ate mesmo pesquisei uma forma de apagar porem não aparece para apagar.

Eu me confundi o token e atualizado toda vez que e feito uma "request" na sessions, como antes desse teste eu havia feito um outro de roubo de sessão eu me "em bananei todo"....
