### ISSUE TITLE
[Dúvida] AWS RDS e acesso ao banco

### ISSUE THREAD

**Issue by victorhcb** [filipedeschamps/tabnews.com.br#1502]
Gente... estava estudando o repositório do tabnews aqui e fiquei com uma dúvida... não sei se aqui era melhor lugar pra postar... peço desculpa de antemão se não for...

Alguém sabe dizer como está configurado o acesso ao DB da AWS?
Vi que tem VPC que restringe o acesso a uma rede privada... mas vi também que tem a opção de acesso publico ao banco de dados, mas em todo lugar que eu vejo fala que não é recomendado escolher essa opção para banco em produção...

Como esse problema foi contornado sem comprometer a segurança do banco?

**Comment by aprendendofelipe** [comment]
Antes o acesso ao banco não podia ser restrito, pois o banco precisava ser acessado pelas lambdas da Vercel, que não era compatível com VPC.

Com o avanço desta [conversa](https://github.com/orgs/vercel/discussions/42), a coisa mudou recentemente. Veja na [documentação da Vercel](https://vercel.com/docs/security/secure-compute)

**Comment by victorhcb** [comment]
Entendi!

Obrigado pelas informações 😊
