### ISSUE TITLE
[SUGESTÃO] Confirmação de cadastro e notificações por WhatsApp

### ISSUE THREAD

**Issue by heldercamargo** [filipedeschamps/tabnews.com.br#1503]
Que tal se ao invés de confirmar o cadastro e enviar notificações por e-mail, fazer isso através de um número WhatsApp? Ao se cadastrar, o usuário além do e-mail, também informaria o seu número WhatsApp, e escolheria a forma que gostaria de ser notificado - E-mail, WhatsApp ou ambos.

**Comment by victorhcb** [comment]
Acredito que o principal limitador dessa implementação seria o custo... buscando aqui rapidamente pela API da META o custo por conversa fica aproximadamente $0,03.

Considerando que o número de disparo de conversas/mensagens seja aproximado ao que temos por email (6000 emails por mês #1451) ficariamos com um custo aproximado de $180,00 por mês.

Referência: https://developers.facebook.com/docs/whatsapp/pricing

**Comment by Rafatcb** [comment]
Acho que armazenar o número de celular do usuário traria preocupações a mais por ser mais um dado pessoal do usuário, e precisaríamos confirmar duas coisas: o e-mail e o telefone (sim, continuaríamos precisando confirmar o e-mail para garantir que é válido e é do usuário).

Isso parece trazer mais preocupação do que benefícios, fora a dependência de um serviço que pode ser substituído daqui alguns anos. Por exemplo: se o Telegram começar a ser mais usado, precisaríamos manter a integração com o WhatsApp e criar uma com o Telegram?

**Comment by aprendendofelipe** [comment]
@heldercamargo, obrigado pela sugestão! 💪

Como a Turma não comprou a ideia, vou fechar a issue, mas qualquer coisa podemos reabrir o debate. 🤝
