### ISSUE TITLE
[SUGESTÃO] Permitir o salvamento de posts ao usuário 

### ISSUE THREAD

**Issue by sempsei** [filipedeschamps/tabnews.com.br#1505]
Permitir o salvamento de posts para o usuário, melhore demais sua experiência. Hoje se eu quero salvar um post do tabnews, salvo como favorito no navegador ou salvo o link da publicação. Mas permitindo o salvamento de post como Medium, Instagram etc, isso se tornaria mais simples e elegante ao usuário.

**Comment by aprendendofelipe** [comment]
@sempsei, obrigado pela sugestão! 💪

Vou fechar apenas por organização, já que ela é duplicada com a #645 🤝
