### ISSUE TITLE
[Sugestão] Links nos comentarios e post

### ISSUE THREAD

**Issue by CodifyBrazil** [filipedeschamps/tabnews.com.br#1506]
Sempre que clico em um link do post ou comentario, sou redirecionado, do tabnews para onde o link aponta, o problema é que toda vez que faço isso, nao quero que o tabnews feche, muita das vezes quero entrar sim no link, mas tambem ficar no tabnews

**Comment by aprendendofelipe** [comment]
@CodifyBrazil, obrigado pela sugestão! 💪

Vamos centralizar a discussão na issue relacionada #477 👍

Recomendo ler o [comentário](https://github.com/filipedeschamps/tabnews.com.br/issues/477#issuecomment-1182110074) do Filipe
