### ISSUE TITLE
[SUGESTÃO] Favoritar/Salvar Artigos

### ISSUE THREAD

**Issue by Edu0liver** [filipedeschamps/tabnews.com.br#1507]
Em vários momento me vejo na situação de deixar a aba do artigo aberta por tempo indeterminado, isso porque posteriormente gostaria de reconsultar o conteúdo ou contribuir com um comentário, então penso que seria bem-vinda uma funcionalidade de favoritar/salvar um artigo, para evitar a situação de salvar links por exemplo .

**Comment by anderood** [comment]
Cara, tambem estou no aguardo desta feature...
Ela esta sendo tratada aqui:

https://github.com/filipedeschamps/tabnews.com.br/issues/645#issue-1337367010

**Comment by aprendendofelipe** [comment]
@Edu0liver, obrigado pela sugestão! 💪

Vou fechar apenas por organização, já que, como o @anderood citou, ela é duplicada com a #645 🤝
