### ISSUE TITLE
[ Sugestão ] Two factor authentication

### ISSUE THREAD

**Issue by mayconbalves** [filipedeschamps/tabnews.com.br#1511]
Questões:
- Implementar isso pode prejudicar a experiência do usuário ?
- Precisaríamos implementar mais algum serviço ? Se sim, quanto custoso  seria ?
- Qual vantagem de implementar o serviço ?

**Comment by aprendendofelipe** [comment]
@mayconbalves, obrigado pela sugestão! 💪

Por organização, vou lhe pedir para participar na #1171 que já trata do assunto. 👍

Vou fechar essa aqui como duplicada. Combinado? 🤝
