### ISSUE TITLE
[Dúvida] Banco de dados do preview da vercel

### ISSUE THREAD

**Issue by victorhcb** [filipedeschamps/tabnews.com.br#1512]
Gente... estava estudando o repositório do tabnews aqui e fiquei com uma outra dúvida... não sei se aqui era melhor lugar pra postar... peço desculpa de antemão se não for...

Como o tabnews cria um banco de dados para cada preview? Isso é criado programaticamente? Onde está hospedado esse BD de homologação?

**Comment by aprendendofelipe** [comment]
Fala @victorhcb!

Não são criadas diferentes instâncias do banco de dados para cada preview. Além disso, as instâncias de banco de dados não são gerenciadas pela Vercel.

Oficialmente temos a instância de produção e a de homologação na AWS. Também já criamos instâncias na Supabase e no Neon para fazer testes pontuais, mas a oficial é da AWS.

Na Vercel já estão configuradas as variáveis de ambiente para os dois bancos (produção e homologação), então cada tipo de deploy se conecta ao banco correspondente (já existente).

Fora a configuração padrão produção/homologação, quando queremos testar algum terceiro banco de dados, basta subir o banco no serviço que for, e informar as novas variáveis de ambiente na Vercel. Nesses casos, configuramos as variáveis de ambientes para valerem apenas para os deploys originados de uma única branch no GitHub.

**Comment by victorhcb** [comment]
Aaah entendi @aprendendofelipe 

Muito obrigado!

A única dúvida que fiquei é como lidamos com migrations de diferentes pull requests então? 

Acredito que isso deva gerar um certo ruído de tabelas e alterações no banco de dados de homologação, né?

**Comment by aprendendofelipe** [comment]
As migrations só são executadas no banco de homologação de forma planejada. É preciso que alguém que possua essa feature dispare intencionalmente o comando via API. Então um PR que depende da execução de uma nova migration não vai funcionar em homologação enquanto não decidirmos dar esse passo.

Talvez você esteja pensando no ambiente de testes no GitHub. Esse não tem relação nenhuma com a Vercel. Um novo ambiente é criado após cada commit sincronizado com o repositório. Nesse sim são executadas todas as migrations do PR, mas o ambiente é isolado e volátil, ou seja, tudo é excluído assim que os testes automatizados terminam.

É possível que a confusão surja porque ao mesmo tempo que esse ambiente de testes é criado no GitHub, é feito um novo deploy no ambiente de homologação na Vercel, mas são dois processos independentes apenas disparados pelo mesmo evento.

**Comment by victorhcb** [comment]
Agora entendi!! Genial

Achei que as migrations rodavam internamente em algum processo de build, mas interessante saber que na verdade elas devem ser rodadas manualmente a cada nova feature, podendo, assim, serem controladas manualmente no ambiente de homologacao.

Muito obrigado @aprendendofelipe pela paciencia e explicação, e me desculpe mais uma vez pelo incomodo!
