### ISSUE TITLE
Bug: Impossível listar meus rascunhos

### ISSUE THREAD

**Issue by leoferreiralima** [filipedeschamps/tabnews.com.br#1513]
Estava validando a api de conteúdo e encontrei um possível gap

quando se cria plublicação via a api de content é possivel passar o status('draft', 'published', 'deleted'), por mais que na tela não haja ainda a opção de criar como rascunho, pela api isso é possível, porém quando listo meus conteúdos os rascunhos não aparacecem.

Olhando no código vi que o status para a rota `/api/v1/contents/[username]` está setado para buscar apenas published

![image](https://github.com/filipedeschamps/tabnews.com.br/assets/36305985/14732841-1cf9-4f6f-87c5-071e519debfa)

Entendo que o correto nesse caso seria verficar se o usuario que está acessando a rota é o mesmo do parametro username e se sim utilizar o filtro de status com draft ou  published, caso for um usuarios acessando os conteudos de outro utilizar somente o published.

Outro ponto que me chamou atenção foi o uso do `user.createAnonymous()` ao invés de utilizar o `authentication.injectAnonymousOrUser`, confesso que não entendi o pq disso, mas talvez seja um código que não foi atualizado.

**Comment by aprendendofelipe** [comment]
@leoferreiralima, obrigado por reportar! 💪

O status `draft` não foi totalmente implementado. Não há maneira de listar esses conteúdos, então eles só são utilizados em alguns dos testes automatizados.

> Entendo que o correto nesse caso seria verficar se o usuario que está acessando a rota é o mesmo do parametro username e se sim utilizar o filtro de status com draft ou published, caso for um usuarios acessando os conteudos de outro utilizar somente o published.
> 
> Outro ponto que me chamou atenção foi o uso do `user.createAnonymous()` ao invés de utilizar o `authentication.injectAnonymousOrUser`, confesso que não entendi o pq disso, mas talvez seja um código que não foi atualizado.

A rota `/api/v1/contents/[username]` possui cache na CDN, então seu retorno não pode depender de dados do usuário.

A possibilidade de publicar com status `draft` provavelmente foi *overengineering*. O salvamento automático dos rascunhos no `localStorage` atendeu parte da justificativa para esse status.

Está pendente um debate sobre a manutenção desse status, para então ser terminada a implementação (talvez a criação de outra rota) ou a remoção da possibilidade de publicar como `draft`.

Eu acredito que a possibilidade de listar as publicações com status `draft` iria facilitar o uso do TabNews como CMS sem o autor precisar participar do ciclo completo de contribuição e nem com a qualidade do conteúdo, então talvez não seja interessante.

**Comment by aprendendofelipe** [comment]
> onde posso encontra-la?

Não existe uma issue que esteja centralizando essa discussão.

> A CDN desse projeto é da própria vercel ou é algo externo na cloud?

Tem diferentes níveis de cache na Vercel e na Cloudflare

**Comment by leoferreiralima** [comment]
Vou criar uma issue para centralizarmos essa discussão então, acredito que seja interessante definirmos se seguiremos ou não com a opção do draft e como
