### ISSUE TITLE
(Bug) Falha ao postar comentários.

### ISSUE THREAD

**Issue by RadioactivePlays** [filipedeschamps/tabnews.com.br#1514]
Ao tentar responder a um comentário, é exibido uma notificação errônea de que não tenho conexão com a internet  que impossibilita a publicação.
![Screenshot_20230919-113439](https://github.com/filipedeschamps/tabnews.com.br/assets/19830027/a553090e-c5c7-4487-b4e1-15cdb1e9b9e7)

**Comment by RadioactivePlays** [comment]
> Não encontrei nenhum erro na última hora.
> 
> Pode dar mais detalhes que ajudem a entender o que aconteceu?
> 
> O problema ainda permanece? Tentou de outro dispositivo?

Ainda persiste, troquei de rede e de dispositivo.

**Comment by aprendendofelipe** [comment]
> Ainda persiste, troquei de rede e de dispositivo.

A Cloudflare está bloqueando suas requisições POST. Aparentemente algo inseguro está sendo enviado nas suas requisições.

Você está usando uma rede confiável ou está em uma rede pública, talvez no aeroporto?

**Comment by RadioactivePlays** [comment]
Rede doméstica mesmo.

**Comment by RadioactivePlays** [comment]
A publicação é [essa](https://www.tabnews.com.br/thegr8wesley/como-compilar-um-kernel-linux-ajuda) .

**Comment by aprendendofelipe** [comment]
@RadioactivePlays, legal que você está conseguindo publicar 🎉

Então o problema é algo contido no texto que você está tentando publicar.

1. Por favor, não esqueça de excluir o comentário de teste antes que ele seja negativado.

2. Envie aqui no GitHub o texto da publicação que está dando erro. Não o texto que já está publicado, mas o texto que você não está conseguindo publicar. Se preferir não postar aqui, então analise o que pode estar contido no texto que possa estar sendo barrado pela Cloudflare. Provavelmente algum comando no meio do texto.

**Comment by RadioactivePlays** [comment]
Ah ok, o texto é o seguinte:

> Muito obrigado pela resposta. Em relação ao item 4 da criação de kernels para dispositivos Android, acho que existem métodos como o AnyKernel para facilitar. Minha maior dificuldade mesmo é em saber qual compiler/toolchain usar ou mesmo entender o conceito destes. Percebi que pode existir um gcc/clang do fabricante do meu aparelho (Motorola), do fabricante do chipset (Qualcomm), da própria ARM, e do AOSP. 
No guia de referência que você indicou, o link para a toolchain AOSP fornecido cai em uma página que indica que o android abandonou o gcc em favor do LLVM, que eu creio que seja o clang.
Ao executar um cat /proc/version no meu dispositivo, mostra que foi utilizado o clang v11.02, seria necessariamente essa a versão que eu teria que utilizar no processo e como obtê-la?

**Comment by aprendendofelipe** [comment]
A Cloudflare está bloqueando por causa do `/proc/version`

Uma maneira de contornar é usar `&#47;` no lugar de `/`, ou seja, `&#47;proc&#47;version;`. Isso vai renderizar corretamente como `/proc/version`.

**Comment by RadioactivePlays** [comment]
Finalmente, enviado. Era isso mesmo, obrigado pelo retorno. Isso é  um bug ou é intencional🤔? Devo fechar esse issue?

**Comment by RadioactivePlays** [comment]
Aparentemente eu devia ter colocado o texto que contém os caracteres formatado como código...

**Comment by aprendendofelipe** [comment]
O pior é que está bloqueando mesmo usando ``` ` ``` ou `<code>`.

> Isso é um bug ou é intencional🤔?

Talvez seja um excesso de zelo pela Cloudflare, mas não acho que vale a pena desativar a regra que está bloqueando isso, pois não sabemos o que mais ela bloqueia.

> Devo fechar esse issue?

Vou fechar essa porque já abri uma específica para melhorar a mensagem de erro quando o bloqueio é pela Cloudflare. 🤝

@RadioactivePlays, muito obrigado por reportar e por ajudar a descobrir o que estava acontecendo! 💪
