### ISSUE TITLE
Informações do Tooltip do BarChart na página `/status` inlegível no tema escuro

### ISSUE THREAD

**Issue by Poveii** [filipedeschamps/tabnews.com.br#1520]
## Problema

Estava navegando pelo Tabnews e fui na página de status para ver como estava os números de novos cadastros e publicações, enfim, eu acabei vendo que no tema escuro as informações do Tooltip não estão legíveis. Aqui embaixo eu fiz até um comparativo:

Tema claro:
![Screenshot from 2023-09-27 09-58-40](https://github.com/filipedeschamps/tabnews.com.br/assets/79858234/f24ab9ec-c522-4992-ad15-09fbf4a5268c)

Tema escuro:
![Screenshot from 2023-09-27 09-58-45](https://github.com/filipedeschamps/tabnews.com.br/assets/79858234/78036b64-3e63-4169-9833-91f4c73274f1)

Sendo que até continua a mesma cor de fundo, a única coisa que muda é a cor da fonte da data que é o maior problema, ao meu ver.

## Solução (???)

Bem, eu dei uma pesquisada no Google sobre o pacote `recharts` e o componente [Tooltip](https://recharts.org/en-US/api/Tooltip), e encontrei que ele pode ser personalizado pelo React inline style, eu posso até implementar mas não entendi muito bem como funciona a troca de tema do tabnews. Mas de qualquer forma, já uma luz para quem for implementar.

**Comment by aprendendofelipe** [comment]
@Poveii, obrigado por reportar! 💪

O problema foi resolvido com o PR #1521 👍
