### ISSUE TITLE
[ Sugestão ] Pop-up de explicação do que são as TabCoin e TabCash.

### ISSUE THREAD

**Issue by DouglasD18** [filipedeschamps/tabnews.com.br#1522]
Poderia abrir um Pop-up para o usuário quando ele clicasse no determinado ícone explicando o que ele é e como conseguir mais.

**Comment by Poveii** [comment]
Eu vejo que isso poderia ser implementado ao **FAQ**, ao invés de abrir pop-up explicando as coisas. Nem o Tabnews e o Github (que a gente usa o design system dele) tem modais assim, eu só vi alguns de **confirmação** de algo, tipo quando você quer arquivar ou privar um repositório.

Podemos implementar a issue com essa ideia: #1380

**Comment by Rafatcb** [comment]
Douglas, muito obrigado pela sugestão! 

Tooltips não são um bom caminho para "educar" o usuário sobre algo tão essencial, e a ideia do @Poveii, apesar de ser um bom primeiro passo, ainda não atenderia a demanda total, pois o usuário precisaria passar pelo processo de descoberta do FAQ.

Então, como teremos o FAQ em breve e surgiu uma ótima sugestão recentemente (https://github.com/filipedeschamps/tabnews.com.br/issues/1575) que parece que solucionará o problema daqui, vou deixar esta como dupllicada da outra, ok? A sugestão é sobre um "tour" para novos usuários, assim o processo de descoberta ocorre naturalmente, e o usuário poderá aprender sobre TabCoins, TabCash, os votos e outros aspectos importantes do TabNews.
