### ISSUE TITLE
[Melhoria  / Bug ] Botão Salvar do edit-profile sem redirecionamento

### ISSUE THREAD

**Issue by espezzialy** [filipedeschamps/tabnews.com.br#1524]
**Problema:** Após editar o perfil, ao clicar em salvar ele chama corretamente a rota e salva, porém o usuário mantém-se na mesma página;

![image](https://github.com/filipedeschamps/tabnews.com.br/assets/55398495/e693ee91-a254-4eeb-a17a-c557fbd0b9f0)

Isso para o usuário pode dar ambiguidade de fluxo, visto que não há um toast ou até mesmo um redirecionamento apontando que foi salvo

Sugestão 1:

Redirecionamento de salvamenmto, após clicar em salvar e a rota ter recebido 200, abrir um modal confirmando que o perfil foi editado

Isso pode ser feito no arquivo: filipedeschamps/tabnews.com.br/pages/perfil/index.public.js

` <FormControl>
          <FormControl.Label visuallyHidden>Salvar</FormControl.Label>
          <ButtonWithLoader
            variant="primary"
            size="large"
            type="submit"
            sx={{ width: '100%' }}
            aria-label="Salvar"
            isLoading={isLoading}>
            onClick={() => router.push('/')}
            Salvar
          </ButtonWithLoader>
        </FormControl>`

Dentro desse componente chamar  o rouiter.push se de fato foi salvo

Sugestão 2: 

Criar um modal para após clicar em salvar, se retorna 200 abre um modal de confirmação, se retorna erro um modal de erro.

**Comment by aprendendofelipe** [comment]
Fala @espezzialy, obrigado pela sugestão! 💪

Uma opção simples é usar o [Flash](https://primer.style/react/Flash) do Primer com uma mensagem que informe que foi salvo com sucesso:

![image](https://github.com/filipedeschamps/tabnews.com.br/assets/77860630/50847b1a-c0de-4fdb-b131-8093c6ad8589)

Ou, se for para redirecionar, acho que o ideal seria ir para a página do perfil do usuário, mas primeiro a gente precisa usar alguma estratégia de interface otimista, pois senão na primeira navegação o usuário poderá ver o conteúdo antigo por causa do cache.

**Comment by iurynogueira** [comment]
Ola! Sou novo por aqui e queria contribuir, posso implementar essa task?

**Comment by aprendendofelipe** [comment]
> Ola! Sou novo por aqui e queria contribuir, posso implementar essa task?

Seja bem vindo @iurynogueira! Nem precisa pedir ou avisar 😉👍

**Comment by kaique-soares** [comment]
Fala @espezzialy :handshake: 

Ocorreu o merge as seguintes PRs:
- #1545
- #1548

Acho que esta issue pode ser fechada, não?

**Comment by Rafatcb** [comment]
@aprendendofelipe pode fechar aqui?

**Comment by aprendendofelipe** [comment]
Apesar da sugestão original não ter sido implementada, acredito que o objetivo principal tenha sido atingido com feedback ao salvar o perfil.

Vou fechar a issue, mas podem comentar aqui mesmo sobre qualquer coisa que queiram adicionar ao assunto e, se for necessário, a gente reabre a issue 🤝
