### ISSUE TITLE
Vamos preparar o repositório para abertura da Milestone de Revenue Share?

### ISSUE THREAD

**Issue by filipedeschamps** [filipedeschamps/tabnews.com.br#1526]
Eu proponho o que foi feito para a abertura da primeira Milestone do projeto, pelo que me lembro:

1. Fechar todas as **Issues**, seja por inatividade ou porque não será atuado no curto prazo.
2. Avaliar todos os **Pull Requests** para entender de vamos fazer o merge ou fechar.
3. Para ambos **Issues** e **Pull Requests**, caso sejam fechados, considerar se é o caso de adicionar a tag de repescagem.

Daria para trabalhar sem fazer este tipo de manutenção, mas acredito que conseguiremos lidar melhor e com **total foco** no trabalho que precisa ser feito para essa Milestone que é **super sensível**. Fora que, para quem é novo no repositório, ver **`230`** Issues e **`36`** Pull Requests abertos é desanimador e passa um sinal que há uma alta chance de sua contribuição ficar pendurada. Vamos mudar isso a partir de hoje? 🤝

**Comment by ZCErik** [comment]
O melhor dia para mudar isso foi ontem, o segundo melhor dia é hoje!

Eu topo! E confesso que quando olhei pela primeira vez senti um pouco desanimado mesmo, mas vou olhar de novo e ver como posso contribuir!

**Comment by aprendendofelipe** [comment]
> 3\. Para ambos **Issues** e **Pull Requests**, caso sejam fechados, considerar se é o caso de adicionar a tag de repescagem.

### Sobre PRs

Penso que a tag de repescagem é uma boa para alguns PRs que não estão associados com nenhuma issue, mas que ainda devem ter alguma implementação baseada no trabalho atual. Mas isso deveria se exceção, pois é muito melhor uma issue documentando o caso e direcionando para o PR, e nesse caso a tag não é mais necessária.

Eu optei por deixar esses PRs como draft, mas é um *trade-off*, pois fica mais fácil desses casos serem encontrados por novos contribuidores, mas também pode dar essa impressão de que uma nova contribuição pode ficar pendurada.

Acho que falta uma documentação de como contribuir, onde podemos estipular um prazo para que os PRs permaneçam com *status draft*, para então fechar e colocar a tag de repescagem (se for o caso).

Só não acho necessária a tag de repescagem para os PRs que tem issues relacionadas, pois quem for dar encaminhamento na issue já tem essa informação documentada.

### Sobre issues

Não acho legal fechar issues que ainda precisem de algum encaminhamento, mesmo que ninguém esteja lidando com elas no momento, a não ser que seja algo que não precisamos de nenhuma contribuição relacionada nem no médio prazo. Pelo contrário, acho que precisamos estimular o encaminhamento delas, principalmente das prioritárias.

Já sobre as issues que tratam de ideias que não vingaram ou que realmente não vamos lidar nem no médio prazo, então podemos fechar. E nesses casos não há necessidade de tag de repescagem. Se for o caso de possível repescagem, penso que seja melhor deixar a issue aberta, do que fechar e serem criadas novas duplicadas de tempos em tempos.

**Comment by natanael-b** [comment]
Sério? Me deram ban me fazendo perder TabCoins e as TabCash que me custaram várias horas produzindo conteúdo sem NENHUMA  justificativa ou tentativa de contato, mancada isso e eu não fui o único #1538

**Comment by Rafatcb** [comment]
<sup>Última atualização: 15/12/2023 18:55, último issue antigo fechado: #1398 e último PR antigo fechado: #1336</sup>

Agora temos *123 issues* (vs 230) e *11 pull requests* (vs 36) abertos :tada:

## Issues

Conseguimos fazer uma boa limpa, *foram 111 issues antigos fechados* (contando apenas os criados antes deste). Vale mencionar que alguns issues novos também foram fechados, mas as listas abaixo contemplam apenas os antigos.

Para termos uma boa imagem sobre o progresso da organização, realizei um filtro na busca do GitHub verificando apenas issues criados antes e fechados depois da criação deste, ordenando pela data de atualização mais recente: [`is:issue closed:>=2023-10-03 created:<=2023-10-03 sort:updated-desc`](https://github.com/filipedeschamps/tabnews.com.br/issues?q=is%3Aissue+closed%3A%3E%3D2023-10-03+created%3A%3C%3D2023-10-03+sort%3Aupdated-desc).

Talvez algum issue abaixo esteja classificado na categoria errada, mas a maioria está na categoria correta.


### Resolvidos/Implementados

1. https://github.com/filipedeschamps/tabnews.com.br/issues/788
2. https://github.com/filipedeschamps/tabnews.com.br/issues/1414
3. https://github.com/filipedeschamps/tabnews.com.br/issues/1378
4. https://github.com/filipedeschamps/tabnews.com.br/issues/1422
5. https://github.com/filipedeschamps/tabnews.com.br/issues/1524

### Já resolvidos anteriormente

Esses já haviam sido resolvidos, mas provavelmente ficaram abertos por esquecimento.

1. https://github.com/filipedeschamps/tabnews.com.br/issues/686
2. https://github.com/filipedeschamps/tabnews.com.br/issues/958
3. https://github.com/filipedeschamps/tabnews.com.br/issues/927
4. https://github.com/filipedeschamps/tabnews.com.br/issues/1124
5. https://github.com/filipedeschamps/tabnews.com.br/issues/879 (talvez possa ser considerado duplicado de #1156)
6. https://github.com/filipedeschamps/tabnews.com.br/issues/915
7. https://github.com/filipedeschamps/tabnews.com.br/issues/833
8. https://github.com/filipedeschamps/tabnews.com.br/issues/1127
9. https://github.com/filipedeschamps/tabnews.com.br/issues/1035
10. https://github.com/filipedeschamps/tabnews.com.br/issues/909
11. https://github.com/filipedeschamps/tabnews.com.br/issues/978
12. https://github.com/filipedeschamps/tabnews.com.br/issues/1194 (2 sugestões, 1 resolvida e 1 duplicada)
13. https://github.com/filipedeschamps/tabnews.com.br/issues/1208
14. https://github.com/filipedeschamps/tabnews.com.br/issues/979 (3 sugestões, 2 resolvidas e 1 duplicada)
15. https://github.com/filipedeschamps/tabnews.com.br/issues/987 (2 sugestões, 1 resolvida e 1 duplicada)
16. https://github.com/filipedeschamps/tabnews.com.br/issues/959
17. https://github.com/filipedeschamps/tabnews.com.br/issues/1166
18. https://github.com/filipedeschamps/tabnews.
com.br/issues/772
19. https://github.com/filipedeschamps/tabnews.com.br/issues/735
20. https://github.com/filipedeschamps/tabnews.com.br/issues/924
21. https://github.com/filipedeschamps/tabnews.com.br/issues/903
22. https://github.com/filipedeschamps/tabnews.com.br/issues/866
23. https://github.com/filipedeschamps/tabnews.com.br/issues/1424

### Duplicados

Os issues duplicados foram fechados para concentrar a discussão num único issue.

1. https://github.com/filipedeschamps/tabnews.com.br/issues/856 (resolvido)
2. https://github.com/filipedeschamps/tabnews.com.br/issues/790
3. https://github.com/filipedeschamps/tabnews.com.br/issues/967
4. https://github.com/filipedeschamps/tabnews.com.br/issues/798
5. https://github.com/filipedeschamps/tabnews.com.br/issues/793
6. https://github.com/filipedeschamps/tabnews.com.br/issues/1066
7. https://github.com/filipedeschamps/tabnews.com.br/issues/1456
8. https://github.com/filipedeschamps/tabnews.com.br/issues/762
9. https://github.com/filipedeschamps/tabnews.com.br/issues/935
10. https://github.com/filipedeschamps/tabnews.com.br/issues/993 (resolvido)
11. https://github.com/filipedeschamps/tabnews.com.br/issues/1371 (resolvido)
12. https://github.com/filipedeschamps/tabnews.com.br/issues/1245
13. https://github.com/filipedeschamps/tabnews.com.br/issues/1004
14. https://github.com/filipedeschamps/tabnews.com.br/issues/1057
15. https://github.com/filipedeschamps/tabnews.com.br/issues/1056
16. https://github.com/filipedeschamps/tabnews.com.br/issues/970
17. https://github.com/filipedeschamps/tabnews.com.br/issues/1209
18. https://github.com/filipedeschamps/tabnews.com.br/issues/1016
19. https://github.com/filipedeschamps/tabnews.com.br/issues/752
20. https://github.com/filipedeschamps/tabnews.com.br/issues/990
21. https://github.com/filipedeschamps/tabnews.com.br/issues/612
22. https://github.com/filipedeschamps/tabnews.com.br/issues/899
23. https://github.com/filipedeschamps/tabnews.com.br/issues/995
24. https://github.com/filipedeschamps/tabnews.com.br/issues/1017
25. https://github.com/filipedeschamps/tabnews.com.br/issues/1007
26. https://github.com/filipedeschamps/tabnews.com.br/issues/998
27. https://github.com/filipedeschamps/tabnews.com.br/issues/753
28. https://github.com/filipedeschamps/tabnews.com.br/issues/878
29. https://github.com/filipedeschamps/tabnews.com.br/issues/920
30. https://github.com/filipedeschamps/tabnews.com.br/issues/1000
31. https://github.com/filipedeschamps/tabnews.com.br/issues/1116
32. https://github.com/filipedeschamps/tabnews.com.br/issues/614
33. https://github.com/filipedeschamps/tabnews.com.br/issues/940
34. https://github.com/filipedeschamps/tabnews.com.br/issues/991
35. https://github.com/filipedeschamps/tabnews.com.br/issues/1086
36. https://github.com/filipedeschamps/tabnews.com.br/issues/1478
37. https://github.com/filipedeschamps/tabnews.com.br/issues/1026
38. https://github.com/filipedeschamps/tabnews.com.br/issues/980
39. https://github.com/filipedeschamps/tabnews.com.br/issues/1462
40. https://github.com/filipedeschamps/tabnews.com.br/issues/1040
41. https://github.com/filipedeschamps/tabnews.com.br/issues/1054
42. https://github.com/filipedeschamps/tabnews.com.br/issues/1091
43. https://github.com/filipedeschamps/tabnews.com.br/issues/1079
44. https://github.com/filipedeschamps/tabnews.com.br/issues/1320
45. https://github.com/filipedeschamps/tabnews.com.br/issues/1109
46. https://github.com/filipedeschamps/tabnews.com.br/issues/885
47. https://github.com/filipedeschamps/tabnews.com.br/issues/1011
48. https://github.com/filipedeschamps/tabnews.com.br/issues/1046
49. https://github.com/filipedeschamps/tabnews.com.br/issues/1398

### Não planejado

1. https://github.com/filipedeschamps/tabnews.com.br/issues/598
2. https://github.com/filipedeschamps/tabnews.com.br/issues/949
3. https://github.com/filipedeschamps/tabnews.com.br/issues/986
4. https://github.com/filipedeschamps/tabnews.com.br/issues/913 (não tenho certeza)
5. https://github.com/filipedeschamps/tabnews.com.br/issues/942
6. https://github.com/filipedeschamps/tabnews.com.br/issues/1437
7. https://github.com/filipedeschamps/tabnews.com.br/issues/606
8. https://github.com/filipedeschamps/tabnews.com.br/issues/1261
9. https://github.com/filipedeschamps/tabnews.com.br/issues/1222
10. https://github.com/filipedeschamps/tabnews.com.br/issues/904 (futuramente)
11. https://github.com/filipedeschamps/tabnews.com.br/issues/876
12. https://github.com/filipedeschamps/tabnews.com.br/issues/908
13. https://github.com/filipedeschamps/tabnews.com.br/issues/791
14. https://github.com/filipedeschamps/tabnews.com.br/issues/1032
15. https://github.com/filipedeschamps/tabnews.com.br/issues/999
16. https://github.com/filipedeschamps/tabnews.com.br/issues/1503
17. https://github.com/filipedeschamps/tabnews.com.br/issues/1135
18. https://github.com/filipedeschamps/tabnews.com.br/issues/1167
19. https://github.com/filipedeschamps/tabnews.com.br/issues/1107
20. https://github.com/filipedeschamps/tabnews.com.br/issues/1118

### Off-topic/dúvidas

1. https://github.com/filipedeschamps/tabnews.com.br/issues/887
2. https://github.com/filipedeschamps/tabnews.com.br/issues/695
3. https://github.com/filipedeschamps/tabnews.com.br/issues/1129
4. https://github.com/filipedeschamps/tabnews.com.br/issues/1097
5. https://github.com/filipedeschamps/tabnews.com.br/issues/1015
6. https://github.com/filipedeschamps/tabnews.com.br/issues/886
7. https://github.com/filipedeschamps/tabnews.com.br/issues/932
8. https://github.com/filipedeschamps/tabnews.com.br/issues/554
9. https://github.com/filipedeschamps/tabnews.com.br/issues/822
10. https://github.com/filipedeschamps/tabnews.com.br/issues/918
11. https://github.com/filipedeschamps/tabnews.com.br/issues/1197

## Pull Requests

Do lado dos PRs, *foram 26 PRs antigos fechados*. Acredito que o peso dos PRs abertos causa uma impressão pior em quem vai colaborar do que a quantidade de issues abertos, pois a pessoa pode pensar que a contribuição dela ficará pendurada, sem motivo para não ter sido mergeada.

Usei o mesmo tipo de filtro para os PRs: [`is:pr closed:>=2023-10-03 created:<=2023-10-03 sort:updated-desc`](https://github.com/filipedeschamps/tabnews.com.br/pulls?q=is%3Apr+closed%3A%3E%3D2023-10-03+created%3A%3C%3D2023-10-03+sort%3Aupdated-desc).

### Implementado

1. https://github.com/filipedeschamps/tabnews.com.br/pull/1525

### Fechados

Os PRs foram fechados por motivos diferentes, recomendo abrir e ler o comentário realizado no momento de fechamento para entender cada um. Alguns foram implementados em outro PR, outros foram "abandonados", outros "postergados" etc. Assim como fiz na lista de issues, os PRs abaixo contém apenas os antigos.

1. https://github.com/filipedeschamps/tabnews.com.br/pull/1190
2. https://github.com/filipedeschamps/tabnews.com.br/pull/1481
3. https://github.com/filipedeschamps/tabnews.com.br/pull/1476
4. https://github.com/filipedeschamps/tabnews.com.br/pull/1455
5. https://github.com/filipedeschamps/tabnews.com.br/pull/1408
6. https://github.com/filipedeschamps/tabnews.com.br/pull/1428
7. https://github.com/filipedeschamps/tabnews.com.br/pull/1413
8. https://github.com/filipedeschamps/tabnews.com.br/pull/557
9. https://github.com/filipedeschamps/tabnews.com.br/pull/599
10. https://github.com/filipedeschamps/tabnews.com.br/pull/799
11. https://github.com/filipedeschamps/tabnews.com.br/pull/947
12. https://github.com/filipedeschamps/tabnews.com.br/pull/982
13. https://github.com/filipedeschamps/tabnews.com.br/pull/984
14. https://github.com/filipedeschamps/tabnews.com.br/pull/996
15. https://github.com/filipedeschamps/tabnews.com.br/pull/1202
16. https://github.com/filipedeschamps/tabnews.com.br/pull/1165
17. https://github.com/filipedeschamps/tabnews.com.br/pull/1295
18. https://github.com/filipedeschamps/tabnews.com.br/pull/1295
19. https://github.com/filipedeschamps/tabnews.com.br/pull/1433
20. https://github.com/filipedeschamps/tabnews.com.br/pull/1195
21. https://github.com/filipedeschamps/tabnews.com.br/pull/1279
22. https://github.com/filipedeschamps/tabnews.com.br/pull/1123
23. https://github.com/filipedeschamps/tabnews.com.br/pull/1480
24. https://github.com/filipedeschamps/tabnews.com.br/pull/797
25. https://github.com/filipedeschamps/tabnews.com.br/pull/1336

**Comment by Rafatcb** [comment]
Acredito que os seguintes issues estejam no caminho para serem fechados também, mas podem receber mais opiniões/reações/respostas nos comentários para chegar num consenso maior:

1. https://github.com/filipedeschamps/tabnews.com.br/issues/951
2. https://github.com/filipedeschamps/tabnews.com.br/issues/994
3. https://github.com/filipedeschamps/tabnews.com.br/issues/1013
4. https://github.com/filipedeschamps/tabnews.com.br/issues/1071
5. https://github.com/filipedeschamps/tabnews.com.br/issues/1076
6. https://github.com/filipedeschamps/tabnews.com.br/issues/1269
7. https://github.com/filipedeschamps/tabnews.com.br/issues/1522
8. https://github.com/filipedeschamps/tabnews.com.br/issues/1529

**Comment by filipedeschamps** [comment]
> Agora temos 121 issues (vs 230) e 11 pull requests (vs 36) abertos 🎉

Que trabalho absuuuuuurdo de tão sensacionaaaaaaaaaal 😍 🎉 🎉 🎉

**Comment by Rafatcb** [comment]
Pessoal, fiz a última limpa do ano hoje e estamos numa situação bem melhor. Exatamente agora, são **99 issues** abertos e **6 PRs**, sendo que todos os PRs estão em andamento com as revisões e implementações conforme revisões.

Quero agradecer a todos que ajudaram nesse processo, desde o @aprendendofelipe que fechou vários issues e ajudou a decidir sempre que eu tive dúvida, até outros participantes do repositório que deixaram suas opiniões nos issues sobre a utilidade ou não de um novo recurso a ser implementado, por exemplo.

E também agradecer a todos que abriram PR, pois mesmo com os PRs sendo fechados, a revisão do código e a sugestão de implementação trouxeram informações que deverão ser consideradas numa implementação num novo PR.

Além disso, os issues e PRs que estão abertos foram organizados com [labels](https://github.com/filipedeschamps/tabnews.com.br/labels) para facilitar a busca e identificação do assunto na lista de issues/PRs.

Por último, estou fechando esse issue como resolvido 🎉 🎉. Vamos começar o ano novo com o pé direito no repositório 😁

**Comment by filipedeschamps** [comment]
> Vamos começar o ano novo com o pé direito no repositório 😁

Vamos com certeza meu caro!! E isso também ajuda muito naquela ideia do repositório do TabNews se tornar o melhor local para pessoas treinarem contribuições no mundo open source, e com isso acabar fortalecendo de pouco em pouco o próprio projeto 💪  Sinto que `2024` vai ser um ano bem diferente 🤝 

Parabéns novamente por todo trabalho!! 😍
