### ISSUE TITLE
[Bug] Link externo sem protocolo na url navega para uma rota inexistente da aplicação

### ISSUE THREAD

**Issue by ikaikyy** [filipedeschamps/tabnews.com.br#1527]
Estava usando o TabNews e notei um comportamento estranho, ao clicar em algum link externo, por exemplo "www.google.com", a aplicação entende o link como uma rota propria e navega para https://www.tabnews.com.br/www.google.com, o link externo só é aberto caso o protocolo da url esteja presente, como em "https://www.google.com".

**Comment by aprendendofelipe** [comment]
Fala @ikaikyy, não vejo como um bug do TabNews, mas um engano de quem inseriu a URL de forma incompleta.

Se um protocolo não é informado, então o navegador pode entender que é uma URL relativa e não absoluta.

Se fosse o caso, o GitHub teria o mesmo bug. Na verdade o renderizador de markdown do TabNews até tentar ajudar mais que o do GitHub ao tentar "adivinhar" o protocolo e inserir `http://` no atributo `href` da tag `a`:

Como o link foi inserido | TabNews | GitHub
-- | :--: | -- 
`[www.google.com](www.google.com)` |❌|❌ [www.google.com](www.google.com)
`<a href="www.google.com">www.google.com</a>` |insere `http`|❌ <a href="www.google.com">www.google.com</a> 
`[www.google.com](https://www.google.com)` |✔|✔ [www.google.com](https://www.google.com) 
`<a href="https://www.google.com">www.google.com</a>`  |✔|✔ <a href="https://www.google.com">www.google.com</a>
`https://www.google.com` |✔|✔ https://www.google.com 
`www.google.com`  |✔|✔ www.google.com 


Vou fechar a issue, mas fique à vontade para reabrir se achar necessário. Combinado? 🤝
