### ISSUE TITLE
[ Sugestão / Feature ] Botão para navegar entre publicações

### ISSUE THREAD

**Issue by ikaikyy** [filipedeschamps/tabnews.com.br#1530]
## Descrição
Algo que vem me incomodando muito quando estou usando o TabNews é o fato de, ao terminar de ler uma publicação e seus comentários, tenho que voltar à página inicial para poder acessar outro conteúdo, comportamento na maioria das vezes frustrante, pois quebra a imersão do usuário.

Sinto que toda vez que eu quero procurar algum conteúdo relevante, tenho que ler vários títulos tentando julgar se é ou não relevante, e caso não seja, novamente tenho que voltar à página inicial e repetir o processo.

## Motivação
Basicamente toda rede social atualmente tem algum sistema que permita consumo contínuo aos seus conteúdos, sem quebrar a imersão do usuário, fazendo até com que muitos se viciem e/ou nem vejam o tempo passar. 

Dá para tirar como exemplo o TikTok com seu sistema de scroll, ou até mesmo o Twitter que mostra tweets relacionados ao post e/ou relevantes ao usuário. Como o TabNews ainda não tem um algoritmo que possa recomendar posts ao usuário, a melhor solução creio eu seria a simples implementação de um botão que pulasse para a próxima publicação ou voltasse para a anterior.

## Pontos para discussão
- Em qual lugar da página colocar os botões?
- Botões são realmente a melhor solução?
- Navegar apenas para publicações que o usuário ainda não viu e/ou ainda não gastou TabCoins? Ou navegar livremente entre as publicações?

## Sugestão
Minha sugestão seria adicionar os botões no Header da aplicação, e no meio deles implementar um link com o nome do dono do post, e ao lado a posição ordinal do post em relação aos posts desse usuário, algo como:

### <-- Usuário #xyz -->

**Comment by Rafatcb** [comment]
Seguindo com o comentário do @Poveii, que a comunidade concordou mais, estou fechando este issue para organizar o repositório. Obrigado pela sugestão, @ikaikyy!
