### ISSUE TITLE
AJUDA! Ao tentar entrar na minha conta do TabNews, deu erro!

### ISSUE THREAD

**Issue by gelzinn** [filipedeschamps/tabnews.com.br#1534]
# Ao tentar entrar na minha conta do TabNews, deu erro!

O que eu faço? Não fiz nada na minha conta para acontecer isso.

![image](https://github.com/filipedeschamps/tabnews.com.br/assets/60621494/a374be93-5623-45fb-82a5-8dd40ae01ad4)

**Comment by aprendendofelipe** [comment]
Olá @gelzinn, se o usuário está sem a permissão para criar sessão, significa que a conta foi banida por violação dos termos de uso do TabNews.

Se ainda restar dúvidas mesmo após a leitura dos [termos](https://www.tabnews.com.br/termos-de-uso), por respeito ao sigilo de dados de todos envolvidos, sugiro que sua dúvida seja sanada via email para `contato@tabnews.com.br`, onde o remetente deve ser o mesmo email do usuário que foi banido. Combinado? 🤝

Vou fechar a issue por não se tratar de um bug

**Comment by gelzinn** [comment]
Mandei o email. Se for possível quero a resposta o quanto antes.

**Comment by gelzinn** [comment]
Ok @aprendendofelipe, mandei o email. Se for possível quero a resposta o quanto antes. Realmente não faz sentido nenhum pra mim.

Inclusive, sugiro que mudem a mensagem para facilitar o entendimento do usuário. Não faz sentido nenhum mostrar:
> Verifique se este usuário possui a feature "create:session"
