### ISSUE TITLE
Erro ao realizar login

### ISSUE THREAD

**Issue by rafatrinity** [filipedeschamps/tabnews.com.br#1536]
![Screenshot_2023-10-17-15-33-30-237_com.android.chrome-edit.jpg](https://github.com/filipedeschamps/tabnews.com.br/assets/20962670/fcbe5534-e235-4c3b-82c5-3359eab49137)

Observação: e-mail e senha estão corretos, testei isso em 3 navegadores e em 2 dispositivos diferentes, com rede móvel e com rede cabeada.

**Comment by aprendendofelipe** [comment]
Olá @rafatrinity, se o usuário está sem a permissão para criar sessão, significa que a conta foi banida por violação dos termos de uso do TabNews.

Se ainda restar dúvidas mesmo após a leitura dos [termos](https://www.tabnews.com.br/termos-de-uso), por respeito ao sigilo de dados de todos envolvidos, sugiro que sua dúvida seja sanada via email para contato@tabnews.com.br, onde o remetente deve ser o mesmo email do usuário que foi banido. Combinado? 🤝

Vou fechar a issue por não se tratar de um bug

**Comment by rafatrinity** [comment]
Agradeço pelo feedback

Em qua., 18 de out. de 2023 08:13, Felipe Barso ***@***.***>
escreveu:
