### ISSUE TITLE
[ Sugestão / Feature ] Contagem de visualizações nos posts

### ISSUE THREAD

**Issue by salimcabus** [filipedeschamps/tabnews.com.br#1537]
Acho que seria interessante um contador de visualizações em cada post influenciando também nos posts relevantes ;)

**Comment by Rafatcb** [comment]
É algo legal. Já foi sugerido aqui: https://github.com/filipedeschamps/tabnews.com.br/issues/1115. Acho melhor concentrar a discussão lá.

**Comment by aprendendofelipe** [comment]
Olá @salimcabus, obrigado pela sugestão! 💪

Reafirmo o que o @Rafatcb falou, e vou fechar essa como duplicada. Combinado? 🤝
