### ISSUE TITLE
Porque fui banido?

### ISSUE THREAD

**Issue by natanael-b** [filipedeschamps/tabnews.com.br#1538]
Tentei fazer login e recebi o seguinte erro:

> Você não possui permissão para fazer login. Verifique se este usuário possui a feature "create:session".

Então descobri que recebi um "nuke":

Minha conta:

 - https://www.tabnews.com.br/natanael755

Não recebi nenhum email e nenhuma forma de contato informando que regra eu violei, perdi todas as minhas publicações sem nunca ter recebido nenhuma flag ou aviso

**Comment by aprendendofelipe** [comment]
Olá @natanael-b, por respeito ao sigilo de dados, sugiro que sua dúvida seja sanada via email para [contato@tabnews.com.br](mailto:contato@tabnews.com.br), onde o remetente deve ser o mesmo email do usuário que busca a informação. Combinado? 🤝

**Comment by natanael-b** [comment]
Entrei em contato mas agora não adianta mais já perdi todos os meus post, horas produzindo conteúdo, as TabCash e afins
