### ISSUE TITLE
feat: Perfil do usuário

### ISSUE THREAD

**Issue by iget-master** [filipedeschamps/tabnews.com.br#1539]
Sinto falta no tabnews de uma forma de ver quem aquela pessoa que está escrevendo é, qual sua contribuição pra comunidade tabnews, uma forma de ver sua credibilidade.

Para resolver isso, acho que seria interessante adicionar mais informações a pagina de perfil por exemplo:

* Links para redes sociais (linkdn, github, stackoverfkow, ...)
* Biografia
* Idade
* localização

Além desses dados preenchidos pelo usuário, poderia exibir as publicações de maior relevância do usuario, em uma tab do lado do conteúdo recente.

Acham essa funcionalidade útil?

<a href="https://md-poll.vercel.app/polls/9d4ca19c-7dce-452d-a895-64c93ba8607f/vote?option=0&close" target="_blank">
  <img src="https://md-poll.vercel.app/api/polls/9d4ca19c-7dce-452d-a895-64c93ba8607f/options/0/img" alt="Sim"/>
</a>
<br/>
<a href="https://md-poll.vercel.app/polls/9d4ca19c-7dce-452d-a895-64c93ba8607f/vote?option=1&close" target="_blank">
  <img src="https://md-poll.vercel.app/api/polls/9d4ca19c-7dce-452d-a895-64c93ba8607f/options/1/img" alt="Não"/>
</a>
<br/>
<small>Click on the option you want to vote.</small>
<br/>
<small>Enquete criada com o <a href="https://md-poll.vercel.app">md-poll</a>!

**Comment by iget-master** [comment]
> Olá @iget-master, interessante sua sugestão e também o projeto de enquetes :handshake: 
> 
> Bom, logo após o meu voto o resultado ficou assim:
> ![image](https://github.com/filipedeschamps/tabnews.com.br/assets/57193392/a7efd1bc-b007-4bdc-9e3d-4eeb06229441)
> 
> Eu votei _Não_ porque acredito que temos formas mais simples de resolver o problema (no tocante a parte técnica) e abaixo vou explicar melhor, veja se faz sentido:
> 
> - Dado o contexto atual do projeto, em que estamos mirando a #1490. Também veja a issue #1526
> 
> Penso que poderíamos resolve o problema utilizando o recurso de **Descrição** presente na página de edição do perfil. É um recurso com grande pontencial de entrega para o usuário já que é um campo que aceita markdown:
> 
> ![image](https://github.com/filipedeschamps/tabnews.com.br/assets/57193392/0ca0df0f-921f-4f04-ba1d-e96a1b88ddf6)
> 
> E acredito que tem um limite suficiente para incluir links úteis e uma **descrição mais elaborada**:
> 
> https://github.com/filipedeschamps/tabnews.com.br/blob/85d6e91e61bd5b217ff555fc4a6de741a8ced504/infra/migrations/1688768453152_alter-table-users-add-description.js#L5
> 
> Concluindo, penso que podemos resolver o problema com o que já temos sem encostar em código e que talvez o que esteja faltando seja uma divulgação melhor do recurso, com exemplos simples e práticos por meio de publicações dentro do próprio TabNews.
> 
> Um exemplo de utilização para links úteis é o perfil do @filipedeschamps, que neste exato momento está assim:
> ![image](https://github.com/filipedeschamps/tabnews.com.br/assets/57193392/e5a56829-f613-45f4-b7da-8afdd64a0afd)
> 
> O que na minha visão, confirma o que eu escrevi acima sobre ser um recurso com grande pontencial de entrega para o usuário.
> 
> @iget-master faz sentido?

Para ser sincero, eu não havia percebido que ja existe esse campo em markdown.

Sendo assim, acho que podemos fechar esse issue por ser um feature duplicado.

**Comment by aprendendofelipe** [comment]
@iget-master, obrigado pela sugestão! 💪

A descrição no perfil dos usuários já foi implementada de maneira preliminar no PR #1470, e isso foi anunciado em uma [publicação no TabNews](https://www.tabnews.com.br/FelipeBarso/tabnews-6-milhoes-de-visualizacoes-e-muita-novidade).

Ainda faltam ajustes, mas é melhor centralizar a conversa na issue que já está com mais interações (#1466).

Vou fechar essa duplicada. 🤝
