### ISSUE TITLE
MODEL:CONTENT:CREDIT_OR_DEBIT_TABCOINS:NEGATIVE_USER_EARNINGS

### ISSUE THREAD

**Issue by samsepiol1** [filipedeschamps/tabnews.com.br#1540]
![inspecior](https://github.com/filipedeschamps/tabnews.com.br/assets/49918079/a2eb36e9-69a9-4dbd-ba1c-e752bf183020)

Olá a todos, boa tarde. Criei uma nova conta no TabNews, visto que a minha anterior foi excluída, e comecei a repostar artigos antigos que eram da outra conta. Em uma das publicações, recebi uma avaliação negativa, o que acabou me impedindo de comentar ou publicar novos conteúdos. Pelo que verifiquei esse código que aparece é referente ao error_id.

Interessantemente, consegui publicar tanto o comentário quanto o post alguns longos minutos depois

**Comment by samsepiol1** [comment]
A regra de negócio que faz essa verificação se encontra na pasta dos models em content.js

/[models](https://github.com/filipedeschamps/tabnews.com.br/tree/main/models)
/content.js

**Comment by aprendendofelipe** [comment]
No seu caso havia apenas um conteúdo negativado e, se entendi direito, logo foi positivado, então não foi necessário apagar. É isso?

Se a mensagem estivesse dizendo para apagar "certa publicação", poderia ter feito você excluí-la sem necessidade.

Imagina se alguém tem mais de um conteúdo negativado, e outros positivados, de forma que com a exclusão de qualquer um deles o saldo já seria suficiente para poder criar novas publicações. Se a gente listar os negativados, pode induzir a exclusão de todos, mas quem deveria decidir isso é o próprio autor. 

A mensagem é apenas para informar um autor de que ele deve revisar os seus conteúdos recentes. E dar mais uma oportunidade da pessoa procurar saber o que é esperado das publicações no TabNews, já que muitos ignoram o aviso que aparece antes da primeira publicação.

Não acho que devemos listar as publicações negativadas.

Já a mensagem do erro sempre pode ser melhorada. Inclusive direcionar para o FAQ quando ele for implementado 👍

- #1380
