### ISSUE TITLE
Problema de login [Iphone]

### ISSUE THREAD

**Issue by BlocodeGold** [filipedeschamps/tabnews.com.br#1544]
Eu uso iPhone 8 Plus IOS 16.7.2
E lá não existe opção de login de conta alguém ajuda ?

**Comment by aprendendofelipe** [comment]
Olá @BlocodeGold, deveria estar aparecendo o botão "Entrar" no "Header".

![image](https://github.com/filipedeschamps/tabnews.com.br/assets/77860630/de2c633a-e93c-47c3-8729-d41ac5be4dbd)

Você está usando a versão oficial do TabNews? Consegue enviar um print da tela?

**Comment by aprendendofelipe** [comment]
Parece que você está usando algum aplicativo de terceiros, daí teria que entrar em contato com o desenvolvedor dessa versão.

Enquanto isso, recomendo usar a versão oficial:

https://www.tabnews.com.br/

Vou fechar a issue por não se tratar de algo que possamos resolver 🤝

**Comment by BlocodeGold** [comment]
Ué vocês não tem aplicativo pra Mobile?

**Comment by aprendendofelipe** [comment]
Mobile existem os Apps desenvolvidos pela comunidade e que usam a API oficial 👍
