### ISSUE TITLE
[Sugestão/Feature] Seria interessante um Analytics

### ISSUE THREAD

**Issue by eletroswing** [filipedeschamps/tabnews.com.br#1547]
Talvez seria interessante uma forma de monitorar publicações no tabnews, com visualizações pelo  tempo, tabcoins ganhos e perdidos de uma publicação. Assim, os autores do tabnews poderiam fazer um tracking de seus posts, e onde poderiam melhorar com eles.
Acredito que todas as informações necessárias para isso já são salvas de alguma forma no db, só precisando fazer a implementação.

**Comment by aprendendofelipe** [comment]
@eletroswing, obrigado pela sugestão! 💪

Recomendo concentrarmos o debate na issue #717 que trata do mesmo assunto. 👍

Vou fechar essa como duplicidade. 🤝
