### ISSUE TITLE
[Sugestão / Feature] Favoritar publicações

### ISSUE THREAD

**Issue by patricks-js** [filipedeschamps/tabnews.com.br#1550]
Seria interessante se pudéssemos **favoritar publicações** para voltar e consultar novamente, assim como dar uma star em um repositório no GitHub.

Encontro conteúdo muito relevantes para mim no TabNews que gostaria de guardar para ler novamente, e nesse caso, eu tenho que salvar o link no WhatsApp ou algo assim. Então, uma feature assim seria muito legal para o público que consome os conteúdos.

**Comment by kaique-soares** [comment]
Olá @patricks-js, obrigado pela sugestão :handshake: 

Acho que esta issue está duplicada com a #645, caso esteja, sugiro fechar esta issue aqui e concentrar as discussões na #645 por organização :+1:

**Comment by aprendendofelipe** [comment]
Boa @patricks-js e @kaique-soares, vou fechar essa aqui como duplicada 🤝
