### ISSUE TITLE
Invalidar ou dificultar tentativas de login múltiplas em um dispositivo com dados que não conferem

### ISSUE THREAD

**Issue by eletroswing** [filipedeschamps/tabnews.com.br#1553]
# Por quê
Do jeito que está, alguns scripts podem ser feitos a fim de quebrar a senha de um usuario por 'brute force', e, apesar da cloudflare oferecer uma ótima proteção, isso acaba se tornando um problema em casos em que o atacante possui diversos ips e um conhecimento de que a infraestrutura passa pelo cloudflare

# A ideia
Implementar uma forma de captcha, ou de dificultar(ou até dar um timeout) em um ip que tente por multiplas vezes fazer login em uma mesma conta.

Poderia ser algo do tipo:
depois de 3 erros: ter que resolver um captcha pra tentar de novo
depois de 10 erros: o ip desse usuario tentando fazer login toma um timeout progressivo
após ser reconhecido o ataque: o bloqueio desse ip que tentou fazer a invasão

**Comment by aprendendofelipe** [comment]
@eletroswing, obrigado pela sugestão! 💪

> Do jeito que está, alguns scripts podem ser feitos a fim de quebrar a senha de um usuario por 'brute force'

Essa afirmação será sempre verdadeira, independentemente do que fizermos. O que vai mudar é a complexidade do ataque.

> apesar da cloudflare oferecer uma ótima proteção, isso acaba se tornando um problema em casos em que o atacante possui diversos ips e um conhecimento de que a infraestrutura passa pelo cloudflare

Mas esse é justamente um ponto em que a Cloudflare pode se sair melhor do que alguma proteção desenvolvida por nós e que também será de conhecimento público, já que o código do TabNews é aberto.

Sobre a sua ideia, talvez esteja faltando detalhes. Eu acredito que ela só adicionaria proteção se for baseada no usuário, mas não no IP (acho melhor deixar a parte do IP para a Cloudflare).

Então se houverem muitas tentativas de login para um mesmo usuário, podemos aplicar algum bloqueio temporário para a conta específica, independentemente do IP. É isso?

----

> Já temos uma proteção hoje: #635

Isso @Rafatcb, já há proteção no código, mas na prática ela não está sendo necessária, pois a Cloudflare nos defende absurdamente melhor.

> Não sei se a configuração de ambiente está diferente

É diferente do que está no código. O que manda é o definido nas variáveis de ambiente.

> Apesar disso, essa proteção não bloqueia o IP permanentemente (até onde averiguei).

Isso mesmo. Só fazemos bloqueio permanente pela Cloudflare.

> E não acho o CAPTCHA uma ideia útil para esse cenário porque quem deseja "quebrar" o sistema pode usar a API ao invés de utilizar o próprio site.

Da forma como foi proposto realmente não ajudaria. Mas o desafio da Cloudflare sim protege inclusive a API.

**Comment by Rafatcb** [comment]
Acabei de ver um issue específico sobre CAPTCHA no Login e Cadastro. Como lá teve discussão também, vou linkar aqui: https://github.com/filipedeschamps/tabnews.com.br/issues/1170.

**Comment by aprendendofelipe** [comment]
É verdade @Rafatcb! 👍

@eletroswing, como ambas lidam com o mesmo problema, vamos manter o debate na #1170 🤝
