### ISSUE TITLE
[Sugestão] Mudança de comportamento de links para outros sites

### ISSUE THREAD

**Issue by santosesantos** [filipedeschamps/tabnews.com.br#1556]
Faz algum tempo que clico em algum link de um post, esperançoso que vai abrir em uma nova guia, e acaba substituindo a guia atual, **"quebrando a leitura"** do post que eu estava gostando.

Já escutei em algum lugar que ao utilizar âncoras que direcionam para **outro site/domínio**, devemos fazer com que abra uma **nova guia**, ao invés de substituir a guia atual. Creio que seja uma boa prática na Web ou algo do tipo.

Portanto, creio que seria uma boa _feature_ para tornar esse nosso ambiente **mais agradável** de se utilizar.

**P.S.:** Adoraria contribuir diretamente com esse desenvolvimento, mas confesso que não sei por onde começar. Já clonei o repo e estou desbravando alguma forma de editar o comportamento dos **Links (components)**, adicionando um _target:"_blank"_ para começar, mas ainda não tô conseguindo bons resultados. Se alguém já tiver alguma ideia e, quem sabe, até me propor alguma ação, estou atenciosamente disposto a trabalhar nisso. 😃

**Comment by kaique-soares** [comment]
@santosesantos muito obrigado pela sugestão!

Algumas outras issues foram abertas no passado tratando desse assunto mas eu diria que a issue #477 tem um detalhe  especial, esse [comentário](https://github.com/filipedeschamps/tabnews.com.br/issues/477#issuecomment-1182110074) do @filipedeschamps que traz uma reflexão bem interessante.

:bulb: Uma dica: Podemos utilizar o combo `Ctrl + Click` para abrir um link em nova aba do navegador.

Recomendo fechar esta issue aqui por ser duplicada e centralizar as discussões na #447  :handshake:

**Comment by santosesantos** [comment]
Putsz, ainda tentei procurar se já tinha alguma carakkkkk.

Blz, muito obrigado. Vou comentar algo lá em breve.
