### ISSUE TITLE
[ Sugestão / Feature ] Poder salvar conteúdos que achou relevante no perfil

### ISSUE THREAD

**Issue by ethamorim** [filipedeschamps/tabnews.com.br#1561]
### Como

MInha ideia é basicamente ter uma forma de podermos salvar posts que achamos interessante, seja ela com uma opção de salvar em um vetor (bookmark), ou apenas um vetor com todos os post que marquei como relevante desde que minha conta foi criada (embora isso exclua usuários que ainda não tenham TabCoins, mas também estou ciente da cultura do TabNews).

### Por quê?

O TabNews é um lugar que se encontra muitos posts valiosos, e gostaria de poder voltar a eles sempre que possível, e a única forma de fazer isso atualmente, até onde eu saiba, é salvando o link em algum lugar externo, o que não é o fim do mundo, mas imagino que seria uma boa funcionalidade para se ter no site.

**Comment by aprendendofelipe** [comment]
@ethamorim, obrigado pela sugestão! 💪

Sugiro centralizar essa discussão na issue #645 👍

Vou fechar essa aqui como duplicada. 🤝
