### ISSUE TITLE
[Sugestão / Feature] Adicionar nuvem de tags

### ISSUE THREAD

**Issue by emerson-oliveira** [filipedeschamps/tabnews.com.br#1564]
## Contexto

Acredito que a inclusão de tags nas postagens seria uma adição valiosa para o nosso site. As tags podem ajudar a categorizar e relacionar postagens por temas, como css, wordpress, elementor, javascript, react, react-router, entre outros.

## Funcionamento

Ao criar uma nova postagem, o autor poderá escolher até 3 tags que sejam relevantes para o conteúdo da postagem. Posteriormente, os visitantes poderão sugerir até +3 tags. As tags que receberem mais votos ficarão visíveis para os usuários.

Com base nas tags mais sugeridas, poderíamos implementar uma seção de “postagens relacionadas” no final de cada postagem. Isso permitiria aos usuários navegar de um conteúdo relacionado para outro sem precisar voltar para a página inicial.

## Execução:

- [ ] **Desenvolvimento da funcionalidade de tags:** Permitir que os autores adicionem até 3 tags ao criar uma postagem.
- [ ] **Sugestões de tags pelos visitantes:** Implementar uma funcionalidade que permita aos visitantes sugerir até +3 tags para cada postagem.
- [ ] **Implementação de votação de tags:** Desenvolver um sistema de votação para as tags sugeridas.
- [ ] **Seção de postagens relacionadas:** Com base nas tags mais votadas, criar uma seção de “postagens relacionadas” no final de cada postagem.

**Comment by Rafatcb** [comment]
Emerson, tags são uma excelente sugestão, e achei muito bom você ter trazido uma sugestão de implementação detalhada assim. Não me lembro de ter visto uma sugestão de escolha de tags por meio de votos.

Acredito que podemos separar sua sugestão em duas partes: tags e publicações relacionadas. Já existem issues sobre esses pontos, inclusive com alguma discussão em andamento:

* https://github.com/filipedeschamps/tabnews.com.br/issues/742
* https://github.com/filipedeschamps/tabnews.com.br/issues/1478

O que você acha de comentar a parte relevante da sugestão nos issues relacionados e fechar este aqui?
