### ISSUE TITLE
Favoritar post 

### ISSUE THREAD

**Issue by HeytorPires** [filipedeschamps/tabnews.com.br#1568]
Implementar favoritar posts como no mobile, e interligar ambas as plataformas em um lista de favoritos, gosto Bastante da opção de favoritar no mobile, seria interessante de re-ler ao rever algumas publicação do tab news posteriormente.
Obrigado

**Comment by Rafatcb** [comment]
É uma boa sugestão. Existe uma discussão com sugestões de implementação aqui:

* https://github.com/filipedeschamps/tabnews.com.br/issues/645

Acho melhor fechar este issue e concentrar a discussão lá.

**Comment by aprendendofelipe** [comment]
Turma, obrigado pelas contribuições! 💪

Vou fechar diversas issues com assuntos relacionados. Por isso estou listando abaixo as que serão mantidas abertas e onde recomendo concentrarmos o que foi debatido/sugerido aqui:

- #645 
- #738
- #742 

Fechando essa aqui 🤝
