### ISSUE TITLE
[Duvida] Quem pode adicionar labels às issues?

### ISSUE THREAD

**Issue by emerson-oliveira** [filipedeschamps/tabnews.com.br#1569]
### Descrição

Notei que muitas issues em nosso repositório não estão utilizando labels. Acredito que a utilização de labels poderia melhorar a organização e a eficiência de nosso trabalho. Estou interessado em contribuir mais ativamente para o projeto, revisando as issues e adicionando labels apropriadas.

No entanto, não estou certo sobre o processo para adicionar labels às issues. É uma permissão exclusiva dos mantenedores do repositório? Se não, poderiam me orientar sobre como posso adicionar labels às issues?

**Comment by aprendendofelipe** [comment]
Como hoje o repositório do TabNews é pessoal, não é possível adicionar membros com acesso exclusivo para triagem, então apenas quem tem acesso de escrita no repositório consegue gerenciar as etiquetas.

Para quem tem acesso, o processo é explicado na documentação:

[Gerenciar etiquetas](https://docs.github.com/pt/issues/using-labels-and-milestones-to-track-work/managing-labels)

**Comment by Rafatcb** [comment]
Emerson, obrigado pela sugestão!

Para não deixar esse issue sem explicação, aqui vai um resumo do que foi feito:

Dei uma organizada nos issues colocando labels. Alguns eu não soube qual colocar (por exemplo, se era algo específico de `back`, `front` ou ambos), então deixei sem. Além disso, adicionei descrição à maior parte dos labels.

Aproveitei para criar os labels:

* [desempenho](https://github.com/filipedeschamps/tabnews.com.br/labels/desempenho)
* [segurança](https://github.com/filipedeschamps/tabnews.com.br/labels/seguran%C3%A7a)
* [SEO](https://github.com/filipedeschamps/tabnews.com.br/labels/SEO)
* [testes](https://github.com/filipedeschamps/tabnews.com.br/labels/testes)

Também aproveitei para traduzi-los para português, já que tudo no repositório é em português, com exceção do código. Deixei alguns termos que são mais usados em inglês do que em português (`back`, `front` e `bug`) e anglicismos como `mergear`  ("mergear" me parece mais usado do que "mesclar"). Também deixei o `good first issue` porque parece algo padrão usado pelo algoritmo do GitHub, conforme dito na [documentação](https://docs.github.com/pt/communities/setting-up-your-project-for-healthy-contributions/encouraging-helpful-contributions-to-your-project-with-labels).

Coloquei label de `pendente` em alguns PRs. Ainda não terminei de avaliar todos.

**Comment by emerson-oliveira** [comment]
Sensacional! Muito Obrigado..
