### ISSUE TITLE
Favoritos

### ISSUE THREAD

**Issue by JamisonCarvalho** [filipedeschamps/tabnews.com.br#1579]
### Descrição

Eu costumo favoritar os post que quero ler dps ou ate msm que nao quero perder de vista para rever no futuro, no APP tem um botão de FAVORITOS, entao uso ele para fazer isso, mas na versão web nao tem, seria interessante. Obrigado a todos pelo projeto.

**Comment by Rafatcb** [comment]
Jamison, obrigado pela sugestão. Estou fechando esse issue para concentrar a discussão sobre essa funcionalidade em https://github.com/filipedeschamps/tabnews.com.br/issues/645, ok? Lá a sugestão já foi para um pouco além: não apenas ter favoritos, mas sim listas, com a possibilidade de serem listas públicas ou particulares.

**Comment by JamisonCarvalho** [comment]
obrigado @Rafatcb
