### ISSUE TITLE
A Wiki foi descontinuada ?

### ISSUE THREAD

**Issue by emerson-oliveira** [filipedeschamps/tabnews.com.br#1585]
### Assunto

Outro

### Dúvida

Li a wiki do projeto e achei um lugar repleto de insights e explicações sobre as decisões tomadas. É um excelente guia para quem deseja contribuir com o projeto. No entanto, notei que ela não é atualizada desde 10/03/2022.

A Wiki foi descontinuado ou há previsão de retomar as wikis em algum momento?

**Comment by filipedeschamps** [comment]
@emerson-oliveira ótima pergunta meu caro! Acredito que, com tudo o que está acontecendo, por hora não há planos de voltar com o Wiki, mas uma ótima forma de navegar pelo desenvolvimento do projeto é pelas Milestones (ou pelas [issues](https://github.com/filipedeschamps/tabnews.com.br/issues/1490) das Milestones). Fora que estão num ótimo estágio para participar das discussões 🤝
