### ISSUE TITLE
[Dúvida] Custos do TabNews

### ISSUE THREAD

**Issue by ErickCReis** [filipedeschamps/tabnews.com.br#1587]
### Assunto

Outro

### Dúvida

Estou abrindo essa issue apenas a título de curiosidade.

1. Qual o custo mensal para rodar o TabNews?
2. Qual serviços externos são utilizados?
3. Além da Vercel, existem outras empresas que cobrem alguns desses custos?

Acredito que seria interessante ter alguma forma de acompanhar essas informações de forma mais fácil, talvez incluir em www.tabnews.com.br/status

**Comment by mthmcalixto** [comment]
@ErickCReis Eu acredito que o maior gasto está em banco de dados. 

Como site está hospedado na [Vercel ](https://vercel.com/) e é serverless o gasto é menor em relação a hospedagem

Acredito também que com envio de email não é cobrado, por que usa [Nodemailer](https://nodemailer.com/)

Não vejo outros serviços que foram utilizados além desses

Acho eu que essas informações não serão compartilhadas, mas seria interessante para ter uma transparência

**Comment by kaique-soares** [comment]
- @ErickCReis e @mthmcalixto sugiro darem uma olhada [neste comentário](https://github.com/filipedeschamps/tabnews.com.br/issues/826#issuecomment-1338339498) do @aprendendofelipe que foi feito quando o #826

**Comment by aprendendofelipe** [comment]
Na minha opinião, hoje o custo tecnológico é desprezível quando comparado com todo o tempo que pessoas dedicam para ajudar a manter o TabNews funcionando, seja na criação e curadoria de conteúdos ou na evolução do código. 😍

De qualquer forma, nada deve ter mudado desde que o @filipedeschamps fez a [publicação no TabNews que citou os custos tecnológicos](https://www.tabnews.com.br/filipedeschamps/tabnews-atinge-1-5-milhoes-de-views-e-futuro-do-projeto-alerta-de-textao#:~:text=mais%20para%20frente.-,Custos,-Na%20issue%20oficial).

Obs.: Eu acabo de editar a publicação do Filipe apenas para arrumar a formatação de um trecho que estava sendo interpretado pelo ByteMD como fórmula matemática. Só troquei um `$` por `&#36;`

Antes | Depois
--- | ---
![image](https://github.com/filipedeschamps/tabnews.com.br/assets/77860630/fd54cba2-8269-4750-a527-25d82a50e2bf) | ![image](https://github.com/filipedeschamps/tabnews.com.br/assets/77860630/c27ade3e-d07c-4303-a4d4-45a5cad06fba)

**Comment by Rafatcb** [comment]
Acho que pode ser legal termos isso no README ou em algum outro lugar.

A propósito, não precisamos ter o logo da Vercel em algum lugar por causa da parceria?

**Comment by ErickCReis** [comment]
@kaique-soares e @aprendendofelipe muito obrigado pelos links, acho que já tinha visto eles em algum outro momento, mas acabei não encontrando mais, esse foi uns dos motivos para a issue também.

> Na minha opinião, hoje o custo tecnológico é desprezível quando comparado com todo o tempo que pessoas dedicam para ajudar a manter o TabNews funcionando, seja na criação e curadoria de conteúdos ou na evolução do código. 😍

Concordo totalmente.

> De qualquer forma, nada deve ter mudado desde que o @filipedeschamps fez a [publicação no TabNews que citou os custos tecnológicos](https://www.tabnews.com.br/filipedeschamps/tabnews-atinge-1-5-milhoes-de-views-e-futuro-do-projeto-alerta-de-textao#:~:text=mais%20para%20frente.-,Custos,-Na%20issue%20oficial).

Entendi, não imaginava que o custo se manteria estável durante todo esse período.

**Comment by Rafatcb** [comment]
Vou fechar este issue, visto que alguns valores já foram respondidos na publicação do TabNews mencionada acima, e agora temos o fim da parceria com a Vercel, que está sendo acompanhado no issue https://github.com/filipedeschamps/tabnews.com.br/issues/1724, com alguns valores mencionados lá.
