### ISSUE TITLE
Erro 403 ao realizar cadastro

### ISSUE THREAD

**Issue by ThisIsDjonathan** [filipedeschamps/tabnews.com.br#1591]
### Descrição

Encontrei um problema ao tentar efetuar o cadastro no TabNews.

A mensagem de erro diz "Não foi possível se conectar ao TabNews. Por favor, verifique sua conexão." mas minha conexão a internet parece estar ok. Depois de atualizar a página algumas vezes, consegui fazer o cadastro.

O http response retornou 403 Forbidden:

<img width="1916" alt="image" src="https://github.com/filipedeschamps/tabnews.com.br/assets/8337704/5c0e42c8-eea4-4a0c-9bbc-39287b16fd3e">

### Passos para reproduzir o problema

1. Ir até a página de cadastro https://www.tabnews.com.br/cadastro
2. Informar dados;
3. Clicar em cadastrar.

### Navegadores testados

Outro

**Comment by aprendendofelipe** [comment]
@ThisIsDjonathan, obrigado por reportar! 💪

Vi que você já conseguiu criar a conta. 🎉

Uma dúvida: Na primeira tentativa você deixou a janela aberta na página de cadastro por alguns minutos, ou foi só o tempo de preencher o formulário?

Nos últimos dias o site está propositalmente em um modo mais restrito, então ao navegar para a página de cadastro a Cloudflare faz uma verificação do seu navegador e libera o uso da API de cadastro por um certo tempo. Se o cadastro não for submetido nesse intervalo, é necessário acessar a página novamente para reiniciar o tempo. Imagino que foi isso que ocorreu.

Se foi isso, acho que podemos fechar a issue, pois já temos duas relacionadas em como precisamos lidar melhor com requisições bloqueadas pela Cloudflare. Uma é mais parecida com essa, pois se aplica quando habilitamos alguma proteção extra, como no login ou cadastro, e a outra é pra quando a Cloudflare desconfia da requisição por conta própria:

- #1344
- #1516

**Comment by ThisIsDjonathan** [comment]
@aprendendofelipe deixei aberto um tempinho sim. Deve estar relacionado ao Cloudflare então!

**Comment by aprendendofelipe** [comment]
Legal @ThisIsDjonathan, então vou fechar essa aqui como duplicidade. 🤝

Muito obrigado! 💪
