### ISSUE TITLE
[Sugestão] Seria legal os links abrir em uma nova guia do navegador

### ISSUE THREAD

**Issue by Thiago-duart** [filipedeschamps/tabnews.com.br#1592]
### Descrição

Minha opinião, acho mais interessante isso estar automático mas e um gosto pessoal ...

**Comment by Rafatcb** [comment]
@Thiago-duart obrigado pela sugestão. Já temos um issue sobre isso e sugiro concentrarmos a discussão lá: https://github.com/filipedeschamps/tabnews.com.br/issues/477.

Inclusive, já foi abordado na discussão a possibilidade de permitir isso ser configurável por usuário.
