### ISSUE TITLE
Erro ao me Cadastrar

### ISSUE THREAD

**Issue by Thiago0808** [filipedeschamps/tabnews.com.br#1597]
### Descrição

Estou tentando fazer cadastro no TabNews, mas fica aparecendo a seguinte mensagem: 
Não foi possível se conectar ao TabNews. Por favor, verifique sua conexão.

Minha internet é boa, e eu também passei pelo mesmo erro em outras 2 internets.

### Passos para reproduzir o problema

1. Vá em cadastrar
2.  Coloque seus dados
3.  Clique em Li e estou de acordo com os Termos de Uso
4.  Clique em Criar cadastro
5. E agora aparecerá a mensagem "Não foi possível se conectar ao TabNews. Por favor, verifique sua conexão."

### Navegadores testados

Chrome

**Comment by aprendendofelipe** [comment]
@Thiago0808, obrigado por reportar.

Quanto tempo levou entre abrir a tela de cadastro e clicar em "Criar cadastro"?

Dever ser o mesmo caso do #1591.
