### ISSUE TITLE
Problema com cadastro de usuário novo.

### ISSUE THREAD

**Issue by rafinha-dev** [filipedeschamps/tabnews.com.br#1609]
### Descrição

Tentei me cadastrar essa manhã no tabnews pensando em talvez blogar por ali. 
Porém ao tentar concluir o cadastro houve algum erro que não corresponde com a situaçao que tenho. 
![Screenshot_2024-01-23-06-54-55-53_3aea4af51f236e4932235fdada7d1643](https://github.com/filipedeschamps/tabnews.com.br/assets/77486864/cc510791-4386-4ddb-809b-4416560e77ef)
Ele pediu para verificar minha conexão no entanto já tentei de dois dispositivos diferentes em duas redes diferentes.

### Passos para reproduzir o problema

Tentar fazer o cadastro de um novo usuário.

### Navegadores testados

Firefox

**Comment by aprendendofelipe** [comment]
@rafinha-dev, obrigado por reportar! 💪

A página de cadastro está com uma proteção extra ativada, então é necessário que a Cloudflare execute uma verificação para liberar o envio dos dados de cadastro.

A verificação deveria acontecer automaticamente ao navegar para a página de cadastro, mas se já houver cache do JS dessa página no navegador, e a navegação for SPA, a verificação não ocorre, então o envio de dados do cadastro acaba sendo bloqueado.

Por enquanto, se o cadastro estiver sendo bloqueado, basta **atualizar a página de cadastro** (<kbd>F5</kbd>) que a verificação irá ocorrer, então será possível efetuar o cadastro. Só que se passar de 5 minutos entre a atualização da página e o envio dos dados, terá que atualizar novamente.

Já estou fazendo testes com o [Turnstile da Cloudflare](https://developers.cloudflare.com/turnstile/) para a verificação ocorrer sempre que necessário, mesmo pela navegação SPA ou após os 5 minutos de validade. Logo devo abrir o PR. 👍

**Comment by rafinha-dev** [comment]
Opa, agora o cloudflare está pedindo para confirmação antes de entrar na página, cadastro feito com sucesso 💪. 
Obrigado pela agilidade @aprendendofelipe
