### ISSUE TITLE
Migrar conta de Mailgun do `TabNews` para conta do `curso.dev`

### ISSUE THREAD

**Issue by filipedeschamps** [filipedeschamps/tabnews.com.br#1614]
## Início da conversa

Em conversa recente com a `Mailgun` (sistema que usamos para disparar emails transacionais tanto no `TabNews` quanto `curso.dev`), estava reclamando sobre a _entregabilidade_ de alguns emails, mais especificamente os `Códigos de Ativação` do curso que são enviados no momento que uma pessoa faz a matrícula. Então eles sugeriram eu passar pelo `Business Verification process`:

<img width="1397" alt="image" src="https://github.com/filipedeschamps/tabnews.com.br/assets/4248081/53148494-61ce-4490-ba52-bcb59ad1c3cf">

## Problema de duas contas

Processo na qual passei e o `curso.dev` já está num pool melhor de IPs, porém detectaram que tenho **duas** contas no Mailgun e de fato, como expliquei ali em cima, usamos uma para cada serviço. Expliquei que são duas iniciativas separadas, mas fiquei inseguro com o que pode acontecer daqui para frente:

<img width="1387" alt="image" src="https://github.com/filipedeschamps/tabnews.com.br/assets/4248081/9e20d974-5deb-4a85-ae14-37c5f444ea04">

### Sugestão de implementação

Sugiro migrarmos a conta de Mailgun do `TabNews` para dentro da conta do `curso.dev` para:

1) Não ter a conta cancelada do nada
2) Aproveitar do pool de IPs com maior reputação
3) Economizar uma mensalidade de `USD 35.00`, dado que eu pago mensalidade separada para as duas contas.

O que acham?

**Comment by Rafatcb** [comment]
“Usar uma única conta” significa que os e-mails enviados pelo curso.dev e pelo TabNews virão do mesmo remetente?

Outra pergunta, o issue #1451 será “abortado” ou a medida proposta é mais urgente e temporária, permanecendo até a implementação do Resend?

**Comment by aprendendofelipe** [comment]
Pelo volume atual envios mensais, não vejo razão para pagar pelas duas contas separadamente, então podemos migrar sim.

Sobre o processo de migração, para garantir que não haja interrupções no envio de e-mails, sugiro ativar temporariamente um serviço alternativo pelo menos durante o processo de alteração das configurações de DNS e validação do domínio do TabNews na conta do Curso.dev

**Comment by filipedeschamps** [comment]
Boa! Eu atropelei total aquela issue da Resend e não considerei, erro meu! 🤝 

Então estava pensando: talvez seja uma boa testar a Resend mesmo, até para ver na prática a qualidade do serviço e as funcionalidades do painel. E como o @aprendendofelipe já criou os records de DNS, estamos na cara do gol, correto?

**Comment by aprendendofelipe** [comment]
Correto @filipedeschamps, eu já tinha testado o Resend em homologação na época, mas hoje testei de novo e está funcionando bem.

Então agora ativei o plano com o código que o Zeno nos forneceu e já mudei as variáveis na Vercel.

Só falta um redeploy para colocar o Resend em produção. Bora?

**Comment by filipedeschamps** [comment]
Bora!

**Comment by aprendendofelipe** [comment]
Após testes delicinhas em produção 😉, acho que está funcionando... só precisou pegar no tranco... 😅

Apenas o primeiro envio com o Resend resultou em erro. Foi um comentário que fiz para o Rafa. Até cheguei a fazer rollback após o erro, mas quando vi pelo log do Resend que outro usuário tinha criado outro comentário instantes depois do meu,  e que o dele tinha funcionado, então voltei para o Resend e segue funcionando normalmente.

**Comment by Rafatcb** [comment]
Hoje apaguei comentários duplicados de +- 4 usuários diferentes. A primeira ocorrência foi um comentário "quadruplicado". Não investiguei a fundo, mas estou com a impressão de que, ao ocorrer um erro no envio do envio de e-amil (`sendReplyEmailToParentUser`), é lançada uma exceção e então o usuário recebe um erro (possivelmente 500) e acha que o comentário não foi publicado.

**Comment by aprendendofelipe** [comment]
> Hoje apaguei comentários duplicados de +- 4 usuários diferentes. A primeira ocorrência foi um comentário "quadruplicado". Não investiguei a fundo, mas estou com a impressão de que, ao ocorrer um erro no envio do envio de e-amil (`sendReplyEmailToParentUser`), é lançada uma exceção e então o usuário recebe um erro (possivelmente 500) e acha que o comentário não foi publicado.

Sim, é exatamente isso que está ocorrendo. Um comportamento bem ruim por retornar o erro e mesmo assim criar a publicação.

**Comment by Rafatcb** [comment]
> O que acham?

Faz sentido para mim. Eu até pesquisei algo mas não encontrei nada desses erros especificamente com o Resend.

**Comment by aprendendofelipe** [comment]
O domínio do TabNews já foi migrado para a conta do Curso.dev no Mailgun. 🚀

Ainda aguardo um retorno do suporte do Resend para ver se dou continuidade no #1451 pelo menos como contingência ou se abandonamos a ideia.

Fechando aqui 🤝
