### ISSUE TITLE
Retornar resposta da criação de conteúdo independente do resultado da notificação

### ISSUE THREAD

**Issue by Rafatcb** [filipedeschamps/tabnews.com.br#1630]
### Descrição

Ao criar um novo conteúdo (`POST /api/v1/contents`), o backend realiza o `commit` da transação e depos envia uma notificação por e-mail. Quando ocorre um erro nessa etapa, o usuário é alertado que o conteúdo não foi criado (o que não é verdade), e pode acabar criando o mesmo conteúdo várias vezes.

https://github.com/filipedeschamps/tabnews.com.br/blob/60769894251259449bc7f2c964a706955a57557c/pages/api/v1/contents/index.public.js#L170-L175 

### Passos para reproduzir o problema

Em ambiente de desenvolvimento:

1. Modifique a função `sendReplyEmailToParentUser` para lançar um erro (pode adicionar um `throw new Error()`).
2. Crie um comentário em alguma publicação.
3. Você receberá uma mensagem de que um erro inesperado ocorreu, mas o comentário terá sido criado (sem você saber).

Em ambiente de homologação/produção, isso só ocorre quando há um problema no envio de e-mail.

### Possível solução

Creio que o mais adequado seja não esperar pelo envio de e-mail para responder a requisição. Talvez seja possível utilizar o [`waitUntil`](https://vercel.com/docs/functions/edge-middleware/middleware-api#waituntil) para isso, mas não tenho certeza.

**Comment by aprendendofelipe** [comment]
> Creio que o mais adequado seja não esperar pelo envio de e-mail para responder a requisição. Talvez seja possível utilizar o [`waitUntil`](https://vercel.com/docs/functions/edge-middleware/middleware-api#waituntil) para isso, mas não tenho certeza.

Acho que `waitUntil` só funcionaria na Edge.

Se a ideia é responder rápido com o sucesso na publicação, mas manter a lambda rodando para continuar o envio do email, acho que teria que usar *stream*.

Tem também outras melhorias que podem ser feitas:

- Processar o envio de email em paralelo ao `filterOutput`.
- Capturar o erro no envio de email e apenas disparar para nosso monitoramento, mas sem retornar o erro para o usuário.
- Configurar um serviço de contingência para ser usado automaticamente sempre que o principal retornar algum erro. Capturando o erro também para o monitoramento.

Sobre um serviço alternativo, o suporte do Resend me respondeu que identificou a causa dos problemas intermitentes que tivemos, e que uma solução seria implementada. Pode ser um bom teste se configurarmod o Resend como principal e o Mailgun como contingência.

**Comment by Rafatcb** [comment]
> Acho que `waitUntil` só funcionaria na Edge.

É para o Edge, sim. Eu estava em dúvida se usávamos Edge, serverless ou outra coisa.

As melhorias que você propôs também são ótimas.

**Comment by ErickCReis** [comment]
Faz sentido implementar um sistema de fila/mensagens para ficar responsável pelo envio desses emails? A Upstash tem um serviço legal, o [QStash](https://upstash.com/docs/qstash/overall/getstarted), que deve funcionar bem nesse cenário.

---

Comecei a dar uma olhada nessa opção e só para deixar "anotado" encontrei duas opções para conseguir utilizar o QStash no ambiente de desenvolvimento sem depender de uma conta:
- [Bunnygram](https://bunnygram.vercel.app/)
- [qstash-simulator](https://github.com/vincentserpoul/qstash-simulator)

**Comment by Rafatcb** [comment]
Uma fila pode ser útil, tendo em vista que futuramente teremos notificações pelo site (https://github.com/filipedeschamps/tabnews.com.br/issues/738), e a fila pode ajudar a garantir/aumentar as chances de entrega da notificação, dependendo de como for implementada. Estou apenas palpitando porque não tenho experiência prática com filas.

**Comment by mthmcalixto** [comment]
@Rafatcb isso aqui pode ser resolvido em https://github.com/filipedeschamps/tabnews.com.br/pull/1701?

**Comment by Rafatcb** [comment]
@mthmcalixto este issue foi resolvido no PR #1632, enviando a resposta por stream antes do envio do e-mail. Ainda não tive tempo para rever o seu PR, mas suponho que esse problema não tenha voltado.

**Comment by Rafatcb** [comment]
O Next 15 (RC) anunciou uma função chamada [`after`](https://rc.nextjs.org/docs/app/api-reference/functions/unstable_after), que ainda está em fase experimental.

Estou colocando a label `repescagem` no issue para lembrarmos de verificar quando ficar estável.
