### ISSUE TITLE
[Feature/Melhoria] Migrar do Jest para Vitest

### ISSUE THREAD

**Issue by ErickCReis** [filipedeschamps/tabnews.com.br#1631]
### Descrição

Hoje o TabNews conta com uma quantidade de testes relativamente grande, e como a maior parte deles são testes de integração rodar todos eles acaba demorando alguns minutos, isso impacta não somente o desenvolvimento mas também o ambiente de CI.

Com certeza podemos melhorar o fluxo de testes para agilizar alguma coisa, mas provavelmente não deve ser algo simples. 

O [Vitest](https://vitest.dev/) compartilha praticamente a mesma API do Jest porém consegue ser muito mais rápido.

---

Fiz essa migração no meu [fork do TabNews](https://github.com/ErickCReis/tabnews.com.br/pull/1) e a [action](https://github.com/ErickCReis/tabnews.com.br/actions/runs/7859337643) demorou 2m 8s para finalizar, hoje esse tempo fica na faixa dos 4m.

Se for uma mudança que faz sentido para o TabNews posso abrir o PR para mostrar os detalhes do processo de migração.

**Comment by Rafatcb** [comment]
Erick, obrigado pela sugestão e pela implementação no seu fork! Nunca usei o Vitest mas já ouvi falar bem, e pelos resultados que você obteve, parece ser uma ótima troca.

Estamos adicionando o `eslint-plugin-jest` no PR https://github.com/filipedeschamps/tabnews.com.br/pull/1629, mas imagino que precisaríamos trocar pelo [`eslint-plugin-vitest`](https://www.npmjs.com/package/eslint-plugin-vitest). Consegue confirmar essa informação?

Seria interessante também testar [isso](https://github.com/filipedeschamps/tabnews.com.br/pull/1611#discussion_r1488348135). Tenho suspeitas que o Vitest lidaria bem com esse cenário, diferente do Jest.

**Comment by ErickCReis** [comment]
Fiquei meio sem tempo esses últimos dias, assim que possível faço esses testes @Rafatcb .

Se por acaso outra pessoa quiser seguir com essa melhoria, pode ficar a vontade em pegar o que já implementei, a minha branch já está desatualizada e deve precisar de alguns ajustes depois da sincronização com a main.

**Comment by ErickCReis** [comment]
> Estamos adicionando o `eslint-plugin-jest` no PR #1629, mas imagino que precisaríamos trocar pelo [`eslint-plugin-vitest`](https://www.npmjs.com/package/eslint-plugin-vitest). Consegue confirmar essa informação?

Sim, foi necessário fazer a troca, existem diferenças entre as regras, mas preferi manter as configurações recomendas.

> Seria interessante também testar [isso](https://github.com/filipedeschamps/tabnews.com.br/pull/1611#discussion_r1488348135). Tenho suspeitas que o Vitest lidaria bem com esse cenário, diferente do Jest.

Funcionou sem problema, só foi necessário adicionar um dependência que lida com os _path alias_ do jsconfig.json

---

Atualizei minha branch e abri o PR com a troca.

Essa foi a diferença de tempo das actions:

<img width="1074" alt="Captura de Tela 2024-03-04 às 21 38 28" src="https://github.com/filipedeschamps/tabnews.com.br/assets/30873873/50de22aa-117e-4b77-b357-847fe8edd236">
