### ISSUE TITLE
[BUGFIX] Dialog de busca não acompanha o color theme

### ISSUE THREAD

**Issue by eng-gabrielscardoso** [filipedeschamps/tabnews.com.br#1636]
### Descrição

![Captura de tela de 2024-02-25 11-22-22](https://github.com/filipedeschamps/tabnews.com.br/assets/67348001/194d8330-5008-45ae-99eb-1b52107a6484)
![image](https://github.com/filipedeschamps/tabnews.com.br/assets/67348001/04e4890c-6c0f-4ff1-87b9-9ac0fbadf250)

Ao navegar pelo Tabnews percebi que a caixa de dialog do buscador não está acomphando o color scheme (está setado unicamente para light), assim como também apresenta algumas inconsistências no estilo (e.g. o ícone de close está levemente diferente do utilizado no componente de dialog em outras partes do sistemas). 

Numa busca simples não consegui encontrar nenhuma issue relatando isso, e ao olhar o código percebi que as configurações estão forçando o estilo para "light" mesmo quando trocamos o tema para "dark". 

Gostaria de saber se isso é um problema ou se há alguma razão mais detalhada do porquê estar assim. Caso seja necessário corrigir posso cuidar disso em uma PR após a confirmação.

### Passos para reproduzir o problema

1. Entre na plataforma no tema "light" e clique na caixa de pesquisa
2. Troque para o tema "dark" e clique na caixa de pesquisa

### Navegadores testados

Chrome, Firefox

### Possível solução

Ao invés de setar os estilos unicamente para "light" poderia se utilizar o estilo computado no `useTheme` e deixar a mudança mais dinâmica. Talvez também seja necessário refatorar algumas coisas do componente `SearchBox`

**Comment by Rafatcb** [comment]
Gabriel, obrigado pela sugestão!

No PR de criação da barra de pesquisa, o Felipe Barso criou um comentário (https://github.com/filipedeschamps/tabnews.com.br/pull/1472#issuecomment-1636227427) explicando o motivo de não ter feito o modo escuro, mas acredito que faça sentido manter o issue aberto, porque, como foi dito em https://github.com/filipedeschamps/tabnews.com.br/pull/1472#issuecomment-1639005029, aceitamos PRs com essa correção :+1:

> Se alguém quiser criar uma estilização diferente para a busca em modo escuro, é só enviar o PR 💪

**Comment by aprendendofelipe** [comment]
@eng-gabrielscardoso, obrigado pela issue! 💪

@Rafatcb, acredito que seja melhor fechar a issue para não darmos a entender que incentivamos algum PR relacionado.

Se um PR for aberto, será revisado, mas essa busca foi implementada de maneira propositalmente simples por ser um experimento de coleta de dados para uma implementação futura, algo que não está nos planos de curto prazo.

Se concordar, pode fechar 🤝
