### ISSUE TITLE
[FRONTEND] Criação de Figma unificado

### ISSUE THREAD

**Issue by eng-gabrielscardoso** [filipedeschamps/tabnews.com.br#1637]
### Descrição

Creio que para melhorar o processo de desenvolvimento do frontend, seria interessante a criação de um Figma unificado, onde se estruturar, prototipar, votar e implementar novas páginas para o sistema

E.g. atualmente acredito que seria muito bom fazer uma atualização da página principal de notícias, então um Figma para isso seria muito bom para:

1. Quem for implementar não perder tempo ou trabalho caso não seja aceito
2. Haja uma transparência no que está sendo desenvolvido e o caminho para o qual a UI do sistema está indo

### Sugestão de implementação

Deixo a cargo dos comentários nessa issue

**Comment by Rafatcb** [comment]
Gabriel, obrigado pela sugestão!

Já surgiram algumas sugestões para mudar a interface, mas acho muito improvável isso acontecer, porque uma mudança grande exige um esforço maior no desenvolvimento e também é algo muito pessoal: existirão pessoas que apontarão a interface nova como "melhor", e outras como "pior". É mais palpável lidarmos com sugestões específicas onde há uma melhoria clara na UI/UX. De toda forma, existe o issue https://github.com/filipedeschamps/tabnews.com.br/issues/951 falando sobre "uma nova interface", que recebeu feedback apenas na época de lançamento do TabNews.

Sobre a sugestão de usar o Figma para concentrar a votação e prototipação, acho que não precisamos disso. Como dificilmente será implementada uma mudança radical, não há necessidade de prototipar no Figma toda a interface que o TabNews tem hoje, basta realizar uma sugestão mudando o próprio HTML ou usando alguma ferramenta para transmitir a ideia para as outras pessoas, até mesmo o Paint pode servir.

Assim, podemos compartilhar as imagens num issue específico do GitHub e os usuários podem reagir e sugerir melhorias. Um exemplo onde isso ocorreu foi no issue https://github.com/filipedeschamps/tabnews.com.br/issues/1510 (ainda não concluído).

Então, vou fechar esse issue como não planejado, ok? Mais uma vez, obrigado pela sugestão e pelo carinho com o TabNews!
