### ISSUE TITLE
Text to speech para deficientes visuais (e preguiçosos)

### ISSUE THREAD

**Issue by PedroHenriqueM01** [filipedeschamps/tabnews.com.br#1640]
### Descrição

Acho que deveria ter uma botão de text to speech para traduzir o texto escrito em áudio para facilitar a "leitura" para deficiente visuais (e preguiçosos)

### Sugestão de implementação

Podemos usar modelos de TTS da open ai, mas isso geraria um custo operacional.
mas também podemos pesquisar uma opção gratuíta ou uma lib para gerar áudio em cima de texto

**Comment by aprendendofelipe** [comment]
@PedroHenriqueM01, você teve algum problema ao usar alguma ferramenta de Texto-para-Voz com o TabNews?

Poderia dar mais detalhes?

**Comment by Rafatcb** [comment]
Seria a mesma sugestão do issue #1442?

**Comment by aprendendofelipe** [comment]
> Seria a mesma sugestão do issue #1442?

Acredito que sim, mas perguntei por desencargo para saber se houve algum problema com as ferramentas já disponíveis.

Vou fechar essa aqui como duplicidade, mas também acho que a #1442 poderia ser fechada.

@PedroHenriqueM01, se não for a mesma coisa, podemos reabrir a issue 🤝
