### ISSUE TITLE
Possibilidade de traduzir o próprio post/comentário

### ISSUE THREAD

**Issue by FMorschel** [filipedeschamps/tabnews.com.br#1648]
### Descrição

Inspirado pela issue #35.

Eu tinha um post pessoal no site medium falando sobre programação. Como eu gostaria que aquele conteúdo alcançasse mais pessoas, escrevi o post em inglês por lá.

Gostaria de sugerir que os posts criados pelos usuários pudessem ser "traduzidos" de uma maneira mais coerente do que utilizando o tradutor do próprio navegador que as vezes perde alguns conceitos ou troca palavras. E isso seria apenas um extra, nos posts que o(a) autor(a) quisesse/soubesse fazer.

### Sugestão de implementação

Minha sugestão aqui é um conceito simples, em relação a implementação, não tenho certeza. 

Pensei em algo como adicionar uma "tag" ou algo assim, no corpo do texto, indicando qual a língua em que está sendo escrito o texto. Algo como no lançamento de novas versões de apps na loja Google Play:

```
<pt-BR>
Escreva aqui no idioma pt-BR
</pt-BR>
```

E poderíamos, ao mostrar os posts, ter um dropdown com as possíveis linguas dos posts. Talvez adicionando isso ao url e no html da pagina para auxiliar motores de busca a classificarem aquele conteúdo com a lingua certa.

Não penso em ter, de momento a funcionalidade do #35, assim como o próprio Medium, o GitHub e alguns vários outros sites não tem versões com as linguas diferentes que os seus usuários postam, acredito que ao menos o texto poderia ter essa opção.

**Comment by aprendendofelipe** [comment]
@FMorschel, como você viu com sua publicação negativada, conteúdos em inglês não são bem recebidos pelos usuários do TabNews.

Talvez um dia chegue o momento de repescar a #35, mas isso não está nos planos de médio prazo, por isso vou fechar a issue. 🤝
