### ISSUE TITLE
Tabcoins negativos

### ISSUE THREAD

**Issue by FMorschel** [filipedeschamps/tabnews.com.br#1649]
### Descrição

Eu comecei a usar o site e pelo que eu entendi, se eu não tenho tabcoins eu não poderia utilizar eles.

Eu postei o mesmo conteúdo ontem tanto em inglês quanto em português, nessa ordem. Segue os links:

https://www.tabnews.com.br/fmorschel/great-dart-e-flutter-object-extensions
https://www.tabnews.com.br/fmorschel/otimas-extensoes-pra-objetos-em-dart-e-flutter

Hoje estou com tabcoins negativos.

### Passos para reproduzir o problema

Não sei exatamente o que eu fiz de errado aqui, mas ao fazer esse meu segundo post, eu tenho a sensação de que ele tentou "auto curtir" ou algo assim pois eu não tentei por não ter os coins. Aliás, tentei mais tarde e ele me diz que não posso dar upvote nas minhas proprias postagens.

![Imagem mostrando o post com um upvote e o login com um tabcoin negativo](https://github.com/filipedeschamps/tabnews.com.br/assets/52160996/4756c5ae-1b91-4535-a2b7-f1bca4a79fe5)

### Navegadores testados

Chrome

**Comment by aprendendofelipe** [comment]
@FabricioFFC, sua publicação em inglês recebeu votos negativos. Recomendo apagar a publicação antes que você perca mais TabCoins com ela.

Após apagar a publicação, veja o [FAQ](https://www.tabnews.com.br/faq) e o [Sobre (que é uma publicação do Filipe)](https://www.tabnews.com.br/filipedeschamps/tentando-construir-um-pedaco-de-internet-mais-massa) para entender melhor o TabNews.

Se isso responder suas dúvidas, pode fechar a issue, por favor 🤝

**Comment by FMorschel** [comment]
Minha publicação em inglês está com o valor de 0 tabcoins desde o momento em que eu criei ela. Foi minha primeira publicação. O valor de TabCoins negativos ocorreu apenas quando eu cirei minha publicação em português.

**Comment by aprendendofelipe** [comment]
Sua publicação começou com 1 TabCoin, já recebeu 2 votos negativos, e provavelmente continuará sendo negativada.

O FAQ e a publicação do Filipe ajudaram com as dúvidas? Quer sugerir alguma melhoria no texto do FAQ?

**Comment by FMorschel** [comment]
Entendi, acho que vou procurar (ou criar) uma issue. Gostaria de entender melhor por que as pessoas estão marcando meu post como negativo. Vou sugerir criar um campo de observações para votos negativos.
