### ISSUE TITLE
Poderíamos vincular uma descrição mais detalhada sobre os TabCoins recebidos diariamente no FAQ?

### ISSUE THREAD

**Issue by FMorschel** [filipedeschamps/tabnews.com.br#1652]
### Assunto

Outro

### Dúvida

Poderíamos vincular uma descrição mais detalhada sobre os TabCoins recebidos diariamente no FAC?
https://www.tabnews.com.br/FelipeBarso/tabnews-agora-com-recompensas-diarias-em-tabcoins

O que temos hoje no FAC:

---

## O que é TabCoin?
TabCoin é a moeda de troca no sistema de qualificação de conteúdos do TabNews. Você utiliza seus TabCoins para qualificar conteúdos dos outros e, por sua vez, recebe ou perde TabCoins com base nas qualificações recebidas em seus próprios conteúdos.

## Como ganhar TabCoins?
As formas de ganho de TabCoins são:

**Criando um conteúdo**: existe um algoritmo que leva em consideração os TabCoins dos seus conteúdos mais recentes para definir quantos TabCoins você ganhará ao criar um novo conteúdo.
**Recebendo votos positivos**: quando outro usuário avalia positivamente seu conteúdo.
**Recompensa diária**: você pode ganhar TabCoins ao acessar o TabNews pelo menos uma vez no dia. Existe um algoritmo que leva em consideração as qualificações dos seus conteúdos mais recentes e também a quantidade de TabCoins que você possui. Quanto melhor avaliados forem seus conteúdos e menos TabCoins você possuir, mais receberá na recompensa diária.

**Comment by Rafatcb** [comment]
@FMorschel obrigado pela sugestão!

Vou citar minha opinião, que deixei em outro comentário (https://github.com/filipedeschamps/tabnews.com.br/issues/1575#issuecomment-2000655379):

> Não queremos explicar com detalhes porque, além de ser algo complicado e mutável, o objetivo não é que a pessoa busque "a melhor forma de ganhar pontos", e sim que entenda a ideia geral de "quão melhor forem seus conteúdos, mais TabCoins você receberá".

Acredito que saber a "fórmula exata" não irá ajudar a ter um desempenho melhor no TabNews porque envolvem muitas variáveis, e se você tentar otimizar para o ganho de TabCoins, provavelmente terá "menos ganhos" do que se agisse de forma natural (mas continuando a focar na qualidade dos conteúdos).

Qual seu objetivo com essa proposta? Que necessidade você possui que deseja resolver? Talvez tenha uma outra solução para o problema que você encontrou que não seja detalhar exatamente como ganhar TabCoins.

**Comment by FMorschel** [comment]
Não acredito que necessariamente seja preciso passar os últimos parágrafos do post que botei o link acima. Mas penso mais nesse trecho:

> ### Como Ser Recompensado?
> Para ganhar os TabCoins extras, os usuários precisam ter recebido mais qualificações positivas do que negativas em suas publicações e usar a maior parte dos TabCoins ganhos para qualificar conteúdos (não acumular TabCoins).

Hoje no FAC temos:

> **Recompensa diária**: você pode ganhar TabCoins ao acessar o TabNews pelo menos uma vez no dia. Existe um algoritmo que leva em consideração as qualificações dos seus conteúdos mais recentes e também a quantidade de TabCoins que você possui. Quanto melhor avaliados forem seus conteúdos e menos TabCoins você possuir, mais receberá na recompensa diária.

Acredito que talvez removendo do FAC o inicio da segunda frase: 

> [...] **Existe um algoritmo que** leva em consideração as [...]

Pois, para mim, soa mais como algo que eu posso aprender e "tirar vantagem" caso eu tenha esse intuito.

E acho que adicionar a informação do post:

> [...] usar a maior parte dos TabCoins ganhos para qualificar conteúdos (não acumular TabCoins).

Pois essa parte explica melhor que o objetivo do site não é acumular TabCoins, mesmo tendo essa opção. E talvez indicar juntamente dessa ultima informação, mais uma vez, o objetivo do uso dos TabCoins.

**Comment by Rafatcb** [comment]
Dizer que tem um algoritmo não deveria dar a impressão de que você pode tirar vantagem, por causa da explicação que vem a seguir:

> Quanto melhor avaliados forem seus conteúdos e menos TabCoins você possuir, mais receberá na recompensa diária.

Ou seja, não há como tirar vantagem, apenas produzindo conteúdos bem avaliados.

> Pois essa parte explica melhor que o objetivo do site não é acumular TabCoins, mesmo tendo essa opção. E talvez indicar juntamente dessa ultima informação, mais uma vez, o objetivo do uso dos TabCoins.

Não vejo como sendo necessário deixar ainda mais explícito para não acumular TabCoins justamente pela frase que citei anteriormente (_"...e menos TabCoins você possuir..."_). Inclusive, não acho que o acúmulo de TabCoins seja um problema hoje. Existem usuários que votam pouco, mas não me parece que esse seja o motivo.

**Comment by FMorschel** [comment]
Obrigado pelas respostas. Vou fechar a issue pois acho que não tenho mais nada a acrescentar.
