### ISSUE TITLE
Tags nas postagens

### ISSUE THREAD

**Issue by FMorschel** [filipedeschamps/tabnews.com.br#1653]
### Descrição

Estava passando pelo post https://www.tabnews.com.br/filipedeschamps/tabnews-a-diferenca-entre-revelantes-e-recentes do Filipe e me deparei com uma questão que ele levanta ali, sobre talvez a aba de relevantes não ser necessariamente algo que os usuários queiram ver. 

Entendo esse ponto, apenas gostaria de levantar mais um, e se o usuário **quer** ver o conteúdo mais relevante, como ja pensado, mas pensando em "filtrar" esse conteúdo para ignorar alguns posts relacionados a tecnologias que o usuário não usa?

Por exemplo, se estou entrando lá nos relevantes hoje vejo alguns posts sobre [NextJS](https://www.tabnews.com.br/igoroliveiraa/duvida-qual-a-melhor-forma-de-persistir-um-dado-em-next-js), [Docker](https://www.tabnews.com.br/nadojba/iniciando-com-kubernetes-com-kind-e-docker) e [IA](https://www.tabnews.com.br/devJlucassantos/inteligencia-artificial-em-2024-uma-odisseia-no-mundo-real). Mas eu não trabalho com necessariamente nenhuma dessas áreas. Acho interessante dar uma olhada em coisas fora do seu espectro por poder gerar insights diferentes ou incitar a fazer algo novo, mas eu por exemplo, trabalho com Dart e Flutter. A não ser que a Google lance uma atualização nova, grande sobre isso, poucos conteúdos referentes a isso vão parar na pagina de relevantes. 

### Sugestão de implementação

Eu gostaria que pudessemos "classificar" os posts com tags (como no StackOverflow por exemplo ou as issues aqui) para que, por exemplo, no meu caso, os posts fossem um pouco mais relevantes pra mim, mas ainda assim relevantes para a comunidade que se importa com aquela "tag".

**Comment by aprendendofelipe** [comment]
Fechando por duplicidade com #742

**Comment by FMorschel** [comment]
Desculpe! Não encontrei essa issue.
