### ISSUE TITLE
testes, testes, testes

### ISSUE THREAD

**Issue by nobregao** [filipedeschamps/tabnews.com.br#1664]
### Assunto

Contribuição

### Dúvida

a procura de testes necessários 🔍

o que estou pensando:
- o que é interessante implementar de teste para o projeto? que ainda não existe ou, talvez, precise melhorar o escopo.
- será que tem algum tipo de teste importante, mas, no backlog (ou na mente de alguém 😅), não teve prioridade?

com isso jogado na mesa 🙃... faz sentido essa discussão?

ps: é para meu tcc da pós (não é meme 😅)

**Comment by Rafatcb** [comment]
@nobregao obrigado pelo interesse!

> o que é interessante implementar de teste para o projeto? que ainda não existe ou, talvez, precise melhorar o escopo.

Não temos nenhum teste no frontend. Já foi levantado o assunto de criar testes e2e com o Playwright (https://github.com/filipedeschamps/tabnews.com.br/issues/255), e provavelmente esse tipo de teste é o que teria um impacto mais positivo dentre os possíveis testes a serem criados. Esses testes costumam ser mais lentos, então também seria necessário colocar na balança e entender o quão demorado realmente são, e quais os fluxos mais importantes para serem testados dessa forma.

Não cheguei a investigar o issue mencionado e a implementação para entender se ainda temos impeditivos técnicos quanto à realizar uma nova implementação hoje.

Além disso, existe o issue https://github.com/filipedeschamps/tabnews.com.br/issues/1405, que é sobre testes e está aberto.

Também existem refatorações que podem ser feitas em testes existentes, como por exemplo uma que foi mencionada em https://github.com/filipedeschamps/tabnews.com.br/pull/1601#pullrequestreview-1813937412:

> E aproveitando sobre o assunto testes... Eu acho que não estamos adotando uma boa estratégia ao limpar o banco de dados a cada teste. Falo especificamente sobre os testes que só usam o método GET.
>
> Testes que podem ser executados com um mesmo conjunto de dados (no banco de dados) poderiam ser agrupados e executados de forma mais rápida.
>
> Em alguns casos também daria para usar test.each ou describe.each para testes idênticos em que só mudam os dados de entrada e saída.

---

> será que tem algum tipo de teste importante, mas, no backlog (ou na mente de alguém 😅), não teve prioridade?

De certa forma, é questão de prioridade mesmo. Os testes são importantes e as funcionalidades do backend costumam ser cobertas por eles. Não me lembro de ter lido outros comentários sobre coisas que podem ser implementadas nos testes e que eu não mencionei acima.

**Comment by aprendendofelipe** [comment]
> com isso jogado na mesa 🙃... faz sentido essa discussão?

Acho que faz mais sentido manter a issue aberta se ela focar em pontos específicos que precisam ser resolvidos.

Caso a dúvida esteja sanada com a excelente resposta do @Rafatcb, pode fechar essa issue, caso contrário, pode manter aberta até saná-la.

Caso queira contribuir com algum desses pontos, sugiro criar uma nova issue mais específica (o título é bastante importante), ou contribuir nas discussões já existentes, que podemos reabrir, se for o caso.

> ps: é para meu tcc da pós (não é meme 😅)

Nesse caso, uma publicação no TabNews em que você fale sobre o seu TCC também pode lhe trazer mais material 👍

**Comment by nobregao** [comment]
a cabeça já está trabalhando. muito obrigado pelo contexto e ideias @Rafatcb!

@aprendendofelipe acredito que faz sentido e vou fechar por aqui.

objetivo cumprido 🎯
