### ISSUE TITLE
[Feature] Adicionar uma forma de visualizar melhor as imagens de posts

### ISSUE THREAD

**Issue by hiroshimorowaka** [filipedeschamps/tabnews.com.br#1666]
### Descrição

> Estou abrindo uma nova issue porque não achei nenhuma issue relacionada com esse tópico, mas talvez seja só desatenção, então peço desculpas adiantadas para caso já exista uma cobrindo esse tópico.

Eu acho que seria bem interessante colocar uma funcionalidade no front-end onde ao clicar em uma imagem de uma publicação, ela seja exibida em algum modal para facilitar a visualização.

### O que essa sugestão resolve

Eu pensei nessa funcionalidade agora mesmo enquanto lia esse post: https://www.tabnews.com.br/pierrefreire/minha-jornada-com-rust

Nesse post tem um [comentário](https://www.tabnews.com.br/GMNDS/711d4688-df20-4d94-8476-b6fbe8a5fb67) com uma imagem de diagrama em alta qualidade, mas no computador não da pra ver essa imagem, fica bem difícil de enxergar. Pra você conseguir visualizar, você tem que clicar com o botão direito, abrir imagem em nova guia e ai sim ver a imagem, o que fica meio chatinho de ficar fazendo, já que é necessário você sair do site do TabNews.

Nos celulares acho que poderia ou não ser útil, já que tem como você dar zoom pelo próprio navegador e visualizar a imagem em maior qualidade, mas no computador não, e mesmo se você der zoom na página, a imagem não aumenta, ela é redimensionada para ocupar o mesmo espaço na tela. (por questões de responsividade).

### Ideia de implementação

Acho que poderia ser algo parecido com o Notion, onde ao clicar duas vezes em cima da imagem, ele abre um modal/dialog com a imagem grande na tela e da a opção de dar zoom:

### Imagem em tamanho normal no Notion

![Imagem de tamanho normal](https://github.com/filipedeschamps/tabnews.com.br/assets/82670390/f7e0da60-559c-4bfe-ade9-6e880a268924)

### Modal com imagem redimensionada
![Imagem aumentada](https://github.com/filipedeschamps/tabnews.com.br/assets/82670390/da02365d-cc2a-4184-b560-6c27d6634748)

Mas no caso do TabNews, eu acho que seria melhor apenas um clique em cima da imagem para abri-la.

**Comment by kaique-soares** [comment]
Olá @hiroshimorowaka, obrigado pela sugestão :handshake:

> (...) mas no computador não, e mesmo se você der zoom na página, a imagem não aumenta, ela é redimensionada para ocupar o mesmo espaço na tela. (por questões de responsividade).

Por aqui, aplicar um zoom na página foi suficiente para visualizar o conteúdo da imagem perfeitamente (sugiro que veja o vídeo em tela cheia :+1:)

https://github.com/filipedeschamps/tabnews.com.br/assets/57193392/bd729296-9afe-4092-87a6-36c47bcad988

A issue abaixo está relacionada ao assunto, sugiro que veja:
- #1437

**Comment by hiroshimorowaka** [comment]
Acho que é mais pelo fato da minha visão ser meio prejudicada então. 
Eu tava pensando em algo onde você teria a capacidade dar zoom, tipo assim: 

https://github.com/filipedeschamps/tabnews.com.br/assets/82670390/40ea3a1a-db41-480b-8b8c-d44c63279991

Porque pra eu enxergar o que ta escrito nos quadradinho eu tenho que dar um zoom maior, ai eu prefiro abrir em outra aba e dar zoom. Então essa sugestão me veio a cabeça, mas realmente, só dar zoom na pagina ou abrir a imagem de forma separada em outra guia resolve também kkkkk

**Comment by Rafatcb** [comment]
Acho que esse problema do zoom continuaria, caso fosse uma imagem com uma resolução muito grande, certo?

Tendo a concordar com o @kaique-soares. Minha impressão é que faz sentido deixar isso na mão do usuário (bastaria fazer `[![descrição](imagem)](link para a imagem)`), principalmente porque algumas publicações já possuem links em imagens, o que deixaria de funcionar com esse novo recurso.

**Comment by hiroshimorowaka** [comment]
> Tendo a concordar com o @kaique-soares. Minha impressão é que faz sentido deixar isso na mão do usuário (bastaria fazer `[![descrição](imagem)](link para a imagem)`), principalmente porque algumas publicações já possuem links em imagens, o que deixaria de funcionar com esse novo recurso.

Realmente, quebraria as imagens com Links, então acho melhor deixar de lado essa sugestão. 
Fica melhor deixar na mão do usuário mesmo

**Comment by Rafatcb** [comment]
Ok, @hiroshimorowaka! Vou fechar este issue, obrigado pela sugestão :handshake:
