### ISSUE TITLE
Evolução da arquitetura - App Directory/Nextjs

### ISSUE THREAD

**Issue by phricardo** [filipedeschamps/tabnews.com.br#1669]
### Descrição

Pensando em evolução do projeto e seguindo as novas versões e recomendações do Next.js, há movimentos para migrarmos para app directory? 

### Sugestão de implementação

Pensando em evolução do projeto e seguindo as novas versões e recomendações do Next.js, há movimentos para migrarmos para app directory? 

Quais impactos?
Ganhamos beneficios com isso?

Levantando apenas como um questionamento para debate aqui...

**Comment by aprendendofelipe** [comment]
@phricardorj, como o TabNews é baseado em páginas estáticas e com a parte dinâmica vindo da API, eu não considero a migração para a pasta `/app`, por si só, uma evolução do projeto.

Mas é natural que isso vá acontecer de forma incremental conforme forem surgindo necessidades. Talvez a criação de páginas que compartilhem uma parte dinâmica (ao invés de estática + API) ou, no caso da API, a criação de novas rotas ou melhorias nas existentes.

Por enquanto eu não recomendaria a migração de nenhuma página só por migrar. Se não houver nenhum ganho real com a migração, não vale a pena ficarmos tão presos ao Next.js.

Faz sentido?
