### ISSUE TITLE
Favoritar / Start ⭐

### ISSUE THREAD

**Issue by gusperandio** [filipedeschamps/tabnews.com.br#1670]
### Descrição

Estava lendo uma história no TabNews e me deparei com uma situação.

Queria ler novamente certo trecho depois, pra que não precise ficar salvando os textos em outras anotações etc.
Minha ideia seria criar uma sessão de favoritar aquela pub para poder ler dps ou re-aproveitar o conteudo. ⭐

**Comment by aprendendofelipe** [comment]
@gusperandio, obrigado pela sugestão! 💪

Vou fechar porque o assunto já é abordado na #645 🤝
