### ISSUE TITLE
Busca trazendo resultados fora do tabnews

### ISSUE THREAD

**Issue by marcos-venicius** [filipedeschamps/tabnews.com.br#1672]
### Descrição

![image](https://github.com/filipedeschamps/tabnews.com.br/assets/94018427/9cbb8c00-ddba-40cc-bbfd-0b63838368d5)

Como podemos ver, ao buscar um termo qualquer como por exemplo "batata", são trazidos vários resultados de fora da plataforma, diretamente do google.

Não sei se isso é intencional (acredito que não), e no caso, em todas as tabs está retornando tudo, tanto em "Todos os resultados" quanto em "GitHub" quanto em "TabNews"

### Passos para reproduzir o problema

1. Clicar no input de pesquisa
2. Digitar um termo qualquer como "batata"

### Navegadores testados

Chrome, Firefox

### Possível solução

Poderíamos tentar uma estratégia de semantic search, utilizando talvez um langchain, por exemplo.

Talvez, dê para configurar no software que está sendo utilizado hoje, não tenho certeza.

Mas, acredito que trazer resultados que se limitão a aplicação seria uma grande melhoria de usabilidade.

**Comment by aprendendofelipe** [comment]
Os primeiros itens que aparecem na sua imagem não são resultados da busca, e sim propagandas do Google, que é o serviço de busca que está sendo utilizado de forma gratuita, então tem propaganda.

Note que está escrito **Patrocinado** em negrito.

**Comment by marcos-venicius** [comment]
Sim, isso é um fato.

Mas, no caso, é justamente disso que falo.

De ou ter um sistema de busca interno, ou remover esses links patrocinados.

Até porque, logo mais, os anúcios serão dos próprios usuários, ai terá anúncios do google também.

Posso estar errado, mas me soa estranho.

**Comment by Rafatcb** [comment]
Isso é intencional, apesar de não ser o ideal. Pode ver o que foi pensado ao tomar a decisão em https://github.com/filipedeschamps/tabnews.com.br/issues/927#issuecomment-1611655366. Ter um mecanismo de busca assim é melhor do que não ter, e nenhuma alternativa melhor foi implementada ainda porque os esforços foram direcionados para outras partes do projeto. 

Para deixar claro, uma melhoria no mecanismo de busca é sim bem-vinda.

**Comment by aprendendofelipe** [comment]
Show @marcos-venicius, considerando como dúvida sanada, então vou fechar aqui. 👍

Qualquer novidade relacionada à busca pode ser adicionada lá na #927, mesmo ela já estando fechada, pois a gente pode reabrir. 🤝
