### ISSUE TITLE
[Ideia] Usar os comentários do TabNews como API/sistema de comentários de blogs e/ou sites terceiros

### ISSUE THREAD

**Issue by dami-i** [filipedeschamps/tabnews.com.br#1674]
### Descrição

A minha sugestão é, na medida do possível, autoexplicativa pelo título.

Eu imaginei algo estilo Disqus ou o antigo Facebook Comments.

Utilizar o sistema de comentários do TabNews como o sistema de comentários de postagens em blogs pessoais.

Se isso for interessante, implicaria em algo além de um possível aumento no consumo da API?

**Comment by Rafatcb** [comment]
Obrigado pela sugestão, @dami-i!

Faz muito tempo que eu não comento em blogs, então não me lembro como funciona o processo de login para isso. O TabNews precisaria fornecer uma interface parecida com o "Entrar com o Google"?

Uma preocupação minha em situações onde as pessoas falam sobre usar o TabNews como CMS do próprio blog, e agora com você sugerindo essa "funcionalidade de comentários", é que a pessoa que publica (ou comenta) precisa seguir os Termos de Uso do TabNews, e se ferir os termos, pode ser banida e ter todas publicações e comentários removidos. 

Além disso, no caso dos comentários, a pessoa pode estar impedida de comentar por causa da pontuação negativa e não entender direito, porque essa é uma dinâmica externa ao blog que a pessoa está lendo.

Um outro ponto é que, na sua sugestão, o autor da publicação (do blog) não conseguiria moderar os comentários, e não acredito que faça sentido criar uma permissão para isso, visto que no TabNews não faz sentido uma pessoa poder remover comentários da publicação dela — essa responsabilidade fica para o moderador, seguindo como guia os Termos de Uso.

Achei sua ideia legal, mas por conta dos pontos que mencionei acima, acredito que não seja viável. De toda forma, se o autor do blog escolher listar suas publicações do TabNews no blog, ele consegue também listar os comentários que a publicação teve, apesar de não conseguir permitir que as pessoas comentem ali diretamente pelo blog dele.

Faz sentido?

**Comment by dami-i** [comment]
@Rafatcb, obrigado por sua resposta.

Faz sentido sim. Eu realmente acho que acrescentaria uma complexidade muito grande ao ecossistema atual e talvez pudesse até mesmo fugir dos objetivos do TabNews pro futuro.

Vou fechar a issue. Abraço!
