### ISSUE TITLE
Tela de Insight dos Posts e Perfil

### ISSUE THREAD

**Issue by DeuzivanLima** [filipedeschamps/tabnews.com.br#1683]
### Descrição

# Ideia Base
Que os autores tivessem uma nova tela onde seria possível visualizar um gráfico de cliques, impressões, tempo médio de leitura e etc.

# Sugestão de Endpoints
- {base_url}/analisar/Usuário/como_fazer_um_script
- {base_url}/analisar/Usuário

A página de insight de posts poderia se parecer com a /status do tabnews, assim sendo necessário poucas mudanças no front (eu acho).

![download](https://github.com/filipedeschamps/tabnews.com.br/assets/158287163/70e5a0a7-30bf-4e72-a5ea-bff3dc42235e)

**Comment by aprendendofelipe** [comment]
@DeuzivanLima, obrigado pela sugestão!

Tempo de leitura, ou de sessão, é um tipo de dado que provavelmente nunca coletaremos dos usuários do TabNews.

Já o alcance das publicações é tema relacionado com #1115, então vou fechar aqui para manter a conversa centralizada lá. 

Combinado? 🤝
