### ISSUE TITLE
Melhorar processamento dos comentários

### ISSUE THREAD

**Issue by MilenaBaruc** [filipedeschamps/tabnews.com.br#1703]
### Descrição

Não há mínimo de caracteres a serem utilizados em um comentário, o que pode trazer problemas a aplicação.

### Passos para reproduzir o problema

1. Clique em responder
2. Escreva um comentário com um caractere ou com 2000 caracteres

### Possível solução

Deve-se colocar um mínimo de pelo menos 20 caracteres e máximo 2000

**Comment by kaique-soares** [comment]
@MilenaBaruc, obrigado por reportar mas esse comportamento que você descreveu é o esperado mesmo :+1: 

---

> Não há mínimo de caracteres a serem utilizados em um comentário

A quantidade mínima de caracteres é definida aqui:
https://github.com/filipedeschamps/tabnews.com.br/blob/74ca3780d80d4562ec5cb4ee49ca321e7c1f8fe2/models/validator.js#L234

E a máxima aqui:
https://github.com/filipedeschamps/tabnews.com.br/blob/74ca3780d80d4562ec5cb4ee49ca321e7c1f8fe2/models/validator.js#L235

> Escreva um comentário com um caractere ou com 2000 caracteres

Repare que as condições que você testou são permitidas :+1: 

---

Fez sentido? Caso sim, acho que podemos fechar essa issue, certo?

**Comment by aprendendofelipe** [comment]
Em complemento à resposta do @kaique-soares, o corpo dos comentários segue as mesmas regras das publicações *root*, tudo é tratado com conteúdo, e isso é uma característica proposital do TabNews.

Essa característica já foi abordada diversas vezes pelo @filipedeschamps, e uma delas acontece na wiki:

https://github.com/filipedeschamps/tabnews.com.br/wiki/016.-Layout-de-dentro-da-not%C3%ADcia

> ...É importante ser assim, principalmente ter um espaço grande para a pessoa digitar o seu comentário (ter o mesmo espaço que a pessoa teve para criar a notícia principal)...

Outro ponto relacionado é que, mesmo aceitando a criação de conteúdos com um único caractere, esse conteúdo não irá ganhar TabCoins iniciais (#1267), e muito provavelmente será negativado.

Vou fechar a issue, mas se houver algo a acrescentar, com justificativa para modificar esse comportamento, podemos reabrir o debate 🤝
