### ISSUE TITLE
havera uma versão em inglês ?

### ISSUE THREAD

**Issue by cardosource** [filipedeschamps/tabnews.com.br#1710]
### Assunto

Repositório

### Dúvida

É um projeto inteiramente pt-br ou ira ter uma versão em inglês ??

**Comment by Rafatcb** [comment]
Esse assunto foi tratado nos primórdios do TabNews, no issue https://github.com/filipedeschamps/tabnews.com.br/issues/35, e o Filipe trouxe uma excelente resposta na época (https://github.com/filipedeschamps/tabnews.com.br/issues/35#issuecomment-895587739), onde cito em especial:

> Minha opinião sobre internacionalizar o TabNews (e pode ser falta de visão minha e estou super aberto a correção), é que não será fácil lançar um projeto internacional e não tem nada a ver com a questão técnica (nem se fizer agora ou depois tanto faz), tem a ver com **penetração do produto no mercado**. O principal ativo do TabNews não é a tecnologia, e nem como estamos usando ela para aplicar nossas ideias (TabCoins, Xp, etc...), o principal ativo é a participação das pessoas aqui no repositório, depois participando criando notícias, comentando coisas com valor concreto e participando do fluxo completo de contribuição. E a versão brasileira é a que está mais próxima dessa realidade, pelo fato das pessoas sensacionais que se reuniram ao redor do canal, se tornaram membros e estão aqui nesse repositório discutindo isso ❤️  não tem nada disso construído no ambiente internacional, e construir isso é um longo caminho, **longo mesmo**, e um mar vermelho.

Esse assunto foi relembrado em março deste ano: https://github.com/filipedeschamps/tabnews.com.br/issues/1648#issuecomment-1999640564

> Talvez um dia chegue o momento de repescar a https://github.com/filipedeschamps/tabnews.com.br/issues/35, mas isso não está nos planos de médio prazo, por isso vou fechar a issue. 🤝

Como a nossa visão não mudou nesses meses, vou fechar este issue e, quando (ou se) chegar o momento, podemos reabrir o #35 e tratar o assunto lá.

Vamos focar nossos esforços no público falante da língua portuguesa, tanto na produção de conteúdo dentro do TabNews quanto na criação de funcionalidades úteis para nós :handshake:

**Comment by cardosource** [comment]
Entendi, obrigado por repassar
