### ISSUE TITLE
Adicionar funcionalidade de Favoritar os posts

### ISSUE THREAD

**Issue by PEAKYCOMMAND** [filipedeschamps/tabnews.com.br#1717]
### Descrição

Opção de favoritar posts

### Sugestão de implementação

Eu acho que existisse uma funcionalidade de favoritar os posts para ler mais tarde seria bem interessante, eu sempre me deparo com posts legais, porém as vezes não tenho tempo para ler naquele mesmo instante.

**Comment by Rafatcb** [comment]
@PEAKYCOMMAND, obrigado pela sugestão. Estou fechando esse issue para concentrar a discussão sobre essa funcionalidade em https://github.com/filipedeschamps/tabnews.com.br/issues/645, ok? Lá a sugestão já foi para um pouco além: não apenas ter favoritos, mas sim listas diferentes, com a possibilidade de serem listas públicas ou particulares.
