### ISSUE TITLE
Tabnews: múltiplos logins associados ao mesmo endereço Gmail. Detalhes na descrição.

### ISSUE THREAD

**Issue by gpoleszuk** [filipedeschamps/tabnews.com.br#1718]
### Assunto

Criação de contas de usuário associadas a um único email

### Dúvida

Tempos depois que o Tabnews foi ao ar, notei que não era possível criar mais que uma conta associada ao meu email. Contudo, é possível criar múltiplas contas a partir de um mesmo email Gmail considerando que este webmail não diferencia logins com pontos, ou seja, ele ignora os pontos que existem entre os caracteres do login. Por exemplo, usando os endereços abaixo, tratados todos como iguais pelo Gmail, é possível criar três contas no Tabnews.

exemplo@gmail.com
ex.em.plo@gmail.com
exem.plo@gmail.com
etc...

Até o momento desta postagem, o Tabnews trata cada um dos emails acima como diferentes, logo podendo-se vincular várias contas de usuários a um único endereço de email real com a simples modificação do email no momento do cadastro.

---

Achei interessante comentar este fato percebido, porém não sei bem como lidar com esta situação em um ambiente que já está em produção. Reforço que não testei se outros _webmails_ dão o mesmo tratamento para seus _logins_ assim como feito pelo Gmail.

Para esta verificação, acho que criei umas 3 contas no Tabnews que ficaram sem uso. Talvez uma busca em todo banco de dados por contas e suas respectivas contribuições ajudem a encontrar aquelas zumbi. Uma notificação poderia se enviada para o usuário avisando-o da inativação da conta e após algum tempo sua exclusão/retenção. Atualmente este procedimento de "garbage collection" tem sido adotada por alguns serviços gratuitos online a fim de expurgar o sistema removendo contas zumbi criadas para testes ou mesmo uso único, esporádico ou mesmo fraudes.

**Comment by Rafatcb** [comment]
Observação legal, @gpoleszuk . Eu não sabia desse comportamento do Gmail com o `.`, mas lembrei do uso do `+`, conforme explicado [aqui](https://support.google.com/a/users/answer/9282734?hl=en#email-address-variation).

Não sei se faz sentido entrarmos nessa briga de gato e rato para proibir esse tipo de uso do e-mail.

**Comment by gpoleszuk** [comment]
Que bom que tomou conhecimento desse comportamento, @Rafatcb. Certamente, é uma briga de gato e rato e o rato sempre fica à frente : ). Valeu por lembrar-nos do recurso "+" disponibilizado pelo Gmail.
