### ISSUE TITLE
Mensagem de erro ao tentar publicar novo conteúdo

### ISSUE THREAD

**Issue by LuanGregati** [filipedeschamps/tabnews.com.br#1721]
### Descrição

Ao tentar publicar um novo conteúdo, a seguinte mensagem de erro é apresentada logo após clicar no botão "Publicar":

![image](https://github.com/filipedeschamps/tabnews.com.br/assets/53376691/5189eb7a-6825-443b-aab2-18b4b9f2cad8)

A mensagem é uma resposta dessa requisição:

![image](https://github.com/filipedeschamps/tabnews.com.br/assets/53376691/3c72a434-5881-45af-9887-ff7df035976a)

## 1. Clique no botão para publicar novo conteúdo.

![image](https://github.com/filipedeschamps/tabnews.com.br/assets/53376691/4780d71f-f53e-4d7a-a8ef-93532dfd7823)

## 2. Adicione título, corpo e fonte.

![image](https://github.com/filipedeschamps/tabnews.com.br/assets/53376691/191c625e-8538-4fac-b3e7-01ccb9569968)

## 3. Clique em "Publicar"

![image](https://github.com/filipedeschamps/tabnews.com.br/assets/53376691/e3b20c63-822a-4f67-9ff1-0076fe7ad76a)

## Conteúdo para teste

**Título:** Pesquisadores de segurança criam extensão falsa para VS Code idêntica à “Dracula Official”, a fim de comprovar como usuários podem ser enganados por hackers devido à falta de controles rigorosos e revisões de código por parte da Microsoft.

**Conteúdo:** A “Darcula”, criada por Amit Assaraf, Itay Kruk e Idan Dardikman, conseguiu receber o selo “verificado” da loja a partir do registro de um domínio falso. Ela funciona de maneira idêntica à verdadeira, mas inclui um código malicioso capaz de roubar informações confidenciais, como nome do host e sistema operacional, registrando cerca de 2 mil downloads, inclusive por uma empresa estimada em mais de 480 bilhões de dólares, que não foi identificada. As informações são do site Bleeping Computer.

**Fonte:** https://www.bleepingcomputer.com/news/security/malicious-vscode-extensions-with-millions-of-installs-discovered/

### Navegadores testados

Chrome, Firefox, Microsoft Edge

**Comment by kaique-soares** [comment]
@LuanGregati muito obrigado por reportar :handshake:

Eu fiz um teste com o tamanho do `Título` e resultou em `238`:

![image](https://github.com/filipedeschamps/tabnews.com.br/assets/57193392/92cf829c-9038-4fc1-91df-9aa8c46f581f)

Especulo que você tenha caído nesta validação aqui:

https://github.com/filipedeschamps/tabnews.com.br/blob/4d62fc6d87dcbab578dd26349800d3475b003a88/models/validator.js#L208

---

Consegue reduzir o tamanho do `Título` e tentar enviar novamente? Na verdade, talvez seja melhor testar em homologação antes.

**Comment by kaique-soares** [comment]
@LuanGregati testei em homologação reduzindo o tamanho do `Título` e consegui publicar, veja :+1:

![image](https://github.com/filipedeschamps/tabnews.com.br/assets/57193392/77a0a6e9-5735-49fe-b9f7-3d05f402c820)

![image](https://github.com/filipedeschamps/tabnews.com.br/assets/57193392/d228cccf-4962-4081-8fcd-007cad5b2aff)

https://tabnews-git-chore-remove-cross-fetch-tabnews.vercel.app/kaiquesoares/pesquisadores-de-seguranca-criam-extensao-falsa-para-vs-code-identica-a-dracula-official-a-fim-de-comprovar-como-usuarios-podem-ser-enganados-por-hackers-devido-a-falta-de-controles-rigorosos-e-revisoes-de-codigo-por-parte

**Comment by Rafatcb** [comment]
@LuanGregati obrigado por reportar o problema; e @kaique-soares obrigado por encontrar uma solução alternativa!

Certamente a API não deveria retornar um erro no `slug`, sendo que ela mesma o gerou. Imagino que, caso o `slug` gerado seja grande demais, a função `getSlug` deveria cortar o final para respeitar a quantidade máxima permitida.

**Comment by aprendendofelipe** [comment]
Obrigado pessoal! 💪

O título ser longo não é o problema. O limite de tamanho do slug (226) é menor do que o do título (255), mas ele é truncado sempre que necessário.

O que está causando o problema é que, ao truncar o slug, ele acabou terminando com hífen, e é isso que não está passando no validador.

Logo mais eu abro o PR com a solução. 🤝

**Comment by kaique-soares** [comment]
@aprendendofelipe perfeito!!!

Estava testando isso kkk:

![image](https://github.com/filipedeschamps/tabnews.com.br/assets/57193392/03b0f577-5a37-4d47-b89a-f365f4d961e5)

**Comment by LuanGregati** [comment]
Obrigado pelas observações, pessoal! Vocês são demais 💪

**Comment by aprendendofelipe** [comment]
@LuanGregati, problema corrigido no PR #1722, e você foi citado na publicação sobre as novidades: 💪

https://www.tabnews.com.br/FelipeBarso/tabnews-corrigidos-bugs-nos-testes-e-na-geracao-de-slugs 🎉
