### ISSUE TITLE
Posso implementar a opção de Login com github?

### ISSUE THREAD

**Issue by Isidro1234** [filipedeschamps/tabnews.com.br#1732]
### Assunto

Contribuição

### Dúvida

Eu só queria perguntar se posso ou não implementar um recurso para o usuário fazer login no website com a conta do github usando a API "Passport"? Estou perguntando porque para isso precisaria cadastrar o site no github Oauth.
![Screenshot_23-6-2024_165029_localhost](https://github.com/filipedeschamps/tabnews.com.br/assets/130857984/8e937369-a465-4d41-9679-0b3151823d5c)

**Comment by aprendendofelipe** [comment]
@Isidro1234, não precisa pedir autorização para realizar nenhuma implementação, mas se quer saber primeiro se a ideia tem chances de ser aprovada, então recomendo que participe da issue relacionada (#922) fornecendo mais detalhes sobre o que está pensando e vendo o que a Turma acha da ideia 💪

Vou fechar aqui como duplicada. Combinado? 🤝

**Comment by Isidro1234** [comment]
sim!! obrigado.
