### ISSUE TITLE
Latex em publicações

### ISSUE THREAD

**Issue by santigonzaga** [filipedeschamps/tabnews.com.br#1750]
### Descrição

Eu encontrei um possível problema na formatação de fórmulas latex em textos publicados

### Passos para reproduzir o problema

1. Quando escreve a publicação está tudo correto
2. Quando publiquei o conteúdo ficou desconfigurado

Exemplo:

$$
\frac{\text{dream outcome} \times \text{perceive likelihood of achievement}}{\text{time delay} \times \text{effort and sacrifice}} = \text{VALUE}
$$

<img width="1337" alt="Screenshot 2024-07-16 at 13 06 20" src="https://github.com/user-attachments/assets/885f70f6-f1a0-4b32-90cb-cad55a71b127">
<img width="1269" alt="Screenshot 2024-07-16 at 13 06 28" src="https://github.com/user-attachments/assets/5d8a8c34-e2a4-41d1-b726-05771afbf4fb">

### Navegadores testados

Google Chrome (Version 126.0.6478.127 (Official Build) (x86_64))

**Comment by Rafatcb** [comment]
@santigonzaga obrigado por reportar isso.

Para facilitar investigações futuras, deixo aqui o código usado no comentário:

```latex
$$
\frac{\text{dream outcome} \times \text{perceive likelihood of achievement}}{\text{time delay} \times \text{effort and sacrifice}} = \text{VALUE}
$$
```

**Comment by aprendendofelipe** [comment]
@santigonzaga, obrigado por relatar! 💪

É muito provável que isso precise ser resolvido diretamente na biblioteca do editor de markdown que utilizamos ([ByteMD](https://www.npmjs.com/package/@bytemd/react)), ou no plugin dela.

Só que está parecendo que a manutenção dela foi descontinuada, então não vale a pena lidar com esse ponto isoladamente (mesmo que seja algo do nosso lado), e o que recomendo é resolvermos a #648 buscando alternativas de editores.

Por isso, vou fechar aqui e isso já vai criar um link pra cá na #648
