### ISSUE TITLE
Página de anúncio tem link para o próprio anúncio

### ISSUE THREAD

**Issue by hkotsubo** [filipedeschamps/tabnews.com.br#1756]
### Descrição

Ao acessar diretamente a página de um anúncio, logo depois do texto foi mostrado um link para o próprio anúncio:

![ad_inception](https://github.com/user-attachments/assets/55634f59-2ee6-47dd-bfc3-ec7d20e7a67c)

Eu entendo isso como bug, pois não faz muito sentido o anúncio ter um link para ele mesmo.

### Passos para reproduzir o problema

Acessar o link de um anúncio (ex: https://www.tabnews.com.br/filipericardo/agora-e-possivel-usar-seus-tabchash)

Obs: Caso haja mais de um anúncio ativo, pode ser que apareça outro. Mas basta recarregar a página (F5) que eventualmente aparecerá o mesmo.

Testei também em outro browser, aba anônima, etc, e realmente não acontece o tempo todo. Mas basta recarregar que uma hora aparece.
No momento em que escrevo, há 2 anúncios ativos, tem vezes que aparece um, tem vezes que é o outro.

### Navegadores testados

Chrome, Firefox, Safari

### Possível solução

O mais simples seria não mostrar o mesmo anúncio na própria página. Ou então não mostrar anúncio nenhum quando for a página de um anúncio.

**Comment by aprendendofelipe** [comment]
Acredito que nas páginas de anúncios não seja interessante mostrar outros anúncios.

Talvez a exceção seja mostrar diferentes anúncios do mesmo autor, caso existam.

**Comment by hkotsubo** [comment]
> Talvez a exceção seja mostrar diferentes anúncios do mesmo autor, caso existam.

Não sei se já devia abrir exceções. A funcionalidade acabou de ser implementada, talvez seja cedo pra sabermos o que faz mais sentido.

Em um primeiro momento podemos simplesmente não mostrar nada. Depois, com o tempo, ir avaliando se faz sentido abrir exceções. Por exemplo, se forem raros os casos em que o mesmo usuário tem mais de um anúncio ativo, talvez nem valha a pena ter esta regra.
