### ISSUE TITLE
Limitar anúncios ativos por usuário

### ISSUE THREAD

**Issue by hkotsubo** [filipedeschamps/tabnews.com.br#1762]
### Descrição

No momento em que escrevo, há 8 anúncios ativos do mesmo usuário <sup>o fato de ser o criador do site é indiferente, ou não?</sup>

Atualmente isso corresponde a 80% dos anúncios ativos. Isso não acaba criando um certo desbalanceamento? Claro que, por ter TabCash suficiente, ele teria todo o direito de criá-los. Mas até que ponto é benéfico que um único usuário praticamente monopolize os anúncios?

Entendo que a funcionalidade é nova e ainda estamos entendendo melhor seus impactos no site. Só queria levantar a discussão para ver se meu questionamento faz sentido.

### Sugestão de implementação

Talvez seja interessante pensar em limites.

Provavelmente uma quantidade máxima de anúncios ativos por usuário, ou não pode ultrapassar determinada porcentagem do total.

E quem sabe combinado com limites de tempo (só pode criar outro anúncio depois de X horas/dias/etc).

O que acham?

**Comment by aprendendofelipe** [comment]
Quem tem mais TabCash tem que ter alguma vantagem sobre quem tem menos. Acho que posso pular a justificativa para essa afirmação. 

Por enquanto que o valor está fixo em 100 TabCash, criar mais anúncios é a única forma de aparecer mais. Quando o  valor for variável, provavelmente vai aparecer mais anúncios de quem optar por investir mais TabCash. É natural.

Pensando em um sistema de anúncios, não é nem um pouco interessante limitar a  quantidade de diferentes anúncios de um mesmo anunciante. Concentrar o investimento em um único anúncio ou diversificar é uma questão estratégica do anunciante.

Por enquanto o Filipe está usando TabCash do usuário dele pra ajudar a testar a funcionalidade. Qualquer um que tenha TabCash suficiente pode fazer o mesmo. Vai aparecer mais vezes os anúncios de quem investir mais. Seja com anúncios iguais ou variados.

Sobre ser o criador do site, não é indiferente não. A Revenue Share prevê que parte das exibições de anúncios seja para custear o próprio TabNews, então o Filipe poderia até não usar nenhum TabCash se não quisesse, mas aí a gente não estaria testando direito a funcionalidade da forma que ela será para o usuário final.

**Comment by aprendendofelipe** [comment]
Um outro ponto é que qualquer regra que beneficie a criação de diferentes usuários por uma mesma pessoa é algo prejudicial ao TabNews

**Comment by hkotsubo** [comment]
> Quem tem mais TabCash tem que ter alguma vantagem sobre quem tem menos

Concordo.

Mas ainda sim, é aceitável que um único usuário monopolize os anúncios? Eu, por exemplo, poderia criar 29 anúncios agora mesmo. E nada impede que todos sejam sobre a mesma coisa (e não necessariamente com o mesmo texto, por exemplo).

Bom, se vcs não vêem problema, tudo bem, podemos até fechar a *issue*. Mas ainda acho que algum limite poderia ter, pra evitar abusos.

---

> qualquer regra que beneficie a criação de diferentes usuários por uma mesma pessoa é algo prejudicial ao TabNews

Não entendi como minha proposta beneficiaria a criação de vários usuários por uma mesma pessoa. Afinal, um novo usuário começaria sem TabCash, e portanto sem a possibilidade de criar anúncios. A pessoa precisaria primeiro receber votos pra depois conseguir votar em alguém e ganhar TabCash (claro que poderia usar a conta anterior para votar na nova, mas isso é trabalho demais pra quem está buscando uma forma fácil de burlar o sistema).

Ou seja, se existisse um limite, não adiantaria nada criar outro usuário para tentar burlar a regra.

**Comment by aprendendofelipe** [comment]
> ...é aceitável que um único usuário monopolize os anúncios?

Não tenho certeza se seu ponto é sobre a quantidade de anúncios ou se é sobre a quantidade de exibições. Considerando que os anúncios serem iguais ou diferentes seja uma decisão que cabe a cada anunciante, acho que o ponto é sobre os anúncios de um usuário aparecerem muito mais do que os de outro usuário, independentemente de ser um único anúncio ou variados desse mesmo usuário.

Em um momento que apenas um único usuário queira publicar anúncios, nesse momento só vai aparecer anúncios desse usuário, o bolo será inteiro dele, mas como poderia ser diferente? Foi o que aconteceu no período que só tinha o anúncio do `filipericardo` publicado.

Em momentos que algum usuário decidir investir mais do que os outros usuários, nesse caso vai haver uma exibição maior desse usuário, o que é justo, ou não? É o que está acontecendo agora, já que poucos usuários criaram anúncios, e um deles investiu mais do que os outros.

Em qualquer caso, a exibição de anúncios será uma razão entre o que o usuário investir e o somatório do que todos os demais investirem. Idealmente teremos muito mais gente anunciando no futuro, ou seja, o bolo será dividido em muito mais pedaços, mas alguns vão comprar mais pedaços do que outros, o que é normal.

> Eu, por exemplo, poderia criar 29 anúncios agora mesmo. E nada impede que todos sejam sobre a mesma coisa (e não necessariamente com o mesmo texto, por exemplo).

Se isso for interessante para você, pode usar o TabCash como achar mais vantajoso. Você mereceu eles 🤝 Só não deixe de ser estratégico, pois usar tudo agora não vai aumentar o tamanho do bolo, mas sim diminuir o tamanho de cada pedaço. Se for criar anúncios iguais, provavelmente os usuários não vão qualificar da mesma forma os diferentes anúncios, mas vai saber, né?

Também é bom considerar que os bolos no futuro devem ter pedaços menores (também podem ser maiores se os visitantes aumentarem), vai depender bastante de como será a disposição dos anunciantes em usar seus TabCash, e das regras que ainda estão sendo pensadas. Estamos aprendendo isso agora, mas não me parece fazer sentido limitar a proporção de exibições por usuário, e sim pelo saldo de TabCash de cada um.


> Bom, se vcs não vêem problema, tudo bem, podemos até fechar a _issue_. Mas ainda acho que algum limite poderia ter, pra evitar abusos.

O que seria abuso? Você só pode comer o bolo inteiro se ninguém mais quiser comer o mesmo bolo que você. Na prática, cada um vai comer mais ou menos bolo, de forma proporcional ao que investir. E só pode investir mais se realmente contribuiu mais com o TabNews e foi reconhecido pela Turma.

 
> > qualquer regra que beneficie a criação de diferentes usuários por uma mesma pessoa é algo prejudicial ao TabNews
> 
> Não entendi como minha proposta beneficiaria a criação de vários usuários por uma mesma pessoa.

É claro que usar diferentes usuários já abre brecha para muitos abusos, então vamos tratar apenas o que tem relação com o limite de anúncios.

Se seus 2900 TabCash fossem o resultado do mesmo esforço que você já teve, mas dividido entre dois usuários, e que isso resultasse em 1500 TabCash para um e 1400 para o outro, a quantidade de anúncios que você poderia fazer seriam os mesmos 29. Se limitarmos os anúncios por usuário, então sim haveria uma vantagem em ter 2 ou mais usuários, pois o seu limite real aumentaria de acordo com o número de usuários utilizados. Dado que o total de exibição de todos os anúncios independe disso, o que aumentaria a chance de aparecer não seria ter mais TabCash para investir, mas sim ter mais usuários com a quantidade suficiente de TabCash para criar os anúncios.

> Afinal, um novo usuário começaria sem TabCash, e portanto sem a possibilidade de criar anúncios. A pessoa precisaria primeiro ganhar TabCoins pra depois conseguir votar em alguém e ganhar TabCash 

E não é assim, seja com ou sem limite? Não entendi a relevância desse ponto para a questão.

> ...(claro que poderia usar a conta anterior para votar na nova, mas isso é trabalho demais pra quem está buscando uma forma fácil de burlar o sistema).

Aqui está tratando de um tipo de abuso real, que combatemos diariamente, mas sem nenhuma relação com a existência de limites de anúncios ativos por usuário.
 
> Ou seja, se existisse um limite, não adiantaria nada criar outro usuário para tentar burlar a regra.

Não consegui chegar nessa conclusão 🤷

**Comment by Rafatcb** [comment]
Acho este issue uma preocupação válida, mas voto para observamos a evolução natural do comportamento das pessoas com os anúncios antes de criar essa limitação. Até o momento:

- A funcionalidade existe há quase 2 dias completos (48h).
- Apenas um anúncio recebeu voto negativo: o [primeiro anúncio](https://www.tabnews.com.br/filipericardo/agora-e-possivel-usar-seus-tabchash), que está com `72` TabCoins, recebeu um voto negativo.
- Apenas três usuários criaram anúncios: `filipericardo`, `filipedeschamps` e `NewsletterOficial`.
- Temos 10 anúncios ativos, 8 de um único usuário.

Como por enquanto o anúncio escolhido para ser exibido é de forma totalmente aleatória, sem contar a quantidade de TabCash investido, nossa análise é limitada nesse sentido, e o comportamento dos usuários pode mudar quando essa dinâmica for inserida. Se optarmos por limitar a quantidade de anúncios, significa que vamos afunilar os caminhos possíveis para os usuários, e podemos tirar conclusões erradas sobre como a funcionalidade deve evoluir.

Além de estarmos pensando em aumentar as chances do anúncio ser escolhido conforme possui mais TabCash, o Filipe comentou em https://github.com/filipedeschamps/tabnews.com.br/issues/1491#issuecomment-2226912945

> Isto irá fazer a página `Classificados` mostrar os anúncios que os usuários estão investindo mais `tabcash`.

O que, se entendi direito, faria a lista de Classificados não ser mais ordenada pela data de publicação (mais novos primeiros), e sim por TabCash (mais TabCash primeiro).

Esses dois pontos me levam a crer que investir a mesma quantidade de TabCash em menos anúncios pode fazê-los serem vistos mais vezes do que criar vários anúncios com o mínimo de TabCash. Por isso eu gostaria de ver o comportamento evoluindo naturalmente antes de criar essa limitação. O que vocês acham?

**Comment by hkotsubo** [comment]
> dividido entre dois usuários, e que isso resultasse em 1500 TabCash para um e 1400 para o outro, a quantidade de anúncios que você poderia fazer seriam os mesmos 29

Na verdade eu estava pensando em um caso específico: um usuário que atingiu o limite de anúncios e só então resolve criar outra conta pra tentar burlar.

Neste caso não valeria a pena, pois até a nova conta ter TabCash suficiente para criar um anúncio, os anteriores (feitos com a conta original) provavelmente já terão expirado e ele já poderia criar outros anúncios.

Enfim, foi isso que eu quis dizer com "*se existisse um limite, não adiantaria nada criar outro usuário para tentar burlar a regra*".

No caso da pessoa já ter outra conta há muito tempo, aí concordo que o limite não resolve.

E indo um pouco além, já vi muitos casos de gente que não conseguia mais publicar por ter pontuação negativa, e criou outra conta pra poder continuar postando. Todo bloqueio ou limite no fundo é um "incentivo" (entre aspas bem grandes) para criar outra conta, mas aí acho que já é outra discussão...

**Comment by hkotsubo** [comment]
> voto para observamos a evolução natural do comportamento das pessoas com os anúncios antes de criar essa limitação

> eu gostaria de ver o comportamento evoluindo naturalmente antes de criar essa limitação

É, talvez eu tenha levantando a bola cedo demais.

Podemos deixar a issue "na geladeira" e revisità-la no futuro. Pode ser que com o tempo eu até mude de ideia, dependendo de como as coisas se desenrolarem...

**Comment by aprendendofelipe** [comment]
Ok, vou fechar a issue, e pode ser aberta uma nova abordando algum problema relacionado, se surgir, e que demande um debate para encontrar uma solução 🤝

Se mantermos essa aberta, alguém pode gastar energia implementando isso, já que o título parece definir um requisito. 👍

**Comment by filipedeschamps** [comment]
@hkotsubo muito obrigado por ter criado essa issue e parabéns a todos por essa ótima conversa! 🤝 

Meu intuito em criar aqueles diversos anúncios, fora testar de verdade a feature, foi para **incentivar** e mostrar aos usuários que é possível e até **muito bem vindo** existir anúncios que não são diretamente vinculados a algum produto tradicionalmente **comercial**. Por exemplo quando eu divulgo o [repositório do Fogo do Doom](https://www.tabnews.com.br/filipedeschamps/algoritmo-fogo-do-doom-implementado-em-varias-linguagens-de-programacao) ou vídeos do meu canal como [este sobre aprender qualquer coisa](https://www.tabnews.com.br/filipedeschamps/3-tecnicas-que-eu-uso-para-aprender-a-programar-qualquer-coisa).

Eu **genuinamente** ficarei muito feliz se as pessoas que não possuem interesse em divulgar algo comercial, utilizem este espaço para divulgar seus projetos pessoais, conteúdos ou qualquer coisa que faça ter valido a pena a contribuição que fez de antemão ao TabNews. Inclusive, será muito **saudável** para os espaços publicitários se eles tiverem uma mistura entre anúncios comerciais e não comerciais.

Por fim, quanto mais anúncios, melhor vamos testar a feature, mais variações irão existir e mais informações sobre o comportamento das coisas teremos, até para evoluir a feature para a **direção certa**. Então @hkotsubo seria muito legal para a variação dos anúncios se você também divulgasse o [livro que está listado aqui no seu perfil do TabNews](https://www.tabnews.com.br/kht) 🤝 

---

Em paralelo a tudo isso, [mais um usuário criou um anúncio](https://www.tabnews.com.br/FelipeLC/3-dias-gratis-na-melhor-plataforma-de-ad-spy-da-internet) 🎉

**Comment by hkotsubo** [comment]
@filipedeschamps 
Sim, eu pretendo criar um anúncio do meu livro.

Só estava esperando um pouco pra ver como a funcionalidade era aceita pela comunidade, além de entender um pouco melhor o funcionamento na prática. Mas em breve criarei sim.
