### ISSUE TITLE
Implementação de categorização de posts

### ISSUE THREAD

**Issue by angelo-francisco** [filipedeschamps/tabnews.com.br#1770]
### Descrição

Com o objetivo de facilitar a pesquisa sugiro a implementação de classificação de posts por tags/categoria, assim se quiséssemos pesquisar por algo relacionado a Java por exemplo, filtraríamos a pesquisa, e assim encontraríamos conteúdo relacionado aos posts que procuramos.

obs.: não sei se isso conflitua com os objetivos do tabnews
Espero deferimento positivo!!!🌟

### Sugestão de implementação

A implementação dessa funcionalidade poderia ser feita adicionando um field a mais aos criar novos posts.

obs.: sou desenvolvedor python e django, conheço pouco do mundo react, angular ou de qualquer outro framework js, pois uso ele superficialmente nos meus sistemas.

**Comment by aprendendofelipe** [comment]
@angelo-francisco, obrigado pela sugestão! 💪

Vou fechar a issue por ser duplicada com #742 🤝
