### ISSUE TITLE
inconsistência na contagem de comentários de uma postagem

### ISSUE THREAD

**Issue by mateusvrs** [filipedeschamps/tabnews.com.br#1777]
### Descrição

Boa noite acredito que tenha encontrado a seguinte incosistência no projeto:

Seja na página **_/{username}/conteudos/{page-number}_** ou em qualquer outra rota que mostre uma publicação feita por um usuário de maneira compacta e/ou reduzida, a contagem de comentários está suscetível a disparidade entre o que é realmente mostrado em tela quando se abre a publicação e o número mostrado no contador de comentários. Dessa forma, uma ocorrência é a forma compacta dizer que a publicação tem 2 comentários e no momento que a mesma é aberta nenhum é mostrado em tela. Observe nas imagens a abaixo:

![Screenshot from 2024-08-11 11-23-32](https://github.com/user-attachments/assets/529ee73c-943f-4cff-a60b-66e876ec3d90)

![Screenshot from 2024-08-11 11-23-48](https://github.com/user-attachments/assets/a1dad288-3b43-43c3-b575-a603fbe77426)

Tal erro foi encontrado no ambiente de desenvolvimento e testado brevemente na aplicação real que está em produção e em ambos ocorreu a mesma inconsistência.

### Passos para reproduzir o problema

Para reproduzir, deve-se seguir os passos no ambiente de desenvolvimento:

1. Faça login com a conta user@user.com
2. Crie uma publicação
3. Comente algo nessa publicação
4. Faça logout da conta user@user.com
5. Entre com outra conta qualquer, pode ser a admin@admin.com
6. Crie 2 comentários na publicação no usuário user@user.com, mas agora respondendo o comentário já feito desse mesmo usuário, ou seja, seus comentários começaram um thread de comentários sobre um já existente
7. Faça logout da conta atual, admin@admin.com
8. Entre com a conta user@user.com
9. Apague o primeiro comentário feito, ou seja, o mais em cima
10. Pronto, agora o bug está feito, como o comentário principal da thread foi apagado a thread inteira não é mostrada em tela, entretanto, a contagem de comentários avalia aqueles que não foram apagados mas faziam parte da thread.

Observa-se que a inconsistência pode necessitar da interação entre dois usuários, mas não é estritamente necessário. Além disso, não é preciso que um usuário seja admin, o mesmo apenas foi utilizado no exemplo para não ser necessária a criação de mais usuários no ambiente de desenvolvimento, visto que os dois utilizados já existem para testes.

### Navegadores testados

Chrome, Firefox

### Possível solução

Uma possível solução observada foi a seguinte:

Observou-se após uma análise de código que a maior parte do bug estava relacionado a uma query de banco de dados que não foi construída adequadamente. Dessa forma o primeiro passo será a definição aprimorada de tal no arquivo **_/models/content.js_** na função **findTree**.  Seguindo, será também necessário adicionar uma nova condição de tratamento na **flatListToTree** para que threads de múltiplos comentários deletados não sejam possíveis, ou seja, aparece apenas o comentário pai deletado mais acima possível na ancestralidade. Por fim, o resultado final da query deve ser tratado no Frontend para que seja mostrado o comentário deletado de forma mais simplificada, ou seja, sem o conteúdo e opções de resposta, mas com uma flag indicando sua deleção em um momento anterior.

Para justificar tal método, pode-se observar o modelo do Reddit, que utiliza a mesma ideia aplicada na minha solução proposta, de forma que os usuários consigam ver que existia um comentário anteriormente ali, mas o mesmo foi deletado e ainda existem outros em sua thread que não foram e podem ser de relevância para aqueles que estão lendo a postagem.

**Comment by Rafatcb** [comment]
@mateusvrs obrigado pela descrição bem detalhada! Esse assunto já foi abordado em https://github.com/filipedeschamps/tabnews.com.br/issues/1462 e decidimos concentrar o assunto no issue https://github.com/filipedeschamps/tabnews.com.br/issues/1089, que fala sobre o comportamento similar ao Reddit que você mencionou.

Por isso, vou fechar este issue.

**Comment by mateusvrs** [comment]
Muito obrigado @Rafatcb, não tinha verificado tal issue.
