### ISSUE TITLE
Existem algumas palavras erradas na página de: "Sobre trabalhar como freelancer""

### ISSUE THREAD

**Issue by HallStackStudios** [filipedeschamps/tabnews.com.br#1784]
### Descrição

Na página que fala: "Sobre trabalhar como Freelancer " existem pequenos erros na escrita

### Passos para reproduzir o problema

Acessar a página para contribuidores e apertar em "Sobre como trabalhar como Freelancer"

### Possível solução

Poderia sar mudado o HTML envolvido na página web

**Comment by Rafatcb** [comment]
Imagino que esteja falando sobre apontar erros ortográficos durante a escrita do conteúdo, visto que o conteúdo que você mencionou foi criado por um usuário. Como mencionado em https://github.com/filipedeschamps/tabnews.com.br/issues/970#issuecomment-1845179627, isso faz parte do editor de texto que usamos, o ByteMD, e estamos concentrando as discussões sobre isso em https://github.com/filipedeschamps/tabnews.com.br/issues/648, visto que provavelmente resolveremos isso ao trocar de editor.

Se não foi esse problema que você quis dizer, pode comentar aqui e reabrimos a issue, se necessário.
