### ISSUE TITLE
feat: Notificações de Engajamento em Postagens

### ISSUE THREAD

**Issue by matheusscode** [filipedeschamps/tabnews.com.br#1792]
## Notificações

Implementar um sistema de notificações que permita aos usuários acompanhar o engajamento em suas postagens. As notificações poderiam incluir:
- Comentários recebidos nos posts.
- Menções e respostas a seus respectivos posts e comentários.
- Número de visualizações das postagens.
- Curtidas ou reações nas postagens.

Melhorar a interação entre os usuários e o acompanhamento de suas postagens, promovendo maior engajamento na plataforma.

</br>

## Sugestão de implementação

![Captura de tela 2024-09-09 182425](https://github.com/user-attachments/assets/c88dff0e-440a-42c1-81f2-f7838be769a4)

[Link para o Figma](https://www.figma.com/design/BuuAXcHtg9BvrrPBDPdbq9/TabNews---Notification?node-id=0-1&t=tSvgdDhKF2GttOyx-1)

@filipedeschamps

**Comment by Rafatcb** [comment]
@matheusscode obrigado pela sugestão! Vou fechar este issue porque já temos uma conversa sobre o assunto de notificações em #738 , mas peço, por favor, que coloque sua sugestão de UI lá porque ela pode servir para quando esse recurso for implementado.

**Comment by matheusscode** [comment]
Fala @Rafatcb, tudo bem! Pode deixar, irei adicionar sim!
