### ISSUE TITLE
Bug no cadastro

### ISSUE THREAD

**Issue by huddmax** [filipedeschamps/tabnews.com.br#1794]
### Descrição

Eu encontrei um bug que está me impedindo de criar uma conta, eu estava tentando criar uma conta utilizando o navegador safari no MacBook 
![Captura de Tela 2024-09-12 às 00 04 31](https://github.com/user-attachments/assets/5ceddf5c-e498-4d5e-8985-d83f168ce128)

### Passos para reproduzir o problema

1. Acesse o site pelo safari
2. Tente cadastrar

### Navegadores testados

Safari

**Comment by aprendendofelipe** [comment]
Fala @huddmax, tudo bem?

Pode nos confirmar se você já estava logado com outro usuário quando tentou realizar o cadastro?

Se estiver com o cookie de sessão válido, o sistema identifica qual é o usuário logado, e que ele não tem a feature `create:user`.

---

Aproveitando...

Recomendamos fortemente que não utilize mais de um usuário, pois isso pode resultar em banimento por violação dos nossos [termos de uso](https://www.tabnews.com.br/termos-de-uso).

E se a intenção era realizar algum teste, peço por favor que utilize a versão de homologação do TabNews. No link abaixo você visualiza todas os últimos deploys em homologação. E normalmente algum dos primeiros da lista estarão disponíveis para testes:

https://github.com/filipedeschamps/tabnews.com.br/deployments

**Comment by Edson5-spec** [comment]
O meu está dando erro quando tento trocar o email 
O pograma diz que vai mandar um email de confirmação mais o email nunca chega
