### ISSUE TITLE
"web.config" no conteúdo da publicação impedindo postagem

### ISSUE THREAD

**Issue by SrVinicius** [filipedeschamps/tabnews.com.br#1795]
### Descrição

Ao tentar publicar um conteúdo contendo o trecho: "web.config", recebo o seguinte erro: 

![image](https://github.com/user-attachments/assets/f7a6f033-ce12-4bdc-a393-07020f634683)

O erro persiste em navegadores como Safari (desktop e mobile), Chrome e Opera GX. 

Ao retirar o "." do trecho "web.config", deixando-o como "web config",  a publicação é feita normalmente. 

Ao utilizar um "teste.php", por exemplo, a submissão do conteúdo ocorre normalmente.

### Passos para reproduzir o problema

Adicionar o trecho "web.config" em alguma publicação 

Segue exemplo:

![image](https://github.com/user-attachments/assets/b93e0ac5-10e5-4a59-9690-77f303d2ad26)

### Navegadores testados

Chrome, Safari, Outro

**Comment by aprendendofelipe** [comment]
@SrVinicius, obrigado por reportar! 💪

A proteção da Cloudflare bloqueia certas sequências de bytes, então a saída é escrever diferente mesmo, como você fez, pois não podemos abrir mão dessa proteção.

Por isso, vou fechar a issue 🤝
