### ISSUE TITLE
Guardar os posts que vc mais gosta

### ISSUE THREAD

**Issue by Edson5-spec** [filipedeschamps/tabnews.com.br#1796]
### Descrição

Eu acho que seria legal ter uma parte onde os usuários do tabnews consigam guardar os posts que mais gostam pra poder aceder mais tarde sem ter que procurar.

**Comment by kaique-soares** [comment]
@Edson5-spec obrigado pela sugestão :muscle: 

- **Acho** que isso já está sendo discutido na issue #645 

O que acha de fechar essa issue aqui e concentrar a discussão lá?

**Comment by Edson5-spec** [comment]
Sem problema
