### ISSUE TITLE
Nao consigo criar um comentario: Requisição bloqueada pelo Firewall

### ISSUE THREAD

**Issue by blmayer** [filipedeschamps/tabnews.com.br#1797]
### Descrição

Bom dia.

Estou tentando criar um comentario em resposta a um comentario no meu post 

https://www.tabnews.com.br/blmayer/pitch-estou-criando-uma-distro-linux-minimalista

porem recebo esse erro:

```
Requisição bloqueada pelo Firewall. Verifique seu equipamento e os dados enviados. Informe ao suporte o valor (cf-ray: 8c4974b89e0ea52b-GRU)
```

Poderiam me ajudar a entender?

Obrigado.

### Passos para reproduzir o problema

1. Crie algum conteudo.
2. espere alguem criar um comentario
3. tentar responder a esse comentario

### Navegadores testados

Outro

**Comment by Rafatcb** [comment]
@blmayer a Cloudflare bloqueia alguns termos específicos com o objetivo de proteger o site. Veja um exemplo de problema similar aqui: https://github.com/filipedeschamps/tabnews.com.br/issues/1619

Para descobrir o ponto exato do problema, você pode tentar criar uma publicação sem título com um trecho do seu comentário. Se der erro de que precisa preencher o título, você sabe que aquela parte do comentário está OK. Se der erro da Cloudflare, vá diminuindo o texto até encontrar qual a parte problemática.

No link acima, o problema era usar o `wget https://...` formatado numa única linha. Em outro caso mais recente (https://github.com/filipedeschamps/tabnews.com.br/issues/1795), o problema era o texto `web.config`.

**Comment by blmayer** [comment]
Esse eh o texto que quero publicar:

```
Muito obrigado!

Eu me baseei na LFS (Linux From Scratch), que eh basicamente uma distro generica, tudo compilado. Mas simplifiquei muitas coisas, meio que indo pra mesma direcao da Alpine Linux, outra distro que adoro. Provavelmente fiz alguns erros que vou descobrir mais pra frente.

Algumas diferencas das demais distros, alem das indicadas acima:

- Nao usa initrd
- a pasta root fica em /home/root, como os demais usuarios
- nao uso a pasta /usr, tudo eh direto na /
- usa o /etc/passwd ao inves de /etc/shadow
- nao necessita de bootloaders nos sistemas com EFI

A ideia eh utilizar melhor as ferramentas ja existentes nos sistemas para torna-lo melhor, por ex. uma das coisas que quero fazer eh utilizar o /etc/issue e o /etc/login.defs para uma melhor experiencia de login. E por ai vai.

Vou mante-los informados.
```

**Comment by aprendendofelipe** [comment]
@blmayer, pode tentar publicar novamente e nos retornar se deu certo?

**Comment by blmayer** [comment]
Deu certo!

Obrigado senhores!
