### ISSUE TITLE
Rendeização da pré visualização dos diagramas mermaid ao escrever um comentário

### ISSUE THREAD

**Issue by gabolera** [filipedeschamps/tabnews.com.br#1799]
### Descrição

Problema de rendeização dos diagramas no momento de pré visualizar um comentário com os diagramas mermaid.

![image](https://github.com/user-attachments/assets/e631fef6-c5f2-4ccc-86e8-50b4656cc6db)

https://github.com/user-attachments/assets/49530e1f-24b0-42f5-a6ad-3eb941c3806d

(Testado com chrome e firefox)

### Passos para reproduzir o problema

1. Inicie a escrita de um comentário
2. Selecione a opção "Timeline" ou outros diagramas.
3. Abra a previsualização do comentário verá que não foi renderizado 
4. Abra uma nova aba no chrome (ou tire o foco do seu navegador clicando na barra de tarefas do windows)
5. Volte para a aba do tabnews do comentário e tudo estará renderizado certo

### Navegadores testados

Chrome, Firefox

**Comment by aprendendofelipe** [comment]
@gabolera, obrigado por relatar! 💪

Executar os passos no [playground](https://bytemd.js.org/playground/) do ByteMD causa o exato mesmo problema, então vou fechar aqui e isso já vai criar um link pra cá na #648
