### ISSUE TITLE
Não consigo trocar o email da minha conta 

### ISSUE THREAD

**Issue by Edson5-spec** [filipedeschamps/tabnews.com.br#1800]
### Descrição

Quando tento trocar o email da minha conta o tabnews diz que vai mandar um email de confirmação mais o email nunca chega.

### Passos para reproduzir o problema

Eu fui no editar perfil e tentei mudar o email 
Tentei no telemóvel

**Comment by aprendendofelipe** [comment]
Descartando algum problema temporário com o serviço de email (do nosso ou do seu lado), também não vai ser enviado nenhum email se você estiver tentando usar um endereço que já está vinculado com outro usuário do TabNews, seja conta ativa ou banida.

Por acaso você já possui conta criada com esse email que está tentando usar? Tentou [recuperar a senha](https://www.tabnews.com.br/cadastro/recuperar) da outra conta?

**Comment by Edson5-spec** [comment]
Não tinha criado nenhuma conta com esse email 
Eu criei um email novo e queria trocar tudo para esse email mais o tabnews não tá mandado o email de confirmação

**Comment by aprendendofelipe** [comment]
@Edson5-spec, não é problema com o envio de email, mas sim por estar tentando cadastrar um endereço já cadastrado. A mensagem só diz que o email será enviado porque se dissesse que o endereço está em uso seria uma brecha de segurança.

Se não foi um usuário banido, tenta recuperar a senha. Se foi banido, pode tentar também, pois irá receber o email de recuperação, mas não vai conseguir acessar a conta.

Vou fechar a issue, pois o processo de alteração do email está ocorrendo normalmente, com diversos casos recentes.

Se tiver alguma dificuldade específica, envia email para `contato@tabnews.com.br`. 🤝
