### ISSUE TITLE
Problema na exibição do texto "Retornar ao topo" do botão (ao passar o mouse sobre ele) quando a página não chegou ao fim do seu conteúdo.

### ISSUE THREAD

**Issue by zehguilherme** [filipedeschamps/tabnews.com.br#1802]
### Descrição

Encontrei um problema na exibição do texto do botão de retornar ao topo da página (apenas desktop).

O texto é exibido acima do botão somente quando a página ainda chegou ao final do seu conteúdo!

# Página que não chegou ao final do seu conteúdo

![image](https://github.com/user-attachments/assets/8191660d-27cb-4aff-bf3a-6be11d28bd44)

# Página que chegou ao final do seu conteúdo

![image](https://github.com/user-attachments/assets/86ee5608-9b0c-401d-a587-a6b81a5abc05)

### Passos para reproduzir o problema

Em qualquer post (estando logado ou não) faça o teste da visualização do texto passando o mouse sobre ele nas 2 situações mencionadas acima (página no meio do seu conteúdo e página no final do seu conteúdo).

### Navegadores testados

Chrome, Microsoft Edge

### Possível solução

O que poderia ser feito é exibir o texto sempre no topo do botão, como já é feito no momento de quando a página já se encontra no final do seu conteúdo.

**Comment by emerson-oliveira** [comment]
@aprendendofelipe , @Rafatcb . Me surgiu uma dúvida, onde ficar o  `@tabnews/ui` é um repositorio novo ?

**Comment by Rafatcb** [comment]
@emerson-oliveira é sim, está neste repositório: https://github.com/aprendendofelipe/tabnews/.

Acho que para corrigir este bug não precisa mexer no outro repositório. Pensei em indicar para este `Tooltip` renderizar sempre para o norte `tooltipDirection="n"`, mas não testei. [Documentação do `IconButton`](https://primer.style/components/icon-button/react/alpha)

**Comment by emerson-oliveira** [comment]
> @emerson-oliveira é sim, está neste repositório: https://github.com/aprendendofelipe/tabnews/.
> 
> Acho que para corrigir este bug não precisa mexer no outro repositório. Pensei em indicar para este `Tooltip` renderizar sempre para o norte `tooltipDirection="n"`, mas não testei. [Documentação do `IconButton`](https://primer.style/components/icon-button/react/alpha)

Ótimo! Vou testar e qualquer novidade aviso no chat
