### ISSUE TITLE
 Usar Umami para Análises de Postagens

### ISSUE THREAD

**Issue by mthmcalixto** [filipedeschamps/tabnews.com.br#1803]
### Olá, pessoal!

Seria legal usar [API do Umami](https://umami.is/docs/api) para analisar as postagens dos usuários? Views de um tópico etc... o bom é que não precisa informar um banner de cookies.

**Comment by kayon-ariel** [comment]
Mostrar um contador de visualizações nos posts seria realmente muuuito útil.

**Comment by mthmcalixto** [comment]
> Mostrar um contador de visualizações nos posts seria realmente muuuito útil.

Acredito que seja possível fazer já que o Umami cobra apenas por eventos, são cliques em locais do site, ele não cobra pela quantidade de views em uma página.

**Comment by mthmcalixto** [comment]
Aqui um exemplo de uso:

**Comment by mthmcalixto** [comment]
Aqui um exemplo de uso:

![image](https://github.com/user-attachments/assets/05d862f0-2b7a-4460-ac16-195f09e03530)

**Comment by mthmcalixto** [comment]
@Rafatcb Exemplo de chamada:

https://api.umami.is/v1/websites/id-website/metrics

Passando Params:
```
startAt: "timestamp"
endAt: "timestamp"
type: "url"
url: "/post/bla-bla"
```

Retorno:

```
[
  {
    "x": "/post/bla-bla",
    "y": 215
  }
]
```

**Comment by aprendendofelipe** [comment]
@mthmcalixto, obrigado pela sugestão!

Vou fechar aqui para que o debate se concentrar na #1115 🤝
