### ISSUE TITLE
unknown flag: --env-file

### ISSUE THREAD

**Issue by rodrigoKulb** [filipedeschamps/tabnews.com.br#1808]
### Descrição

Faz muito tempo que não baixo o repositório na minha maquina, fiz pelo meu fork depois pelo repositório do Filipe ambos apresentaram o mesmo problema. **unknown flag: --env-file**

### Passos para reproduzir o problema

01 - git clone https://github.com/filipedeschamps/tabnews.com.br/
02 - cd tabnews.com.br/
03 - npm install
04 - npm run dev
![Captura de tela em 2024-10-29 23-47-02](https://github.com/user-attachments/assets/9f8b641e-f7f8-449a-8efa-dabcec743b5e)

**Comment by aprendendofelipe** [comment]
Fala Rodrigão! Bom te ver de novo por aqui! 💪

Alguma chance de estar usando alguma versão antiga do Docker que ainda não aceitava `--env-file`?

Será que precisamos atualizar os requisitos de versão do Docker no README?

**Comment by aprendendofelipe** [comment]
> Uma questão que percebi é que a chamada no docker-compose pelo menos aqui no Linux é com - e não espaço.

Se não for apenas pela versão antiga, então você pode estar no cenário 3 do link abaixo, que não é mais recomendado, então sugiro tentar instalar o compose pelos métodos 1 ou 2 da documentação (Docker Desktop ou Compose plugin):

https://docs.docker.com/compose/install/

**Comment by rodrigoKulb** [comment]
show realmente estava faltando o docker-compose-plugin são coisas diferentes:

![Captura de tela em 2024-10-30 13-08-30](https://github.com/user-attachments/assets/fd6275e0-962b-49b2-beda-82dcfbf1dc77)

**Comment by rodrigoKulb** [comment]
finalizando a issue!
