### ISSUE TITLE
Salvar/Arquivar publicações no estilo Medium

### ISSUE THREAD

**Issue by Alan-Graton** [filipedeschamps/tabnews.com.br#1809]
### Descrição

Acho que seria interessante ter uma feature para salvar os posts em algum tipo de pasta assim como o Medium faz. Senti essa necessidade ao encontrar posts muito interessantes e sentir um _medo_ de não lembrar o título do post e não conseguir achá-lo novamente.

Sei que é possível achar posts já visitados pela pag de comentários publicados, mas sinto que o ideal seria ter algo focado nessa feature.

## Exemplo - Medium

Segue exemplo de publicações salvas/arquivadas no Medium

![image](https://github.com/user-attachments/assets/518d0243-b72c-43d1-b59e-aaf393043099)

**Comment by Rafatcb** [comment]
@Alan-Graton obrigado pela sugestão! Já temos um issue sobre isso (https://github.com/filipedeschamps/tabnews.com.br/issues/645), então vou fechar este. Recomendo ler a discussão que ocorreu nos comentários e complementar algo, caso queira.

**Comment by Alan-Graton** [comment]
@Rafatcb Opa, de boa ^-^ Tinha verificado se já havia alguma solicitação parecida com a minha, mas acho que não vi a issue #645. Valeuu!
