### ISSUE TITLE
Colocar o campo fonte como metatag canonical para informar aos motores de buscar qual é o conteúdo original

### ISSUE THREAD

**Issue by feliperfranco** [filipedeschamps/tabnews.com.br#1815]
### Descrição

Notei que todo post a metatag canonical é a propria url do post no tabnew.

Vocês podem adicionar um campo opcional para informar qual é a canonical url ou usar o campo fonte como canonical url

**Comment by aprendendofelipe** [comment]
@feliperfranco, obrigado pela sugestão!

Vou fechar aqui para o debate se concentrar na issue relacionada #860
