### ISSUE TITLE
Problemas de caracteres | Editor Markdown

### ISSUE THREAD

**Issue by Jetrom17** [filipedeschamps/tabnews.com.br#1816]
### Descrição

Problema de caracteres ao escrever em makdown em editor do Tabnews.

![bug2](https://github.com/user-attachments/assets/de714e05-6149-49bc-a613-146ff6b124c7)

### Passos para reproduzir o problema

![bug1](https://github.com/user-attachments/assets/29fe1f52-78af-4329-921c-303d5a820ccd)

Digitar no editor de texto no Tabnews: `$ test $` ou `$ test \$`.

### Navegadores testados

Chrome

**Comment by aprendendofelipe** [comment]
Fala @Jetrom17, não sei se entendi qual é o bug, pois parece estar tudo de acordo com o esperado.

Lembrando que o cifrão (`$`) é o [caractere usado para escrever fórmulas matemáticas](https://github.com/micromark/micromark-extension-math#syntax), então se precisar adicionar dois deles no seu texto, é preciso usar o `&#36;` em pelo menos um deles, caso contrário tudo que estiver no meio deles será considerado uma equação.

Exemplos:

```
$ matematica = a + bx $
$ erro de sintaxe \ $
&#36; não cria equação matemática &#36;
$ também não cria equação matemática &#36;
```

Resulta em:

![image](https://github.com/user-attachments/assets/2142d736-fd92-4575-8659-108a15fae22f)

**Comment by Jetrom17** [comment]
> Fala @Jetrom17, não sei se entendi qual é o bug, pois parece estar tudo de acordo com o esperado.

@aprendendofelipe obrigado pelo retorno.

![Screenshot_20241112-133238.png](https://github.com/user-attachments/assets/dafa52ec-24fd-4be9-8555-70fbf4b0d453)

Imagem aparece um texto que irei publicar futuramente, mas o editor detecta como cálculo matemático, segundo você. Algo que quero que apareça como texto literal.

**Comment by aprendendofelipe** [comment]
É preciso respeitar a sintaxe do nosso editor, que usa `$` para definição de fórmulas matemáticas.

Imagino que o que você pretende escrever seja como abaixo:

```
...ambiente &#36;HOME representa...
...como `cd $HOME`
```

ou


```
...ambiente \$HOME representa...
...como `cd $HOME`
```

e ambos resultam em

![image](https://github.com/user-attachments/assets/a88f0896-c748-447e-bb37-c037d8e46cc5)


Como não é um bug, mas apenas uma característica do nosso editor/visualizador de markdown, estou fechando a issue 🤝
