### ISSUE TITLE
Alterar limite de 20000 caracteres ao publicar um conteúdo

### ISSUE THREAD

**Issue by iamseki** [filipedeschamps/tabnews.com.br#1818]
### Descrição

Recentemente tomei coragem e resolvi escrever minha primeira publicação na plataforma e dei de cara com:

```json
{
    "name": "ValidationError",
    "message": "\"body\" deve conter no máximo 20000 caracteres.",
    "action": "Ajuste os dados enviados e tente novamente.",
    "status_code": 400,
    "error_id": "df7a4bcc-d68f-4767-a51c-af30ca850e95",
    "request_id": "b5f84fdf-d646-4c11-be30-81b5bcdd1582",
    "error_location_code": "MODEL:VALIDATOR:FINAL_SCHEMA",
    "key": "body",
    "type": "string.max"
}
```

Esse é o conteúdo que gostaria de ter publicado: https://github.com/iamseki/postgresql/blob/main/work_mem/tabnews.md e possui  33515 caracteres, cerca de 33kB.

IMHO dependendo do quão profundo o autor quiser ir no conteúdo, 20k como hard limit me parece baixo. Minha sugestão pragmática seria subir esse valor, talvez dobrar para 40k?

E ficou a dúvida, existe algum motivo especial pro valor ser 20k? Ter mais previsibilidade em termos de alocação de storage? Defesa contra algum usuário mal intencionado flodar com um texto na casa dos GB?

### Sugestão de implementação

Imagino que a abordagem simples seria subir esse valor [aqui](https://github.com/filipedeschamps/tabnews.com.br/blob/c747083cea3380c538dcf570e256a16693da3a96/infra/migrations/1649621949432_create-content-table.js#L33-L37) e [aqui](https://github.com/filipedeschamps/tabnews.com.br/blob/c747083cea3380c538dcf570e256a16693da3a96/models/validator.js#L249), lmk se eu estiver errado.

Outra possibilidade seria aplicar algum algoritmo de compressão como Brotli, aqui tem um [benchmark](https://www.ghusse.com/redis/node/compress/does-it-worth-compressing-large-json-in-redis/#brotli-compression) comparando com outros algoritmos, mas também tem seus tradeoffs e não sei dizer se vale a pena mas fica aqui a provocação.

**Comment by aprendendofelipe** [comment]
@iamseki, a escolha do limite de 20 mil caracteres foi definida [nesta discussão](https://github.com/filipedeschamps/tabnews.com.br/pull/262/files#r851394172) e tem se mostrado adequada para o propósito do TabNews.

É verdade que certos conteúdos podem não caber nesse limite, mas remover completamente qualquer restrição não seria uma solução viável e nem interessante. Esse limite tem sido importante para manter a experiência do usuário consistente, tanto na criação quanto na leitura dos conteúdos.

O limite atual incentiva os autores a organizarem e priorizarem suas ideias, garantindo que as publicações sejam focadas no que realmente importa. Para conteúdos mais extensos ou com diferentes perspectivas, há sempre a possibilidade de dividi-los em múltiplas publicações, o que também pode aumentar o engajamento dos leitores.

Além disso, o limite desafia os autores a utilizarem recursos do Markdown de maneira eficiente, como usar tabelas para organizar dados em vez de inserir sequências de caracteres (espaços, pontos etc.) para formatação.

Manter o limite de 20 mil caracteres me parece adequado para um bom equilíbrio entre flexibilidade para o autor e uma experiência clara e acessível para os leitores.

Faz sentido?

**Comment by Rafatcb** [comment]
@iamseki já enfrentei essa barreira dos 20 mil caracteres algumas vezes. Artigos muito longos são menos lidos, porque demandam mais tempo do leitor. O seu não parece longo, mas tem muito código com 4 espaços de identação, e o código causa um aumento significativo na contagem de caracteres (já passei por isso também).

Acho que se você mudar os 4 espaços para 2, e substituir o query plan por uma imagem do planejamento com um link para um gist (ou outro lugar que considere adequado) com todos os detalhes, já conseguirá ter menos de 20 mil caracteres. Vi que você cita um site que faz isso e colocou uma print dele, então seria só uma questão de adaptar essa parte.

**Comment by iamseki** [comment]
@aprendendofelipe Obrigado por compartilhar a discussão e @Rafatcb Obrigado pelas dicas! 

Se entendi bem a [discussão](https://github.com/filipedeschamps/tabnews.com.br/pull/262/files#r851394172), a limitação do PostgreSQL para tipos `TEXT` é em termos de storage e não caracteres, [cerca de 1 GB](https://www.postgresql.org/docs/current/datatype-character.html#DATATYPE-CHARACTER), dá pra testar com:
 
```sql
CREATE TABLE blog_posts (
    id SERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content text NOT null
);

INSERT INTO blog_posts (title, content)
VALUES (
    'Sample Blog Post',
    repeat('A', 1024 * 1024)
    -- repeat('A', 1024 * 1024 * 512) || repeat('B', 1024 * 1024 * 512) -- ESTRESSA CENÁRIO COM O LIMITE DE 1 GB
);

SELECT 
	title, 
	pg_size_pretty(pg_column_size(content)::bigint), 
	char_length(content),
	length(content)
FROM blog_posts
WHERE id = 1;

---
id|title           |pg_size_pretty|char_length|length |
--+----------------+--------------+-----------+-------+
 1|Sample Blog Post|12 kB         |    1048576|1048576|
```

Aparentemente 1kk de caracteres foi armazenado tranquilamente, entendo que remover a restrição é uma má ideia e que o limite estimula a criação de publicações menores, mas ainda acho esse valor conservador e que o ponto do engajamento e tempo de leitura é muito subjetivo, eu particulamente adoro ler posts grandes e auto-contidos, também acho pouco ergonômico ter que escrever o conteúdo e lembrar de identar com 2 espaços em vez de 4 pra não correr o risco de bater no limite. Eu vou ajustar o post pra se adequar ao limite de 20k anw, caso publicações mais densas e profundas se torne relevante para plataforma num futuro plz reabram essa discussão :smile:
