### ISSUE TITLE
usuario com 5 mil de cashcoins que apenas abusa da plataforma

### ISSUE THREAD

**Issue by RodrigoDornelles** [filipedeschamps/tabnews.com.br#1821]
### Assunto

Outro

### Dúvida

existe uma issue #877 sobre reporte de usuarios/postagens, bom, é um recurso importante, e ao meu ver tem muito usuário que não deveria estar na plataforma, exemplo é este usuário, **ele apenas usa um google translate e cola no tabnews**, mesmo colocando como a fonte a postagem exatamente original. _(isso é literalmente plagio)_ usuários leigos sempre dão voto cima nesse tipo de postagem pois o autor não especifica que é uma tradução. isso deveria continuar sendo permetido? para mim é uma brecha para pessoa poder postar anuncios facilmente sem esforço.

[![rafael tabnews plagio](https://github.com/user-attachments/assets/c0b79cee-aef7-4852-9665-0dbc127ba7b6)](https://www.tabnews.com.br/rafael/conteudos/1)

**Comment by Rafatcb** [comment]
Rodrigo, denúncias específicas devem ser feitas pelo e-mail `contato@tabnews.com.br`.

Este usuário sou eu e nenhuma publicação é produzida "apenas usando o Google Tradutor e colando no TabNews". Inclusive, sempre é mencionado que o conteúdo presente é proveniente da fonte, às vezes com adições minhas no meio dele quando me sinto confortável com o assunto, às vezes eu mudo a ordem do conteúdo para fazer mais sentido, não ficar tão longo etc. Se é um conteúdo mais simples e direto ao ponto, faço poucas modificações.

Acho que está claro quando o conteúdo não é meu. Por exemplo, minhas três últimas publicações:

> https://www.tabnews.com.br/rafael/coisas-que-voce-nao-deveria-usar-no-postgresql
> Na Wiki do PostgreSQL existe uma [lista de erros comuns](https://wiki.postgresql.org/wiki/Don't_Do_This) (...)
>
> (...) vale a pena ler o documento completo na fonte, visto que vou destacar apenas alguns tópicos aqui.

> https://www.tabnews.com.br/rafael/como-o-uber-atualizou-sua-infraestrutura-mysql-da-versao-5-7-para-8-0
> Alguns engenheiros do Uber compartilharam esse processo no blog da empresa, e eu resumi os principais pontos.

> https://www.tabnews.com.br/rafael/41-dicas-de-sql-para-desenvolvedores-solucoes-praticas-para-desafios-comuns
> Vou citar algumas dicas nesta publicação, mas recomendo conferir a lista completa no [livro gratuito](https://sqlfordevs.com/ebooks/next-level) (em troca do seu e-mail) e explorar algumas dicas com mais detalhes no [site](https://sqlfordevs.com/tips).

Realmente não ficou claro qual é o problema aqui. De todo modo, vou fechar o issue por não ser um assunto relacionado ao repositório.
