### ISSUE TITLE
Não está ocorrendo o feedback de postagem lida

### ISSUE THREAD

**Issue by horticonecta** [filipedeschamps/tabnews.com.br#1824]
### Descrição

Gravei um vídeo demonstrando o erro, mas basicamente ao clicar, ler ou interagir com uma publicação, ao retornar para a aba de recentes ou relevantes, não está ocorrendo o feedback de conteúdo lido. 

https://github.com/user-attachments/assets/917e198c-8dce-4642-bec2-2b3dea75aaa1

### Passos para reproduzir o problema

1 - Acesse o TabNews.
2 - Clique em uma postagem.
3 - Interaja com ela ou não.
4 - Retorne para a aba correspondente a postagem, relevantes ou recentes. 

### Navegadores testados

Chrome

**Comment by tintinthedev** [comment]
Opa. Não sei o que rolou aí, mas segui os passos aqui e tá funcionando como deveria, o texto das postagem que acesso fica "cinzento", indicando que já as acessei. Talvez tenham resolvido o bug antes mesmo de ver a issue.

**Comment by horticonecta** [comment]
Hoje abri o tabnews e o erro não ocorreu, provavelmente foi um erro momentâneo mesmo.
