### ISSUE TITLE
Possivel inconsistencia no cadastro de usuário

### ISSUE THREAD

**Issue by FelipeIgansi** [filipedeschamps/tabnews.com.br#1833]
### Assunto

Outro

### Dúvida

Hoje, fui me cadastrar no TabNews, pois não lembrava se já havia realizado cadastro anteriormente ou não, então fiz o processo como deve ser feito, inseri user name, email e senha existentes e válidos. E nenhuma mesagem de aviso quanto ao cadastro já existir foi apresentada, apenas fui redirecionado para a tela dizendo que o cadastro deu bom, e a seguinte mensagem: "Caso o e-mail esteja disponível, você receberá um link para confirmar seu cadastro e ativar a sua conta."

Mas pensando do ponto de vista do usuário, creio eu que seria melhor a identificação de que este email JÁ está cadastrado, neste exemplo, e o avisando disso, pois para mim por exemplo, até que eu me lembrasse de que eu no passado já poderia ter me cadstrado, me tomou um tempinho procurando um email de confirmação, que não chegou :(

Enfim ... abro isso para discussão não é um bug, mas achei meio estranho não fazer como geralmente é feito de identificar o e-mail cadastrado e exibir uma mensagem de aviso por exemplo.

![print tela de confirmacao cadastro tabnews](https://github.com/user-attachments/assets/eed02de9-7153-47f5-9b6b-fa907a358861)

**Comment by aprendendofelipe** [comment]
Fala @FelipeIgansi,

Nós não podemos deixar pública a informação de que um email já está ou não cadastrado. Apenas o dono do endereço de email pode saber isso. Por isso o aviso:

> "__Caso o e-mail esteja disponível__, você receberá um link para confirmar seu cadastro e ativar a sua conta."

O endereço pode já estar em uso, ou pode estar vinculado com usuários excluídos/banidos, e nesses casos nenhum email deve ser enviado.

**Comment by FelipeIgansi** [comment]
Ah entendi ...

Então nesse caso, uma duvida genuina. Como funciona o armazenamento dos usuários do site?
Agora fiquei curioso, de como funciona o armazemento já que é uma aplicação open source.
