### ISSUE TITLE
Ideias para página de "Em construção"

### ISSUE THREAD

**Issue by luantoningalvan** [filipedeschamps/tabnews.com.br#23]
Gostaria de usar essa issue para propor a discussão acerca da página "Em construção"

Eu tive uma ideia interessante.
Uma ilustração [Parallax](https://en.wikipedia.org/wiki/Parallax_scrolling) com pessoas trabalhando (desenhos) e na cara de cada pessoa ficaria o avatar de quem participa. Ao passar o mouse pelo avatar pausa a animação e aparece o nome com o link do github.

Isso ficaria ocupando 1/3 da tela na parte de baixo e o restante acima um texto com os dizeres "Em construção" e algum subtítulo

Exemplo de um site usando um fundo que eu imagino: 
[https://www.drugtreatment.com/](https://www.drugtreatment.com/)

**Comment by vladimiremi** [comment]
Caramba! Por que eu não participei disso? Eu não sabia como funcionava essa dinâmica de milestones. Aprendi agora no curso.dev, estou fascinado com tudo isso. Dá pra ver dos primórdios como tudo aconteceu.

**Comment by aprendendofelipe** [comment]
> Caramba! Por que eu não participei disso? Eu não sabia como funcionava essa dinâmica de milestones. Aprendi agora no curso.dev, estou fascinado com tudo isso. Dá pra ver dos primórdios como tudo aconteceu.

É relativo, você pode começar agora e, daqui alguns anos, poder dizer que estava aqui desde os primórdios. 💪

**Comment by vladimiremi** [comment]
Pois é isso que vou fazer. Não consigo parar de ler o que está nas issues.

**Comment by afqbrito** [comment]
Tembém estou chegando agora, via 'curso.dev'.

Sensacional poder vislumbrar tudo isso!

Parabéns a toda a galera que tem participado dessa construção!

**Comment by grecoww** [comment]
Chegando aqui pelo curso.dev, e é como entrar no modo espectador do minecraft e ver a "história sendo feita" 😆
