### ISSUE TITLE
Datas, fontes e fakenews. O que fazer? 

### ISSUE THREAD

**Issue by geovani-brito** [filipedeschamps/tabnews.com.br#27]
Estive lendo o diário e as discussões do projeto e, pelo menos até onde pude acompanhar, acho que ainda não foi discutido alguns pontos que, pelo menos eu, acho relevante quando se trata de consumir conteúdos na internet. 

**O primeiro problema:** informação sem data pode confundir as pessoas. 

Imagine o seguinte cenário: você lê a notícia de que um bug crítico foi encontrado no Windows. Você não sabia disso. Só que essa notícia já tem alguns meses e o bug já foi corrigido. Isso pode te causar uma sensação de urgência desnecessária.  Sendo assim, eu gostaria de levantar algumas questões.

Eu vi que nos layouts testados existe o tempo em que aquela notícia foi postada. Mas não informa de quando é aquela notícia. 

- Se uma pessoa, por engano, postar uma notícia antiga, como ela (a notícia) será tratada? 
- Ficará esperando que alguém note que ela é antiga e avisará ao autor?
- O procedimento padrão será apagar a notícia ou deixar que ela vá perdendo relevância na medida que recebe poucos ou nenhum tabcoins?

**Segundo problema:** as fakenews. 

- O que acontece se uma notícia se mostrar falsa? 
- Só o autor poderá apagar a publicação ou existirá alguma tipo de moderação?
- A notícia receberá alguma tag de "fakenews" como o Facebook anda fazendo? 

Isso me leva também a pensar na fonte da notícia. Uma notícia pode ter mais de uma fonte. Às vezes uma fonte possui mais informações do que a outra. E às vezes as fontes são até conflitantes. 

- Existirá alguma forma de agrupar as mesmas notícias de fontes diferentes como acontece no Google Notícias? 
- Existirá algum rank de fontes confiáveis? 

Resolvi levantar essas questões porque esse é o tipo de coisa que me preocupa bastante quando estou consumindo informação na internet. E para que o TabNews se torne um veículo importante na comunidade de TI acho  importante que o conteúdo dele seja extremamente confiável ou que pelo menos ele mostre que tem o compromisso de oferecer conteúdo relevante e confiável ao ter ferramentas que evitem os problemas que apontei. 

E para ficar claro, não estou esperando que as pessoas postem conteúdos duvidosos por má intenção. Estou considerando o engano mesmo. Acho que todos nós, alguma vez na vida, postou nas redes sociais algum conteúdo desatualizado ou que era fakenews. A gente se engana. É normal.

**Comment by Rafatcb** [comment]
Estou removendo a label `repescar` do issue e criando esse comentário para termos um histórico do motivo dessa decisão.

Como esse issue já foi mencionado no #877, podemos tratar os casos extremos por meio de sinalizações após elas serem implementadas. Para os casos mais simples, os votos negativos por meio dos TabCoins tem funcionado bem até hoje, além de comentários que apontam algo específico.
