### ISSUE TITLE
Extensão do tabnews para navegador

### ISSUE THREAD

**Issue by brunofamiliar** [filipedeschamps/tabnews.com.br#3]
Pessoal, sei que ainda é cedo para pensar em algo do tipo, mas desde que o Filipe divulgou o projeto eu não paro de pensar nessa ideia. Já viram um site chamado [Dailly Dev](https://daily.dev/)? Ele basicamente agrega notícias de diversas fontes e disponibiliza de uma forma acessível cada vez que o usuário abre uma nova aba no navegador; isso na minha opinião é fantástico! Que tal nós trabalhar numa ideia semelhante a essa? 😄

**Comment by Rafatcb** [comment]
Estou removendo a label `repescar` do issue e criando esse comentário para termos um histórico do motivo dessa decisão.

Conforme o projeto andou, acabamos optando por utilizar este repositório apenas para a API e para a "interface oficial" (o site https://www.tabnews.com.br/), permitindo que outras pessoas criem interfaces alternativas como aplicativos e extensões.
