### ISSUE TITLE
Upload de imagens

### ISSUE THREAD

**Issue by ricardomaia** [filipedeschamps/tabnews.com.br#308]
Quando fiz minha primeira publicação no TabNews senti falta de um meio para fazer o upload de imagens. Sendo assim, apelei para o serviço imgur.com e fiz a referência no Markdown.

Uma similaridade que eu notei entre o imgur.com e o GitHub é que ambos suportam o upload de imagens de forma bastante rápida, "colando" o conteúdo do clipboard.

No GitHub, por exemplo, se você cola uma imagem no editor Markdown ele automaticamente faz duas coisas, o upload da imagem e insere a referência para ela em formato markdown no texto do editor, como no exemplo abaixo.

```
![image](https://user-images.githubusercontent.com/0101001/fad7fb44-ea68-4a52-b2ed-01c5a861ca0d.png)
```
Imagino que o primeiro parâmetro seja um identificador do usuário. O segundo é o nome da imagem no formato UUID (universally unique identifier). 

Achei a referência a seguir bem interessante:
https://ourcodeworld.com/articles/read/491/how-to-retrieve-images-from-the-clipboard-with-javascript-in-the-browser

Contudo na implementação da API faz-se necessário observar limitações do tipo de conteúdo, limites de tamanho e duplicidade, opção ou não de excluir etc.

Em se tratando de recursos de infraestrutura, talvez limitar o uso de disco por usuário ou a Vercel teria uma opção de uso ilimitado sem custos adicionais?

De toda forma penso ser de extrema importância o upload de imagens, pois isso certamente agrega valor ao conteúdo publicado, assim como os diagramas [Mermaid](https://mermaid-js.github.io/mermaid)

**Comment by alan-chris** [comment]
Acho valido esta issue de upload de imagens, fui criar um post e deixei sem imagem pela dificuldade em colocar uma

**Comment by fabiobrasileiroo** [comment]
Olá, pessoal! Tentei implementar essa funcionalidade: https://github.com/filipedeschamps/tabnews.com.br/pull/2011. Assim como vocês, eu também sentia falta do upload de imagens e, finalmente, tive motivação e coragem para contribuir com o projeto hehe.

**Comment by hisirdox** [comment]
Esperar alguém revisar essa pr.
