### ISSUE TITLE
Milestone 5 - Lançamento

### ISSUE THREAD

**Issue by filipedeschamps** [filipedeschamps/tabnews.com.br#493]
Turma, chegou a hora de agitar o repositório de novo 😍 então segue abaixo a primeira versão do draft da Milestone 5, onde ao longo dos dias da semana irei criar e separar em issues e cadastrar dentro da [Milestone](https://github.com/filipedeschamps/tabnews.com.br/milestone/9). E dessa vez, teremos 3 categorias:

1. Objeto principal da Milestone
2. Melhorias
3. Itens de segurança

**Mas atenção:** os itens listados abaixo são apenas um norte, algo para nos guiar e não estão listados em ordem de prioridade. Então sinta-se livre em sugerir outras melhorias e discutir outras implementações, mesmo após a inauguração da Milestone 🤝  E caso queira sugerir outros itens, sugiro [centralizar nessa publicação](https://www.tabnews.com.br/filipedeschamps/milestone-5-o-que-nao-pode-faltar-para-o-lancamento-do-tabnews-ajuda).

## Objeto principal da Milestone

1. Lançar publicamente o TabNews (com vídeo no canal)

## Melhorias

Fora as sugestões que foram coletadas naquela publicação do TabNews, esta lista inclui também o que já tinha sido implementado ao longo do fechamento da Milestone 4 e abertura da 5, assim como itens que eu acredito ser importante para o futuro do projeto.

**Lista nova (W.I.P.)**:

1. #497
2. #498
4. #499
5. #502
6. #504
7. #505
8. #507
9. #511
10. #520
11. #521
12. #530
13. #532
14. #534
15. #542
16. #560
17. #569
18. #582
19. #584
20. #586
21. #587
22. #589
23. #591
25. #580
26. #610
27. #384
28. #617
29. #619
30. #622
31. #624
32. #626
33. #631
34. #629
35. #636
36. #638
37. #639
38. #641
39. #644
40. #647 
41. #650
42. #652
44. #658
45. #663
46. #669
47. #671
48. #673
49. #679
50. #680
51. #684
52. #689
53. #691
54. #696
55. #701
56. #705
57. #706
58. #709
59. #713
60. #719
61. #727
62. #728
63. #737
64. #655
65. #745
66. #770
67. #777
68. #781
69. #795
70. #806
71. #730
72. #733
73. #732

## Itens de segurança

1. Validação de email+senha deve tomar o mesmo tempo quando o usuário existe ou não: #186
74. Problema: "Entrada do tipo de senha com auto-preenchimento habilitado" [Fonte](https://www.tabnews.com.br/lengo/falhas-de-seguranca-no-tabnews)
75. Problema: "Práticas recomendadas de HTTP Strict Transport Security (HSTS)" [Fonte](https://www.tabnews.com.br/lengo/falhas-de-seguranca-no-tabnews)
76. Problema: "Content Security Policy (CSP) não implementado" [Fonte](https://www.tabnews.com.br/lengo/falhas-de-seguranca-no-tabnews)
77. Problema: "Páginas sensíveis que podem ser armazenadas em cache" [Fonte](https://www.tabnews.com.br/lengo/falhas-de-seguranca-no-tabnews)
62. Transformar endpoints genéricos em realmente genéricos (sem injetar o usuário).
63. Middleware responder dentro de "4s", conforme [essa resposta](https://github.com/filipedeschamps/tabnews.com.br/issues/744#issuecomment-1252939012) do @aprendendofelipe 

## Itens importantes para próximas Milestones

Novamente, caso você queira puxar essa responsabilidade para a Milestone atual, sinta-se livre 🤝 

1. #496
2. Documentação sobre a API dentro do README - (Proposta em #599)
1. Configurar DMARC to email `contato` do TabNews para emails saindo do Gmail.
1. Refatorar mensagens de erro e deixar elas user friendly.
1. #308  (ideia em #486)
1. Fazer profiling da aplicação para entender quais pontos estão demorando mais, e também quais índices devemos criar no Banco de Dados.
3. Sitemap.
4. Limitar quantidade de upvotes.
6. Barra de busca.
7. Conseguir marcar as pessoas nas publicações.
8. Favoritar publicações e conseguir criar listas compartilháveis públicas e privadas.
10. Página do usuário listar também os comentários que ele fez.
11. Avaliar [TabRewards](https://www.tabnews.com.br/devlyh/sugestao-tabrewards)
12. Conseguir compartilhar o link para o `anchor` de uma resposta na publicação `root` (e não somente o link exclusivo da resposta, talvez inclusive remover essa feature em favor do `anchor`).
13. Toggle nos comentários para compactar ou expandir uma `branch` de respostas.
14. Possibilidade de fazer posts sem texto (inspirado no HackerNews).
16. Estratégia de rankeamento apenas por TabCoins (as melhores publicações históricas), que inclui tanto publicações `root` quanto `child`.
17. #377

**Comment by 33gustavo33** [comment]
Filipe, acho que você esqueceu de fechar a milestone em si, pois ela [ainda está aberta](https://github.com/filipedeschamps/tabnews.com.br/milestone/9)
