### ISSUE TITLE
Adicionar linting para rejeitar variáveis não usadas

### ISSUE THREAD

**Issue by filipedeschamps** [filipedeschamps/tabnews.com.br#496]
## Contexto

O projeto do TabNews começou sem ter essa regra habilitada no Eslint e agora temos vários arquivos que importam dependências/variáveis que não são usadas.

## Execução

- #404

**Comment by Mazin97** [comment]
Essa issue já não foi resolvida na [PR#1410](https://github.com/filipedeschamps/tabnews.com.br/pull/1410)?

**Comment by aprendendofelipe** [comment]
Boa @Mazin97! 💪
