### ISSUE TITLE
[Notificações] Possibilidade de se inscrever em qualquer publicação

### ISSUE THREAD

**Issue by EduardoSpek** [filipedeschamps/tabnews.com.br#523]
Olá amigos!

Assim como no Github, eu acho que seria interessante ter no TabNews a possibilidade de ativar/desativar notificações por email de novas respostas de uma publicação. Desta forma, podemos acompanhar o debate mesmo de uma publicação antiga.

O que acham?

**Comment by aprendendofelipe** [comment]
Turma, obrigado pelas contribuições! 💪

Vou fechar diversas issues com assuntos relacionados. Por isso estou listando abaixo as que serão mantidas abertas e onde recomendo concentrarmos o que foi debatido/sugerido aqui:

- #645 
- #738
- #742 

Fechando essa aqui 🤝
