### ISSUE TITLE
[sugestão] Possibilidade de escolher a ordem do ranqueamento dos conteúdos

### ISSUE THREAD

**Issue by ghost** [filipedeschamps/tabnews.com.br#524]
Heyoo!

Seguinte: Vocês acham válido o usuário poder escolher entre a ordem padrão (essa da relação entre tempo e tabcoins), somente por tempo e priorizando tabcoins (por exemplo, as do dia, dos ultimos 3 ou 7 dias também ranqueadas só pelos tabcoins)?

> Imagino que coisas assim fiquem pras próximas milestones, né?

**Comment by Rafatcb** [comment]
Percebi agora que existe um outro issue (https://github.com/filipedeschamps/tabnews.com.br/issues/1388) que trata sobre esse assunto e já recebeu alguns comentários com sugestões de diferentes ordenações e também cuidados na implementação, então vou fechar aqui como duplicado. Obrigado pela sugestão!
