### ISSUE TITLE
[Sugestão] - Menu de "vagas" de trabalho

### ISSUE THREAD

**Issue by leonardocintra** [filipedeschamps/tabnews.com.br#533]
# Menu Vagas

![image](https://user-images.githubusercontent.com/5832193/180069806-2c73e4d0-4ce1-4690-bf90-e33a82b33bbb.png)

Criar uma tabela de tipo de postagem
Nela cadastra os tipos de POST
EX:
- postagem normal (são os tipos de postagem/noticias que ja é feito hoje)
- vaga de trabalho

Tudo que fosse postagem fica no menu "Tabnews"
Tudo que fosse vaga de trabalho fica no menu "Vagas"

So isso que muda, apenas a filtragem

![image](https://media.giphy.com/media/bAplZhiLAsNnG/giphy.gif)

**Comment by Joao620** [comment]
Será que vindo uma feature de tags, e tivesse funcionalidade de filtragem por tags e tudo mais, já não bastaria? Imagino que a própria comunidade se organizaria em ter tags como _#vaga-de-emprego_, e todos que quisessem ver sobre, podem filtrar por ela.

**Comment by aprendendofelipe** [comment]
@leonardocintra, obrigado pela sugestão! 💪

Vou fechar a issue porque faz sentido o que o pessoal comentou sobre tags, então como já existe a #742 sobre o assunto, recomendo centralizar a discussão por lá. Combinado? 🤝
