### ISSUE TITLE
[bug] site retorna uma listagem vazia logo na primeira vez em que o site é acessado após a invalidação das sessões

### ISSUE THREAD

**Issue by MattFerreira18** [filipedeschamps/tabnews.com.br#550]
Opaa salve galera!

 (Já avisando kkk, esse é o meu primeiro contato com o repo do projeto, assim peço desculpas se caso eu falar ou der alguma sugestão equivocada nessa issue)

 Um bug que aconteceu comigo duas vezes (e acho que todos podem estar enfrentando o msm problema) é que após ter sido feita a [invalidação de todas as sessões](https://www.tabnews.com.br/filipedeschamps/postmortem-todas-as-sessoes-foram-invalidadas-por-conta-do-endpoint-thumbnail) que aconteceu ontem a noite (dia 21/07), é que quando fui acessar a página do tabnews, por estar com a sessão invalidada, foi retornado para mim a listagem de conteúdo vazia. Mas dando reload na página, o site voltou com o comportamento esperado, mostrando a listagem dos conteúdos.

![Screenshot_2022-07-22-20-52-12-511_com android chrome](https://user-images.githubusercontent.com/52766091/180584787-0a947abd-a141-4c7a-a607-65af0c78e34f.jpg)
Exemplo do bug

 Esperamos que no futuro não seja necessário ter que invalidar todas as sessões novamente, mas como uma forma de prevenção e até msm, de melhora para caso haver algum case em o usuário passe por algum conflito com a sua sessão, para não haver uma má UX, acho que poderíamos criar algum approach para prevenir esse comportamento. 

Talvez, a partir de algum retorno específico da API, poderíamos forçar o reload da página no front, ou até, fazer com que a listagem de conteúdos retorne da API msm que a sessão esteja invalidada.

**Comment by aprendendofelipe** [comment]
Com as modificações em #1060 e #1374, acredito que esse bug não deve mais ocorrer.

Então vou encerrar a issue.

Muito obrigado @MattFerreira18! 💪
