### ISSUE TITLE
[Sugestão] Ferramenta para prever custo AWS

### ISSUE THREAD

**Issue by marconneves** [filipedeschamps/tabnews.com.br#554]
Bom dia Devss

Estes dias estava navegando na internet, acho que no LinkedIn se não me engano, e acabei me deparando com um post sobre uma lib/ extensão do VS Code que tem como intuito calcular o custo de uma infra que é usado o Terraform para a mesma, achei uma delicia, dai pensei em falar da mesma por aqui, pois acredito que para um projeto Open source devemos ter total controle sobre o custo de cada alteração que fazemos na infra.

Ferramenta que recomento: https://www.infracost.io
Git publico da mesma: https://github.com/infracost/infracost

Segue um exemplo da extensão do VS Code que gerou no projeto, ambiente de Dev!
![CleanShot 2022-07-23 at 08 24 56](https://user-images.githubusercontent.com/34342635/180603030-0cf05c85-602f-4ec4-9404-f2a3a78b4a4e.png)

E o mesmo print, porem agora em produção!
![CleanShot 2022-07-23 at 08 25 47](https://user-images.githubusercontent.com/34342635/180603052-3107b764-708f-46d8-a908-d64b2c59900e.png)

Para calcular ferramentas mais dinâmicas da AWS como o S3, pode ser usado um arquivo que tem uma simulação de uso mensal, com isso partir deles, é calculado!

**Comment by Rafatcb** [comment]
Ótima recomendação. Creio que podemos fechar esse issue para organizar o repositório. Foi bom ter levado o conteúdo para o TabNews também :+1:

**Comment by aprendendofelipe** [comment]
Show @marconneves, fechando a issue! 💪
