### ISSUE TITLE
Dúvidas gerais sobre a contribuição 

### ISSUE THREAD

**Issue by ghost** [filipedeschamps/tabnews.com.br#565]
Eu fiz um PR recentemente aqui e me surgiram muitas dúvidas sobre fazer isso corretamente, sou novo com tudo isso e quero muito contribuir mas tenho bastante dúvidas ainda (inclusivd fico o tempo inteiro inseguro sobre como agir aqui...
E acredito que mais gente também compartilhe algumas das mesmas dúvidas.

As principais são:

`O que são aqueles "lint commits e como faz eles"? `

`As PRs podem ser mais gerais ou são mais específicas? (Por exemplo as páginas de erro que tô fazendo, coloco as páginas de 500, 404, 410, 403 no mesmo PR ou separado (tá só o PR da 404 por enquanto) )`

`Além do "roteiro" no npm run commit o que mais precisa ter no commit?`
Eu mesmo fiz um PR com a 404 mas não sei se está tudo certo.

`Português, inglês ou tanto faz?`

`Posso abrir issues com perguntas "meio bestas" assim?`

```O que acham de colocar uma explicação de como contribuir com o projeto pra galera (tipo eu kkkk) que tá iniciando e ainda não entende muito bem do processo do github por exemplo? ```
Eu mesmo poderia fazer mas preciso entender primeiro  dkakdka.

**Comment by issdomingoss** [comment]
@aprendendofelipe Ola, tudo bem? Corrigi uma issue e gostaria de fazer o push do meu codigo, porem diz que nao tenho permissao, pode me ajudar quanto a isso? Primeira vez fazendo contribuicao! Abracos!!!

**Comment by kaique-soares** [comment]
Olá @issdomingoss, seja muito bem-vindo ao repositório do TabNews :handshake: 

Suponho que você tenha clonado este repositório diretamente na sua máquina e caso seja isso mesmo, esse erro de permissão é o esperado. Dito isso, você precisa fazer um `fork` deste repositório para sua conta, ou seja, criar uma cópia do TabNews porém na sua conta, onde você tem permissão de escrita.

Após isso, sugiro criar uma nova branch, implementar suas modificações, commitar e abrir uma `Pull Request`. Daí tu deve conseguir enviar sua contribuição para cá :+1: 

Qualquer dúvida, não hesite em perguntar, combinado :+1:

**Comment by aprendendofelipe** [comment]
> @aprendendofelipe Ola, tudo bem? Corrigi uma issue e gostaria de fazer o push do meu codigo, porem diz que nao tenho permissao, pode me ajudar quanto a isso? Primeira vez fazendo contribuicao! Abracos!!!

Boa @issdomingoss! 💪

É como o @kaique-soares explicou. E tem mais dicas nessa publicação do @rodrigoKulb:

https://www.tabnews.com.br/rodrigoKulb/boas-praticas-para-criar-um-pull-request-no-projeto-tabnews-com-br

Muito bem vido! 🤗

**Comment by aprendendofelipe** [comment]
Considerando que o @Rafatcb já referenciou essa issue na mensagem https://github.com/filipedeschamps/tabnews.com.br/issues/605#issuecomment-1838995532 para levarmos ao `CONTRIBUTING.md` parte do que foi esclarecido aqui, e que não houve novas dúvidas desde março, vou dar essa issue como concluída. 🤝

Muito obrigado pelas contribuições! 💪
