### ISSUE TITLE
Proposta de design

### ISSUE THREAD

**Issue by luantoningalvan** [filipedeschamps/tabnews.com.br#6]
Elaborei uma proposta para design e junto com ela diversas funções interessantes

**Link da proposta:** [https://www.figma.com/file/YbgVm2pLpCxhb5XcFIM7hI/TabNews](https://www.figma.com/file/YbgVm2pLpCxhb5XcFIM7hI/TabNews)

Existem comentários no arquivo, porém não tenho ciência que será possível o público ver, então farei os mesmos aqui

## Propostas

- Home com as publicações em destaque. Usuário experiêntes podem adicionar imagens.
- Card de notícia possuirão uma borda lateral indicando o quão em destaque está o assunto sendo uma variação de um tom de cor
- Anúncios terão design padronizado para fácil criação
- Será possível criar uma playlist para um player que faz text to speech
- Ao logar usuário poderá conferir uma barra lateral com suas moedas e atividades que geram pontuação

![Home (1)](https://user-images.githubusercontent.com/10868900/120227036-ce3f6280-c21e-11eb-9090-3d5fc01dceaa.png)

**Comment by Rafatcb** [comment]
Estou removendo a label `repescar` do issue e criando esse comentário para termos um histórico do motivo dessa decisão.

Na fase em que estamos do TabNews, já não faz sentido um "redesign total", primeiro porque seria um grande esforço direcionado para algo estético, enquanto que temos várias coisas legais a serem implementadas (veja o Milestone 7 que estamos agora https://github.com/filipedeschamps/tabnews.com.br/issues/1490); e segundo que a estética é algo bem pessoal e com certeza teremos pessoas que irão preferir a nova e pessoas que preferirão a antiga, então haveria uma divisão do público.

Acredito que a interface que temos hoje tem servido bem o público do TabNews, e fazemos melhorias incrementais nela conforme necessitamos.
