### ISSUE TITLE
[Sugestão] Como contribuir

### ISSUE THREAD

**Issue by allangrds** [filipedeschamps/tabnews.com.br#605]
Seguindo uma mesma linha do código de conduta(CODE_OF_CONDUCT.md) proposta em outra issue(#600), sugiro que tenhamos um guia de como contribuir para o projet(CONTRIBUTING.md).

Nos tópicos podemos abordar:
- Como forkar o repositório e criar um pull request;
- Explicar um pouco sobre o padrão de código(eslint)
- Explicar um pouco sobre o padrão de commit
- Explicar sobre como funcionam as criações de issues

# Referências
- https://chromium.googlesource.com/chromium/deps/mozdownload/+/5d3e0bf7851b093ff9a89d45f13185691c496bec/CONTRIBUTING.md
- https://gist.github.com/PurpleBooth/b24679402957c63ec426
- https://gitlab.com/gitlab-org/gitlab-foss/-/blob/master/CONTRIBUTING.md

**Comment by Rafatcb** [comment]
O `README.md` hoje está bom como base para contribuir no repositório (foi a referência que tive para realizar a primeira contribuição e me serviu bem), então pode ser usado como base para a criação do `CONTRIBUTING.md`.

Acho importante mencionar que um Issue deve ser criado em caso de sugestão/nova funcionalidade, para que não aconteça de algo que vá ser rejeitado seja implementado, ou para receber sugestões de como implementar ou funcionalidades complementares. O problema de "PR rejeitado" acontece bastante com o exemplo de abrir links em novas guias.

Tem um comentário do Felipe Barso falando sobre criar issues antes de PR: https://github.com/filipedeschamps/tabnews.com.br/pull/1528#issuecomment-1751716387

> Se o problema que você quer resolver ainda não estiver documentado em uma issue, então abra uma nova e exponha primeiro o problema, e depois proponha a solução (na issue mesmo e sem preocupação com a implementação).

Esse processo não está documentado, mas por ter visto esse comentário, foi o que fiz antes da minha primeira contribuição.

**Comment by aprendendofelipe** [comment]
@allangrds, muito obrigado por iniciar esse debate! 💪

Acrescentando informações ao que o @Rafatcb já trouxe, tem também uma sugestão de `CONTRIBUTING.md` no PR #1005:

https://github.com/filipedeschamps/tabnews.com.br/blob/5f2d13e2c583a22136ce171f14b440d01d1a60a5/.github/CONTRIBUTING.md

Eu concordo com o @Rafatcb sobre o `README.md` ser usado como base, onde algumas coisas podem sair de lá e ir para o `CONTRIBUTING.md` com os devidos links entre os dois arquivos.

**Comment by aprendendofelipe** [comment]
Analisando o caminho tomado em #1583, fiquei em dúvida se é o melhor caminho. Acredito que temos que separar alguns pontos que ficaram muito misturados ali no CONTRIBUTING.md.

- A parte de "Como rodar o projeto" acho que pode permanecer no README.md. E alguns detalhes extras podem ser adicionados onde fizer mais sentido (README.md ou CONTRIBUTING.md);
- A lista de diferentes formas de como contribuir com o projeto também pode ser adicionada ao README.md, mas sem entrar em detalhes e direcionando para âncoras no CONTRIBUTING.md;
- Explicações detalhadas, e não específicas do TabNews, sobre como contribuir com código aberto, como usar Git e GitHub etc. não precisam estar nesses dois arquivos. Acho que no máximo devemos colocar links para outros documentos auxiliares, sejam do TabNews ou externos;

### README.md

Eu não gostei de como ele ficou vazio. Acho que merece pouca alteração sobre o que temos hoje, e talvez nem precise ser no mesmo PR:

- Adicionar uma explicação do que é o TabNews (talvez igual ao do FAQ);
- Remover o "diário de desenvolvimento", ou mudar o nome para algo que deixe claro que ali só consta o início do desenvolvimento e explicar sobre as milestones;
- Retirar a parte sobre `nvm`, já que é um pouco diferente para o Windows, e por não ser algo obrigatório.
- Listar as formas de contribuir, mas sem entrar em detalhes:  reportar privadamente problemas de segurança, criar conteúdos e comentários no site, debater nas issues do repositório e enviar PRs com as soluções previamente debatidas;


### CONTRIBUTING.md

Dar os detalhes sobre cada forma de contribuir:

- Reportar problemas de segurança: Explicar como reportar privadamente.
- Criar conteúdos e comentários no site: Aqui talvez seja melhor não entrar em detalhes e direcionar para o FAQ ou página "Sobre" do site (e do README.md também pode ir direto para o mesmo local);
- Debater nas issues do repositório: Explicar sobre os tipos de issues e o que é esperado, por exemplo o texto em português;
- Enviar PRs: Citar que devem ser relacionados com as issues previamente debatidas e adicionar parte do que foi colocado no PR #1583. Talvez sem alguns detalhes, como os comandos necessários e outras informações sobre contribuições de código aberto em geral.


Faz sentido?

**Comment by Rafatcb** [comment]
Enquanto eu escrevia o `CONTRIBUTING.md`, me perguntei o que deveria permanecer no `README.md`, tentando evitar um redirecionamento do tipo "Quer contribuir? Veja o outro arquivo. Está lendo o arquivo para contribuir e quer executar o projeto? Veja o outro arquivo e depois volte aqui para continuar a entender como contribuir."

Terei essas observações em mente na próxima alteração do PR.

**Comment by aprendendofelipe** [comment]
> Veja o outro arquivo e depois volte aqui para continuar a entender como contribuir."

Não é um problema, pois é praticamente impossível criar documentação abrangente sem fazer esses desvios. É claro que há formas melhores e piores de se fazer isso. Algo que acho importante, quando envolve procedimentos, é colocar também o link para voltar ao ponto de antes do desvio.

**Comment by Rafatcb** [comment]
O @emerson-oliveira sugeriu (https://github.com/filipedeschamps/tabnews.com.br/pull/1583#issuecomment-1872366331) também adicionarmos ao `CONTRIBUTING.md` metodologias específicas adotadas para o desenvolvimento do front-end e do back-end, por exemplo o uso do [Primer](https://primer.style/guides/introduction). Tem algo mais, específico do TabNews, que possa ser adicionado?

**Comment by Rafatcb** [comment]
Fiz algumas alterações no PR #1583 para separar melhor as informações entre o README e CONTRIBUTING. Além disso, detalhei um pouco mais os tipos de contribuição, tirei as explicações sobre fork, branches e como abrir o PR, deixando os detalhes sobre o template existente, os testes e aprovação dos mantenedores.

Expliquei sobre o Primer no `README.md`, acho que a explicação ficou bem completa, deixando os detalhes para a própria documentação do Primer, e pode evitar alguns erros comuns que já vi acontecerem em PRs:

> ## Sobre o Frontend
>
> Os componentes de UI utilizados no TabNews são do [Primer](https://primer.style/guides/introduction), o design system do GitHub. Ou seja, sempre que for necessário exibir um aviso, input, texto, ou qualquer outra coisa, isso é feito com componentes específicos do Primer.
>
> Além de fornecer os componentes em React, o Primer também possui orientações de como proporcionar uma melhor experiência para o usuário. Você pode buscar orientações mais gerais na documentação do Primer, sobre os [fundamentos](https://primer.style/foundations) e [padrões de UI](https://primer.style/ui-patterns), ou informações específicas sobre [componentes](https://primer.style/components).
>
> Para ter uma melhor experiência com o uso dos componentes Primer, existem alguns conceitos que você deve ter em mente durante o desenvolvimento, como por exemplo: a [propriedade `sx`](https://primer.style/react/overriding-styles) para estilização, [uso de temas](https://primer.style/react/theming) e [conceitos centrais](https://primer.style/react/core-concepts) do Primer.

A parte "sobre o Backend" ficou praticamente vazia porque não consegui pensar no que colocar lá, principalmente porque as modificações que fiz no código até então não tocaram no backend.

Essas informações estão no `README.md`, não sei se seriam melhor no `CONTRIBUTING.md`
