### ISSUE TITLE
[Sugestão] Social Login

### ISSUE THREAD

**Issue by ericxlima** [filipedeschamps/tabnews.com.br#612]
## O problema
Por segurança, é sempre recomendado a utilização daquelas senhas geradas aleatoriamente, o problema delas para o usuário, é não ser fácil de decorar. Uma forma de contornar este pseudo-problema, é associar as aplicações a redes sociais como facebook, google ou github, no qual o usuário só precisa lembrar do login de uma aplicação e logar nas outras a partir dela.

## A solução
Existem tecnologias bastante maduras no mercado como o [https://www.keycloak.org/](https://www.keycloak.org/). Mas por se tratar de uma implementação que utiliza por sua essência as API's das próprias aplicações (google, github, etc) acredito que poderíamos fazer nós mesmos um Social Login 

Encontrei estes seguintes artigos no Google Cloud Docs
- [Como fazer login de usuários com o Google](https://cloud.google.com/identity-platform/docs/web/google?hl=pt-br)
- [Como fazer login de usuários com o Github](https://cloud.google.com/identity-platform/docs/web/github?hl=pt-br)

> Lembrei que em algum momento desses últimos anos, a Apple quis exigir uma lei em que se uma aplicação tivesse login com google e facebook, deveria possuir login com o Apple ID obrigatoriamente por N motivos. Não sei se esse projeto foi pra frente.

**Comment by ceelsoin** [comment]
Posso implementar o login social com keycloak, tenho experiência com a ferramenta e com o protocolo openid connect.

**Comment by coffee-is-power** [comment]
Sobre segurança, eu ontem implementei 2FA no tabnews, tem um PR que ninguém viu ainda #929

**Comment by fabiosvm** [comment]
Que tal login com GitHub e só? TabNews é focado na comunidade de Devs?

**Comment by Rafatcb** [comment]
Acho que essa é uma boa sugestão, mas acabou recebendo mais atenção no issue #922, inclusive com sugestão de UI. Faz sentido fechar como duplicado, @aprendendofelipe ?

**Comment by aprendendofelipe** [comment]
Acho que sim, @Rafatcb!

Vou fechar essa aqui para concentrarmos na #922 🤝
