### ISSUE TITLE
Unfollow e follow no TabNews

### ISSUE THREAD

**Issue by gabrielmelodev** [filipedeschamps/tabnews.com.br#614]
Não seria legal se coloca-se esta funcionalidade para você seguir o perfil de cada usuário.

**Comment by aprendendofelipe** [comment]
Turma, obrigado pelas contribuições! 💪

Vou fechar diversas issues com assuntos relacionados. Por isso estou listando abaixo as que serão mantidas abertas e onde recomendo concentrarmos o que foi debatido/sugerido aqui:

- #645 
- #738
- #742 

Fechando essa aqui 🤝
