### ISSUE TITLE
Docker-compose: comando não encontrado

### ISSUE THREAD

**Issue by andersonFaro9** [filipedeschamps/tabnews.com.br#666]
Boa tarde amigos, tudo bem?
Após tentar rodar o projeto com o comando conforme descrito: "npm run dev" tenho o seguinte erro: "linha 1: docker-compose: comando não encontrado". Como posso resolver, tentei mas não consegui.

**Comment by Ryannnkl** [comment]
Opa!

como o @andersonFaro9  explocou, ``docker-compose`` é um alias para o comando ``docker compose``. Segundo o proprio site do docker o comando docker-compose vai cair em desuso para a nova versão do compose v2 em Junho:

![image](https://user-images.githubusercontent.com/48577990/221443699-0967991a-eb87-47d0-a817-d45437b89ce0.png)

## Solução

mudar os scripts no package.json para utilizar a nova sintaxe do docker compose, os parametros continuam os mesmos só o ``docker-compose`` que vai mudar para ``docker compose``

**Comment by aprendendofelipe** [comment]
Considerando que o @andersonFaro9 disse que conseguiu, e que o PR #1315 adicionou a compatibilidade com os comandos `docker-compose` e `docker compose` ao mesmo tempo, mesmo para quem não usa o Docker Desktop, estou fechando essa issue. 👍
