### ISSUE TITLE
[Bug] Conteúdo Invisível - Markdown que desaparece

### ISSUE THREAD

**Issue by silvaezequias** [filipedeschamps/tabnews.com.br#686]
## Contexto

Testando alguns tipos de markdown, descobri um que dá problema na visualização, veja [nessa publicação](https://tabnews-m7os7e0qs-tabnews.vercel.app/Ezequias/teste-de-markdown). Simplesmente fica invisível.

O markdown que dá problema é esse: 

```
```mermaid
graph TD;
  A-->B;
  A-->C;
  A-->D;
  A-->E;
```

A visualização desse markdown é essa: 

```mermaid
graph TD;
  A-->B;
  A-->C;
  A-->D;
  A-->E;
```

E aqui tá a forma que eu coloquei no TabNews

![Script](https://user-images.githubusercontent.com/63757378/186723439-5f94b9cd-df3b-4eeb-ba5b-03bf0f330142.png)

E assim é como ficou o resultado: 

![Empty](https://user-images.githubusercontent.com/63757378/186723541-8e392f7a-14fa-4414-aae5-b2214755a689.png)

Não sei se isso é um problema do pacote de Markdown que é usado ou é especificamente nesse tipo `code block` que eu usei no markdown.

#### Observação
Eu tentei selecionar tudo usando o CTRL+A e o resultado foi esse: 
![CTRL+A](https://user-images.githubusercontent.com/63757378/186724084-79a307a0-dd65-4c18-8df2-dd7aed92c614.png)

Fui olhar no source-code da página pra ver se existia algum elemento ali e sim, existe mas não está visível

![devtools](https://user-images.githubusercontent.com/63757378/186724280-7eec5adb-7711-4409-ad03-094ee3a32c12.png)

**Comment by aprendendofelipe** [comment]
Solução chegando 🎉

https://github.com/bytedance/bytemd/pull/256

**Comment by aprendendofelipe** [comment]
@silvaezequias isso já deveria ter sido corrigido, então fui conferir sua publicação e tinha dois erros de sintaxe. Provavelmente a sintaxe acabou ficando errada após alguma edição para teste, pois na imagem que você postou está correta.

Veja que está funcionando no link abaixo:

https://tabnews-ek480p79a-tabnews.vercel.app/Ezequias/teste-de-markdown

Então estou fechando como concluído 💪
