### ISSUE TITLE
Mobile React Native

### ISSUE THREAD

**Issue by andersonFaro9** [filipedeschamps/tabnews.com.br#695]
Boa tarde amigos, tudo bem? chegaram a pensar em criar uma versão em mobile com react native, o que acham?

**Comment by aprendendofelipe** [comment]
@andersonFaro9, sei que existem diversas versões de aplicativos do TabNews, mas não me lembro se alguma é em React Native.

De qualquer maneira, como os Apps apenas utilizam a API do TabNews, são projetos independentes. Provavelmente nem valeria a pena fazer um fork, pois nada (ou quase nada) seria aproveitado. Por isso vou fechar a issue. 🤝
