### ISSUE TITLE
[sugestão] métricas das publicações

### ISSUE THREAD

**Issue by jackson541** [filipedeschamps/tabnews.com.br#717]
Um ponto que, para mim, seria interessante é implementar um sistema de métricas das publicações que fazemos. Sinto falta em ver quantas pessoas foram impactas pelo que publiquei ao longo do tempo.

Um exemplo são as métricas que o dev.to apresenta em cada post:
Quantidade de acessos ao longo da semana, mês e desde a publicação
![image](https://user-images.githubusercontent.com/40877357/188898619-920531f8-aded-4a89-8cef-aca58ac037c3.png)

De onde elas vieram:
![image](https://user-images.githubusercontent.com/40877357/188898841-f725058d-8998-484c-a29f-b589cc798f5c.png)

**Comment by aprendendofelipe** [comment]
@jackson541, obrigado pela sugestão! 💪

Vou fechar essa issue para concentrarmos o debate na #1115, pois lá teve mais interações. 🤝
