### ISSUE TITLE
[Sugestão] Notificações usando Novu

### ISSUE THREAD

**Issue by developerdavi** [filipedeschamps/tabnews.com.br#753]
### O problema

Atualmente, só existe um canal de notificação: emails. Escalar isso, criar novos canais de notificações, gerenciar templates, preferências dos usuários etc pode ser chato e levar um tempo. Cheguei aqui na aba de issues e achei algumas ideias relacionadas a isso também: #738, #523.

### A sugestão

Há um tempo, ouvi falar do [Novu](https://novu.co) e resolvi que esse era a solução de notificações que eu gostaria de implementar na minha plataforma ([FreshCoins](https://freshcoins.io)). A solução mencionada permite entregar notificações para os usuários em vários canais (email, sms, barra de notificações, etc) com mínima configuração. Ainda não fiz o release dessa integração em minha plataforma porque estamos focados em outras features no momento com maior prioridade, mas já fiz alguns testes e validei o potencial para minha plataforma e creio ser uma opção válida também para o TabNews, visto que essa parte ainda está bem embrionária.

### Novu

![image](https://user-images.githubusercontent.com/31714350/193360763-5bac0dae-671a-4024-b337-8361f032234a.png)

- Open source (MIT) - [repositório no github](https://github.com/novuhq/novu)
- Pode ser self-hosted ou usar a infra deles que no momento é gratuita e sem limitações
- Suporta muitas integrações nativamente (para email: Nodemailer - o mesmo usado aqui, Amazon SES, SendGrid, Mailjet, etc)
- Tem algumas facilidades tipo um [componente react para mostrar as notificações](https://docs.novu.co/notification-center/react-components) para o usuário + hooks pra você fazer seu componente na mão

Desculpe se esse assunto já foi batido o martelo em algum encontro com os membros, estive muito fora desse meio nos últimos meses, espero que essa issue seja útil haha.

**Comment by aprendendofelipe** [comment]
Turma, obrigado pelas contribuiçoes! 💪

Vou fechar diversas issues com assuntos relacionados. Por isso estou listando abaixo as que serão mantidas abertas e onde recomendo concentrarmos o que foi debatido/sugerido aqui:

- #645 
- #738
- #742 

Fechando essa aqui 🤝
