### ISSUE TITLE
Bug na interface quando tem muitas respostas consecutivas

### ISSUE THREAD

**Issue by 33gustavo33** [filipedeschamps/tabnews.com.br#762]
Eu estava fazendo alguns testes nesse post [aqui](https://tabnews-git-ranking-tabnews.vercel.app/Gustavo33/teste4593832181797422292334945798549354624941348715825899669), e descobri que quando tem muitos comentários a UI quebra. 

Como você vai poder ver acessando o post, depois da resposta `28` a UI simplesmente quebra.

Acredito que a solução pra isso seria definir um limite de respostas consecutivas

**Comment by aprendendofelipe** [comment]
@33gustavo33, obrigado por relatar! 💪

Estou fechando essa issue por ser um problema que já é discutido na #379 🤝
