### ISSUE TITLE
Problema para acessar publicação

### ISSUE THREAD

**Issue by guisouza-dev** [filipedeschamps/tabnews.com.br#772]
Sou novo na plataforma e estou aprendendo a mexer com ela agora, mas acho que houve algum erro pois quando tentei abrir a seguinte publicação apareceu uma tela de erro dizendo: *"Application error: a client-side exception has ocurred(see the browser console for more information)"*

### Imagem e link
![Application error: a client-side exception has ocurred(see the browser console for more information)](https://lh3.googleusercontent.com/zWIeEVmSMSrM_odsR3GHN48j12ba6l0vwXpt2dD1yHC-UWfifejZQwvMwqIC-ewj1hyuADBRC11l3WH4XAnTsJmUb6s51Vdt5REfvW0ugg26jAagDh4Q8Tlh4Gw56mfVX3b5z1VvseNW-b7z2xyRUHSZOsRaZECaocqrortAeoLgoYeQIXRLtbCy8PsFZ7XAb99JeW_qRY10l0cutFIGC8CK2RrvQyCkSUcUH75kS8ZMWNP7TFMs_JuQ80bOCK4L-KHcoiHMKej1shRsNiMtKFJCU1tm6fTpbvEuxrzWHYflA9YeVMVcfIYG2VNS3EqrFDL0V0BWV-XyBfTygk--VMtcznA5TK_mR3V6jH7yvfxDRGhVvJ1wg3FpWCWKYl7VJm8K6x9RL311SFFOJW44JZMV5L9g2OS_vZGKFv30CZJnQ1_Tiel8vU3fpv3y0Gte8iCkcz6Mj7zun1qEf-PX9QT5wbnByx-AvMMM98qlk29LOoBwuSO-UFmNKy0NRME3iV6OdUvu-2Pxr4T72g3CrcNE5j-1WsfWVuXC2EY6siepEGfDKkP2wdIL78CUpKAwlVYl5Cg-PCpdVnm6O1b2R750Y-xoJg8yhM5VFtlFs6C11vIWqaO4QNqYTISwD6pGACGmrTNijWRU79RdniKaRx0YgVJrysOOQWLIQ24IuYpEBF73l1rQNdy5m9gQNx60ixCumqT-o5Nf_h7uWcRwNqyUUqJRAQ3s-fuPqovot3nebsID0rpQt5gmlPL7VFaN8E_-V9rw9yaH1Q8aYQhPyDwPI6L2YvKHdKNkaWK3qCi41HvaU5WdGcVucx0AosCN4WalPYzJXHqcLvqsvELgQkHNU1palLdu-gvjTcgS2dpjsLjdfjawwHyUiGkZZeHq1UItvLSVMlYDmn6nfOnCSl1A-ljwW0GtrMZU=w1793-h969-no?authuser=0)
[https://www.tabnews.com.br/FlaviaCarvalho/publicidade-via-satelite-e-tecnica-e-economicamente-viavel-afirmam-cientistas-russos](https://www.tabnews.com.br/FlaviaCarvalho/publicidade-via-satelite-e-tecnica-e-economicamente-viavel-afirmam-cientistas-russos)

**Comment by aprendendofelipe** [comment]
@guisouza-dev, obrigado por reportar! 💪

Na época chegamos na conclusão de que o Brave estava bloqueando a requisição por conter a palavra "publicidade" na URL.

Não sei se esse problema ainda está presente, provavelmente não, pois ninguém mais reportou.

De qualquer forma, não parece algo que esteja no nosso controle, então estou fechando a issue! 🤝
