### ISSUE TITLE
Criar og:image automaticamente usando a nova biblioteca da vercel

### ISSUE THREAD

**Issue by coffee-is-power** [filipedeschamps/tabnews.com.br#782]
A vercel recentemente criou uma biblioteca pra gerar imagens og automaticamente na Edge usando jsx convencional, seria muito interessante mostrar algumas informações como título, autor e upvotes.

Mais informações:
https://youtu.be/6rYzM_oWi7A

**Comment by ErickCReis** [comment]
Com a implementação de https://github.com/vercel/satori/issues/253 foi possível continuar a implementação.
