### ISSUE TITLE
Apresentar Spinner (Loading) no botão de Publicar/Atualizar

### ISSUE THREAD

**Issue by gabrielew** [filipedeschamps/tabnews.com.br#788]
Hoje já existe uma funcionalidade de desabilitar o botão caso o mesmo esteja com o estado de `isPosting` como true.
Porém, ontem ao realizar uma publicação a minha conexão estava lenta e pensei que havia acontecido algum BUG para meu conteúdo não ter sido de fato enviado.

 Então gostaria de saber se mais pessoas pensam ou já pensaram em algo para melhor ainda mais a usabilidade/feedbacks visuais durante uma publicação.

Edit.: Também percebi que o `aria-label` fica somente como "Publicar" (mesmo se estiver atualizando) e o cursor do mouse não é modificado para `not-allowed`.

**Comment by bernardoeuler** [comment]
Olá pessoal, nesse PR que o @aprendendofelipe mencionou acima eu estou desenvolvendo essa solução para dar um feedback para o usuário de que sua ação ao clicar num botão está sendo processada.

Não sei se isso já está em desenvolvimento  por aqui, mas gostaria da opinião de vocês em relação a implementação.

Queria saber se durante o carregamento é melhor manter somente o spinner no botão  (e retirar o texto)¹ ou manter os dois simultâneamente², e talvez trocar para uma palavra que indique continuidade e pôr reticências (ex: Cadastrando..., Enviando... e etc.).

### Imagens 
Imagem 1:
![images.jpeg](https://user-images.githubusercontent.com/77172676/209735945-4c19c186-e368-4edd-b54e-2594fd694034.jpeg)

Imagem 2:
![images.png](https://user-images.githubusercontent.com/77172676/209736043-773a24c0-9320-4ae8-9615-f6d18599c5ee.png)

**Comment by aprendendofelipe** [comment]
Implementado no #1501 🎉
