### ISSUE TITLE
Alterar o layout padrão das páginas

### ISSUE THREAD

**Issue by silvaezequias** [filipedeschamps/tabnews.com.br#791]
### Contexto
Estou trabalhando na implementação de pesquisa no TabNews: https://github.com/filipedeschamps/tabnews.com.br/tree/search-content-by-keywords.
Essa implementação vai alterar um pouco o layout default das páginas e por isso eu fiz uma representação de como seria (na minha opinião) a melhor forma de implementar isso mantendo o principio de simplicidade do TabNews e sem alterar MUITA coisa no layout:

![Homepage 2.0](https://user-images.githubusercontent.com/63757378/198235290-b52134d4-db9a-4560-b1d7-e783ca557a2e.svg)

Essa é uma versão com o NavBar light
![Homepage with light navbar](https://user-images.githubusercontent.com/63757378/198237077-fed85946-6ae0-4954-a660-7cbf03d40e26.svg)

O que acham desse layout? Isso é apenas um esquema feito no Figma, não está em código ainda. Não implementei responsividade usando esse layout ainda.

Não espero que esse seja o layout final mas que pelo menos ajude com ideias e possibilidades!

**Comment by Jetrom17** [comment]
> ### Contexto
> Estou trabalhando na implementação de pesquisa no TabNews: https://github.com/filipedeschamps/tabnews.com.br/tree/search-content-by-keywords.
> Essa implementação vai alterar um pouco o layout default das páginas e por isso eu fiz uma representação de como seria (na minha opinião) a melhor forma de implementar isso mantendo o principio de simplicidade do TabNews e sem alterar MUITA coisa no layout:
> 
> ![Homepage 2.0](https://user-images.githubusercontent.com/63757378/198235290-b52134d4-db9a-4560-b1d7-e783ca557a2e.svg)
> 
> Essa é uma versão com o NavBar light
> ![Homepage with light navbar](https://user-images.githubusercontent.com/63757378/198237077-fed85946-6ae0-4954-a660-7cbf03d40e26.svg)
> 
> O que acham desse layout? Isso é apenas um esquema feito no Figma, não está em código ainda. Não implementei responsividade usando esse layout ainda.
> 
> Não espero que esse seja o layout final mas que pelo menos ajude com ideias e possibilidades!

Ficou top. Concordo que seja simples, mas eficaz.

**Comment by aprendendofelipe** [comment]
@silvaezequias, muito obrigado pela sugestão de layout! 💪

Pelo baixo volume de utilização da barra de busca dentro do próprio site (irrisório se comparado com a busca diretamente no Google), no momento não vale a pena investir em um sistema de busca próprio mais elaborado.

E sem um sistema mais elaborado, não vale a pena ocupar tanto espaço da Home com a barra de pesquisa simples que temos disponível.

Como a issue é especificamente sobre o layout, por enquanto estou fechando como "não planejado". 🤝
