### ISSUE TITLE
Endpoints

### ISSUE THREAD

**Issue by DanielJ06** [filipedeschamps/tabnews.com.br#793]
Opa, fala turma!
Como ainda estamos no processo de criação das docs do tabnews, alguém tem e poderia disponibilizar uma collection do postman e/ou insomnia ou quem sabe até um swagger para os membros que não tem tanta experiência com backend para "buscar os endpoints na mão"? E quem sabe até usar desse recurso para contribuir pra construção da própria doc futuramente... 🤩

**Comment by Rafatcb** [comment]
Vale mencionar que existe um issue para criação de documentação da API: https://github.com/filipedeschamps/tabnews.com.br/issues/555
