### ISSUE TITLE
[Feature request] - Create dynamic sitemaps

### ISSUE THREAD

**Issue by r3nanp** [filipedeschamps/tabnews.com.br#796]
Boost the website SEO with sitemaps, since we're creating multiple pages would be nice to use [Sitemaps](https://developers.google.com/search/docs/crawling-indexing/sitemaps/build-sitemap). 
It work really well with RSS feeds.

Recommended library:
https://www.npmjs.com/package/next-sitemap

**Comment by aprendendofelipe** [comment]
Considerando que [um feed rss pode ser usado como sitemap](https://developers.google.com/search/docs/crawling-indexing/sitemaps/build-sitemap?hl=pt-br#rss), acabo de adicionar nosso feed no Google Search Console:

![image](https://github.com/filipedeschamps/tabnews.com.br/assets/77860630/761c176f-3ca2-42f2-b047-35750d0b9e69)

**Comment by Rafatcb** [comment]
@aprendendofelipe como ficou o resultado no Google Search Console nessas duas semanas? Resolveu o problema e podemos fechar o issue?

**Comment by aprendendofelipe** [comment]
Acredito que podemos fechar, pois a indexação das novas publicações está ocorrendo bem rápido.

Não dá para saber exatamente de quanto em quanto tempo o Google verifica o feed, mas publicações com menos de 1 hora já aparecem na busca, então isso nos atende bem enquanto não chegarmos em um volume de mais de 30 publicações raiz por hora.

![image](https://github.com/filipedeschamps/tabnews.com.br/assets/77860630/e0ee37d9-a638-405e-af70-fce234c1c64a)

Fechando a issue. 🤝

Obrigado @r3nanp e @Rafatcb! 💪
