### ISSUE TITLE
Criar documentação usando OpenAPI e Redoc

### ISSUE THREAD

**Issue by coffee-is-power** [filipedeschamps/tabnews.com.br#798]
A Api do tabnews está estavel o suficiente a essa altura do campeonato, eu considero a documentação da API algo critico para o lançamento. Com OpenAPI e redoc é facil de documentar a api, basta servir o arquivo do open api e um arquivo html, e o redoc vai montar a interface no navegador. Claro, é preciso manter o arquivo yml para bater com a api real, mas da muito menos trabalho do que refazer a interface inteira.

**Comment by aprendendofelipe** [comment]
Apenas registrando aqui os PRs que já foram abertos e que podem servir de inspiração para a criação de um PR atualizado:

- #599 
- #799

**Comment by aprendendofelipe** [comment]
@coffee-is-power, obrigado pela sugestão! 💪

Vou fechar essa issue e podemos centralizar a conversa na #555 que é mais antiga. Combinado? 🤝
