### ISSUE TITLE
Proposta de estrutura para 2 tipos de clientes.

### ISSUE THREAD

**Issue by danwhat** [filipedeschamps/tabnews.com.br#8]
Cara! Acabei consumir tudo que vocês postaram nas **issues** e no **repo** como um todo. Vocês são sensacionais!

Vou tentar contribuir um pouquinho: talvez seja maluquice, mas a gente não consegue reter tanto os usuários da newsletter quanto os do site não? Eu enxergo 2 tipos de usuários: "usuários que consomem" e "usuários que consomem e contribuem"

Não sei o quanto eficiente seria, mas acredito que conseguimos criar um único site que atenda ambos.
1. Eu imagino o **layout default** o mais limpo possível, pois a maior parte dos usuários querem apenas entrar e consumir assim como fazem no email, e para estes, não faz sentido outras features.
2. E em algum lugar no site poderia ter um botão de **show/hide** para os usuários que querem uma experiência "mais completa" e "tudo bem" ter um passo a mais para acessar esses recursos já que seriam usuários que já estão dispostos a interagir e contribuir para o site.

Rabisquei no figma o que eu imagino. Não se prendam nos detalhes mas sim na ideia como um todo: https://www.figma.com/file/rovD0eecxO0264VseLCcMZ/Untitled?node-id=1%3A2

Coloquei essa ideia aqui, pois faz parte da estrutura do projeto e não apenas uma feature.

<img src="https://i.imgur.com/yBMMOfz.png" width="640" height="360">
<img src="https://i.imgur.com/1zDa1Ap.png" width="640" height="360">

_Originally posted by @danwhat in https://github.com/filipedeschamps/tabnews.com.br/issues/1#issuecomment-855058308_

**Comment by Rafatcb** [comment]
Estou removendo a label `repescar` do issue e criando esse comentário para termos um histórico do motivo dessa decisão.

Na fase em que estamos do TabNews, já não faz sentido um "redesign total", primeiro porque seria um grande esforço direcionado para algo estético, enquanto que temos várias coisas legais a serem implementadas (veja o Milestone 7 que estamos agora https://github.com/filipedeschamps/tabnews.com.br/issues/1490); e segundo que a estética é algo bem pessoal e com certeza teremos pessoas que irão preferir a nova e pessoas que preferirão a antiga, então haveria uma divisão do público.

Acredito que a interface que temos hoje tem servido bem o público do TabNews, e fazemos melhorias incrementais nela conforme necessitamos. Inclusive, tivemos alguns esforços para melhorar o site no modo de Leitura que os navegadores possuem, e que funciona melhor no Edge, se não me engano.
