### ISSUE TITLE
Filtrar os conteúdos root e child exibidos na página do usuário

### ISSUE THREAD

**Issue by ermesonqueiroz** [filipedeschamps/tabnews.com.br#807]
## Contexto

O merge da PR #805 viabilizou a visualização dos conteúdos `child` do usuário em sua própria página, com isso, agora temos 2 tipos de conteúdos na página de usuários, sendo eles: `root` e `child`, como usuário do Tabnews eu ficaria bastante satisfeito se houvesse a possibilidade de filtrar esses conteúdos.

O que vocês acham?

**Comment by guilherssousa** [comment]
> Falando nisso, tem lugar que o conteúdo `child` é chamado de **comentário**, e lugar que é chamado de **resposta**. Seria interessante padronizar isso também.

Comentário seria mais que suficiente para categorizar esses dois, afnial, uma resposta a um comentário é um comentário, não?

**Comment by aprendendofelipe** [comment]
@ermesonqueiroz, obrigado pela sugestão! 💪

No PR #1413 estamos centralizando os dados sobre conteúdos em um único endpoint, e a maneira que foi feita permite filtrar por conteúdos raiz e/ou comentários, então após esse PR será possível implementar essa funcionalidade no front-end 👍

**Comment by aprendendofelipe** [comment]
Como acaba de ocorrer o merge do PR #1188 do @ErickCReis, já é possível consultar pela API de forma separada através dos parâmetros `with_root` e `with_children`.

Para não quebrar os sistemas que utilizam a API atualmente, o endpoint `/api/v1/contents/[username]` continua retornando por padrão os dois tipos de publicações, pois o valor padrão é `true` para os dois parâmetros.

Então basta passar `false` para qualquer um deles para obter apenas o outro tipo de conteúdo. No exemplo abaixo só serão retornados os conteúdos `root` do @filipedeschamps:

https://www.tabnews.com.br/api/v1/contents/filipedeschamps?with_children=false

A versão frontend ainda precisa de implementação, mas como a ideia parece estar bem avançada, isso não deve demorar 🎉
