### ISSUE TITLE
[Sugestão] Criar extensão para o Tabnews

### ISSUE THREAD

**Issue by lucasoliveiracruz** [filipedeschamps/tabnews.com.br#822]
Atualmente uso a extensão `daily.dev`, onde são mostrados alguns cards com links para artigos. Seria muito interessante ter uma extensão de nova aba para o Tabnews.

Eu nunca desenvolvi uma extensão, mas aceito o desafio se a ideia for boa.

**Comment by Joao620** [comment]
Gostaria de adicionar aqui que o tabnews já possui um feed RSS para os posts recentes [aqui](https://www.tabnews.com.br/recentes/rss). E pode ser que já exista uma extensão que notifica sempre que esse feed muda, o meu só aparece o número de mensagens não lidas aumentando

**Comment by coffee-is-power** [comment]
@Joao620 sim eu fiz isso, foi a minha primeira contribuição aqui no tabnews :)

**Comment by brunofamiliar** [comment]
Pessoal, reativei o projeto que mecionei acima. Fiz um [post](https://www.tabnews.com.br/brunofamiliar/extensao-tabnews-para-o-chrome) explicando um pouco melhor, se puderem avaliar a ideia.

**Comment by Rafatcb** [comment]
Extensões e aplicativos móveis acabam saindo do escopo desse repositório, que se limita ao site e à API, como dito inicialmente em https://github.com/filipedeschamps/tabnews.com.br/pull/13#issuecomment-861889280 e colocado em prática com o avanço do repositório. Dito isso, a comunidade já fez algumas extensões para o TabNews, você pode ver alguns exemplos aqui:

* [brunofamiliar — 📣 Extensão TabNews para o Chrome 🌐](https://www.tabnews.com.br/brunofamiliar/extensao-tabnews-para-o-chrome)
* [agjunior — Pitch: Extensão do TabNews para navegador](https://www.tabnews.com.br/agjunior/extensao-do-tabnews-para-navegador)
* [olavomello — 📰 Criei o TabNews Reader - Extensão para o Google Chrome](https://www.tabnews.com.br/olavomello/criei-o-tabnews-reader-extensao-para-o-google-chrome).

**Comment by aprendendofelipe** [comment]
Turma, vou encerrar essa issue por organização do repositório 💪🤝
