### ISSUE TITLE
Erro "A Client-side exception has occurred" ao ficar ocioso dentro do tópico.

### ISSUE THREAD

**Issue by gustavoloopes** [filipedeschamps/tabnews.com.br#827]
![Screenshot_2](https://user-images.githubusercontent.com/56397295/203076566-daf04387-c618-48d1-b705-4fa642d9a882.png)

**Comment by alangabrielbs** [comment]
aqui abri um post e tambem recebi o erro

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/48570772/203078728-72e891d0-38eb-4b0e-b11a-b5fe14baad88.png">

**Comment by filipedeschamps** [comment]
Show turma, muito obrigado por reportar os erros! E sugiro centralizarmos nessa issue #826 daqui para frente 🤝
