### ISSUE TITLE
Um erro interno não esperado aconteceu.

### ISSUE THREAD

**Issue by xdxddxd** [filipedeschamps/tabnews.com.br#829]
Tentei fazer o meu cadastro cadastro e a seguinte mensagem surgiu.

Um erro interno não esperado aconteceu.
Informe ao suporte este valor: 86a554f6-f47c-43ea-a982-2e6697efb50b

**Comment by iurynathan** [comment]
Provavelmente o backend está com problema, também recebi o mesmo error.

9ca70f63-2e3d-46d0-91ba-5f7eb10fa2b7

**Comment by thiagomdiniz** [comment]
Não sei se é relacionado ao mesmo problema, mas depois de ficar um tempo nas paginas ocorreu isso (durante algum request interno/automático).

![image](https://user-images.githubusercontent.com/29825093/203082780-643fe4ee-7510-4000-8301-519d20749707.png)

**Comment by JonathanArgentao** [comment]
#826

**Comment by aprendendofelipe** [comment]
Duplicidade com #826

Estou encerrando todas que dizem respeito ao mesmo problema, mas fique à vontade para reabrir caso não seja duplicidade.

Obrigado!
