### ISSUE TITLE
[Feature] Adicionar uma opção para salvar postagens para ler mais tarde 

### ISSUE THREAD

**Issue by josevansantos** [filipedeschamps/tabnews.com.br#830]
Ter a possibilidade de salvar as publicações em uma coleção, semelhante a opção de salvar do Instagram.

![image](https://user-images.githubusercontent.com/44148461/203080496-f29b7b26-4b3c-4a70-b680-18a14cb995b5.png)

**Comment by MarcosLage** [comment]
Feature necessária poder favoritar para ler depois, ter um botão no fim da pagina para voltar ao topo.

**Comment by aprendendofelipe** [comment]
Obrigado pela issue! 👍

Por organização, estou fechando as duplicadas com a #645 🤝
