### ISSUE TITLE
Erro: 503 em todas as rotas da api

### ISSUE THREAD

**Issue by ezequiaslopesdasilva** [filipedeschamps/tabnews.com.br#831]
## Contexto

Entrei no tabnews como rotina e nenhum conteudo apareceu:

![error-tabnews](https://user-images.githubusercontent.com/63757378/203081588-a9fb5772-1496-4714-9b4e-dc26ef8ec12b.png)

Fui verificar o console pra ver se tinha algo de errado e percebi que todas as requests na api retornava um 503 

![error-tabnews-console](https://user-images.githubusercontent.com/63757378/203081707-ff34d5d6-84d5-4283-9f93-187d98fa645d.png)

## Observação

É a primeira vez no dia que eu tentei entrar no site, não tive nenhum acesso com api - nem usando clientes externos - ontem não fiz nenhuma requisição no tabnews de forma geral.
Não creio que é problema na minha rede pois isso só está ocorrendo no tabnews.

**Comment by felipsbreno** [comment]
#826

**Comment by aprendendofelipe** [comment]
Duplicidade com #826

Estou encerrando todas que dizem respeito ao mesmo problema, mas fique à vontade para reabrir caso não seja duplicidade.

Obrigado!
