### ISSUE TITLE
Erro ao cadastrar novo usuário

### ISSUE THREAD

**Issue by WagnerRiro** [filipedeschamps/tabnews.com.br#832]
Ao tentar realizar a autenticação do token recebido por e-mail para validação do cadastro, recebi o seguinte erro:
![image](https://user-images.githubusercontent.com/114552566/203088779-f1584b8b-cfe5-480f-b2aa-9726434be7b5.png)

após isso tentei cadastrar novamente utilizando o mesmo email, para ver se seria encaminhado um novo token, porém recebi a seguinte mensagem:   **6433b69b-153d-4f9f-82a6-2c9222fc27a9**

![image](https://user-images.githubusercontent.com/114552566/203088667-73aae286-808e-41d9-aaf9-d10c8ee32dbf.png)

**Comment by Just1Dav** [comment]
Passando pelo mesmo problema aqui, tentei várias vezes acessar pelo link enviado no email e sempre dá o mesmo erro na validação do token. Erro `error_id`.

**Comment by rodrigooler** [comment]
same error.

API -> https://www.tabnews.com.br/api/v1/users

```sh
{"name":"InternalServerError","message":"Um erro interno não esperado aconteceu.","action":"Informe ao suporte o valor encontrado no campo 'error_id'.","status_code":503,"error_id":"8fc61dfc-7e49-486c-ba56-d4bad3367924","request_id":"48d5c4ed-4f39-403c-ac6d-5a5a377c13f7","error_location_code":"INFRA:DATABASE:QUERY"}
```

**Comment by JohnVidal77** [comment]
Tambem obtive o erro, a api foi chamada com os dados do form corretamente mas retornou um erro 500 dpeois de uns 30 segundos

**Comment by junque1r4** [comment]
<img width="527" alt="image" src="https://user-images.githubusercontent.com/39351332/203093802-e0f9b66a-5f60-4f62-ba0c-ba1c04c77ab9.png">

Aqui também!

**Comment by junque1r4** [comment]
#826 Está down pela quantidade no lançamento, acompanhe por lá o andamento, já tem muitos issues desse erro abertas!

**Comment by aprendendofelipe** [comment]
Duplicidade com #826

Estou encerrando todas que dizem respeito ao mesmo problema, mas fique à vontade para reabrir caso não seja duplicidade.

Obrigado!
