### ISSUE TITLE
Erro ao realizar login

### ISSUE THREAD

**Issue by pessjr** [filipedeschamps/tabnews.com.br#833]
Tentando realizar login, notei que a sessão é realizada com sucesso porém quando a busca por usuário excede o tempo limite ele redireciona para a página de perfil com informações undefined.
![image](https://user-images.githubusercontent.com/20118730/203089189-7960876e-883c-4d8a-8b6b-2385017472a3.png)
![image](https://user-images.githubusercontent.com/20118730/203089094-1e918a92-fbd8-41d2-840a-af26b45bfbc7.png)

**Comment by junque1r4** [comment]
#826 Está down pela quantidade no lançamento, acompanhe por lá o andamento, já tem muitos issues desse erro abertas!

**Comment by nicolasteofilo** [comment]
Que nem o @junque1r4 falou, essa baixa deve se ter dado pela grande quantidade de pessoas acessando o serviço agora... Mas jájá deve voltar ao normal

**Comment by pessjr** [comment]
Sim, eu já estava imaginando que esse fosse o motivo, porém eu penso que tem algo nesse fluxo que não está batendo.
Se eu faço login e sou autenticado, porém o usuário por alguma razão não retorna, ele não deveria me deixar ser redirecionado para a tela de usuário.

**Comment by aprendendofelipe** [comment]
Vou encerrar essa issue, pois acredito ser um problema que já foi resolvido.

Qualquer coisa é só reabrir 🤝
