### ISSUE TITLE
Erro ao se Cadastrar

### ISSUE THREAD

**Issue by meta4chain** [filipedeschamps/tabnews.com.br#835]

**Comment by junque1r4** [comment]
#826 Está down pela quantidade no lançamento, acompanhe por lá o andamento, já tem muitos issues desse erro abertas!

**Comment by aprendendofelipe** [comment]
Duplicidade com #826

Estou encerrando todas que dizem respeito ao mesmo problema, mas fique à vontade para reabrir caso não seja duplicidade.

Obrigado!
