### ISSUE TITLE
Erro no cadastro

### ISSUE THREAD

**Issue by thiagopabreu** [filipedeschamps/tabnews.com.br#836]
Hoje eu vi o video de lançamento do produto e achei a idéia muito interessante, logo corri para me cadastrar e me veio essa mensagem:
![image](https://user-images.githubusercontent.com/47667256/203093332-2193062e-2bfe-4e42-a626-1e103715c9c4.png)

**Comment by junque1r4** [comment]
Erro aqui também, tentei com outros dispositivos e nada também:
<img width="527" alt="image" src="https://user-images.githubusercontent.com/39351332/203093539-45af3074-092e-4adf-ad22-7ce44e302e4d.png">

**Comment by thiagopabreu** [comment]
![image](https://user-images.githubusercontent.com/47667256/203093864-dd2798b7-7038-4abb-9e57-8b146e507325.png)
tentei novamente e agora essa mensagem

**Comment by berutodo** [comment]
mesmo erro aqui

**Comment by adrian7123** [comment]
mesmo erro

**Comment by manotroll** [comment]
Você realizou muitas requisições recentemente. Informe ao suporte este valor: aaa96c5e-bbeb-402a-ae87-046d19640fc1
mandei um email pra eles sobre esse erro :D
mais um na fila

**Comment by aprendendofelipe** [comment]
Duplicidade com #826

Estou encerrando todas que dizem respeito ao mesmo problema, mas fique à vontade para reabrir caso não seja duplicidade.

Obrigado!
