### ISSUE TITLE
Um erro interno não esperado aconteceu 'error_id'. (2b336774-7b0d-4f2e-8dbc-efa3e740ed36)

### ISSUE THREAD

**Issue by adiliogobira** [filipedeschamps/tabnews.com.br#837]
Um erro interno não esperado aconteceu. Informe ao suporte o valor encontrado no campo 'error_id'. (2b336774-7b0d-4f2e-8dbc-efa3e740ed36)

**Comment by felipsbreno** [comment]
Esse problema já é conhecido e está sendo discutido nesta issue #826 .

pode acompanhar o andamento lá
