### ISSUE TITLE
Erro 503 em contents

### ISSUE THREAD

**Issue by fellipe-costuchenko** [filipedeschamps/tabnews.com.br#838]
Olá,

Encontrei um erro que ocorre a uma chamada de api quando acessa o site e fica aguardando em torno de 1 minuto ocorre novamente uma chamada para https://www.tabnews.com.br/api/v1/contents?strategy=relevant

Parece ser algo intermitente.

![image](https://user-images.githubusercontent.com/58091964/203097331-6c7e168a-9e68-4764-9555-cf9953bb49e8.png)
![image](https://user-images.githubusercontent.com/58091964/203097546-ce3fcd6f-178d-4f51-8e69-d0afba7429dc.png)

Deixando o problema acima de lado, parabéns pelo trabalho com o site de forma geral pessoal!

**Comment by felipsbreno** [comment]
Esse problema já é conhecido e está sendo discutido nesta issue #826  .

pode acompanhar o andamento lá

**Comment by aprendendofelipe** [comment]
Duplicidade com #826

Estou encerrando todas que dizem respeito ao mesmo problema, mas fique à vontade para reabrir caso não seja duplicidade.

Obrigado!
