### ISSUE TITLE
Application error: a client-side exception has occurred (see the browser console for more information).

### ISSUE THREAD

**Issue by alexrintt** [filipedeschamps/tabnews.com.br#840]
For some reason: 

![image](https://user-images.githubusercontent.com/51419598/203096164-39935bc1-40b7-433c-9203-6953dcdf93a9.png)

![image](https://user-images.githubusercontent.com/51419598/203096281-9d6c8936-31aa-4450-89df-ce7f30c8817f.png)

> **Note** it is was thrown several times on post and home page.

I did start scrolling and this unknown exception was thrown; I make use of several extensions but none of them are active on this website, except for those automatic like Adblock, I never had any problems on other websites.

This also appears when tring to back through the browser left arrow:

![image](https://user-images.githubusercontent.com/51419598/203098783-73f098f3-aec2-421d-b548-c4161fa26ed4.png)

### Environment

![image](https://user-images.githubusercontent.com/51419598/203098233-4a6b08a6-a64a-48e1-ab00-07775080d7fa.png)

Google Chrome | 107.0.5304.107 (Official Build) （64 ビット） (cohort: Stable)
-- | --
変更履歴 | 294f9da25eeda7ddca937d7c70b92d53a71745dc-refs/branch-heads/5304@{#1197}
OS | Windows 10 Version 21H2 (Build 19044.2006)
JavaScript | V8 10.7.193.22
ユーザー エージェント | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
コマンドライン | "C:\Program Files\Google\Chrome\Application\chrome.exe" --profile-directory="Profile 1" --flag-switches-begin --flag-switches-end
実行ファイルのパス | C:\Program Files\Google\Chrome\Application\chrome.exe

Any tips or ideas on how to fix that would be helpful, thanks.

**Comment by felipsbreno** [comment]
Hi @alexrintt,

This problem already is know and it is being discussed in #826
