### ISSUE TITLE
Aplication Error

### ISSUE THREAD

**Issue by kerstenbr** [filipedeschamps/tabnews.com.br#842]
Navegador: Firefox
Versão: 107.0 (64 bit)

Até agora não consegui replicar o erro, aconteceu quando eu estava rolando a pagina.
![erro1](https://user-images.githubusercontent.com/84931896/203100006-e5a65f79-b52e-4833-8f47-bdf10a90c4f2.png)
![erro2](https://user-images.githubusercontent.com/84931896/203100028-38aa93ac-3aad-41a3-aaa5-b1ce2751a253.png)
![erro3](https://user-images.githubusercontent.com/84931896/203100036-8d0935c0-1ffc-494e-9791-d10ec77a684b.png)

**Comment by aprendendofelipe** [comment]
Duplicata com #826

Estou encerrando todas que dizem respeito ao mesmo problema, mas fique à vontade para reabrir caso não seja o mesmo problema.

Obrigado!
