### ISSUE TITLE
Erro na tentativa de realizar login

### ISSUE THREAD

**Issue by dougbatista** [filipedeschamps/tabnews.com.br#845]
<img width="1499" alt="Captura de Tela 2022-11-21 às 13 25 16" src="https://user-images.githubusercontent.com/26626451/203107579-e5e970ec-9bec-412a-8a18-85a693ee3689.png">

Boa tarde, pessoal. Estou tendo problema ao tentar realizar login na plataforma.

Minha conta é nova. Detalhes do erro está no print acima.

**Comment by notsogreatdavi** [comment]
Creio que seja por conta do que foi comentado na issue #826 mais cedo. Se for isso, o jeito é esperar por enquanto.

**Comment by aprendendofelipe** [comment]
Duplicidade com #826

Estou encerrando todas que dizem respeito ao mesmo problema, mas fique à vontade para reabrir caso não seja duplicidade.

Obrigado!
