### ISSUE TITLE
Erro de Login

### ISSUE THREAD

**Issue by amarildo5597** [filipedeschamps/tabnews.com.br#846]
O site fica congelado ao fazer login e/ou recuperar senha...

Um erro interno não esperado aconteceu. Informe ao suporte o valor encontrado no campo 'error_id'. (00a23a32-1316-4285-a33b-3b43f3693df0)

**Comment by aprendendofelipe** [comment]
Duplicidade com #826

Estou encerrando todas que dizem respeito ao mesmo problema, mas fique à vontade para reabrir caso não seja duplicidade.

Obrigado!
