### ISSUE TITLE
Sem permissão para fazer login

### ISSUE THREAD

**Issue by Casara** [filipedeschamps/tabnews.com.br#847]
Tive alguns dos problemas já relatados por outros usuários para realizar o cadastro na plataforma. Porém, consegui depois de uma ou duas tentativas sem sucesso.

Meu problema agora se deve ao fato de ter não ter conseguido ativar minha conta com o link recebido por e-email. Em todas as tentativas demorou muito e acabou ocorrendo erro. E agora diz que o token não foi encontrado ou expirou.

Então ao tentar realizar o login estou recebendo uma mensagem de erro informando que não tenho permissão para isso:

![image](https://user-images.githubusercontent.com/2224686/203117650-8e42397b-b85b-4601-8ca4-256709b945be.png)

E não sei onde posso obter um novo token de ativação.

**Comment by Scemist** [comment]
Estou com o mesmo problema, e em complemento, não consigo cadastrar de novo, pois meu usuário já está "sendo usado" pelo cadastro pendente.

**Comment by Casara** [comment]
> Oi @Casara, Imagino que seu usuário no TabNews seja `Casara` mesmo, correto?
> 
> @filipedeschamps, o usuário `Casara` está sem nenhuma _feature_. Imagino que no momento que ele estava ativando a conta o sistema deve ter caído logo após a remoção de `read:activation_token`, mas antes de concluir a inclusão das novas _features_.
> 
> Precisamos resolver esse _TODO_ ou, no mínimo, inverter, fazendo a inclusão das novas antes de remover `read:activation_token`:
> 
> https://github.com/filipedeschamps/tabnews.com.br/blob/fa27bf9c7203d948eea2d889abd35b649697198b/models/activation.js#L97-L109

@aprendendofelipe Sim, meu usuário é `Casara`.

**Comment by aprendendofelipe** [comment]
> Estou com o mesmo problema, e em complemento, não consigo cadastrar de novo, pois meu usuário já está "sendo usado" pelo cadastro pendente.

@Scemist, seu usuário é esse mesmo `Scemist`? Se for, esse usuário possui a *feature* `read:activation_token`, então você pode fazer a ativação ou a recuperação da senha.

**Comment by filipedeschamps** [comment]
Show turma! E @aprendendofelipe obrigado pela investigação!

@Casara acabei de incluir na sua conta as features necessárias para fazer o login, peço que tente novamente: https://www.tabnews.com.br/login

@Scemist neste caso sugiro você seguir o que o @aprendendofelipe falou 🤝

**Comment by Scemist** [comment]
@aprendendofelipe, deu tudo certo, ao tentar fazer o login o link foi enviado e confirmado. Obrigado!

**Comment by filipedeschamps** [comment]
Em paralelo turma, respondi todos os emails sobre problema de cadastro/login que o suporte do TabNews respondeu. Foram mais de 100 emails. Vamo que vamo!! 🤝 👍

**Comment by Casara** [comment]
@filipedeschamps deu tudo certo aqui também. Obrigado!
