### ISSUE TITLE
Erro ao realizar o cadastro

### ISSUE THREAD

**Issue by ricopozzi** [filipedeschamps/tabnews.com.br#851]
<img width="535" alt="Captura de Tela 2022-11-21 às 11 30 18" src="https://user-images.githubusercontent.com/44952024/203126808-777b1db0-9497-4c0b-bb74-e49f4ee9967c.png">

Fica dessa meneira e não sai da tela ao realizar o login

**Comment by aprendendofelipe** [comment]
Duplicata de #826

Estou encerrando todas que dizem respeito ao mesmo problema.

Obrigado pela Issue!
