### ISSUE TITLE
[Sugestão] -  Tags para cada post

### ISSUE THREAD

**Issue by ropoko** [filipedeschamps/tabnews.com.br#854]
Criar tags/categorias para cada post, dessa forma podendo ser possível filtrar posts que falam sobre um mesmo assunto, facilitando a busca.

Como por exemplo: Posts sobre JavaScript teriam uma tag `javascript`.

**Comment by Poveii** [comment]
Creio que isso pode até ajudar o SEO do TabNews quando pesquisado, porque seria as palavras chaves da publicação.

**Comment by Rafatcb** [comment]
Essa ideia foi sugerida também no Issue #742

**Comment by ropoko** [comment]
> Essa ideia foi sugerida também no Issue #742

Ah, não tinha encontrado nenhuma issue com essa sugestão, vou fechar aqui.
