### ISSUE TITLE
Primeira Publicação que faço e não consigo

### ISSUE THREAD

**Issue by jhon4than** [filipedeschamps/tabnews.com.br#858]
![image](https://user-images.githubusercontent.com/44447117/203140513-f0d045f9-3659-463d-900f-e1cfcc267eb1.png)

**Comment by Rafatcb** [comment]
O @filipedeschamps derrubou a API momentaneamente, então agora não é possível fazer nada. Você pode acompanhar o progresso no Issue #826

**Comment by jhon4than** [comment]
Ok , vou fechar essa issue
