### ISSUE TITLE
[Sugestão] - Separa conteúdos por categorias

### ISSUE THREAD

**Issue by jhon4than** [filipedeschamps/tabnews.com.br#859]
Separar cada tema por categorias ou até linguagens por exemplo...
API
C#
JAVA
REACT
JAVASCRIPT
DEVOPS

**Comment by VacariGabriel** [comment]
Essa mesma ideia foi sugerida na issue https://github.com/filipedeschamps/tabnews.com.br/issues/742

**Comment by rodrigoKulb** [comment]
@jhon4than conforme informado pelo @VacariGabriel já estamos falando sobre esse assunto na Issue #742 a mais antiga sobre o assunto, poderia finalizar essa para seguirmos a discussão lá? Obrigado!

**Comment by aprendendofelipe** [comment]
@jhon4than, obrigado pela sugestão! 💪

Estou fechando por ser duplicada. Combinado? 🤝
