### ISSUE TITLE
Erro ao cadastrar

### ISSUE THREAD

**Issue by taprontodev** [filipedeschamps/tabnews.com.br#861]
Tentei cadastrar aqui pela primeira vez e deu isso aqui:
"Você realizou muitas requisições recentemente. Informe ao suporte este valor: 4b4aaf60-ec13-419e-b206-d7ae5328e6a6"

**Comment by LucianoLimaS** [comment]
Mesmo erro aqui comigo: Você realizou muitas requisições recentemente. Informe ao suporte este valor: 8f7fb033-bece-4fd6-a258-e2ff2cf7d2dc

**Comment by aprendendofelipe** [comment]
Duplicidade com #826 826

Estou encerrando todas que dizem respeito ao mesmo problema, mas fique à vontade para reabrir caso não seja o mesmo problema.

Obrigado!
