### ISSUE TITLE
Error Many Requests ao salvar comentário

### ISSUE THREAD

**Issue by CarlosZiegler** [filipedeschamps/tabnews.com.br#863]
Erro ao postar um comentário:
![image](https://user-images.githubusercontent.com/38855507/203143711-aa75eaa2-784e-4223-b336-4217f3da67ec.png)

Achei estranho pois eu apenas comentei uma publicação e recebi esse erro, eu até esperava isso se estivesse postando mais conteúdos, porém não foi o caso. Isso está correto? caso sim desconsiderar a issue. 

Link: https://www.tabnews.com.br/sestrem/supabase-banco-de-dados-pouco-conhecido-no-brasil-porem-extremamente-poderoso

**Comment by iaglourenco** [comment]
O mesmo ocorre ao tentar se cadastrar
![image](https://user-images.githubusercontent.com/24625361/203144463-9d33afa3-d1c3-4f54-9305-f6d46fbf1796.png)

**Comment by VacariGabriel** [comment]
Parece que a API foi derrubada. Sugiro acompanhar essa issue https://github.com/filipedeschamps/tabnews.com.br/issues/826

**Comment by aprendendofelipe** [comment]
Duplicidade com #826

Estou encerrando todas que dizem respeito ao mesmo problema, mas fique à vontade para reabrir caso não tenha relação.

Obrigado!
