### ISSUE TITLE
Não recebo o link para confirmar o cadastro

### ISSUE THREAD

**Issue by fetuffani** [filipedeschamps/tabnews.com.br#864]
De forma resumida, a linha do tempo foi

- Me cadastrei (com dificuldades pois a página estava intermitente)
- Recebi o link para confirmação no e-mail
- Não consegui utilizar (novamente a intermitência)
- O link expirou
- Esperei
- Tentei fazer o login
- O site disse que foi enviado um novo link para confirmação do e-mail
- Dessa vez não recebi nada (nem caixa de spam ou lixo eletrônico)
- Já faz algumas horas que o site apenas me exibe a mensagem "_Você realizou muitas requisições recentemente. Tente novamente mais tarde ou contate o suporte caso acredite que isso seja um erro._"

Desde então não consigo concluir meu cadastro

**Comment by gabrielsozinho** [comment]
A API está offline porque o TabNews estava recebendo muitos acessos. Você pode acompanhar o que está acontecendo aqui: #826

**Comment by aprendendofelipe** [comment]
Duplicidade com #826

Estou encerrando todas que dizem respeito ao mesmo problema, mas fique à vontade para reabrir caso não tenha relação.

Obrigado!

**Comment by fetuffani** [comment]
Estou reabrindo pois mesmo depois da API voltar a funcionar, ainda não recebo o email de confirmação.

Tentei ontem de noite, não recebi. Tentei hoje cedo e também não recebi o link para confirmar o cadastro.

Estou num loop eterno de tentar fazer login e receber a mensagem "_O seu usuário ainda não está ativado. Verifique seu email, pois acabamos de enviar um novo convite de ativação._".
