### ISSUE TITLE
Sugestão: opção de pesquisar por temas dos tópicos

### ISSUE THREAD

**Issue by tjbass2021** [filipedeschamps/tabnews.com.br#869]
Aqui uma sugestão para implementação no site de uma coisa aparentemente trivial que senti falta - que não sei se não está disponível de propósito ou se está sendo ou será implementada - que é a opção de pesquisar por assunto nos tópicos dos artigos publicados. Seria bastante interessante procurar por assuntos específicos para discussões, até evitando abrir uma nova discussão de um exato assunto que já vem sendo discutido na rede.

É isto! De resto estou adorando a rede e já consumindo muito o material lá e contribuindo nos debates!

**Comment by robertluiz** [comment]
Eu ia escrever uma issue agora, da para fazer com google api tipo assim  [Adding Google Custom Search to a headless Ghost blog with a React/Redux front end](https://medium.com/@tony.m.pdx/adding-google-custom-search-to-a-headless-ghost-blog-with-a-react-redux-front-end-b8b79b6dfff7) mas obviamente sem redux

**Comment by Rafatcb** [comment]
Relacionada (e talvez duplicada): #791 
Duplicada fechada: #441

**Comment by volfgam** [comment]
Também senti falta

**Comment by tjbass2021** [comment]
Quando pesquisei não encontrei nada, mas vendo agora, vou fechar a issue.
