### ISSUE TITLE
Bug com teclado mobile

### ISSUE THREAD

**Issue by Jetrom17** [filipedeschamps/tabnews.com.br#872]
Teclado usado:

• Google.

Sistema operacional usado:

• Android (V.: 11).

Bug:

• Ao digitar no fórum, há problemas de exibição de texto ou mau comportamento das caracteres, quando as sugestões do teclado estão ativados.

> Jeiel Miranda.

**Comment by ermesonqueiroz** [comment]
@Jeiel17 teria como gravar a tela e colocar aqui? Pra ficar mais fácil entender o que de fato está acontendo.

**Comment by Jeiel17** [comment]
> @Jeiel17 teria como gravar a tela e colocar aqui? Pra ficar mais fácil entender o que de fato está acontendo.

Aqui está:

https://user-images.githubusercontent.com/72875404/203188376-f77e4804-6aeb-4441-b702-78a774886ec0.mp4

**Comment by aprendendofelipe** [comment]
Olá @Jeiel17, esse é um problema já conhecido com a biblioteca `ByteMD`.

Recomendo acompanhar via #648
