### ISSUE TITLE
Sugestão: retornar do navegador

### ISSUE THREAD

**Issue by felipemarchi** [filipedeschamps/tabnews.com.br#873]
**Eu**, como usuário leitor do tabnews,
**Desejo** manter a altura de rolagem da página de notícias (ex. Relevantes ou Recentes)
**Quando** eu entrar sem querer em uma notícia e retornar para a página anterior através do botão retornar do navegador
**Para** que eu corrija minha ação ou continue procurando outros títulos de onde eu parei

**Comment by aprendendofelipe** [comment]
Implementado em #1176
