### ISSUE TITLE
[Sugestão] Criar temas para o TabNews

### ISSUE THREAD

**Issue by RafaMoralles** [filipedeschamps/tabnews.com.br#874]
Eu, como usuário leitor do tabnews,
Desejo alterar o tema do site para dark
Quando eu entrar nas configurações de perfis
Para agradar aos usuários que tem dificuldade com temas claros.

**Comment by felipsbreno** [comment]
@RafaMoralles 

Tem esse [PR](https://github.com/filipedeschamps/tabnews.com.br/pull/377) para adicionar o tema dark

**Comment by RafaMoralles** [comment]
Muito obrigado, vou acompanhar a thread
