### ISSUE TITLE
Feature: Implementar nosso próprio validador

### ISSUE THREAD

**Issue by moliveiraz** [filipedeschamps/tabnews.com.br#876]
Bom, para validarmos alguns campos nas requisições usamos o **Joi** para essa tarefa. Diante disso, acho interessante criarmos o **nosso próprio validador** para suprir apenas em contextos que faz necessário sem carregar algo extra.

**Comment by Rafatcb** [comment]
Depois de um ano desde o lançamento oficial do TabNews, não me parece que surgiu a necessidade de criar um validador do zero. As bibliotecas existem para facilitar e permitir que nos concentremos no que é essencial para o projeto.

Podemos, então, fechar esse issue?
