### ISSUE TITLE
Sugestão: Notificação de respostas dentro da plataforma

### ISSUE THREAD

**Issue by caduamorimm-dev** [filipedeschamps/tabnews.com.br#878]
Acredito que um botão de notificação seria mais interessante que receber um aviso via e-mail, mais prático e rápido para interagir.

**Comment by aprendendofelipe** [comment]
Turma, obrigado pelas contribuições! 💪

Vou fechar diversas issues com assuntos relacionados. Por isso estou listando abaixo as que serão mantidas abertas e onde recomendo concentrarmos o que foi debatido/sugerido aqui:

- #645 
- #738
- #742 

Fechando essa aqui 🤝
