### ISSUE TITLE
Criar índices para queries mais frequentes

### ISSUE THREAD

**Issue by lemuelroberto** [filipedeschamps/tabnews.com.br#879]
O objetivo é otimizar a utilização de recursos, melhorando tempo de resposta do banco de dados, o que impactará positivamente no número de conexões simultâneas.

Um dos problemas discutidos na #826 é a ausência de índices para as [queries mais frequentes](https://github.com/filipedeschamps/tabnews.com.br/issues/826#issuecomment-1322480535) da aplicação em produção.

Ao maximizar a utilização de índices nas queries mais frequentes o time ganha tempo para pensar melhor nos problemas de performance mais difíceis de resolver.

**Comment by filipedeschamps** [comment]
## Balance Operations

Query que está dentro da stored procedure `get_current_balance()` (exemplo com uma publicação com `70` TabCoins):

```sql
SELECT
	COALESCE(sum(amount), 0)
FROM
	balance_operations
WHERE
  balance_type = 'content:tabcoin'
  AND recipient_id = 'c1c79d7f-e373-45a9-b79a-9c0c9c441f61'
;
```

```
| QUERY PLAN |
| --- |
| Aggregate  (cost=2484.59..2484.60 rows=1 width=8) (actual time=43.052..43.053 rows=1 loops=1) |
|   ->  Seq Scan on balance_operations  (cost=0.00..2484.59 rows=2 width=4) (actual time=42.404..43.041 rows=69 loops=1) |
|         Filter: ((balance_type = 'content:tabcoin'::text) AND (recipient_id = 'c1c79d7f-e373-45a9-b79a-9c0c9c441f61'::uuid)) |
|         Rows Removed by Filter: 79331 |
| Planning Time: 0.079 ms |
| Execution Time: 43.073 ms |
```

O tempo de execução aqui estava alternando entre **50ms** e **8ms** (o que pode pesar bastante no caso de uma lista de conteúdos).

**Comment by lemuelroberto** [comment]
@filipedeschamps , para a primeira eu já acertei os índices, porém só produção pode dizer se realmente vai funcionar.

Se quiser pode dar uma olhada aqui: https://explain.depesz.com/s/WTVL

Em instantes eu subo uma PR com índices para a primeira.

**Comment by filipedeschamps** [comment]
Show! Depois me explica que negócio legal é esse que você colocou no link! Eu tava para fazer o PR sobre o Balance Operations, vou fazer para você dar uma olhada 🤝

**Comment by lemuelroberto** [comment]
@filipedeschamps , enviei um e-mail com o título "Posso ajudar?" para contato@tabnews.com.br. Se quiser trocar ideia síncrona é só me dar um salve lá.

**Comment by filipedeschamps** [comment]
@lemuelroberto showwww!! O email literalmente abarrotou com o problema da API hoje, eu vou demorar para conseguir limpar eles, mas seria legal a gente ter uma conversa sim! 🤝 

Em paralelo, fiz o PR #880 para o Balance Operations, veja o que acha.

**Comment by migueloliveiraz** [comment]
@filipedeschamps, existe alguma possibilidade para fazer doações para o projeto?

**Comment by filipedeschamps** [comment]
@migueloliveiraz não tinha pensado nisso e não tenho a resposta no momento, mas **muito** obrigado por se disponibilizar 😍

**Comment by migueloliveiraz** [comment]
@filipedeschamps, queria discutir acerca do backend do projeto de uma mais profunda. Tenho alguns pontos que referem-se à forma em que foi `construído`. Para isso, é preciso uma issue ou algo mais hight-level como discord?

**Comment by filipedeschamps** [comment]
@migueloliveiraz há um discord não oficial do TabNews, peço que veja: https://www.tabnews.com.br/Ezequias/junte-se-a-nossa-comunidade-no-discord

Mas não estou conseguindo participar de forma síncrona, então sugiro começar lendo o diário de desenvolvimento: https://github.com/filipedeschamps/tabnews.com.br/wiki

Sugiro também mantermos essa issue sobre os índices que estamos criando 🤝

**Comment by aprendendofelipe** [comment]
> Total, estou analisando aqui e tentando entender onde estão os gargalos dentro das queries. Vou mandando um query planner por query, dá uma acompanhada @aprendendofelipe

@filipedeschamps, só agora estou chegando nisso 😅

Mas o @lemuelroberto mandou muito bem! 🤝🚀

**Comment by lemuelroberto** [comment]
@filipedeschamps @aprendendofelipe , fechando a issue.
Se julgarem que faz sentido mantê-la aberta, é só reabrir, e fico à disposição para aprofundarmos a discussão.
