### ISSUE TITLE
[FEATURE] Favoritar postagens

### ISSUE THREAD

**Issue by brendo10x** [filipedeschamps/tabnews.com.br#884]
User Story: Eu como usuário gostaria de poder favoritar postagens que gostei para rever depois.

Fica a sugestão ;)

**Comment by Rafatcb** [comment]
Duplicada do #830 e #645

**Comment by aprendendofelipe** [comment]
@brendo10x obrigado pela sugestão! 💪

Por organização, estou fechando as duplicadas com a #645 🤝
