### ISSUE TITLE
[FEATURE] Botões de compartilhar nas redes sociais

### ISSUE THREAD

**Issue by brendo10x** [filipedeschamps/tabnews.com.br#885]
User Story: eu como usuário gostaria de poder clicar no botão de compartilhar (twitter, WhatsApp, etc..) a postagem nas minhas redes sociais para que meus amigos vejam também.

Fica a dica ;)

**Comment by fdc2001** [comment]
Boas, Estou a testar esse sistema, mas quais redes socias sugerias colocar?

![image](https://user-images.githubusercontent.com/51190714/203278384-cd903adc-7137-46d2-94f0-1985d9b8d456.png)

Estes é os que já pus, ainda falta colocar mais bonitinhos

**Comment by brendo10x** [comment]
Opa, ficaria bacana se colocasse o botão do LinkedIn, Twitter e WhatsApp. Acredito que sejam as redes sociais que dariam um "boom" nas postagens do TabNews.

**Comment by fdc2001** [comment]
https://github.com/filipedeschamps/tabnews.com.br/pull/888

Já fiz agora é aguardar 😁

**Comment by brendo10x** [comment]
Rapaz, o omi é rápido, viu. Kkkk
Show de bola, obrigado por implementar!!

**Comment by ErickCReis** [comment]
Um tempo atrás já iniciaram a implementação dessa feature (https://github.com/filipedeschamps/tabnews.com.br/pull/814) e acabaram optando por algo mais simples que está nesse PR: https://github.com/filipedeschamps/tabnews.com.br/pull/875

**Comment by Rafatcb** [comment]
Acredito que podemos fazer um único botão, para ficar mais simples, e assim concentrar a discussão no issue #813 ou #1398 (talvez fosse melhor, inclusive, fechar um destes, porque cada um aborda uma parte diferente da mesma coisa).

**Comment by Rafatcb** [comment]
Bom, para organizar o repositório, vou fechar este issue e orientar seguir a discussão no #813. Obrigado pela sugestão!
