### ISSUE TITLE
[FEATURE] Visualizar postagens via shell

### ISSUE THREAD

**Issue by brendo10x** [filipedeschamps/tabnews.com.br#886]
User Story: eu como usuário gostaria de poder visualizar as postagens no terminal para ver de forma ágil e simples.

Obs: não somente visualizar, mas disponibilizar comandos para interagir com o TabNews via shell de comandos no terminal.

Obs: fica a dica ;)

**Comment by Rafatcb** [comment]
Acho que isso sai do escopo do projeto. O TabNews possui uma API para outras pessoas fazerem integração como desejarem.

**Comment by Rafatcb** [comment]
@aprendendofelipe seguindo com o objetivo de organizar as issues, me parece que essa está fora do escopo.

Além disso, como já foi mencionado, existem alguns projetos que a comunidade fez para isso. Alguns outros exemplos são:

* [Pitch: Yet another TabNews CLI. Este estou fazendo em Go. - cetorres](https://www.tabnews.com.br/cetorres/pitch-yet-another-tabnews-cli-este-estou-fazendo-em-go)
* [Pitch: Tabnews no terminal - vadolasi](https://www.tabnews.com.br/vadolasi/estou-desenvolvendo-um-editor-de-codigo-online)

**Comment by aprendendofelipe** [comment]
Exato @Rafatcb! 💪

Fechando...
