### ISSUE TITLE
[FEATURE] TabNews na versão mobile Android

### ISSUE THREAD

**Issue by brendo10x** [filipedeschamps/tabnews.com.br#887]
User Story: eu como usuário gostaria de poder ter o  TabNews na versão mobile Android para visualizar as postagens no celular.

Obs: Indico essas ferramentas para versão mobile: Flutter ou React

**Comment by thisiscleverson** [comment]
Existe uma iniciativa de um projeto mobile do TabNews.

Post: https://www.tabnews.com.br/higor/aplicativo-do-tabnews
repositório: https://github.com/higorpo/tabnews-mobile

**Comment by danielkv** [comment]
Eu me interesso em fazer parte do projeto. Trabalho com RN e posso ajudar a comunidade a desenvolver. Só precisamos uma documentação da API.

**Comment by thisiscleverson** [comment]
existe duas documentação da api não oficial do tebnews. Uma é do @coffee-is-power e a outra do @gabrielsozinho.

1. https://coffee-is-power.github.io/tabnews-openapi/
2. https://www.tabnews.com.br/GabrielSozinho/documentacao-da-api-do-tabnews

**Comment by danielkv** [comment]
Ah show, vou dar uma olhada! Quem estiver interessado em seguir esse projeto em RN, podemos iniciar! Pelo que vi o projeto que já estava em andamento em Flutter acho que ficou meio abandonado, está parado há uns 6 meses

**Comment by coffee-is-power** [comment]
Eu tenho um app mobile na minha conta do GH,só ver lá tabnews-mobile em Flutter

**Comment by danielkv** [comment]
> Eu tenho um app mobile na minha conta do GH,só ver lá tabnews-mobile em Flutter

Você chegou a publicar o app?

**Comment by coffee-is-power** [comment]
Ainda não está pronto, falta várias features e tem muitos bugs

**Comment by danielkv** [comment]
> Ainda não está pronto, falta várias features e tem muitos bugs

Haha acontece com os melhores devs! Então não tenho muito conhecimento em Flutter, por isso sugeri em RN.

**Comment by coffee-is-power** [comment]
Algumas screenshots:
![Screenshot_20221122-131851_TabNews.png](https://user-images.githubusercontent.com/92828847/203324045-fb812171-7c3e-4efd-b6ab-9f995f125425.png)![Screenshot_20221122-131908_TabNews.png](https://user-images.githubusercontent.com/92828847/203324036-a2ca04de-b17d-431a-99bb-1f3aa1525f31.png)

**Comment by coffee-is-power** [comment]
@danielkv o problema do RN e a pulverização do js, precisa de lib pra tudo! Só pra rodar o app no celular e preciso rodar uns 5 comandos.

**Comment by coffee-is-power** [comment]
E também o flutter usa o skia pra renderizar os widgets invés de usar os componentes do sistema, então fica consistente em todas as plataformas

**Comment by danielkv** [comment]
> @danielkv o problema do RN e a pulverização do js, precisa de lib pra tudo! Só pra rodar o app no celular e preciso rodar uns 5 comandos.

> E também o flutter usa o skia pra renderizar os widgets invés de usar os componentes do sistema, então fica consistente em todas as plataformas

eu utilizo Expo pra desenvolver, não sofro mais com isso. haha. Mas não tenho nada contra Flutter não. Como trabalho com React / React Native há mais de 6 anos, tenho mais afinidade com a tecnologia. Apesar de achar o Flutter um puta Framework, não me sinto seguro em iniciar um projeto com ele sozinho, mais por experiencia mesmo.

Nem mesmo gosto de entrar em discussão que um é melhor por conta disso e aquilo. Acho que os 2 tem suas vantagens e desvantagens. O melhor mesmo é o que funciona! Se Flutter funcionar, perfeito. Se RN funcionar, ótimo.

Caso queira ajuda em alguma coisa do projeto, pode contar comigo, não tenho muita XP com Flutter, mas bastante XP em várias outras tecnologias e arquiteturas. Fico a disposição!

**Comment by coffee-is-power** [comment]
Bom como qualquer coisa que quiser aprender,só faz qualquer coisa independente se for útil ou não, só cria um projeto e escreve código.

**Comment by danielkv** [comment]
> Bom como qualquer coisa que quiser aprender,só faz qualquer coisa independente se for útil ou não, só cria um projeto e escreve código. Foi assim que aprendi dart.

Claro irmão! Assim mesmo que se aprende. Assim como se aprofundar nas tecnologias que já se sabe.

**Comment by avuenja** [comment]
Estamos desenvolvendo um também, onde já tem um app dos testes em alpha para baixar no release.

Segue algumas das features.

## Features:

- [x] Dark mode
- [x] Leitura de conteúdos
- [x] Pull To Refresh
- [x] Infite Scroll
- [x] Visualização de Comentários das publicações
- [x] Login do usuário
- [x] Meus conteúdos
- [x] Gerencimaneto de conta
- [x] Criação de conta pelo App
- [ ] Resposta dos conteúdos
- [ ] Postagens de conteúdos
- [ ] Visualização do perfil de outros usuários
- [ ] Favoritos (local database)
- [ ] Opção ler mais tarde (local database)
- [ ] Buscar conteúdos (?)

Quem puder contribuir, é sempre bem vindo. E é muito legal que o pessoal está muito animado, e criando seus próprios clientes do TabNews.

**Repositório**: https://github.com/avuenja/tabnews-app

**Comment by DiegoRamosGomes** [comment]
> Eu me interesso em fazer parte do projeto. Trabalho com RN e posso ajudar a comunidade a desenvolver. Só precisamos uma documentação da API.

Eu passo pela mesma coisa que vc e por isso comecei a fazer um APP em RN, caso queira dar uma olhada
https://github.com/DiegoRamosGomes/tabnews-app

**Comment by avuenja** [comment]
@DiegoRamosGomes muito bom meu querido! Lembro de você ter comentado no post lá, que ia fazer para treinar o RN.

Vou acompanhar! Bora pra cima! 👊🏻

**Comment by aprendendofelipe** [comment]
Turma, considerando que já existem diferentes versões de aplicativos que se utilizam da API do TabNews, podemos dar essa issue como encerrada. 🤝
