### ISSUE TITLE
Não recebo o link para confirmar o cadastro

### ISSUE THREAD

**Issue by fetuffani** [filipedeschamps/tabnews.com.br#890]
depois da API voltar a funcionar, ainda não recebo o email de confirmação.

Tentei ontem de noite, não recebi. Tentei hoje cedo e também não recebi o link para confirmar o cadastro.

Estou num loop eterno de tentar fazer login e receber a mensagem "_O seu usuário ainda não está ativado. Verifique seu email, pois acabamos de enviar um novo convite de ativação._".

PS: Não consegui reabrir minha outra issue #864

**Comment by Enr1coFreitas** [comment]
Estava ocorrendo o mesmo problema comigo, portanto refiz o login e recebi a mesma mensagem que ti. Porém recebi o e-mail de confirmação e deu tudo certo.
Recomendo ir testando e efetuando login até o recebimento do e-mail de confirmação.

**Comment by gabrielsozinho** [comment]
Verifique a sua caixa de lixeira e spam, talvez o email tenha ido parar lá. 👍🏻

**Comment by fetuffani** [comment]
> Verifique a sua caixa de lixeira e spam, talvez o email tenha ido parar lá. 👍🏻

Já verifiquei e não se encontra em nenhuma caixa, nem de spam, nem lixo eletronico

**Comment by gabrielsozinho** [comment]
Uma solução é você criar uma nova conta usando o `seuemail+seuusername@gmail.com`. Assim você vai receber um código (no email mesmo). Só acho que você não vai conseguir usar o mesmo username que queria, além disso, quando for logar você vai precisar usar o email dessa forma que cadastrou.

**Comment by aprendendofelipe** [comment]
Oi @fetuffani, você fez mais um teste hoje após o almoço? No período da manhã a API novamente ficou fora do ar por alguns minutos e você pode ter tentado justo nesse horário.

**Comment by fetuffani** [comment]
> Oi @fetuffani, você fez mais um teste hoje após o almoço? No período da manhã a API novamente ficou fora do ar por alguns minutos e você pode ter tentado justo nesse horário.

Acabei de fazer um novo teste e ainda não recebo o email de confirmação.

**Comment by Enr1coFreitas** [comment]
Então provavelmente o seu cadastro não foi efetivado. Tente com outro e-mail, deve funcionar...

**Comment by aprendendofelipe** [comment]
@fetuffani, qual é o provedor de email que está utilizando?

**Comment by fetuffani** [comment]
> Então provavelmente o seu cadastro não foi efetivado. Tente com outro e-mail, deve funcionar...

O cadastro foi efetivado sim, tanto que não consigo utilizar o mesmo email ou username



> @fetuffani, qual é o provedor de email que está utilizando?

Estou usando o @outlook.com

**Comment by aprendendofelipe** [comment]
@fetuffani, acabei de fazer um cadastro utilizando outlook.com e, apesar do primeiro email ter sido marcado como lixo eletrônico, eu recebi também o segundo email de ativação, que é enviado ao tentar fazer login sem ativar a conta.

Então, a princípio, os emails estão sendo entregues.

Tenta pesquisar por "Ative seu cadastro no TabNews" dentro do Outlook para ver se a mensagem não foi parar em alguma pasta mais escondida.

Alguma chance de ter cometido algum erro de digitação no endereço de email na hora do cadastro? Daí pode estar preenchendo o mesmo endereço incorreto se estiver utilizando o autopreenchimento.

**Comment by fetuffani** [comment]
> Tenta pesquisar por "Ative seu cadastro no TabNews" dentro do Outlook para ver se a mensagem não foi parar em alguma pasta mais escondida.
> 
> Alguma chance de ter cometido algum erro de digitação no endereço de email na hora do cadastro? Daí pode estar preenchendo o mesmo endereço incorreto se estiver utilizando o autopreenchimento.

Então, eu consegui fazer o cadastro pouco antes da API ter sido desligada por excesso de atividade, chegou o email de ativação normalmente. Quando fui fazer a verificação, a API estava desligada já e não consegui verificar. No dia seguinte tentei acessar o link e a chave de verificação já havia expirado. Agora quando tento fazer o login ele diz que foi enviado uma nova chave porém não recebo nada.

Ou seja, não é problema de recebimento ou de digitação do email já que o primeiro eu cheguei a receber, só não consegui confirmar pois a API estava offline e a chave expirou

**Comment by aprendendofelipe** [comment]
@fetuffani, por favor, envie um email para contato@tabnews.com.br informando essa *issue* e avise a gente por aqui quando enviar.

@filipedeschamps, por favor, depois que o @fetuffani enviar o email, responda para ele pra gente ver se ele consegue receber essa resposta ou onde vai parar essa mensagem.

**Comment by fetuffani** [comment]
> @fetuffani, por favor, envie um email para [contato@tabnews.com.br](mailto:contato@tabnews.com.br) informando essa _issue_ e avise a gente por aqui quando enviar.

Fiz o envio do email usando o mesmo endereço que usei pra cadastrar, fico aguardando resposta

Desde já, obrigado pela ajuda! Se precisarem de algo ou informação a mais, fico feliz em ajudar!

**Comment by filipedeschamps** [comment]
Turma, respondi o email e também vou caçar nos logs do Mailgun para entender o que está acontecendo 🤝

**Comment by filipedeschamps** [comment]
Identifiquei porque @fetuffani não estava recebendo mais emails: por algum motivo, o Mailgun recebeu um `complaint` do seu provedor. Isso pode ter acontecido por alguma ação manual sem querer, ou por conta de servidor conversando com servidor mesmo 😂 

@fetuffani peço que tente novamente 👍

**Comment by fetuffani** [comment]
> Identifiquei porque @fetuffani não estava recebendo mais emails: por algum motivo, o Mailgun recebeu um `complaint` do seu provedor. Isso pode ter acontecido por alguma ação manual sem querer, ou por conta de servidor conversando com servidor mesmo 😂
> 
> @fetuffani peço que tente novamente 👍

Que estranho hahah, única coisa que fiz foi mover o email da caixa de de spam para a caixa de entrada.

Mas enfim, consegui receber a resposta e fazer a ativação da conta!

Agradeço a ajuda @filipedeschamps @aprendendofelipe @gabrielsozinho @Enr1coFreitas !

Estou marcado a issue como resolvida!
