### ISSUE TITLE
Sugestão: Separar Conteúdo de Comentários nas páginas de perfil.

### ISSUE THREAD

**Issue by guilherssousa** [filipedeschamps/tabnews.com.br#891]
## Ideia 

A sugestão é que comentários e conteúdos originais sejam exibidos separadamente, em um formato de abas ou com tags para filtrar esses conteúdos.

## Motivação

A maior razão para se adicionar essa feature é que melhora a experiência na hora de checar perfis que interagem muito com a comunidade, pois assim você poderá escolher se prefere ver seus posts originais ou seus comentários, sem ter que ficar lidando com paginação para achar o conteúdo desejado.

## Exemplo
Um grande exemplo de site que faz essa separação é o Reddit: 

Nele, você inicia com uma visão com todas as atividades (como o TabNews mostra, por agora) e também existem enésimas opções para filtrar o conteúdo, com destaques para Postagens e Comentários.
![image](https://user-images.githubusercontent.com/47110995/203310186-18f14ac5-ab9d-495d-a844-5b901a91f7d1.png)

**Comment by Rafatcb** [comment]
É uma boa ideia e eu concordo, já dei minha opinião na _issue_ duplicada: #807

**Comment by aprendendofelipe** [comment]
Boa @guilherssousa! Recomendo centralizar a discussão na #807

**Comment by aprendendofelipe** [comment]
Por organização, estou fechando a duplicada. 🤝
