### ISSUE TITLE
[FEATURE] Separar Post e Peguntas, adicionar categorias, área de perguntas urgentes(com recompensa)

### ISSUE THREAD

**Issue by DaniloCarSan** [filipedeschamps/tabnews.com.br#893]
**Separar Post e Perguntas**
Criar uma parte de perguntas e outra de posts(artigo,tutorial) pois está confuso

**Adicionar categorias**
Adicionar categorias tanto para posts e perguntas ou adicionar tags e separa por elas,

**Área de perguntas urgentes**
Criar uma área de perguntas urgentes que a pessoa que está perguntando pode oferecer tabcoins para a melhor resposta  como recompensa ou pagar para colocar sua pergunta lá.

**Comment by yuriveiga** [comment]
Apenas complementando, para facilitar as buscas poderia ser criada uma arvore de tags. 

Algo do tipo: 
                                 
Tag mãe: **Carreira em tech** 
Tags filhas: 
              **Inicio de carreira**
              **Transição de carreira** 
              **Aperfeiçoamento**
