### ISSUE TITLE
[UX] Melhorar mensagem de confirmação ao alterar `username`

### ISSUE THREAD

**Issue by fgandraf** [filipedeschamps/tabnews.com.br#895]
1-Fiz um comentário em uma postagem;
2-Resolvi mudar meu nome de usuário;
3-O comentário foi apagado mas as coins geradas foram mantidas. 

Nao sei se esse era mesmo o comportamento esperado mas

"escrever comentário->mudar nome de usuário->escrever comentário->mudar nome de usuário....."

Resulta em coins sem participação efetiva.

**Comment by filipedeschamps** [comment]
Fala meu caro, muito interessante! Quando você quer dizer "comentário foi apagado", você usou o comando de apagar o comentário, ou a URL para o seu comentário mudou (e a antiga está dando `404`)?

Qual seu usuário no TabNews para eu poder avaliar?

**Comment by Rafatcb** [comment]
Tentei reproduzir no ambiente de [staging](https://tabnews-1y5i5q50q-tabnews.vercel.app/) e ao apagar o comentário, as TabCoins eram removidas. Caso alguém queira testar, sugiro usar esse link (https://tabnews-1y5i5q50q-tabnews.vercel.app/) ao invés do site em produção.

**Comment by brunofamiliar** [comment]
> Tentei reproduzir no ambiente de [staging](https://tabnews-1y5i5q50q-tabnews.vercel.app/) e ao apagar o comentário, as TabCoins eram removidas. Caso alguém queira testar, sugiro usar esse link (https://tabnews-1y5i5q50q-tabnews.vercel.app/) ao invés do site em produção.

Realmente em staging, quando removo o comentário o tabcoins são retirados. Eu não consegui acompanhar toda thread dessa feature #352; mas acredito que este é o comportamento correto @filipedeschamps certo? Porque senão pode gerar um "faturamento" falso de tabcoins, visto que tabcoins são ganhas apenas quando é gerado valor na plataforma

**Comment by fgandraf** [comment]
Usuário antigo: fgandraf
Usuário novo: felipeGandra
Postagem: https://www.tabnews.com.br/JhowBR/resumao-clean-code

@filipedeschamps Quando fiz o comentário e mudei o nome de usuário, ele apenas desapareceu da postagem. Então fiz novamente (gerando novas 2 coins). Agora, entrei para verificar e está aprecendo os dois.

![image](https://user-images.githubusercontent.com/41455881/203332949-1261687c-15b3-43c4-a7d2-0129e46e50ba.png)

**Comment by brunofamiliar** [comment]
> 

Esse problema realmente vai acontecer, ainda não foi implementado uma tratativa; por isso o alerta:

![image](https://user-images.githubusercontent.com/32016729/203333182-e7767df4-e6b5-49d9-b25f-346a23cba75d.png)

**Comment by filipedeschamps** [comment]
Show turma, então é isso mesmo! Ao mudar o nome de usuário a URL absoluta antiga (com o username antigo) de fato deixa de existir, mas o conteúdo nesse caso não é apagado.

**Comment by fgandraf** [comment]
> > 
> 
> Esse problema realmente vai acontecer, ainda não foi implementado uma tratativa; por isso o alerta:
> 
> ![image](https://user-images.githubusercontent.com/32016729/203333182-e7767df4-e6b5-49d9-b25f-346a23cba75d.png)

Eu vi esse alerta mas como fiz um "comentário" em uma publicação, não pensei que quebraria. De qualquer maneira, vou excluir um dos duplicados e verificar se as coins são recalculadas.

**Comment by fgandraf** [comment]
Pronto! exclui a duplicada e as coins foram recalculadas corretamente.
Ficando então apenas a sugestão para mudar o texto para algo como "Isto irá quebrar todas as URLs das sua publicações e comentários" (ou "postagens e comentários")
Valew turma!

**Comment by fgandraf** [comment]
Ah! talvez limitar a quantidade de vezes que um usuário pode mudar o nome (máximo 2 por exemplo, ou talvez, limitar por tempo: 1 alteração a cada X meses)

**Comment by dfeprado** [comment]
Seria uma boa idéia tornar o nome de usuário uma chave substituta e linkar as moedas à uma chave interna, evitando que alterações de nomes de usuário criem problemas?

**Comment by votanruchel** [comment]
Para os links quebrados acredito que invés de limitar o usuário a trocar o nickname x vezes, criar uma espécie de permalink na qual mesmo com o nickname antigo continuaria funcionando e os novos passariam a conter o novo nickname, claro que teria que implementar uma tratativa para um novo usuário não poder utilizar o nickname legado de outro usuário.

**Comment by aprendendofelipe** [comment]
Editei o título para corresponder ao que está pendente na issue, que é melhorar a mensagem aqui:

https://github.com/filipedeschamps/tabnews.com.br/blob/4e4d030cd4c0c2e240c96e5cfea16e43604aa223/pages/perfil/index.public.js#L81-L86

**Comment by ErickBessa** [comment]
@aprendendofelipe Gostaria de contribuir com essa issue, sabe se tem alguém atuando nela?

**Comment by aprendendofelipe** [comment]
> o que acha da mensagem "_Isto irá quebrar todas as URLs de seus conteúdos e comentários_." ser implementada?

"Conteúdos" já abrange publicações e comentários, mas pela motivação da issue, é melhor colocar "publicações e comentários". E acho que "Isso" fica mais correto no lugar de "Isto".

`Isso irá quebrar todas as URLs de suas publicações e comentários.`
