### ISSUE TITLE
Adicionar 2fa no tabnews

### ISSUE THREAD

**Issue by coffee-is-power** [filipedeschamps/tabnews.com.br#897]
2FA e uma coisa que eu acho importante pra seguranca de qualquer conta, o fato de só ter e-mail, nome de usuário e senha e um pouco assustador, não e muito seguro.
Eu quero tentar implementar 2FA no tabnews, vai ser um ótimo exercício!

**Comment by coffee-is-power** [comment]
Eu só tenho uma pergunta, como será que vamos armazenar o segredo do 2FA de maneira segura?

**Comment by aprendendofelipe** [comment]
@coffee-is-power, obrigado pela proposta! 💪

Por organização, vou fechar essa issue, e vamos centralizar a conversa no #1171, que já possui mais interações. Combinado? 🤝
