### ISSUE TITLE
[FEATURE] - Criação de rascunhos na criação de um novo conteúdo

### ISSUE THREAD

**Issue by Enr1coFreitas** [filipedeschamps/tabnews.com.br#899]
**Criação de uma nova funcionalidade de rascunho na criação de um novo conteúdo.**
-- Seria bacana uma implementação de rascunhos ao iniciar a criação de um novo conteúdo.
-- Nem sempre temos a ideia ou o conteúdo 100% preparado, e poder salvar um rascunho, ideias ou até mesmo anotações seria uma funcionalidade bem bacana para que pudessemos testar e verificar a usabilidade.

**Comment by coffee-is-power** [comment]
O tabnews já tem isso, se você sair da página de criar post, ele guarda o texto e você pode publicar mais tarde.

**Comment by aprendendofelipe** [comment]
@Enr1coFreitas, obrigado pela sugestão! 💪

Vou fechar essa issue para concentrarmos na #960, em que há mais interações. 🤝
