### ISSUE TITLE
Sugestão + PR: Adicionar Issue Templates

### ISSUE THREAD

**Issue by guilherssousa** [filipedeschamps/tabnews.com.br#902]
Abri um PR #892 onde crio e explico toda a razão do uso de Issue Templates para padronizar e direcionar a criação de isseus no repositório do Tabnews!

**Comment by aprendendofelipe** [comment]
Em complemento ao texto que já se encontra no início dos templates, acham que vale a pena adicionar uma caixa de seleção obrigatória (no final) com algo como "Pesquisei e não encontrei nenhuma discussão relacionada"?

Ou uma caixa de seleção, dando também a opção "Encontrei e estou citando as issues relacionadas"?

Faz sentido?

**Comment by Rafatcb** [comment]
@aprendendofelipe acho que uma caixa de seleção obrigatória será ótima.
