### ISSUE TITLE
Link de corfirmação indo sempre pra junk do email

### ISSUE THREAD

**Issue by eramoss** [filipedeschamps/tabnews.com.br#903]
demorei um tempo para achar o link de confirmação, não sei como pode ser resolvido, mas pode ser um problema para novos usuários futuros. Porém acredito que isso se resolva com a popularidade do site

**Comment by GTSouza** [comment]
Talvez seja resolvido com a configuração DKIM e SPF (configuração no DNS do domínio)

Validação:
https://toolbox.googleapps.com/apps/checkmx/check?domain=tabnews.com.br&dkim_selector=

Sugestão:
https://support.google.com/a/answer/174124

**Comment by aprendendofelipe** [comment]
@eramoss, obrigado por reportar! 💪

Acredito que o problema pode ter ocorrido nos primeiros dias após o lançamento devido a grande mudança no volume de emails disparados, mas nunca mais ninguém reportou nada parecido.

Por isso vou fechar a issue. 🤝
