### ISSUE TITLE
[Feature] Versão GraphQL da API

### ISSUE THREAD

**Issue by SeltikHD** [filipedeschamps/tabnews.com.br#907]
Eae devs!

Vocês também acham que seria uma boa adição uma versão GraphQL da atual API do TabNews?

Ao meu ver algumas vantagens seriam:

- Escolher exatamente a informação desejada;
- Melhor controle de versionamento da API;
- Mais amigável para quem está desenvolvendo;

Caso tenham mais alguma sugestão podem comentar para complementar ainda mais a ideia.

**Comment by SeltikHD** [comment]
Bem comentado @brendo10x, outra vantagem que também não comentei é documentação, devido ao Schema que se é criado, o próprio GraphQL já diz os campos e funções disponíveis pra consulta.

Uma biblioteca que tenho em mente pra fazer o backend em GraphQL é o Apollo, alguém alguma ideia de mais alguma que de pra colocar ir complementar a API?

**Comment by nordyc** [comment]
Principalmente se usar um Apollo, consegue criar uma boa documentação e com ambiente de teste

**Comment by SeltikHD** [comment]
Eu tava dando uma olhada, e decidi que vou usar o Nexus para a criação do Schema e o Apollo para o servidor. Tô sem tempo para desenvolver a API agora, mas vou tentar começar no final de semana, aí vou falando o progresso aqui.
