### ISSUE TITLE
Loading page

### ISSUE THREAD

**Issue by am-castro** [filipedeschamps/tabnews.com.br#908]
Seria interessante adicionar um loading no projeto, para desaparecer quando for carregado.

`https://codepen.io/akai/pen/oNpOVP`

**Comment by aprendendofelipe** [comment]
Considerando a data da sugestão, que foi na época do lançamento, período em que o volume de acessos foi muito grande e o sistema ficou instável, acredito que a intenção era usar um loading como fallback das páginas estáticas que ainda não tinham cache (`fallback: true` no `getStaticPaths` do Next).

Como usamos `fallback: 'blocking'`, quando alguém acessa uma página que ainda não está em cache, o Next não devolve nada até que a página seja gerada no servidor. Normalmente isso é muito rápido, mas se ocorre em um momento de instabilidade, por exemplo com lentidão no banco de dados, isso prejudica a experiência.

Mesmo tendo a `Progressbar`, como em boa parte dos sistemas, o progresso dela não tem relação com o progresso real da navegação, então ela para de crescer se a navegação demorar mais do que determinado tempo (acho que 200ms).

Naquele momento do lançamento, esse loading simples talvez fosse uma solução emergencial interessante, mas nas condições atuais normais, acredito que até pode fazer sentido usar `fallback: true`, mas com um fallback mais elaborado. Talvez usando Skeleton, mas não vejo isso como uma dor que mereça uma issue aberta tanto tempo, então estou fechando. 🤝
