### ISSUE TITLE
[FEATURE] Pesquisar por título da postagem

### ISSUE THREAD

**Issue by brendo10x** [filipedeschamps/tabnews.com.br#909]
User Story: Como usuário gostaria de pesquisar por título da postagem para encontrar o post desejado.

**Comment by klawdyo** [comment]
Pode usar "site:" também.

Ex.:

> site:tabnews.com.br como usar jwt

**Comment by Rafatcb** [comment]
A barra de pesquisa foi implementada em Julho/2023 (https://github.com/filipedeschamps/tabnews.com.br/pull/1472). Não é uma pesquisa que se restringe à busca por título, mas me parece que resolve a dor original, então poderíamos encerrar essa issue.

**Comment by aprendendofelipe** [comment]
@brendo10x, obrigado pela proposta! 💪

Concordo com o @Rafatcb sobre a necessidade original ter sido atendida. 👍

Em um futuro devemos desenvolver um sistema de busca próprio, que permita incluir filtros específicos, mas com a demanda atual não vale a pena o custo/benefício.

Vou fechar a issue, mas qualquer coisa podemos reabrir. 🤝
