### ISSUE TITLE
Separar comentários e posts

### ISSUE THREAD

**Issue by am-castro** [filipedeschamps/tabnews.com.br#911]
Acho ideal separar esses dois, não só por ícone.

O que acho incrível é que posso estudar React agora na prática, vou tentar criar essa separação com TABS, podendo clicar em um tab para ver publicações e no outro tab para ver comentários do usuário!

![image](https://user-images.githubusercontent.com/16366137/203405523-cd77d948-60ab-4673-b29a-0706bd5ed47b.png)

**Comment by aprendendofelipe** [comment]
Boa @am-castro!

Recomendo dar continuidade por essa duplicada #807

**Comment by am-castro** [comment]
Obrigado, vou fechar essa issue e acompanhar a #807

**Comment by am-castro** [comment]
Obrigado, vou fechar essa issue e acompanhar a #807
