### ISSUE TITLE
[Feature] RSS feed and Dark mode!

### ISSUE THREAD

**Issue by IGN-Styly** [filipedeschamps/tabnews.com.br#912]

**Comment by lucasalberto01** [comment]
Eu estava olhando justamente isso e já tem uma PR para isso #377

**Comment by ErickCReis** [comment]
O TabNews já tem suporte a RSS: https://www.tabnews.com.br/rss
Foi implementado nesse PR: https://github.com/filipedeschamps/tabnews.com.br/pull/621
