### ISSUE TITLE
[Infra][Proposta de melhoria] Utilizar PostgreSQL Connection Pooling em produção

### ISSUE THREAD

**Issue by lemuelroberto** [filipedeschamps/tabnews.com.br#913]
Considerando o problema do número de conexões como um todo - #826 - um problema conhecido de deployments serverless é um consumo maior do número de conexões com banco de dados, uma vez que o reuso de uma mesma conexão em múltiplas requisições é não trivial.

Uma solução clássica para esse problema é a utilização de Connection Pooling. O [PgBouncer](https://www.pgbouncer.org/) é uma solução open source muito utilizada pela comunidade PostgreSQL, o [Amazon RDS Proxy](https://aws.amazon.com/rds/proxy/faqs/) é uma solução gerenciada da Amazon e tem algumas outras opções no mercado.

Essa é uma solução com baixo custo de desenvolvimento pois é apenas na camada de infra. A aplicação se conecta ao Pooler como se estivesse conectando ao banco, e o Pooler faz uma gestão mais eficiente das conexões com o banco de dados.

Considerando o problema, fico à disposição para aprofundar na discussão.

**Comment by aprendendofelipe** [comment]
Boa @lemuelroberto! No PR #715 eu sugeri a utilização do PgBouncer. Já o RDS Proxy eu vi que teria algumas complicações no nosso caso, então nem comentei.

Mas agora com a experiência que tivemos nesses dois dias, e dado o alto custo de manter as lambas conectadas ao pool e aguardando o banco ter recursos para responder as consultas, acho que ainda não é o momento de usarmos algo como o PgBouncer.

Acho que é uma ideia que vai contra o que é dito em #915. Por favor, me corrija se não fizer sentido o que eu disse! 🤝

**Comment by lemuelroberto** [comment]
@aprendendofelipe , que maravilha que já discutiram o uso de um Pooler como o PgBouncer. Acredito que pode ajudar bastante na manutenção e gerenciamento mais saudável das conexões com o banco de dados.

Com relação ao timeout mais restrito proposto em #915 e a utilização de um Pooler, são estratégias complementares.

De um lado, timeouts mais restritos forçam uma previsibilidade maior da qualidade do serviço pois protege a infraestrutura como um todo em um momento de maior tráfego ou em um momento que a infraestrutura esteja sofrendo por qualquer que seja a razão, como por exemplo a indisponibilidade do banco de dados.

Do outro lado temos a gestão mais adequada das conexões com o banco de dados considerando a característica do deployment da aplicação que é efêmera (serverless). O uso de PgBouncer é muito comum, e recomendado, por exemplo em aplicações PHP tradicionais, que também abrem e finalizam as conexões com o banco a cada nova requisição HTTP.

Desse modo, a proposta de limitar mais o timeout da aplicação e a gestão das conexões com o banco de dados são complementares e juntas podem representar uma melhora significativa em momentos em que a infra tem mais demanda, resultando numa melhor garantia da qualidade de serviço.

**Comment by lemuelroberto** [comment]
@filipedeschamps @aprendendofelipe , fechando a issue.
Se julgarem que faz sentido mantê-la aberta, é só reabrir, e fico à disposição para aprofundarmos a discussão.
