### ISSUE TITLE
[Question] Tem algo no roadmap para migrar para typescript ?

### ISSUE THREAD

**Issue by lucasalberto01** [filipedeschamps/tabnews.com.br#914]
Typescript agora vai ser o padrão para as novas aplicações em nextjs. Parece ser esse o caminho que o next está adotando junto com uma boa parte do mercado

**Comment by coffee-is-power** [comment]
Mas assim, e como dizem, typescript e o js só que voce type mais

**Comment by lucasalberto01** [comment]
@coffee-is-power ou menos... Porque o autocomplete funciona melhor XD

**Comment by pedroarm** [comment]
Acredito que por se tratar de um projeto open source, seria interessante a implementação das tipagens. Além do mercado estar cada vez mais aderindo à tecnologia, o typescript facilita ao contribuir com o código de outro coleguinha sem gastar dias para entender o que um método espera ou retorna.

**Comment by Rafatcb** [comment]
Não temos nada sobre TypeScript no roadmap, e o Filipe falou um pouco sobre o porquê decidiu seguir com JavaScript no início do projeto [aqui](https://www.tabnews.com.br/filipedeschamps/d70220d2-ff19-4cbf-8b8c-50e1e563980b) e o assunto também já foi mencionado no issue https://github.com/filipedeschamps/tabnews.com.br/issues/319.

Vale lembrar também que a forma como o projeto está estruturado já protege de alguns erros de tipagem: temos testes automatizados e validadores na entrada e saída da API.

Creio que hoje seja mais importante criar a documentação da API (https://github.com/filipedeschamps/tabnews.com.br/issues/555) do que adicionar tipagem na base de código, por exemplo, mas nada impede que futuramente o TypeScript seja adicionado. Em algumas partes do código, usamos JSDoc para facilitar o desenvolvimento.

Como não temos planos para adicionar TypeScript no momento, vou fechar este issue.
