### ISSUE TITLE
[Infra][Proposta de melhoria] Definir limite de tempo máximo de execução mais restritos em produção

### ISSUE THREAD

**Issue by lemuelroberto** [filipedeschamps/tabnews.com.br#915]
Cada escolha, uma renúncia. Geralmente os padrões do tempo máximo de execução, ou timeout, são muito maiores do que nós usuários consideramos adequado para carregar uma página ou para uma API responder com dados.

Um ponto importante nessa balança da escolha do timeout é o custo que isso impõe para a infra em momentos de pico de tráfego, pois quanto maior o timeout, maior o número de conexões ativas com o banco de dados e sim por diante.

Quando consideramos a precificação de plataformas serverless como a Vercel, segurar requisições abertas implica em custo financeiro direto e imediato.

O padrão da Vercel para o Maximum Execution Duration é 10s para o plano Hobby e 60s para o plano Pro. E é justamente por isso que o custo foi às alturas no momento de pico ontem: https://github.com/filipedeschamps/tabnews.com.br/issues/826#issuecomment-1322222580.

Minha sugestão é [limitar o Maximum Execution Duration (maxDuration)](https://vercel.com/docs/project-configuration#project-configuration/functions/description/functions-property-with-serverless-functions) ao mínimo aceitável. Sendo bem sincero, acredito que entre 1 e 2 segundos é um bom equilíbrio entre experiência para o usuário e controle de custos de infra.

Fico à disposição para aprofundar a discussão.

**Comment by filipedeschamps** [comment]
Show, faz sentido! O link ali sobre como limitar acredito que não esteja levando para o lugar certo 🤝 

E como limite, talvez 10 segundos seja algo mais seguro 🤝

**Comment by aprendendofelipe** [comment]
Boa @lemuelroberto, mas acredito que podemos implementar um limite variável, pois se uma ou outra requisição demorar mais, não será problema, mas quando uma certa quantidade de requisições começar a demorar demais, reduzimos esse limite por um tempo para a conta não explodir.

Mesmo que optarmos por deixar o limite padrão em 10s fixo, ainda causará prejuízo em caso de uma rajada com milhares de requisições simultâneas, pois a simultaneidade impede a Vercel ou qualquer outro sistema de rate-limit de identificar rapidamente o ataque.

Podemos definir um intervalo de alguns milissegundos para que o banco responda em condições normais. Mas sempre que esse limite de tempo passar, entramos no modo protegido, em que usamos um Redis para guardar a informação se outras requisições simultâneas estão demorando. Se for um ataque, já retornamos o erro sem esperar o limite da lambda.

O que acha?

**Comment by lemuelroberto** [comment]
@filipedeschamps @ErickCReis , de fato errei no link kkkk
É o link que o Erick colou mesmo.

**Comment by lemuelroberto** [comment]
> Mesmo que optarmos por deixar o limite padrão em 10s fixo, ainda causará prejuízo em caso de uma rajada com milhares de requisições simultâneas, pois a simultaneidade impede a Vercel ou qualquer outro sistema de rate-limit de identificar rapidamente o ataque.

Hoje o limite já será de 10 segundos se o plano for o Hobby. O @filipedeschamps deve ter melhor a métrica de quanto é o tempo de processamento das requisições. Minha sugestão é limitar a aplicação para responder em no máximo t segundos, onde t é, por exemplo o tempo de resposta da aplicação em 95% das requisições. Então com as métricas que o @filipedeschamps coletar da aplicação, se ela responder em até 1 segundo para, por exemplo 95% das requisições, esse seria o limite para a configuração maxDuration.

Ainda sobre esse ponto, a estratégia de rate-limit vem pra resolver um problema específico que é um "abuso" pontual da aplicação por parte de um IP ou usuário. Desse modo, é uma solução complementar ao timeout, pois resolvem problemas diferentes, mas no mesmo contexto de qualidade de serviço e resiliência da aplicação.

Considerando "abusos" pontuais, pode ser utilizadas soluções como AWS Shield para IPs (ou faixas) específicos. Essa mesma solução também serve para ataques mais sofisticados como DDoS que chegam de vários IPs e aí a solução de rate-limit ajudará pouco.

**Comment by lemuelroberto** [comment]
@filipedeschamps @aprendendofelipe , fechando a issue.
Se julgarem que faz sentido mantê-la aberta, é só reabrir, e fico à disposição para aprofundarmos a discussão.
