### ISSUE TITLE
[ Error ] Quando tento acessar da erro.

### ISSUE THREAD

**Issue by Kaduh15** [filipedeschamps/tabnews.com.br#917]
![IMG_20221122_214844.jpg](https://user-images.githubusercontent.com/81159579/203449469-125a1a84-9364-41cd-99ba-9e4507dd0d7a.jpg)
 
Esse erro aparece quando tento logar.

**Comment by coffee-is-power** [comment]
Isso deve ser algum bug no tabnews, todos os usuários devem ter o create session, ao menos que você tenha sido banido.

**Comment by Rafatcb** [comment]
@Kaduh15 após o cadastro, um e-mail de confirmação é enviado, você chegou a clicar no link para confirmar o e-mail?

**Comment by Kaduh15** [comment]
Quando criei a conta olhei meu email e cliquei no link para confirmar o email mas por conta instabilidade na hora deu um erro que não me recordo, então tentei logar e foi enviado outro link no email e esse aparentemente deu tudo certo.

**Comment by Kaduh15** [comment]
Ainda estou com o mesmo problema

**Comment by iurisilvio** [comment]
Tenho o mesmo problema. Criei a conta durante o pico inicial e não consegui logar desde então. Acho que não confirmei a conta e não consigo fazer agora.

**Comment by Kaduh15** [comment]
@iurisilvio ainda está com problemas? Consegui resolver enviando um e-mail para contato@tabnews.com.br e eles resolveram

**Comment by iurisilvio** [comment]
Continua ruim por aqui. Mandei agora email, obrigado!
