### ISSUE TITLE
Dúvida sobre propriedade intelectual

### ISSUE THREAD

**Issue by AnderRedna** [filipedeschamps/tabnews.com.br#918]
Boa noite, eu gostaria de saber se existe alguma documentação sobre o que é permitido ou não para criar com a api.
Duvidas como:
Posso utlizar a api do tabnews para projetos e utilizar esses projetos de maneira comercial? Se não, qual o limite para esse uso?
Posos utilizar os assets do tabnews para a criação de um aplicativo do tabnews?

**Comment by coffee-is-power** [comment]
Na minha opinião use o bom senso

**Comment by OGabrielPereira** [comment]
https://github.com/filipedeschamps/tabnews.com.br/blob/main/pages/termos-de-uso/index.public.js Você pode encontrar algumas informações aqui

**Comment by OGabrielPereira** [comment]
https://github.com/filipedeschamps/tabnews.com.br/blob/main/pages/termos-de-uso/index.public.js 

https://github.com/filipedeschamps/tabnews.com.br/blob/main/LICENSE

Suas respostas estão aqui
