### ISSUE TITLE
Sugestão de funcionalidade - "Mostrar senha" 

### ISSUE THREAD

**Issue by leonardodimarchi** [filipedeschamps/tabnews.com.br#919]
Uma funcionalidade/melhoria na UI sobre algo que particularmente gosto bastante de utilizar.

**A sua sugestão de funcionalidade está relacionada a algum problema? Por favor descreva.**
Permitir visualização da senha antes de clicar em Enviar, nas telas de Login/Cadastro

**Descreva a funcionalidade que gostaria**.
Botão para mostrar a senha durante o Login / Cadastro

**Descreva as alternativas que considerou***.
Adicionar um botão com ícone de olho aberto/fechado ou um texto de "Mostrar senha"/"Esconder senha"

**Contexto adicional***
![image](https://user-images.githubusercontent.com/62081192/203461614-c14a1805-0591-4f3d-b3d6-54ad6f2e024b.png)
![image](https://user-images.githubusercontent.com/62081192/203461813-204995ce-6ffa-4a1e-9389-d2873e633514.png)

Utilizei o template de Issue presente no PR [#892](https://github.com/filipedeschamps/tabnews.com.br/pull/892#pullrequestreview-1190990951) como base

**Comment by nicolasteofilo** [comment]
Interresante, acho que vou aderir fazer essa funcionalidade, achei bem interessante...

**Comment by aprendendofelipe** [comment]
Implementado em #1297 🚀
