### ISSUE TITLE
Sugestão para um sistema de notificação

### ISSUE THREAD

**Issue by JhonyDomingos** [filipedeschamps/tabnews.com.br#920]
Olá Boa noite devs

Seria interessante criar um sistema de notificação para notificar as respostas dos usuários nos post ex
caso eu crie um post sobre uma duvida referente alguma tecnologia, então eu receber uma notificação por comentario referente a uma solução sugerida em alguma duvida para pingar aqui mesmo perfil sabe.. sabemos que chega a notificação via e-mail, porém aqui na aplicação ficaria massa, pois quando logasse poderia se organizar com base nas notificações recebidas aqui!

**Comment by coffee-is-power** [comment]
Dá pra imaginar como isso iria funcionar, da pra fazer como o discord, tem a API rest pra mandar mensagens e etc e tem o websocket que manda eventos para o client

**Comment by Joao620** [comment]
Mas temos que nos lembrar que nosso cliente é um site. E notificações vinda de sites não funcionam ainda com IOS

**Comment by Rafatcb** [comment]
Notificações dentro da plataforma realmente seriam um ótimo adendo. Acredito que possamos concentrar a discussão nesse issue: #878. Existe também o issue #523, sobre receber notificações de outras publicações.

**Comment by aprendendofelipe** [comment]
Turma, obrigado pelas contribuições! 💪

Vou fechar diversas issues com assuntos relacionados. Por isso estou listando abaixo as que serão mantidas abertas e onde recomendo concentrarmos o que foi debatido/sugerido aqui:

- #645 
- #738
- #742 

Fechando essa aqui 🤝
