### ISSUE TITLE
Confetes 🎊 (animação)

### ISSUE THREAD

**Issue by Jetrom17** [filipedeschamps/tabnews.com.br#930]
No meu Linux (Mint) após publicar, os confetes são liberados lentamente. Enquanto no meu Android (11) os confetes rodam normalmente, sem "lag".

[Issue, já existe? I am sorry].

**Comment by lucasalberto01** [comment]
Eu estou utilizando o pop_os e os confetes estão indo normalmente :thinking:

**Comment by Jetrom17** [comment]
> Eu estou utilizando o pop_os e os confetes estão indo normalmente :thinking: 

Seu é Linux (Mint) também?

**Comment by Rafatcb** [comment]
Tenho um notebook um pouco mais antigo, Windows 10, com i7 7500U, 8GB RAM e GeForce 940mx que quando eu usava, a animação não era fluida também, inclusive a de voto negativo. No meu notebook mais novo, não lembro de ter visto ela travar alguma vez.

Acredito que seja um problema de performance mesmo, não deveria travar, já que é uma animação simples.

**Comment by Joao620** [comment]
@Jetrom17 eu tenho um Linux mint 20.3 ~~eu acho~~, em um computador Phenom II (para ver se é só uma questão de performance mesmo). Mais tarde eu testo e respondo aqui

**Comment by coffee-is-power** [comment]
acredito que seja problema do driver de video

**Comment by Jetrom17** [comment]
> acredito que seja problema do driver de video, a lib provavelmente usa webgl pra renderizar as animações

E tem solução?

**Comment by Joao620** [comment]
@Jetrom17 é, no meu linux mint 20.03, rodando num phenom ii, firefox 106, não teve problema nenhum com a animação. Entra [aqui](http://alampros.github.io/react-confetti/) que é uma demonstração do react-confetti, a lib usada para isso e vê se tem problemas grandes de performance.

E @coffee-is-power, pelas minhas pesquisa a lib não usa webgl não, fazendo um profile rapidinho eu vi muito uso das função de _fill_ e _draw_ do canvas, e o meu computador tem problemas de driver e roda webgl com glitch. Mas talvez tenha uma função no código com isso que eu não tenha visto

**Comment by Jetrom17** [comment]
> @Jetrom17 é, no meu linux mint 20.03, rodando num phenom ii, firefox 106, não teve problema nenhum com a animação. Entra [aqui](http://alampros.github.io/react-confetti/) que é uma demonstração do react-confetti, a lib usada para isso e vê se tem problemas grandes de performance.
> 
> E @coffee-is-power, pelas minhas pesquisa a lib não usa webgl não, fazendo um profile rapidinho eu vi muito uso das função de _fill_ e _draw_ do canvas, e o meu computador tem problemas de driver e roda webgl com glitch. Mas talvez tenha uma função no código com isso que eu não tenha visto

Ok, irei conferir. Darei retorno em breve mencionando novamente.
