### ISSUE TITLE
[question] : O Tabnews tem um discord ou um grupo no telegram ?

### ISSUE THREAD

**Issue by lucasalberto01** [filipedeschamps/tabnews.com.br#932]
Eu procurei para ver se o @filipedeschamps tinha algum server no discord mas não encontrei nenhum link :cry: 

Acham interessante criar um grupo no telegram ou um server no discord para discutir coisas do tabnews e poder ficar em call ?

**Comment by thisiscleverson** [comment]
A comunidade criou um grupo no discord.
Segue o link: https://www.tabnews.com.br/caiodomingues/recebendo-noticias-diretamente-no-discord

**Comment by lucasalberto01** [comment]
Eu vi a publicação mas parece ser somente um bot no discord :c Não tem nenhum server do discord nos comentários ou no post

**Comment by gabrielsozinho** [comment]
Acho que ele confundiu os links, mas aqui está: https://www.tabnews.com.br/Ezequias/junte-se-a-nossa-comunidade-no-discord 😁👍🏻

**Comment by coffee-is-power** [comment]
Sinceramente uma comunidade do tabnws nao faz sentido porque o tabnews já é lugar de conversar, é uma comunidade gerando valor.

**Comment by Rafatcb** [comment]
Para discussões de desenvolvimento, sugestões e bugs me parece que o melhor lugar é o GitHub, para ficar com o histórico e facilitar a busca e referências por meio do número da issue/PR. Lembrando que problemas de segurança devem ser enviador para o e-mail `contato@tabnews.com.br`, de forma privada.

Agora, discord ou outra comunidade para oturos tipos de conversa, realmente não tem nada oficial, mas alguns membros da comunidade chegaram a criar canais assim (como já mencionado acima). Isso pode ser pesquisado pela própria busca do www.tabnews.com.br.

@aprendendofelipe acho que podemos fechar essa issue.
