### ISSUE TITLE
[FEATURE] Exibir total de visualizações do post

### ISSUE THREAD

**Issue by brendo10x** [filipedeschamps/tabnews.com.br#935]
Como usuário gostaria de visualizar o total de visualizações do meu post para verificar o engajamento.

Fica a dica :D

**Comment by Rafatcb** [comment]
Acho que podemos concentrar essa discussão aqui: https://github.com/filipedeschamps/tabnews.com.br/issues/1115
O issue apontado é mais novo, mas já tem alguns comentários discutindo sobre. O que acha, @aprendendofelipe ?
