### ISSUE TITLE
suporte a expressões matemáticas

### ISSUE THREAD

**Issue by demetrius-mp** [filipedeschamps/tabnews.com.br#936]
Existe algum plano para dar suporte a expressões matemáticas?

O github dá suporte, exemplo a seguir: $\theta_B^{2} = \frac{1}{e}$.

Não sei exatamente a biblioteca de renderização utilizada no tabnews, mas existem opções como [KaTex](https://github.com/KaTeX/KaTeX), e [MathJax](https://github.com/mathjax/MathJax) para javascript.

Acredito que o ByteMD tenha suporte, vide o [playground](https://bytemd.js.org/playground/) com a opção `math` nos plugins.

Caso poucas publicações utilizem este recurso, acredito que seja possível o criador do conteúdo selecionar alguma opção "Habilitar KaTex" por exemplo, e enviar os arquivos de renderização (css e javascript do KaTex) somente para as páginas que utilizem esse recurso. 
Dessa forma não é necessário enviar os arquivos em todas as páginas, o que economizaria em tempo de loading.

Segue um [comparativo](https://www.intmath.com/cg5/katex-mathjax-comparison.php) entre a velocidade do KaTex e do MathJax.

**Comment by aprendendofelipe** [comment]
@demetrius-mp, obrigado pela sugestão! 💪

Foi implementado em #1323
