### ISSUE TITLE
[FEATURE] Possibilidade de marcação / salvar posts interessantes para leitura posterior

### ISSUE THREAD

**Issue by HugoMata** [filipedeschamps/tabnews.com.br#937]
Como o título já diz, seria interessante adicionar um botão / ícone para marcar um post para leitura posterior, ou para ficar salvo no meu perfil.

**Comment by leocunhadev** [comment]
É uma ótima sugestão, mas acredito ser duplicidade do Issue #645.

**Comment by aprendendofelipe** [comment]
Obrigado pela issue! 👍

Por organização, estou fechando as duplicadas com a #645 🤝
