### ISSUE TITLE
[Feature] Buscar imagens de usuário do Gravatar

### ISSUE THREAD

**Issue by joaocabraldev** [filipedeschamps/tabnews.com.br#939]
Buscar a imagem de usuário do [Gravatar](https://br.gravatar.com/) conforme o email cadastrado.

Poderiam ser utilizados os pacotes do npm para isso, por exemplo: [https://www.npmjs.com/package/gravatar](https://www.npmjs.com/package/gravatar) ou utilizar a própria API diretamente.

**Comment by coffee-is-power** [comment]
O tabnews não vai ter avatares, o Filipe deschamps já falou isso no tabnews

A quinta, 24/11/2022, 02:14, João Antônio Cabral ***@***.***>
escreveu:

**Comment by Jetrom17** [comment]
@joaocabraldev interessante isso. Desconhecia sobre essa plataforma.

**Comment by Rafatcb** [comment]
Isso precisa ser estudado um pouco melhor antes da decisão ser tomada. Já vi alguns debates na Stack Exchange sobre os riscos de privacidade, por exemplo:

* [Is Gravatar a privacy risk? (2010)](https://meta.stackexchange.com/questions/44717/is-gravatar-a-privacy-risk)
* [Off-site avatar images are a privacy risk (2019)](https://meta.stackexchange.com/questions/328966/off-site-avatar-images-are-a-privacy-risk)

E o TabNews se preocupa tanto com a privacidade que não faz uso de cookies de terceiros nem nada do tipo 👍

**Comment by Jetrom17** [comment]
> Isso precisa ser estudado um pouco melhor antes da decisão ser tomada. Já vi alguns debates na Stack Exchange sobre os riscos de privacidade, por exemplo:
> 
> * [Is Gravatar a privacy risk? (2010)](https://meta.stackexchange.com/questions/44717/is-gravatar-a-privacy-risk)
> * [Off-site avatar images are a privacy risk (2019)](https://meta.stackexchange.com/questions/328966/off-site-avatar-images-are-a-privacy-risk)
> 
> E o TabNews se preocupa tanto com a privacidade que não faz uso de cookies de terceiros nem nada do tipo 👍

Uma pena os vídeos do Filipe Deschamps ser no YouTube.

**Comment by fabiosvm** [comment]
Que pena! Não consigo imaginar nenhuma questão de segurança ou privacidade sobre o gravatar. Só não exigir que o usuário TENHA um cadastro lá, o site/app do TabNews apenas usaria o link do gravatar do usuário se não der 404. Inclusive apenas nos caso de falta de um imagem de avatar do próprio.

Lembrando como é o link do Gravatar:

```
 "https://www.gravatar.com/avatar/" + md5(email)
```

Esse é o meu: [https://www.gravatar.com/avatar/8a0f96138345dc870b03c1557c2c2569](https://www.gravatar.com/avatar/8a0f96138345dc870b03c1557c2c2569)
