### ISSUE TITLE
[Feature] Acompanhar Tópico

### ISSUE THREAD

**Issue by miroswd** [filipedeschamps/tabnews.com.br#940]
Digamos que tenha um tópico levantado que ainda não tenha respostas , mas que eu quero ficar por dentro do engajamento, por exemplo: alguém criou o tópico "quero saber mais sobre x assunto", visto que eu também tenho interesse, gostaria de acompanhar a evolução do tópico.

**Comment by Rafatcb** [comment]
É uma boa sugestão. Já foi dada algumas vezes, parece existir interesse da comunidade e faz sentido para mim.

Dito isso, creio que podemos concentrar a discussão no issue https://github.com/filipedeschamps/tabnews.com.br/issues/523.

**Comment by aprendendofelipe** [comment]
Turma, obrigado pelas contribuições! 💪

Vou fechar diversas issues com assuntos relacionados. Por isso estou listando abaixo as que serão mantidas abertas e onde recomendo concentrarmos o que foi debatido/sugerido aqui:

- #645 
- #738
- #742 

Fechando essa aqui 🤝
