### ISSUE TITLE
UX - Confusão sobre o que é a "fonte" da publicação

### ISSUE THREAD

**Issue by Rafatcb** [filipedeschamps/tabnews.com.br#941]
Hoje reparei pela terceira vez que uma pessoa confundiu o significado de "fonte" ao criar uma publicação, colocando um link para uma fonte do Google. Acho que podemos pensar em algo para deixar mais claro que é a fonte da notícia, a referência, e não uma fonte de tipografia.

![Publicação com fonte para um link do Google Fonts](https://user-images.githubusercontent.com/26308880/203782609-eddbcdc6-d893-4509-a87d-b0b49d1a58b5.png)

Atualmente, nosso formulário para criar uma publicação está assim:

![Um campo para o título, um para o corpo e um para a fonte, sem orientações](https://user-images.githubusercontent.com/26308880/203802576-ab7af424-9072-45dd-9a88-0e406066072e.png)

**Comment by coffee-is-power** [comment]
complicado...

**Comment by lucasmiqueias** [comment]
Fonte Bibliográfica, talvez esse seja um termo não ambíguo que pode ser utilizado.
No pratenses, talvez possa ter (Exemplo: Wikipedia, Medium...)

OBS: O input de Fonte Bibliográfica poderia ser dentro da área de texto. Como ele está separado, acabamos acreditando (por questão de acessibilidade) que é um input necessário.

**Comment by ValadaresX** [comment]
Me confundi hoje escrevendo um post. Super valido ser mais descritivo.

**Comment by aprendendofelipe** [comment]
Será que complementar o `placeholder` ajudaria?

Talvez algo como:

`Fonte (opcional, exemplo: https://origem.site/noticia)`

**Comment by aprendendofelipe** [comment]
Ou

`https://fonte.opcional.da/noticia`

**Comment by Rafatcb** [comment]
Como comentei em https://github.com/filipedeschamps/tabnews.com.br/issues/1529#issuecomment-1847647347, recomendo quem for corrigir isso, dar uma olhada na documentação do [TextInput](https://primer.style/components/text-input) para ver como essa tela ficaria com labels, indicador de campo obrigatório, e placeholder de exemplo. O formulário está aqui:

https://github.com/filipedeschamps/tabnews.com.br/blob/4e4d030cd4c0c2e240c96e5cfea16e43604aa223/pages/interface/components/Content/index.js#L444-L507

E lembra de ver como fica no comentário também, não apenas na publicação principal.
