### ISSUE TITLE
RegEx para validar e-mail no campo de recuperação de senha

### ISSUE THREAD

**Issue by bertonni** [filipedeschamps/tabnews.com.br#942]
Aparentemente não há um tratamento do input de recuperação de senha. Testei com um texto simples, sem @ e fui encaminhado para a página que avisa que um e-mail foi enviado.

Parabéns pelo projeto!

**Comment by Rafatcb** [comment]
Não é recomendado usar RegEx para validação de e-mails porque é algo extremamente complexo e passível de erros, como mencionado aqui: [How can I validate an email address using a regular expression?](https://stackoverflow.com/questions/201323/how-can-i-validate-an-email-address-using-a-regular-expression)

Dito isso, acho que não temos necessidade de validar o e-mail porque já existe um e-mail de confirmação para verificar se este realmente existe. O que acho que é ter uma lista de possível erros de digitação para auxiliar o usuário no cadastro/login, o que já temos hoje:

https://github.com/filipedeschamps/tabnews.com.br/blob/af2788f427a3db54088f6da326b79b609a1670ac/pages/perfil/index.public.js#L261-L413

Inclusive, isso já está duplicado no projeto:

https://github.com/filipedeschamps/tabnews.com.br/blob/af2788f427a3db54088f6da326b79b609a1670ac/pages/cadastro/index.public.js#L213-L365

Então acho que podemos aproveitar para realizar esse `TODO` 👍. Pode ser feito um _hook_ para essa sugestão, e acho interessante mudar o nome da função também, porque lendo apenas ele, não consegui entender o que a função fazia.

PS: A alternativa de ser um módulo _open source_ também é interessante.

**Comment by bertonni** [comment]
Entendi, mas essa verificação ocorre na hora de redefinir a senha também? Porque, caso haja um erro de digitação nesse campo, o usuário vai receber uma mensagem de que o e-mail foi enviado, sendo que este e-mail nunca vai chegar, certo? Caso não seja nenhuma das opções listadas.

**Comment by filipedeschamps** [comment]
Interessante, na verdade existe uma validação pelo Joi, que começa aqui:

https://github.com/filipedeschamps/tabnews.com.br/blob/fa27bf9c7203d948eea2d889abd35b649697198b/pages/api/v1/recovery/index.public.js#L22

Depois vem para cá:

https://github.com/filipedeschamps/tabnews.com.br/blob/fa27bf9c7203d948eea2d889abd35b649697198b/pages/api/v1/users/index.public.js#L41

Nesse caso é preciso entender se o Joi de fato está validando um `@` por conta da dinâmica desse valor que o @Rafatcb apontou.

**Comment by Rafatcb** [comment]
Acabei de realizar o teste e, caso você informe um e-mail errado para recuperar a senha, aparece o erro:

> O "email" informado não foi encontrado no sistema.

**Comment by bertonni** [comment]
Massa. Muito obrigado pelas respostas. Eu havia sugerido uma RegEx porque o campo aceita um texto sem @, só questão de UX mesmo =)

Parabéns mais uma vez pelo projeto. Tá massa

**Comment by aprendendofelipe** [comment]
Fechando a issue, pois entendi que o assunto foi resolvido. 💪

Qualquer coisa é só reabrir 🤝
