### ISSUE TITLE
Autocomplete salvando campo errado no primeiro cadastro com Chromium

### ISSUE THREAD

**Issue by rturket** [filipedeschamps/tabnews.com.br#943]
Quando cadastrei tabnews no browser Brave [Version 1.45.127 Chromium: 107.0.5304.110 (Official Build) (64-bit)](https://brave.com/latest/) pedi para salvar meu login/pass na ferramenta de credenciais do Chromium e quando fui usar no login percebi que usou meu username e não meu email como precisava para logar, creio que podemos trocar para que o default salvo seja o correto, ou seja, o email.

**Comment by coffee-is-power** [comment]
Talvez possa ser arrumado, mas por agora não parece ser uma prioridade, tem outras coisas para fazer.

**Comment by GoulartNogueira** [comment]
Não é problema do navegador.
No Firefox também tive esse comportamento.

**Comment by GoulartNogueira** [comment]
Eu *ACHO* que se mudar a odem dos campos no cadastro, resolve o problema.

Hoje está:

> Nome do Usuário
> Email
> Senha

Minha hipótese é que o navegador armazena sempre o primeiro campo do formulário.
Então minha sugestão é colocar:

> Email
> Nome do Usuário
> Senha


Algum dev front confirma minha hipótese?

**Comment by GoulartNogueira** [comment]
Se algum dev quiser contribuir com o projeto, pode testar essa hipótese.
Se resolver, faz o pull request!

**Comment by aprendendofelipe** [comment]
Boa @Rafatcb, já está rodando em produção! 🚀🚀🚀
