### ISSUE TITLE
Sugestão: Fixar um conteúdo no perfil

### ISSUE THREAD

**Issue by guilherssousa** [filipedeschamps/tabnews.com.br#944]
## A sua sugestão de funcionalidade está relacionada a algum problema? Por favor descreva.

Eu gostaria de criar vários conteúdos sobre o mesmo tema e gostaria de criar um único post onde eu consiga centralizar todas as postagens, assim, existiria um acesso fácil aos conteúdos, mas atualmente essa funcionalidade não está presente.

## Descreva a funcionalidade que gostaria.

Adicionar uma opção de fixar um conteúdo no perfil do usuário, para que os usuários que entrem em seu perfil consigam ver a publicação em destaque.

## Descreva as alternativas que considerou.
Como citado em várias outras issues como #891 e #807, outra solução seria separar os conteúdos entre postagens originais e comentários.

**Comment by Rafatcb** [comment]
Na época em que essa sugestão foi feita, ainda não existia a descrição no perfil do usuário (https://github.com/filipedeschamps/tabnews.com.br/issues/1466). Acho que essa funcionalidade deixou de fazer sentido, visto que agora você pode destacar o que quiser ali.

A discussão de filtro de conteúdo raiz e comentário é boa também, mas ainda não foi implementada, e como você disse, podemos concentrar a discussão sobre isso no issue https://github.com/filipedeschamps/tabnews.com.br/issues/807.

Acredito que faça sentido fechar o issue agora.

**Comment by aprendendofelipe** [comment]
@guilherssousa, obrigado pelas sugestões! 💪

Vamos seguir a recomendação do @Rafatcb! 👍

Vou fechar a issue 🤝
