### ISSUE TITLE
[Feature] Salvar/Favoritar Posts

### ISSUE THREAD

**Issue by itsdanniels** [filipedeschamps/tabnews.com.br#945]
Um implementação interesante seria para salvar/favoritas os posts que gostamos para reaproveitar o conteudo em um outro momento e não perdemos com o tanto de publicações que irão adentrar no site.

**Comment by Tiago321123** [comment]
sim, é o que mais quero!!

**Comment by ViniUme** [comment]
Eu também, já achei posts que são valiosos demais para perder

**Comment by leocunhadev** [comment]
Primeira coisa que eu vi faltar, já perdi algumas coisas muito interessantes.

**Comment by leocunhadev** [comment]
É uma ótima sugestão, mas acredito ser duplicidade do Issue #645.

**Comment by aprendendofelipe** [comment]
Obrigado pela issue! 👍

Por organização, estou fechando as duplicadas com a #645 🤝
