### ISSUE TITLE
[UX] Troca de nome de usuários um pouco confusa

### ISSUE THREAD

**Issue by guilhermeais** [filipedeschamps/tabnews.com.br#948]
- Criei minha conta utilizando o username 'GuilhermeAis';
- Quis trocar o username para 'guilhermeias';
- Recebi o erro dizendo que já existe esse username.

Por mais que haja a diferença de CamelCase pra lowercase, esse comportamento é o esperado?

### Detalhes da requisição:
response: 
![image](https://user-images.githubusercontent.com/73388069/203822524-cc715f05-dd72-4650-ba40-dd0c8eb9a98b.png)

headers:
![image](https://user-images.githubusercontent.com/73388069/203822556-cef456be-66f2-4c8a-9b63-c76e26ca17b8.png)

**Comment by Rafatcb** [comment]
Acredito que o nome de usuário seja considerado o mesmo porque a URL não diferencia o _case_ do texto, então a página gerada para cada usuário `https://tabnews.com.br/usuario` seria a mesma coisa para `GuilhermeAis` e `guilhermeias`, logo, não poderia ter dois usuários diferentes com esses nomes.

Apesar disso, como o nome do usuário é exibido em outros lugares de acordo com o _case_ salvo, acredito que deveria ser possível sim mudar o nome para um _case_ diferente.

Existe um teste que confirma o comportamento atual, mas acho que poderíamos mudar isso:

https://github.com/filipedeschamps/tabnews.com.br/blob/af2788f427a3db54088f6da326b79b609a1670ac/tests/integration/api/v1/users/%5Busername%5D/patch.test.js#L185-L215

**Comment by guilhermeais** [comment]
Sim, eu dei uma olhada nesse teste e vi que também:

No código, o username que vem da query string, parece que respeita o camelCase, da uma olhada:
`pages/api/v1/users/[username]:62`
![image](https://user-images.githubusercontent.com/73388069/203831575-7282486f-42ab-47a9-9a79-64695b5c1837.png)


Agora, tem uma validação do usuário que ele padroniza para o o lowercase:
`models/user.js:458`
![image](https://user-images.githubusercontent.com/73388069/203831667-f67f9beb-188e-46eb-90d5-964426d3253e.png)


Igual você falou, como o nome é exibido em outros lugares respeitando o case, talvez seria legal poder trocar

**Comment by Rafatcb** [comment]
> No código, o username que vem da query string, parece que respeita o camelCase

Me expressei mal. O código diferencia sim, mas o navegador não. Então ao acessar a página, você pode digitar o nome do seu usuário como quiser — foi isso o que eu quis dizer anteriormente.

**Comment by guilhermeais** [comment]
> > No código, o username que vem da query string, parece que respeita o camelCase
> 
> Me expressei mal. O código diferencia sim, mas o navegador não. Então ao acessar a página, você pode digitar o nome do seu usuário como quiser — foi isso o que eu quis dizer anteriormente.

Ah sim!! Agora entendi a sua resposta 100% 

Mas enfim... Por mais que seja um detalhe, eu preferiria poder mudar o username pra lowercase, haha! Talvez seja uma boa mudar a validação pra comparar também o case que a string está.
Será que vale a pena alterar e abrir um PR? 🤔

**Comment by Lorenzobattistela** [comment]
Existe alguma maneira de a troca de nome de usuário não quebrar o URL? 

Por exemplo, se eu tiver uma conta com 20 publicações e quiser trocar o usuário, provavelmente n trocaria pra n quebrar os links de todas elas.

Não é um problema grave, mas existe essa possibilidade?

**Comment by LFSousa** [comment]
> Existe alguma maneira de a troca de nome de usuário não quebrar o URL?
> 
> Por exemplo, se eu tiver uma conta com 20 publicações e quiser trocar o usuário, provavelmente n trocaria pra n quebrar os links de todas elas.
> 
> Não é um problema grave, mas existe essa possibilidade?

Ao meu ver isso é um fato que quem quiser trocar de nome vai ter que lidar. Acontece em todos os lugares da internet.
O próprio GitHub já é um grande exemplo... Trocou teu username, quebrou o link de tudo onde teus repositórios estavam configurados.
