### ISSUE TITLE
[Sugestão] Alterar fluxo de contribuição, merge e deploy

### ISSUE THREAD

**Issue by aprendendofelipe** [filipedeschamps/tabnews.com.br#949]
Agora, com o aumento de contribuidores e também dos usuários do TabNews, eu acho que vale a pena aquela estratégia de termos uma *branch* intermediária. Principalmente para não ficar invalidando o cache a todo momento no ambiente de produção.

Na verdade a intermediária até poderia ser a própria `main` e aí deixamos outra *branch* para produção.

A ideia seria criar uma *branch* `production` e deixar a `main` um pouco mais dinâmica. Dinâmica apenas no sentido de, na hora de aprovar e fazer *merge* dos PRs, não precisar se preocupar se é o melhor momento para fazer *deploy* em produção. Não digo que devemos relaxar com as revisões dos PRs.

Então a `main` dispararia apenas o *deploy* no ambiente de homologação, e quando for o melhor momento para o *deploy* em produção, fazemos o *merge* da `main` na `production` com as contribuições acumuladas.

O que acham?

**Comment by aprendendofelipe** [comment]
Isso também ajudaria com as contribuições que não mudam nada no ambiente de produção, mas que iriam invalidar os caches ao serem aprovadas, como, por exemplo, as que só alteram a documentação.

**Comment by Rafatcb** [comment]
Faz sentido para mim. Imagino que, num cenário onde 3 PRs fossem mergeados quase que ao mesmo tempo (digamos que com um intervalo de cinco minutos entre cada um), seria melhor ter um lote de atualizações enviadas uma única vez, fazendo uso da branch `production`, certo?

Pergunto porque nunca usei o Next, então não sei se entendi exatamente o que está acontecendo hoje.

**Comment by aprendendofelipe** [comment]
> Faz sentido para mim. Imagino que, num cenário onde 3 PRs fossem mergeados quase que ao mesmo tempo (digamos que com um intervalo de cinco minutos entre cada um), seria melhor ter um lote de atualizações enviadas uma única vez, fazendo uso da branch `production`, certo?

Isso mesmo @Rafatcb, os 3 merges iriam ocorrer na `main` e só depois seria feito o *merge* da `main` na `production`. Com isso os novos *commits* aprovados passariam todos de uma vez para a `production`, resultando em um único *deploy* no ambiente de produção na Vercel.

> Pergunto porque nunca usei o Next, então não sei se entendi exatamente o que está acontecendo hoje.

Não tem relação com o Next.js em si, mas sim na maneira como fazemos *deploy* na Vercel.

**Comment by coffee-is-power** [comment]
Talvez era melhor renomear a main pra staging e criar a branch production. Fica mais claro o que cada coisa faz

**Comment by aprendendofelipe** [comment]
> Talvez era melhor renomear a main pra staging e criar a branch production. Fica mais claro o que cada coisa faz

Oi @coffee-is-power, mudar o nome da *branch default* não mudaria o fluxo, então poderia ser qualquer coisa que deixasse claro para os contribuidores que é ali que eles devem clonar, criar o PR etc.

Mas não acredito que `staging` deixaria isso mais claro do que `main`. Poderia ser outro nome, mas no momento não estou vendo nenhum ganho em renomear a `main`. Também não criaria outra *branch* para configurar como *default* , pois acho que isso iria quebrar o histórico de contribuições.

A minha proposta não muda o que já estamos fazendo com a `main`, que é só mergear o que já estiver totalmente testado e aprovado. Só vai mudar que esse *merge* não vai mais disparar um *deploy* no ambiente de produção. O deploy em produção só vai acontecer quando a `main` for mergeada na `production`.

Os testes devem continuar sendo realizados nas *branchs* originais dos contribuidores, onde, agora com a nova configuração do repositório, está mais fácil de testar e fazer *deploy* diretamente delas.

Faz sentido?

**Comment by yuric18** [comment]
Tive conhecimento do projeto hoje, fiquei bem interessado nele e em contibuir com ele.

Porém, senti falta de um `CONTIBUTING.md` descrevendo qual o fluxo ideal para contribuição e também de templates para abertura de issues/features requests.

Pretendo abrir um merge essa semana adicionando esses templates para ajudar. 
De repente, segurar um pouco o CONTRIBUTING.md até que a definição desse issue seja feita 😄 , o que acham?

**Comment by cezarmezzalira** [comment]
@aprendendofelipe cai de paraquedas aqui, mas li todas as respostas e achei interessante o modelo de duas branchs: `main` para contribuição e `production` para deploy em produção.

Isso vai de encontro com modelo [trunk-based](https://www.atlassian.com/continuous-delivery/continuous-integration/trunk-based-development) que a Atlassian sugere como melhor modelo atualmente para ambientes de CI/CD.

A ideia do modelo trunk-based é que os existam commits apenas em uma única branch, incentivando commits pequenos, com cobertura de testes e que podem ser facilmente incorporados a branch main. Além disso, é sugerido o merge diário dessa branch com a branch de produção, fazendo com que o código que está no repositório está como production ready a qualquer momento.

Em teoria, como o projeto já tem pipelines de teste automatizado e alta cobertura de de testes, seria um caminho fácil.

Vale a pena a leitura do artigo no link acima para entender mais detalhes.

O que me dizem?

**Comment by cezarmezzalira** [comment]
> Minha proposta de separar a `main` da `production` só aproxima um pouco mais desse modelo por permitir que mudanças pontuais já aprovadas possam ir sendo mescladas sem preocupação se é um bom momento para _deploy_ em produção.

Nesse caso, pensando por outro lado, a ideia do Filipe é sempre trabalhar por Milestone. 

Isso me faz pensar que o modelo [git-workflow](https://www.atlassian.com/git/tutorials/comparing-workflows/gitflow-workflow) também seria interessante, haja visto que a branch `main` vai conter as releases e a branch principal seria a `development`, que seria base para novas branch's de trabalho e também para uma branch intermediaria de `release`, que após as devidas validações, acaba sendo mergeada tanto na `main` quanto na `development`. 

Porém, existe um trade off que o projeto entraria numa espécie de freezing até a próxima `release` ser mergeada na `development`.

O que me dizem sobre essa outra abordagem?

**Comment by aprendendofelipe** [comment]
Fechando essa issue porque a solução não me parece mais fazer sentido com o volume atual de contribuições
