### ISSUE TITLE
Tab - TabCoins

### ISSUE THREAD

**Issue by Jetrom17** [filipedeschamps/tabnews.com.br#950]
Os "like" e "no like", os tabCoins continuam a funcionar para gastar na mesma página. Não era para ter um limite?

**Comment by JonathanArgentao** [comment]
Se eu entendi bem sua pergunta, a resposta é: você pode gastar quantas tabcoins quiser em uma mesma publicação, até chegar a 1. Não tem limite para gastar na mesma publicação.

**Comment by Jetrom17** [comment]
> Se eu entendi bem sua pergunta, a resposta é: você pode gastar quantas tabcoins quiser em uma mesma publicação, até chegar a 1. Não tem limite para gastar na mesma publicação.

E não deveria ter?

**Comment by JonathanArgentao** [comment]
No projeto não é previsto ainda, por enquanto todos são livres pra usar suas tabcoins como quiserem, mas se quiser sugerir essa mudança, com um bom argumento, acho que a comunidade poderia discutir.

**Comment by Alexbrazdasilva** [comment]
Não, pois como as tabcoins são "difíceis" de conseguir, cada usuário deverá regrar as suas coins.

Você recebe coins por ter feito um comentário ou um post :arrow_right: Se o post ou comentário de outro usuário for relevante pra você, você "gasta" suas coins pra valorizar

-- Essa é a parte bacana, na minha opinião.

**Comment by Jetrom17** [comment]
@Alexbrazdasilva e @JonathanArgentao  publiquei essa discussão aqui. Contribuem por favor. 

https://www.tabnews.com.br/Jetrom/tabnews-tabcoins-bonus

**Comment by Jetrom17** [comment]
![Screenshot_20221124-203355-898.png](https://user-images.githubusercontent.com/72875404/203874664-17716626-ae57-42ab-9419-0f42b8de1d55.png)

Como podes ver, estou tendo dificuldade para pontuar outros posts que quero por sugerir limite de tabCoins.
