### ISSUE TITLE
[UX/UI] - Melhoras para listagem de tópicos

### ISSUE THREAD

**Issue by VitorFigm** [filipedeschamps/tabnews.com.br#951]
# Listagem de tópico
![image](https://user-images.githubusercontent.com/65882994/203867063-6122aed3-e9c5-4593-b3cb-93f5ef97f46f.png)

# Muita Informação
A tela inicial está jogando muita coisa de uma vez para o usuário olhar, o que possívelmente o deixa com uma sensação de confusão, isso pode ser resolvido facilmente com uma margem maior separando cada tópico.

# Ilustração
É interessante permitir os criadores dos tópiucos colocarem uma ilustração no começo de cada tópico para que o usuário não precise ler tópico por tópico pra saber qual deles lhe interessa.

# Protótipo
Acredito que algo deste tipo já ficaria interessante:
![test](https://user-images.githubusercontent.com/65882994/203865695-8fa22e25-6197-40ea-9c83-1f012203fb9c.png)

# Outra ideia

Outra ideia seria se inspirar em listagem de outros sites populares que seguem esse estilo de blog, como o [Medium](https://medium.com/). Acho que essas linhas transparente pra separar cada tópica deixa a tela bastante agradável.

**Comment by VitorFigm** [comment]
Caso alguém tenha em mente alguma página que segue esse formato de listagem de blog, seria interessante colocar aqui no comentário pra usar como inspiração.

**Comment by coffee-is-power** [comment]
Acho que uma thumb era melhor, 

O design que eu tô pensando e que ele pega a thumb e coloca no fundo da listagem do conteúdo, e quando VC passa o mouse ele revela a thumb inteira

E também isso precisa ser controlado porque podem trollar e colocar p ou algo assim, tem sistemas que conseguem detectar isso, mas nada e perfeito.

**Comment by Rafatcb** [comment]
Não acho que tenha muita informação. Na verdade, acho que o TabNews lida muito bem em mostrar apenas o essencial, dando um destaque para o título, o que facilita de ler apenas títulos em um _scan_ rápido no site.

Colocar imagens deixaria muito poluído, com ainda mais coisas na tela e menos informações úteis. Como usuário do site, eu entro para ver o que ainda não vi, então quanto mais publicações couberem na minha tela sem precisar dar scroll e com uma leitura fácil, melhor. Inclusive, o fato de diferenciar publicações visitadas das não visitadas contribui positivamente com meu desejo de _ver o que ainda não vi_.

**Comment by VitorFigm** [comment]
> Não acho que tenha muita informação. Na verdade, acho que o TabNews lida muito bem em mostrar apenas o essencial, dando um destaque para o título, o que facilita de ler apenas títulos em um _scan_ rápido no site.
> 
> Colocar imagens deixaria muito poluído, com ainda mais coisas na tela e menos informações úteis. Como usuário do site, eu entro para ver o que ainda não vi, então quanto mais publicações couberem na minha tela sem precisar dar scroll e com uma leitura fácil, melhor. Inclusive, o fato de diferenciar publicações visitadas das não visitadas contribui positivamente com meu desejo de _ver o que ainda não vi_.
> 
> O TabNews é inspirado no [Hacker News](https://news.ycombinator.com/).

Bom, cada um tem seu gosto. Mas eu acredito que, em termos de design, o entendimento popular é que falta de [espaço negativo](https://uxplanet.org/negative-space-in-ui-design-tips-and-best-practices-98311cb2ad16) não costuma ser bom para uma UI, e ter espaço negativo acaba sendo mais importante que ter mais elementos por scroll.

E sobre a imagem tem que lembrar que ela é um informação útil, é só vê algumas pesquisas mostradas [nesse artigo aqui](https://gugaalves.net/marketing/marketing-visual-29-dados-mostrando-seu-valor/#:~:text=O%20c%C3%A9rebro%20humano%20processa%20imagens,que%20lembram%20o%20que%20leram.), nós tendemos a tirar informações de imagens muito mais rápido que textos, a imagem acaba sendo tão útil quanto o título em si.

**Comment by brunoinds** [comment]
Quando entro no TabNews, quase que instantaneamente sinto a falta da thumb nos artigos. Sem imagens, dá até preguiça de abrir o artigo.  Imagens valem mais que mil palavras e é a chave para que a primeira vista, chame a atenção. É extremamente essencial e creio que deveria ser uma prioridade no time de FrontEnd. Deve-se quanto antes implementar uma thumb pra os posts.

A implementação mais simples seria usar a primeira imagem adicionada no corpo do artigo. Um parse do Markdown e recuperar a primeira imagem para ser a thumbnail.

**Comment by Rafatcb** [comment]
Como este issue não teve interações para avançar o assunto, estou fechando-o para organizar o repositório. De forma geral, será bem difícil realizar uma grande mudança na UI do TabNews porque cada pessoa terá um gosto, e a interface atual tem atendido bem o público do site.

Agradeço pela colaboração dos que participaram neste issue. No momento atual do TabNews, os esforços estão direcionados para o Milestone 7 https://github.com/filipedeschamps/tabnews.com.br/issues/1490.
