### ISSUE TITLE
[Feature] Cadastro com google/github

### ISSUE THREAD

**Issue by avoguga** [filipedeschamps/tabnews.com.br#952]
## Descrição do problema

O TabNews ainda não possui cadastro com essas plataformas. Creio que ficaria bem mais dinâmico a entrada de novos usuários se a plataforma possuísse alguma forma de login que pudesse ser feita com um auth em alguma dessas plataformas.

**Comment by dopplerpng** [comment]
Google: Oauth2 para autenticação para o uso de API do Google

**Comment by nicolasteofilo** [comment]
Realmente, é bem provável  que quase todo dev tenha uma conta no GitHub, iria facilitar bastante mesmo

**Comment by GoulartNogueira** [comment]
Já solicitado aqui: #922 

Para organizar melhor, sugiro fechar esta issue aqui e centralizarmos a conversa por lá.
(por simples questão de cronologia)
