### ISSUE TITLE
UX - Página de redirecionamento ao logar

### ISSUE THREAD

**Issue by Rafatcb** [filipedeschamps/tabnews.com.br#956]
Hoje vi no TabNews uma publicação que, resumidamente, era um "oi", e isso estava escrito nela:

> Desculpa por esse primeiro post meio estranho, mas sinceramente estava meio indeciso sobre o que postar

Ao logar, a pessoa é redirecionada para a página de [criar uma publicação](https://www.tabnews.com.br/publicar). Talvez a pessoa do exemplo anterior tenha imaginado que **precisasse** publicar algo.

Pensei em duas alternativas para melhorar esse fluxo de login:

1. **A ideal:** redirecionar para a página que o usuário estava antes de ir para o Login. O motivo: isso não altera o fluxo que a pessoa já estava. Por exemplo, pode ser que ela estivesse lendo uma publicação, quisesse dar um voto ou comentar algo, então será redirecionada de volta para a publicação. Não sei quão complexo isso é.
2. **A simples:** redirecionar para a _home_. O motivo: é a página com os principais conteúdos do momento.

**Comment by aprendendofelipe** [comment]
@Rafatcb você foi citado no post comemorativo 🎉

https://www.tabnews.com.br/FelipeBarso/tabnews-dark-mode-e-novas-funcionalidades-do-editor

Vou fechar a issue, ok? 👍
