### ISSUE TITLE
[Feature] [UX] Permitir redimensionar o campo de postagens e respostas

### ISSUE THREAD

**Issue by dineiar** [filipedeschamps/tabnews.com.br#958]
Uma alteração simples: permitir redimensionar verticalmente o editor onde se escrevem as postagens e respostas.

Em uma busca rápida na documentação do ByteMD e CodeMirror, isso parece ser possível alterando diretamente o CSS: a documentação do CodeMirror tem um [exemplo](https://codemirror.net/5/demo/resize.html) de autoresize infinito. Na minha opinião o melhor dos mundos seria combinar isso com um `maxHeight`, dessa forma daria para deixar ele redimensionar automaticamente até certo limite pré-definido.

**Comment by aprendendofelipe** [comment]
@dineiar, obrigado pela sugestão! 💪

Isso foi implementado no #1348
