### ISSUE TITLE
[Feature] Rotacionar os assuntos relevantes 

### ISSUE THREAD

**Issue by KitsuneSemCalda** [filipedeschamps/tabnews.com.br#959]
Poderíamos adicionar relevância por dia/semana/mês para que os assuntos relevantes dentro da tabnews possam ser recomendados mais facilmente recomendados e encontrados

**Comment by aprendendofelipe** [comment]
Oi @KitsuneSemCalda, ainda não temos histórico suficiente para sabermos quais seria as melhores maneiras de classificar os conteúdos como relevantes. Então estamos ajustando o algoritmo conforme vamos entendendo a interação dos usuários com o sistema.

Por enquanto não temos as variações de ranqueamento, pois ainda precisamos ajustar melhor o ranqueamento principal.

Sobre rotacionar os assuntos, eles são rotacionados, mas entra no mesmo caso, que ainda estamos fazendo os ajustes conforme o aprendizado. Já deu para perceber que com o volume atual será viável uma rotação mais rápida, então vamos fazer isso. 👍

Tudo está público aqui no GitHub e o algoritmo atual ocorre nesta consulta:

https://github.com/filipedeschamps/tabnews.com.br/blob/fa27bf9c7203d948eea2d889abd35b649697198b/models/queries.js#L1-L1

**Comment by Rafatcb** [comment]
Me parece que o algoritmo do TabNews evoluiu bem ao longo desse ano de vida, e o Relevantes está bem diversificado. Para atender demandas específicas, acho mais adequado concentrar os esforços no issue https://github.com/filipedeschamps/tabnews.com.br/issues/742, porque as tags vão permitir filtrar conteúdos de um tema específico, nem que seja um "recentes", sem rankeamento.

Faz sentido, @aprendendofelipe ?

**Comment by aprendendofelipe** [comment]
Faz sentido @Rafatcb, pois o ranqueamento foi evoluindo conforme o sistema foi permitindo novas consultas, e isso deve continuar acontecendo.

Não vejo necessidade de manter a issue aberta. 🤝
