### ISSUE TITLE
[FEATURE] Rolagem infinita das postagens

### ISSUE THREAD

**Issue by brendo10x** [filipedeschamps/tabnews.com.br#961]
Como usuário gostaria que a página de listagem de postagens trouxesse mais conteúdos a medida em que faço scroll na página.

- Inicialmente pode ser um botão de 'carregar mais'.

Dica a dica :D

**Comment by Rafatcb** [comment]
Não sei se isso faz sentido para o TabNews. Um dos objetivos do site é se distanciar das redes sociais e suas técnicas para prender usuários. O comentário https://github.com/filipedeschamps/tabnews.com.br/issues/477#issuecomment-1182110074 não aborda diretamente esse assunto, mas fala sobre o espírito de deixar a pessoa livre. O scroll infinito é algo que incita a pessoa a ficar ali "vendo só mais um pouquinho".

Um outro issue que levanta um problema similar é o https://github.com/filipedeschamps/tabnews.com.br/issues/1530, sobre um botão para navegar para a próxima publicação, e a comunidade está pendendo mais para o lado de não ter isso.

**Comment by aprendendofelipe** [comment]
Dado que a ideia não atraiu ninguém para o debate em mais de um ano, e nem mesmo surgiram outras sugestões citando rolagem infinita, acredito que podemos fechar essa issue, pois isso não deve ser implementado no médio prazo.

O que acham?

**Comment by Rafatcb** [comment]
Seguindo com o comentário do @aprendendofelipe, como não houve pronunciamento contrário, estou fechando aqui para organizar o repositório. Obrigado pela sugestão, Brendo.
