### ISSUE TITLE
Editor Markdown sem suporte para Autocomplete

### ISSUE THREAD

**Issue by silvaezequias** [filipedeschamps/tabnews.com.br#967]
## Contexto
Eu estava lendo esse comentário https://github.com/filipedeschamps/tabnews.com.br/issues/493#issue-1303907543 e percebi que um dos planos para a próxima Milestone é _"O poder de marcar as pessoas enquanto escreve o conteúdo"_. Pra implementar isso, eu fui pesquisar mais sobre o editor usado que é o [ByteMD](https://github.com/bytedance/bytemd) e percebi que ele não tem suporte para Autocomplete, que é na maioria das vezes a função usada para marcar pessoas ou itens enquanto digita.
Duas opções que eu pensei de forma superficial é:
 1. Construir um plugin para o ByteMD que dá esse suporte de autocomplete
 2. Migrar para o editor de texto do [Primer](https://primer.style/react/drafts/MarkdownEditor) quem tem suporte à isso.

O MarkdownEditor do Primer está com a tag de `Draft` e provavelmente vai sofrer bastante atualizações conforme o tempo, acredito que usar ele no lugar do ByteMD é muito mais vantajoso pois ele tem muito mais features que o ByteMD, segue uma pequena lista:
 - Formatação (atalhos de teclado e botões da barra de ferramentas)
 - Uploads de arquivos (arrastar e soltar, colar, clicar para fazer upload)
 - Sugestões inline (emojis, @menções e #referências)
 - Respostas salvas
 - Colagem de markdown (ou seja, cole o URL no texto selecionado para criar um link)
 - Edição de lista (crie um novo item de lista em Enter)
 - Recuando o texto selecionado

Quanto ao design do editor, não se diferencia muito do design usado no tabnews:

![Representação do Editor de Texto do Primer](https://user-images.githubusercontent.com/63757378/204041661-5a35933b-7c91-44d1-892f-0d9c00228177.png)

Aqui está o Link dele: https://primer.style/react/drafts/MarkdownEditor
Link do MarkdownViewer: https://primer.style/react/drafts/MarkdownViewer

**Comment by MathGoOli** [comment]
Eu gostaria que o TAB news tivesse como editar texto igual o notion.

**Comment by aprendendofelipe** [comment]
@silvaezequias, obrigado pela sugestão! 💪

Como ela surgiu primeiro na issue #648, vamos centralizar as conversas sobre o editor de markdown por lá. 👍🤝
