### ISSUE TITLE
Erros ortográficos

### ISSUE THREAD

**Issue by drocha87** [filipedeschamps/tabnews.com.br#970]
Eu percebi que a plataforma usa o code mirror como area de texto. O problema é que (até onde eu sei) ele não tem (ou ainda não tem implementado) a possibilidade de ativar o corretor ortográfico. Sendo assim tenho percebido muitos posts com erros de português, e eu não acho que seria legal a gente corrigindo o pessoal através dos comentários.

Hoje em dia muitas pessoas esperam que o corretor dê aquela filtrada nos erros, sendo assim aumentaria e muito a qualidade dos posts se o editor de texto tivesse essa funcionalidade.

**Comment by aprendendofelipe** [comment]
É verdade @drocha87, usamos o ByteMD, que é baseado no CodeMirror V5, mas existe uma nova versão sendo desenvolvida como [HashMD](https://github.com/pd4d10/hashmd) e que usará o CodeMirror V6, onde esse problema deve ser superado.

Então a solução para o TabNews deve ser a troca do editor ou aguardar a nova versão. E as discussões sobre isso podem ser centralizadas na #648.

Vou fechar essa aqui 🤝
