### ISSUE TITLE
[Feature] - Adicionar o link do Github em seu cadastro

### ISSUE THREAD

**Issue by pedropagotto** [filipedeschamps/tabnews.com.br#971]
Pessoal o que vocês acham de cadastrar o link do seu perfil do github no perfil do tabnews?

Essa informação poderia ser exibida dentro dos seus posts de uma forma sutil, pois ai fica fácil de ter acesso aos códigos de exemplo e até de seguir essa pessoa lá no github. 

Desculpe o exemplo simples:
![image](https://user-images.githubusercontent.com/13180552/204050109-b71c6a19-a0fc-4102-bcad-120443ab69f5.png)

Aonde está o icone vermelho poderia ser o icone do github com um link para direcionar para o perfil da pessoa que escreveu o post.

**Comment by FilipeRicardo** [comment]
Faria mais sentido o usuário ter uma página própria, igual no github, onde ele pudesse editar, e caso queira, colocar o link do github, usando o mesmo padrão das páginas dos artigos.

**Comment by pedropagotto** [comment]
@FilipeRicardo Achei interessante! Tipo essa?
<img width="1383" alt="image" src="https://user-images.githubusercontent.com/13180552/204086603-bf8b4da8-195f-4a0a-adc2-230e702c96a4.png">

**Comment by Rafatcb** [comment]
Obrigado pela sugestão, Pedro!

Como hoje existe uma área de Descrição no perfil do usuário (https://github.com/filipedeschamps/tabnews.com.br/pull/1470), onde a pessoa pode colocar os links que deseja, estarei fechando este issue pelo mesmo motivo que o https://github.com/filipedeschamps/tabnews.com.br/issues/1371 foi fechado, ok?
