### ISSUE TITLE
Diferenciar autor do post nos comentários do mesmo

### ISSUE THREAD

**Issue by igorroc** [filipedeschamps/tabnews.com.br#972]
O `TabNews` é maravilhoso em sua simplicidade. Mas tem um ponto que eu sempre me atrapalho quando vou ver algum artigo: **quem comentou foi o autor do post?**

Eu acredito que não seja tão complicado de fazer isso, e vai deixar a sessão de comentários muito mais organizada!

Seguindo o padrão das cores `azul` *(TabCoins)* e `verde` *(TabCash)*, daria pra estilizar algo parecido com isso:

![Print da tela](https://i.imgur.com/DjbtMzy.png)

**Comment by miguel5g** [comment]
Hey @igorroc, admito que também já fiquei confuso em relação a isso, acho que isso seria uma adição legal.

**Comment by miguel5g** [comment]
Fala pessoal, acredito que niguém tentou implementar ainda, então fiz alguns testes aqui e acho que da para implementar sem muitos problemas, o meu código ta alguns commits atrasadoas, mas caso seja isso que vou mostrar posso abrir uma pr pronta em breve :smile: 

![image](https://user-images.githubusercontent.com/53842126/206064680-6390f78c-554e-4587-9b70-4d76c72e7c24.png)

Tem um único bug que é questão da borda cinza no primeiro comentário do dono do post, ele fica assim pois a alteração de content mode ocorre internamente, e ele continua recebendo as props `frame=true`, eu não sei se é uma feature ou bug, mas depois que recarrega a página e atualiza o estado pai ele fica igual o de baixo, alguém sabe informar?

**Comment by aprendendofelipe** [comment]
> Me surgiu uma dúvida quanto à implementação: se eu estiver no link de um comentário, o usuário realçado deve ser o autor desse comentário ou o autor do conteúdo raiz?

Acredito que deveria ser destacado o autor do conteúdo principal da página visitada, seja comentário ou raiz.

Numa versão mais elaborada, poderia diferenciar o autor do conteúdo raiz e do comentário visitado, mas pode não ficar com uma boa UX.

E pelo bem da UX, devemos pensar nisso ao mesmo tempo que pensamos como identificar usuários novos e também os possíveis verificados.

**Comment by Rafatcb** [comment]
Talvez colocar um label como o GitHub faz, mas do lado do nome do usuário, pode ser uma opção mais viável do que usar cores para isso, porque o label é mais explicativo e ainda pode ter um Tooltip, apesar de não chamar tanta atenção (pode ser um label colorido, mas aí tem que tomar cuidado pra não virar um carnaval). 

![Interface do GitHub para o comentário do autor de um issue](https://github.com/filipedeschamps/tabnews.com.br/assets/26308880/3facec49-a3bc-473a-9769-ac9617190caa)

Se for usar cores no nome do usuário, acho que precisaríamos deixar de usar o azul como padrão e usar algo mais neutro (cinza, por exemplo), mas ainda seria importante ter alguma explicação do que a cor significa.

**Comment by Rafatcb** [comment]
Abri o PR #1589 com uma implementação similar ao que é no GitHub. No PR está com o texto `Autor` mas deixei imagens de como seria com `Autor(a)`:

| Autor | Autor(a) |
|--- | --- |
| ![Nome "Betty3", Label e tooltip "Autor"](https://github.com/filipedeschamps/tabnews.com.br/assets/26308880/7f6b658d-f027-414e-b055-deecd6c6b8be) | ![Nome "Betty3", Label e tooltip "Autor(a)"](https://github.com/filipedeschamps/tabnews.com.br/assets/26308880/fdc1f78c-7bb2-4a42-9c00-914dc779c5bf) |
| ![Nome "rafael", Label e tooltip "Autor"](https://github.com/filipedeschamps/tabnews.com.br/assets/26308880/5e9a7130-831f-4b58-8e2b-604f8aa6394c) | ![Nome "rafael", Label e tooltip "Autor(a)"](https://github.com/filipedeschamps/tabnews.com.br/assets/26308880/97196c8e-e9c4-4f00-9936-85eaefdd68f7)

**Comment by aprendendofelipe** [comment]
> Se for usar cores no nome do usuário, acho que precisaríamos deixar de usar o azul como padrão e usar algo mais neutro (cinza, por exemplo), mas ainda seria importante ter alguma explicação do que a cor significa.

Acho que pode ser mais interessante usar cores nos labels, não no nome do autor.

> Abri o PR #1589 com uma implementação similar ao que é no GitHub. No PR está com o texto `Autor` mas deixei imagens de como seria com `Autor(a)`:

"Autor" fica melhor, tanto visualmente, como para ferramentas de acessibilidade.
