### ISSUE TITLE
Posso dar mais de um UpVote

### ISSUE THREAD

**Issue by igorroc** [filipedeschamps/tabnews.com.br#973]
Não sei dizer se é proposital ou não, mas atualmente é permitido enviar mais de um UpVote para um post.

Acredito que o melhor seria limitar a quantidade de UpVotes em 1 para cada post, e existir alguma forma de mostrar ao usuário que aquele post já recebeu o seu UpVote

**Comment by coffee-is-power** [comment]
Isso é o sistema de tabcoins, se você tiver tabcoins suficientes você pode dar um tabcoin e o dono do post recebe um tabcoin, se você retirar um tabcoin, você perde tabcoins e o autor tambem perde 1 tabcoin.

**Comment by aprendendofelipe** [comment]
Fala @igorroc, obrigado pelas sugestões! 💪

Sobre limitar os votos, no passado foi implementado o limite de 1 voto por IP em cada conteúdo, mas percebemos que 1 só voto era pouco, então agora o limite é de 3 votos por IP, mas isso ainda pode ser alterado futuramente. De qualquer forma, ainda é possível dar mais votos, bastando usar outro IP, mas tudo fica registrado, então qualquer abuso vai acabar com a exclusão dos usuários envolvidos.

Sobre mostrar ao usuário que o post já foi votado, hoje foi aberta a issue #1510 especificamente sobre isso, então vou fechar a sua e qualquer novidade podemos conversar na específica. Combinado? 🤝
