### ISSUE TITLE
[Feature] Possibilidade de modificar posts de outros usuários.

### ISSUE THREAD

**Issue by eusolomax** [filipedeschamps/tabnews.com.br#974]
Seria muito interessante se as pessoas pudessem adicionar ou corrigir informações no post de outros usuários, claramente sendo aplicado **somente se/quando o dono do post permitir a modificação**.

Assim, faria os posts terem a oportunidade de serem mais completos e organizados caso o dono permita aquela modificação!

**Comment by ezequiaslopesdasilva** [comment]
#714

**Comment by eusolomax** [comment]
Obrigado, não tinha visto esta issue antes!
