### ISSUE TITLE
[ERRO] Sem permissão “read:session” pós ativação

### ISSUE THREAD

**Issue by Enzoerb** [filipedeschamps/tabnews.com.br#975]
![C6CD0484-B044-4598-8098-E568EF3FF077](https://user-images.githubusercontent.com/33969883/204065255-ac0b6b5b-4d44-42c0-a17d-baf968515fc7.jpeg)

Criei minha conta, e ativei o cadastro através da verificação de e-mail. Porem, quando tento logar da esse erro:

>  Você não possui permissão para executar esta ação. Verifique se este usuário já ativou a sua conta e recebeu a feature "read:session".

(enviei o print e escrevi o erro pra ficar mais fácil de pesquisarem o issue se alguém tiver o mesmo)

**Comment by mardenrafael** [comment]
Estou tendo o mesmo problema...

**Comment by Rafatcb** [comment]
Esse erro aconteceu na época de lançamento do TabNews, onde houveram muitos cadastros, interações, instabilidade na plataforma, a API fico readonly por um período... Pode ser que a verificação tenha se perdido no meio disso tudo. Estou supondo isso porque não vi mais reclamações por esse motivo.

@aprendendofelipe Pode dar tua opinião? Pensei em fechar o issue, mas talvez você tenha mais informações sobre isso.

**Comment by aprendendofelipe** [comment]
Realmente esse problema ocorreu com frequência no momento do lançamento, mas o que permitia que ele ocorresse já foi corrigido em #1439
