### ISSUE TITLE
Elogios, Sugestões, Dicas.

### ISSUE THREAD

**Issue by ffsolutions** [filipedeschamps/tabnews.com.br#979]
Criei uma publicação detalhando:

https://www.tabnews.com.br/felipeoz/elogios-sugestoes-dicas

Abraço

**Comment by lucas-williams** [comment]
Opa, deixo aqui como sugestão um "side bar" para as principais dúvidas dos membros da comunidade, ou seja, uma área visível que direcione de maneira simplificada questões como:

- Como reportar falhas de segurança?
- Como fazer elogios ou reclamações?
- Sugestões e dicas de aperfeiçoamento da plataforma e etc.
- Principais noticias da semana

Qual seria o objetivo do sidebar?
Evitar que membros criem tabnews repetidas na plataforma tornando o ambiente "flodado".

**Comment by lucas-williams** [comment]
Minha outra sugestão seria a possibilidade de integrar um "sistema de avatar", onde os membros poderiam criar ou personalizar avatares nas suas fotos de perfil.

**Comment by Rafatcb** [comment]
As sugestões que estão na publicação do TabNews são:

> Categorias, Assuntos ou Temas

Podemos marcar como duplicada de https://github.com/filipedeschamps/tabnews.com.br/issues/742, pois a discussão está sendo concentrada lá.

> Busca

Já implementado.

> TabCoin e TabCash em Blockchain

O assunto já foi tratado, de certa forma, e tem uma grande discussão em https://github.com/filipedeschamps/tabnews.com.br/issues/11. O issue está fechado mas com tag de repescagem. Também tem uma sugestão aqui: https://github.com/filipedeschamps/tabnews.com.br/issues/1438.

Tendo em vista, então, a organização do repositório, podemos fechar essa issue?

As outras sugestões realizadas em comentários também já foram feitas em issues diferentes.
