### ISSUE TITLE
minhas sugestões para contribuir com a comunidade.

### ISSUE THREAD

**Issue by wellyton-xs** [filipedeschamps/tabnews.com.br#980]
Eu tive uma ótima impressão ao entrar na comunidade, por isso quero contribuir com o que for. Não sei se já foi pautado essas ideias antes por aqui mas vamos lá.

Tem alguns pontos que eu gostaria de comentar.

1)  sistema de buscas
2) sistema de perguntas

1 - seria incrível ter algum sistema de buscas na plataforma, já que assim caso tenhamos alguma dúvida ou quisermos adiquirir algum tipo de conhecimento podemos procurar rápidamente pelas postagens, foi algo que senti bastante falta por aqui e acho ser necessário.

2 - sistema de perguntas, além das postagens compartilhando alguns conhecimentos seria interessante. Já que quando criamos alguma postagem estamos sujeitos ao ganho de tabcoins quando fizessemos uma pergunta em busca de algum conhecimento pagariamos os nossos tabcoins por ele. Pensei em fazer minhas perguntas com postagens normais mas não faria sentido eu ganhar por fazer alguma pergunta sentiria como se estivesse trapaceando *risos*

por enquanto esses são os pontos que tenho a comentar, logo trarei novas ideias se as tiver.

**Comment by wellyton-xs** [comment]
Outra coisa que acho que seria ótima, algum tipo de sistema de estrelinha ou salvar um post ou discussão para poder reler ou comentar mais tarde, seria bastante interessante.

**Comment by Rafatcb** [comment]
Com o objetivo de organizar os issues abertos no repositório, vou sugerir issues para direcionar os assuntos e permitir fechar essa como duplicada:

1. A busca já foi implementada (https://github.com/filipedeschamps/tabnews.com.br/pull/1472)
2. https://github.com/filipedeschamps/tabnews.com.br/issues/1026: Apesar de abordar dois assuntos (acho que seria mais produtivo a issue ser editada e focar apenas na parte das perguntas, pois já há outro para notificação), ela vai um pouco mais a fundo sobre o sistema de perguntas. Sua ideia sobre isso gastar TabCoin para fazer perguntas pode ser colocada lá.
3. https://github.com/filipedeschamps/tabnews.com.br/issues/645

**Comment by aprendendofelipe** [comment]
Turma, obrigado pelas contribuições! 💪

Pelos menos nas primeiras versões, a questão de perguntas pode ser uma tag específica, combinada com tags do assunto sobre a dúvida.

Por organização, vou fechar diversas issues com assuntos relacionados. Por isso estou listando abaixo as que serão mantidas abertas e onde recomendo concentrarmos o que foi debatido/sugerido aqui:

- #645 
- #738
- #742 

Fechando essa aqui 🤝
