### ISSUE TITLE
[Sugestões] Labels nos posts

### ISSUE THREAD

**Issue by Suburbanno** [filipedeschamps/tabnews.com.br#981]
Seria interessante a implementação de labels, melhorando o filtro de conteudo.

Exemplo:
![image](https://user-images.githubusercontent.com/13632826/204096052-2f48046c-4d30-43cf-92f9-7669eccfb992.png)
![image](https://user-images.githubusercontent.com/13632826/204096063-9826173f-97a5-4234-b7d9-f4d6f4595110.png)
![image](https://user-images.githubusercontent.com/13632826/204096176-b4e24eb9-9a85-4cbe-a38a-ed5332e3deca.png)

Obs: É só um exemplo, toda questão de estética pode melhorar.

**Comment by peeeuzin** [comment]
Tava pensando isso mesmo, estou implementando `search` (#982) para API e isso pode ser uma boa implementar essa ideia junto um `search`

**Comment by Dev-Lyh** [comment]
Fiz um post sobre isso no TabNews.
Foi antes de ver que já tinha uma `issue` registrada.
Realizei alguns designs de como que ficariam as labels na parte do conteúdo em si, mas também, gostei muito do conceito da sua última ideia, bate bem com o resto do design do TabNews. Vou deixar aqui o link do meu post no TabNews e também deixarei aqui quais foram os meus designs preferidos por mesclarem com o design system do TabNews.

### *Qualquer feedback é bem vindo. Não vejo a hora dessa implementação acontecer kkkk*

## Design 1:
![Tags abaixo do título, lado direito](https://github.com/Dev-Lyh/AAGXNBA9CVU37VNTTXX/blob/master/Desktop%20-%203.png?raw=true)

## Design 2:
![Tags abaixo do conteúdo, lado direito](https://github.com/Dev-Lyh/AAGXNBA9CVU37VNTTXX/blob/master/Desktop%20-%204.png?raw=true)

### **Link para o post:** [Algumas ideias de como as labels ficariam no TabNews](https://www.tabnews.com.br/devlyh/algumas-ideias-de-como-as-labels-ficariam-no-tabnews)

**Comment by Suburbanno** [comment]
@Dev-Lyh Bem mais interessantes as sugestões, obrigado. Resta apenas o @filipedeschamps e a comunidade tratar essa sugestão com carinho e implementar, estou sentindo falta disso lá.

**Comment by evertonrj** [comment]
Com toda certeza essa feature trará um UP para o tabnews.

Talvez seja interessante definir alguns parâmetros para fica bem organizado a estrutura de tags.

minha dica lá no tabnews.

https://www.tabnews.com.br/oAnalista/tags-para-classificar-os-posts
