### ISSUE TITLE
Recaptcha para evitar bots

### ISSUE THREAD

**Issue by peeeuzin** [filipedeschamps/tabnews.com.br#986]
Para evitar que bots criam posts e ganham `TabCoins`/`TabCash` de forma automática, precisamos adicionar algum `reCAPTCHA` ou um "verificador de bots" para que não aconteça.

**Comment by coffee-is-power** [comment]
Tem 2 opções aqui,da pra colocar o recaptcha sempre, até da primeira vez que cria a conta, ou colocr quando é, por exemplo, a 3 vez que cria uma conta do mesmo IP

**Comment by peeeuzin** [comment]
> Tem 2 opções aqui,da pra colocar o recaptcha sempre, até da primeira vez que cria a conta, ou colocr quando é, por exemplo, a 3 vez que cria uma conta do mesmo IP

Sem contar que existe reCAPTCHA invisiveis e dá pra colocar esse tipo de reCAPTCHA sempre quando cria um post

**Comment by gabrielsozinho** [comment]
Mas e a API? Se for pra fazer spam, a pessoa faria spam através da API que é pública.

**Comment by peeeuzin** [comment]
> Mas e a API? Se for pra fazer spam, a pessoa faria spam através da API que é pública.

o reCAPTCHA da google retorna um `token` para poder acessar a API.

**Comment by aprendendofelipe** [comment]
@peeeuzin, obrigado pela sugestão! 💪

Nós temos proteção da Cloudflare, então ela já nos ajuda diariamente a enfrentar os bots. Dependendo da situação ela já exige desafios, a maioria é invisível para os usuários.

Também existem diferentes mecanismos implementados no código do TabNews para evitar abusos. Obviamente nenhum nos protege 100%.

Vou fechar a issue, mas qualquer novidade, é só reabrir. Combinado? 🤝
