### ISSUE TITLE
[SUGESTÃO] Menu fixo / botão flutuante

### ISSUE THREAD

**Issue by GHCMelo** [filipedeschamps/tabnews.com.br#987]
Acompanhando algumas postagens riquíssimas em conteúdo, acabo descendo muito na página e sinto falta de um menu fixo ou de um botão flutuante para voltar ao topo novamente.

**Comment by gabrielsozinho** [comment]
Eu particularmente sou mais a favor do botão flutuante, isso porque eu sinto que com um menu fixo a tela acaba perdendo espaço.

Atualmente a interface do meu TabNews é assim, acho bastante agradável (apesar de ter um grande contraste).
![interface do meu tabnews](https://user-images.githubusercontent.com/90806505/204114205-41f339fa-8da4-486e-9de7-ff45ee81e853.png)

Personalizei assim usando as extensões Dark Reader e Stylus. Inclusive usando o Stylus você consegue deixar o menu fixo.

**Comment by Rafatcb** [comment]
O botão de voltar ao topo foi implementado no começo de 2023! Parece que esqueceram de fechar a issue.

A implementação está aqui: https://github.com/filipedeschamps/tabnews.com.br/pull/1039

**Comment by aprendendofelipe** [comment]
@GHCMelo, obrigado pelas sugestões! 💪

A discussão sobre o header fixo ainda está em aberto no #1225, então é melhor concentrarmos lá 🤝

E o botão já foi implementado, como o @Rafatcb citou 👍

Por organização, estou fechando essa issue 🤝
