### ISSUE TITLE
Markdown -  Sugestões de novos comandos para a plataforma

### ISSUE THREAD

**Issue by lucas-williams** [filipedeschamps/tabnews.com.br#989]
Olá, seja bem-vindo! Utilize está área para sugerir que novos comandos de markdown sejam incorporados a plataforma.

Abraços.

**Comment by SureAndrey** [comment]
Marcado de texto

```
==texto à ser marcado==
```

**Comment by rafaelbarbosas** [comment]
> Fórmulas matemáticas:. Não encontrei comandos que permitisse escrever tais fórmulas:

Foi exatamente para dar essa sugestão que eu entrei aqui.
Adicionar os comandos:

```markdown
```math
```

e o inline \$ [equação aqui] \$

**Comment by 33gustavo33** [comment]
> Marcador de texto
>
> ```
> ==texto à ser marcado==
> ```

@SureAndrey, dá pra usar a tag html **mark** pra essa finalidade, é só escrever:
```html
<mark>texto a ser marcado</mark>
```

**Comment by aprendendofelipe** [comment]
@lucas-williams, obrigado pela issue! 💪

Vou fechar ela porque está bem genérica, o que dificulta as discussões. 🤝

Mas a compatibilidade com fórmulas matemáticas, que foi o item mais pedido aqui, já foi implementado em #1323 👍
