### ISSUE TITLE
[Feature] - Dei upvotes/downvotes? 😕

### ISSUE THREAD

**Issue by lucas-williams** [filipedeschamps/tabnews.com.br#990]
Gostaria de sugerir aqui que fosse incluído um "contador" de upvotes/downvotes ou simplesmente um indicador informando se um post/comentário já recebeu um upvote/downvote meu, pois acontece que as vezes fico confuso se dei up/downvote ou não em determinado post/comentário.

**Comment by wallasfmorais** [comment]
Talvez poderia ser tratado com uma estratégia diferente. 
Não cheguei ainda a ver se já foi discutido isso anteriormente ou não, mas não seria melhor ser um toggle? Explico:
Não faz sentido a mesma pessoa dar up/down vote mais de uma vez em uma mesma publicação a não ser com uma não tão boa intenção (mesmo que a intenção seja no fundo positiva [gostei tanto que vou dar 2 upvote] apenas cria desequilíbrio).

**Comment by GoulartNogueira** [comment]
> Não faz sentido a mesma pessoa dar up/down vote mais de uma vez em uma mesma publicação

Discordo. O Medium, por exemplo, não tem downvote e eles permitem upvotes ilimitados.
E a ideia do tabnews é justamente ter um "custo" no upvote. Você gasta tabCoins para votar, então se um usuário gostou muito de um post e quiser gastar 10 moedas. Está 100% no seu direito!

**Comment by natanael-b** [comment]
A questão é que pode gerar o efeito cancelamento por motivos pessoais

**Comment by natanael-b** [comment]
> O Medium, por exemplo, não tem downvote e eles permitem upvotes ilimitados
 
A ideia de upvote do medium é completamente diferente da do TabNews não dá pra comparar
 
> Você gasta tabCoins para votar, então se um usuário gostou muito de um post e quiser gastar 10 moedas. Está 100% no seu direito!

O principal problema desse modo de pensar é que ele ignora o "Efeito Felipe Neto" alguém que acumulou 1000 Tab Coins em uma ou mais contas pode descarregar de uma vez só num post por exemplo, isso pode creditar uma resposta prejudicial a comunidade (exemplo, spam, disseminação de pragas virtuais, informação errada) ou mesmo levar ao limbo um usuário sem que ele viole nada, em outras palavras pode levantar ideias muito erradas e trazer o cancelamento do Twitter pro TabNews o que é o oposto da plataforma
 
Importante lembrar que TabCoins **não** funcionam como dinheiro, **TabCash** sim, TabCoins é o poder de incentivar ou punir uma ideia isso só funciona se o poder de cada conta for nivelado

**Comment by natanael-b** [comment]
@filipedeschamps o que pensa sobre o assunto, é algo importante que pode definir a saúde da plataforma

**Comment by Rafatcb** [comment]
Duplicada: https://github.com/filipedeschamps/tabnews.com.br/issues/752

**Comment by Rafatcb** [comment]
Tem uma issue mais recente que teve mais atenção da comunidade, recebendo algumas sugestões de como exibir essa informação: https://github.com/filipedeschamps/tabnews.com.br/issues/1510, recomendo concentrar a discussão lá.

**Comment by aprendendofelipe** [comment]
Seguindo a sugestão do @Rafatcb, vamos concentrar a discussão na #1510. 🤝

Vou encerrar essa aqui 😉
