### ISSUE TITLE
Follow, UnFollow, Notificação

### ISSUE THREAD

**Issue by LuriqueGon** [filipedeschamps/tabnews.com.br#991]
Só de olhar dá para notar quão o tabnews realmente é diferente da internet de "hoje", essa proposta realmente encanta o olhar de qualquer amante da internet, da verdadeira internet.

--- **Notificação** ---

    Mas tem algo que eu me acostumei muito com a internet, e isso é a notificação. Não por e-mail, mas no próprio site, como aquele <sino> que fica sempre lá no cabeçalho. E quando clica aparece as ultimas postagens das pessoas que você "Segue" ou mais Visualizar/lê.
    
    Me bateu uma curiosidade muito grande, se o tabnews vai fazer algo como isso. Um meio do sistema interpretar os assuntos e autores que certo usuário mais visualiza, e então formar um 'algoritmo' sobre isso, para que ele sempre tenha uma boa recomendação na sua barra de notificação, ou até mesmo em uma seção a parte.
    
--- **Follow** ---

    Meio que ao incrementar as notificações, eu acredito que algo como o follow poderia existir, ou algo do gênero. Eu também pensei que pudesse haver um meio de unir o follow com os coins e cashs, meio que para seguir você gastasse algo, para ser um pouco diferente do padrão, e talvez ganhar algo quando receber seguidos. Mas claro, precisaria de um meio de "Segurar" isso, já que um mesmo usuário poderia criar varias contas, só para conseguir seus coins/cash.
    
    Eu realmente adoro essa parte que a internet criou, a parte de "Seguir" e fazer parte dos "conteúdos" das pessoas que você realmente gosta. Realmente acharia muito top algo assim.
    
    Já que os Ups, que lembram muito o like, já estão de pé, realmente seria muito agradável ter o complemento do Follow E Notif.

--- **Conclusão** ---

Vamos juntos evoluir ao maximo essa ideia, a ideia do tabnews, UP!!

**Comment by Rafatcb** [comment]
São boas sugestões. Me parece que podemos concentrar as discussões sobre cada uma individualmente nos seguintes issues:

* https://github.com/filipedeschamps/tabnews.com.br/issues/878
* https://github.com/filipedeschamps/tabnews.com.br/issues/523

**Comment by aprendendofelipe** [comment]
Turma, obrigado pelas contribuições! 💪

Vou fechar diversas issues com assuntos relacionados. Por isso estou listando abaixo as que serão mantidas abertas e onde recomendo concentrarmos o que foi debatido/sugerido aqui:

- #645 
- #738
- #742 

Fechando essa aqui 🤝
