### ISSUE TITLE
[FEATURE] Descrição no perfil do usuário

### ISSUE THREAD

**Issue by braiansmarzaro** [filipedeschamps/tabnews.com.br#993]
Será muito legal se puder criar uma pequena descrição própria no perfil, para se apresentar e dizer quais temáticas gosta de discutir. Isso pode vir junto com a sugestão de follow!

**Comment by otaviolms** [comment]
Show, além de poder adicionar por exemplo um link de portfolio ou mesmo perfil do GitHub

**Comment by rubensflinco** [comment]
Pessoal Pull Request Aberto, aguardando Revisão e Merge:
https://github.com/filipedeschamps/tabnews.com.br/pull/1471

**Comment by aprendendofelipe** [comment]
@braiansmarzaro, obrigado pela sugestão! 💪

A descrição no perfil dos usuários já foi implementada de maneira preliminar no PR #1470.

Ainda faltam ajustes, mas é melhor centralizar a conversa na issue onde a discussão avançou mais. Então vou fechar essa. Combinado? 🤝
