### ISSUE TITLE
Como faço para contribuir no Tabnews?

### ISSUE THREAD

**Issue by ArthurMadureira** [filipedeschamps/tabnews.com.br#994]
Olá gente, estou tentando contribuir com o tabnews no Github para melhorar a dashboards da página de status, porém, quando eu do **npm run dev** aparece o seguinte erro:

```error during connect: this error may indicate that the docker daemon is not running: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/json?all=1&filters=%7B%22label%22%3A%7B%22com.docker.compose.project%3Dinfra%22%3Atrue%7D%7D": open //./pipe/docker_engine: The system cannot find the file specified.```

Como faço para resolver este erro?

**Comment by gustarpd** [comment]
essa mensagem indica que o serviço do docker não está iniciado, verifica o seu docker desktop. ele está aberto?

**Comment by pietrobs** [comment]
Boa tarde! Estava com esse problema agora mesmo.

A única solução foi desinstalar e instalar o docker novamente, mas dessa vez configurando corretamente o terminal do linux (WSL 2) que a instalação sugere!

**Comment by Rafatcb** [comment]
Como esse issue é antigo, estou fechando ele por falta de acompanhamento. Para quem ter um problema parecido, confirme se o Docker está executando na máquina. Lembre-se de ler a [documentação do Docker](https://docs.docker.com/config/daemon/troubleshoot/) para verificar se seu problema está lá.
