### ISSUE TITLE
[TabCoins] Concentração versus Distribuição

### ISSUE THREAD

**Issue by johnathanmelo** [filipedeschamps/tabnews.com.br#995]
SUGESTÃO DE MELHORIA:

Um usuário deveria poder dar apenas 1 upvote ou 1 downvote por publicação. Isso forçaria usuários com muitas TabCoins a DISTRIBUIR suas TabCoins para muitos bons conteúdos diferentes, ao invés de dar a este usuário o poder de CONCENTRAR seus TabCoins para uma única publicação de um único usuário.

Visto que o TabCoin é o item de principal valor da plataforma, permitir ao usuário usar todos os seus TabCoins para votar em uma única publicação abre margem para manipulação, pois ele pode dar MUITOS downvotes para desfavorecer uma publicação, ou super favorecer uma única publicação.

Ou seja: PARA O BEM DE TODA COMUNIDADE, devemos premiar a DISTRIBUIÇÃO de recursos, e impedir a transferência CONCENTRADA de recursos.

Com concentração: PODER GERA PODER.
Com distribuição: PODER GERA PREMIAÇÃO DISTRIBUÍDA PERMEANDO TODA A COMUNIDADE.

**Comment by coffee-is-power** [comment]
sinceramente, isso depende da pessoa, porque tabcoins é como dinheiro, você gasta como quiser, e quando você posta alguma coisa é o equivalente a imprimir dinheiro

**Comment by lucas-williams** [comment]
Exatamente como mencionado pelo @coffee-is-power , os tabcoins funcionam parecidos com dinheiro. Eu por exemplo tenho 100, mas não gastaria todos eles pra acabar com uma publicação! Porém, se eu acumular muitos coins, eu poderia dar muitos downvotes em alguém e isso não me prejudicaria nos meus coins por exemplo, então nesse aspecto, seria interessante limitar a quantidade e up/downvotes.

**Comment by johnathanmelo** [comment]
Exatamente pela TabCoin ser como dinheiro que eu sugeri essa melhoria. 

No mundo real, não temos essa limitação nas transfências de dinheiro, e isso gera uma série de problemas e desigualdade social, privilegiando os mais ricos.

Como nesse ambiente digital nós podemos controlar as regras, penso que seria uma ótima melhoria visando o bem da comunidade e impedindo super usuários de manipular o mecanismo.

**Comment by 33gustavo33** [comment]
> No mundo real, não temos essa limitação nas transfências de dinheiro, e isso gera uma série de problemas e desigualdade social, privilegiando os mais ricos.

Não vejo muito problema nisso, pois os mais ricos no TabNews seriam as pessoas que produziram **valor concreto** pra comunidade.

Porém, eu também acho que deveria ter um limite de TabCoins, porém não um limite de 1 tabcoin, mas um limite de 5 tabcoins ou algo assim.

**Comment by johnathanmelo** [comment]
> Porém, eu também acho que deveria ter um limite de TabCoins, porém não um limite de 1 tabcoin, mas um limite de 5 tabcoins ou algo assim.

Concordo 100%. Meu ponto é que deve existir ALGUM limite nos upvotes e downvotes, para não potencializar o poder dos ricos em TabCoins, e forçar eles a distribuir melhor os votos entre outras publicações relevantes para a comunidade.

**Comment by Rafatcb** [comment]
Hoje temos um limite de 3 votos a cada 72 horas. Na época em que esse issue foi criado, a quantidade de votos numa publicação era ilimitada.

Apesar disso, esse tipo de situação ainda está em discussão, podemos fechar este issue para focar a discussão no issue abaixo:

* https://github.com/filipedeschamps/tabnews.com.br/issues/1166
