### ISSUE TITLE
[sugestão] - área semelhante ao Product Hunt 

### ISSUE THREAD

**Issue by kleidimilson** [filipedeschamps/tabnews.com.br#997]
Olá devs! Essa semana tive uma ideia, e se o tabnews possibilitasse a divulgação de projetos assim como o Product Hunt.
Na minha visão seria muito interessante uma comunidade brasileira para validar novos produtos.

**Comment by filipedeschamps** [comment]
Acho ótimo e poderia aproveitar o prefixo Pitch e filtrar por isso, tem **muita coisa legal já**: https://www.google.com/search?q=site%3Atabnews.com.br+pitch&oq=site%3Atabnews.com.br+pitch&aqs=chrome..69i57j69i58.5531j1j7&sourceid=chrome&ie=UTF-8

**Comment by Rafatcb** [comment]
Kleidimilson, obrigado pela sugestão!

Acredito que a implementação de tags (https://github.com/filipedeschamps/tabnews.com.br/issues/742), permitindo listar os conteúdos delas, resolveria esse problema. Bastaria existir e usar a tag `Pitch`, como o Filipe mencionou. Por esse motivo, estou fechando o issue para concentrarmos a discussão no outro.

Se eu entendi errado, por favor me corrija e reabrimos o issue se necessário.
