### ISSUE TITLE
[FEATURE] Exibição de mensagem de instabilidade/manutenção 

### ISSUE THREAD

**Issue by brendo10x** [filipedeschamps/tabnews.com.br#998]
Minha sugestão é exibir de forma fixa mensagens de instabilidade ou manutenção programada na página do TabNews. Fica melhor assim ao invés de cadastrar um post, pois acaba se perdendo na listagem e as pessoas não visualizam. 

Fica a dica :D

**Comment by Rafatcb** [comment]
Apesar desse tipo de mensagem só ter sido usada assim que o TabNews foi lançado (pelo o que me lembro), existe um issue sobre o assunto:

* https://github.com/filipedeschamps/tabnews.com.br/issues/1181

Acho que podemos fechar este e concentrar a discussão lá.

**Comment by aprendendofelipe** [comment]
@brendo10x, obrigado pela sugestão! 💪

Isso ainda está pendente, mas podemos concentrar na #1181, onde o Filipe já inseriu mais detalhes 🤝
