### ISSUE TITLE
[SUGESTÃO] Aba de sugestões para ajudar com o spam na área principal de tabs.

### ISSUE THREAD

**Issue by gu-maia** [filipedeschamps/tabnews.com.br#999]
Boa noite!

Passei praticamente o dia todo lendo tabs hoje. Notei que boa parte das publicações são sugestões que deveriam estar aqui no repositório.

Publicações no estilo: "acho que poderiam acrescentar um x em y lugar..."

Na minha opinião, além de afogarem as outras publicações, não oferecem valor concreto ao usuário, _e sim ao projeto_ como plataforma. Tenho certeza que todas as sugestões são bem-vindas, mas será que não vale a pena criarmos uma seção separada apenas para isso? Um "Sugestões" ao lado de recentes, por exemplo.

Estou chegando agora! Se isso já tiver sido debatido por vocês aqui, peço que por favor fechem o issue.

Se for para frente, me disponibilizo para ajudar na implementação.

Obrigado!

**Comment by itsmaia** [comment]
Nesse mesmo sentido, caso implementado, seria interessante implementar também uma ferramenta para que moderadores possam mover o conteúdo para a aba correta.

**Comment by aprendendofelipe** [comment]
@gu-maia obrigado pela sugestão! 💪

Concordo com o @Rafatcb, então vou fechar a issue por enquanto 🤝
